foo: 0.0.1-0 in 'jade/distribution.yaml' [bloom]
ros/rosdistro pull request #12725
Opened 2016-09-16 15:51 UTC by nlyubova

Increasing version of package(s) in repository `foo` to `0.0.1-0`:

- upstream repository: https://github.com/ros-naoqi/naoqi_dcm_driver.git
- release repository: https://github.com/ros-naoqi/naoqi_dcm_driver-release.git
- distro file: `jade/distribution.yaml`
- bloom version: `0.5.22`
- previous version for package: `null`

## naoqi_dcm_driver

```
* refactoring
* adding a wrapper for Memory Proxy
* updating the README
* exit Touch service
* adding the diagnostics class
* adding tools for AnyValue conversion
* fixing velocity control
* initial commit
* Contributors: Natalia Lyubova
```

2016-09-16 15:58 UTC, dirk-thomas commented on jade/distribution.yaml
> +  foo:
Please choose a reasonable repository name for your entry, e.g. `naoqi_dcm_driver`.

2016-09-16 16:01 UTC, dirk-thomas requested changes
Please choose a reasonable repository name for your entry, e.g. naoqi_dcm_driver.

2016-09-16 16:02 UTC, dirk-thomas approved these changes

2016-09-16 16:03 UTC, dirk-thomas requested changes
Please choose a reasonable repository name for your entry (instead of `foo`), e.g. `naoqi_dcm_driver`.

2016-09-16 16:05 UTC, nlyubova commented
Done! sorry for typo

2016-09-16 16:11 UTC, dirk-thomas commented
After the rename the inserted entry needs to be moved to the correct location in alphabetical order.

2016-09-16 16:11 UTC, dirk-thomas approved these changes

2016-09-16 16:16 UTC, nlyubova commented
done

2016-09-16 16:20 UTC, dirk-thomas commented on jade/distribution.yaml
> +      - naoqi_dcm_driver
For a repo containing only a single package with the (now) same name as the repo you have to remove the `packages` list.

2016-09-17 08:03 UTC, nlyubova commented
Donc!

2016-09-17 14:06 UTC, merged