Added theano
ros/rosdistro pull request #13228
Opened 2016-11-16 21:21 UTC by eruffaldi

2016-11-16 22:56 UTC, tfoote commented
I see python-theano available as a debian package: https://packages.debian.org/unstable/main/python-theano starting with stretch 
And ubuntu: http://packages.ubuntu.com/yakkety/python-theano starting with yakkety. 

Could you fill in the rules for the other distros so that others can use this? Note that you can use the short hand and skip the `packages:` line to be more compact.

2016-11-16 22:56 UTC, tfoote commented
It's also in fedora as of 23: https://admin.fedoraproject.org/pkgdb/package/rpms/python-theano/

2016-11-17 05:28 UTC, eruffaldi commented
Added fedora,debian,arch, older ubunuts
Thanks,
-E

2016-11-17 10:52 UTC, tfoote requested changes
Thanks for the update. I've added 2 comments on the lines that are failing CI.

And it would be great to have wily and xenial support for Kinetic users.

2016-11-17 10:52 UTC, tfoote commented on rosdep/python.yaml
> +    sid: [python-theano]
Please don't add sid. It's a rolling target so we don't try to define what's in it. This is also failing the CI due to being out of alphabetical order.

2016-11-17 10:52 UTC, tfoote commented on rosdep/python.yaml
> +  debian:
There's trailing whitespace on this line.

2016-11-17 13:59 UTC, eruffaldi commented
The changes are implemented. Right?

2016-11-17 19:25 UTC, tfoote approved these changes

2016-11-17 19:25 UTC, tfoote commented
Yeah, I added them thanks.

2016-11-17 20:19 UTC, merged