Added php to rosdep rules
ros/rosdistro pull request #13613
Opened 2017-01-18 20:37 UTC by kmhallen

* https://packages.debian.org/jessie/php5
* http://packages.ubuntu.com/trusty/php5
* http://packages.ubuntu.com/xenial/php

2017-01-18 20:41 UTC, dirk-thomas approved these changes

2017-01-18 23:55 UTC, tfoote requested changes

2017-01-18 23:55 UTC, tfoote commented on rosdep/base.yaml
> +    xenial: [php]
@kmhallen thanks for these updates. We also try to keep Fedora rules in sync: like here: https://admin.fedoraproject.org/pkgdb/package/rpms/php/

And looking at debian it looks like php7.0 is available on stretch. And like xenial php is provided by php7.0 http://packages.ubuntu.com/xenial/php7.0

so the rules for xenial and stretch should be php7.0 not just php.

Also would you mind adding yakkety and zesty?

2017-01-19 19:29 UTC, kmhallen commented
* https://www.archlinux.org/packages/extra/x86_64/php/
* https://packages.debian.org/jessie/php5
* https://packages.debian.org/stretch/php7.0
* https://packages.debian.org/sid/php7.1
* https://admin.fedoraproject.org/pkgdb/package/rpms/php/
* http://packages.ubuntu.com/trusty/php5
* http://packages.ubuntu.com/xenial/php7.0

2017-01-19 21:25 UTC, tfoote approved these changes

2017-01-19 21:26 UTC, tfoote commented
I removed sid and added yakkety and zesty.

2017-01-19 21:26 UTC, merged