Added python-cheetah as fedora rosdep.
ros/rosdistro pull request #13695
Opened 2017-01-24 21:38 UTC by tonybaltovski

2017-01-24 23:21 UTC, tfoote requested changes
It looks like python-cheetah has an rpm available. Unless there's a reason otherwise we should use that.

https://apps.fedoraproject.org/packages/python-cheetah

2017-01-25 00:13 UTC, tonybaltovski commented
You are right, I only searched for cheetah which had no results.

2017-01-25 00:17 UTC, tfoote commented
Yeah, not the best search interface. I think I found the same results when the other rules were contributed.

2017-01-25 00:17 UTC, tfoote approved these changes

2017-01-25 00:18 UTC, merged