update wxwidgets, from xenial we need to use gtk3.0
ros/rosdistro pull request #13886
Opened 2017-02-14 01:51 UTC by k-okada

update wxwidgets, from xenial we need to use gtk3.0

I decied to switch to gtk 3.0 from xenial, as wxpython entry do
http://packages.ubuntu.com/trusty/libwxgtk3.0-dev

2017-02-14 01:55 UTC, dirk-thomas approved these changes
This will affect already released packages depending in this key. They need to be rebloomed to get the new mapping.

2017-02-14 08:15 UTC, k-okada commented
yes, and these packages should be failed within the build firm.
http://build.ros.org/job/Kbin_uX64__jsk_rviz_plugins__ubuntu_xenial_amd64__binary/3/console#console-section-12


--
◉ Kei Okada


2017-02-14 10:55 GMT+09:00 Dirk Thomas <notifications@github.com>:

> *@dirk-thomas* approved this pull request.
>
> This will affect already released packages depending in this key. They
> need to be rebloomed to get the new mapping.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros/rosdistro/pull/13886#pullrequestreview-21661713>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAeG3DVygbdNiohBJf1wQTSNfBf0XyW5ks5rcQl2gaJpZM4L_9Rn>
> .
>

2017-02-14 20:45 UTC, tfoote requested changes
This should also be updated for debian: It lookslike 3.0 was published as of Jessie: https://packages.debian.org/jessie/libwxgtk3.0-dev
And 2.8 was last in wheezy: https://packages.debian.org/wheezy/libwxgtk2.8-dev

http://packages.ubuntu.com/trusty/libwxbase2.8-dev vs http://packages.ubuntu.com/trusty/libwxgtk3.0-dev

2017-02-14 20:45 UTC, tfoote commented on rosdep/base.yaml
> +  ubuntu:
This line is is here twice.

2017-02-14 20:52 UTC, wjwwood commented
Also, perhaps a bit off-topic, but why does your `jsk_rviz_plugins` package depend on `wx`?

2017-02-14 23:42 UTC, k-okada commented on rosdep/base.yaml
> +  ubuntu:
@tfoote sorry, fixed now.

2017-02-14 23:50 UTC, k-okada commented
> Also, perhaps a bit off-topic, but why does your jsk_rviz_plugins package depend on wx?

@wjwwood Good question, may be we do not need that. I just afraid something bad happens by changing dependency. I'll try to remove that https://github.com/jsk-ros-pkg/jsk_visualization/pull/664
https://github.com/jsk-ros-pkg/jsk_visualization/commit/a7f3f76f86efcc73069eb1f840ccab90f5c12e00

2017-02-15 01:29 UTC, wjwwood commented
I mean, do whatever works for you. I don't mind that you're using `wx`, and I think we should fix the rosdep rule. Just curious.

2017-02-15 01:34 UTC, tfoote approved these changes

2017-02-15 01:34 UTC, tfoote commented on rosdep/base.yaml
> +  ubuntu:
+1

2017-02-15 01:34 UTC, tfoote commented on rosdep/base.yaml
> +    stretch: [libwxgtk3.0-dev]
Thanks for the debian updates. I removed the sid entry since we don't target sid because it's a rolling target.

2017-02-15 02:10 UTC, merged