Add rosdep keys for OpenVDB
ros/rosdistro pull request #13950
Opened 2017-02-21 19:52 UTC by pjreed

This is a library for the efficient storage & manipulation of sparse volumetric data on a 3D grid.  It's developed and used by DreamWorks Animation for use in feature film production.  We're using it to manipulate LIDAR point clouds.  Home page: http://www.openvdb.org/

Arch: https://www.archlinux.org/packages/?sort=&q=openvdb&maintainer=&flagged=
Debian: https://packages.debian.org/search?keywords=openvdb&searchon=names&suite=stable&section=all
Gentoo: https://packages.gentoo.org/packages/media-gfx/openvdb
Ubuntu: http://packages.ubuntu.com/search?suite=all&searchon=names&keywords=openvdb

No packages in Fedora.

2017-02-21 19:55 UTC, dirk-thomas commented
The keys need to be in alphabetical order:

> ERR: list out of alphabetical order line 2187.  'libopenvdb' should come before 'libopenvdb-dev'

2017-02-21 19:59 UTC, tfoote requested changes
Thanks for filling in all the different platforms. I just had two comments about the supported ubuntu and debian platform lists.

2017-02-21 19:59 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libopenvdb3.2]
Please define `stretch` but not `sid` stretch is in the process of stabilizing, but sid is a rolling release so we can't target it efficiently.

2017-02-21 19:59 UTC, tfoote commented on rosdep/base.yaml
> +    trusty: [libopenvdb2.1]
Please fill in the current platforms we support: missing are saucy, utopic, vivid, wily. And soon we'll add yakkety and zesty for Lunar which would be great too.

2017-02-21 20:07 UTC, tfoote approved these changes

2017-02-21 20:07 UTC, pjreed commented
saucy, utopic, vivid, and wily aren't listed on packages.ubuntu.com, so I'm not sure what keys are appropriate for them; is there a better place to look?

2017-02-21 22:28 UTC, tfoote commented
You get to browse the archives ;-)

saucy: http://old-releases.ubuntu.com/ubuntu/dists/saucy/universe/binary-amd64/  1.1
utopic: http://old-releases.ubuntu.com/ubuntu/dists/utopic/universe/binary-amd64/ 2.3
vivid: http://archive.ubuntu.com/ubuntu/dists/vivid/universe/binary-amd64/ 2.3
wily http://archive.ubuntu.com/ubuntu/dists/wily/universe/binary-amd64/  3.0

2017-02-22 15:42 UTC, pjreed commented
Ok, thanks.

2017-02-22 16:24 UTC, merged