Adding xsens-awinda to documentation index for distro
ros/rosdistro pull request #14401
Opened 2017-03-31 08:10 UTC by Raffa87

2017-03-31 18:05 UTC, tfoote requested changes

2017-03-31 18:05 UTC, tfoote commented on indigo/distribution.yaml
> +   source:
Please review your indentation it appears to be breaking the parsing as seen in the CI failure.

2017-04-03 14:29 UTC, dirk-thomas commented
The diff shows several unrelated changes. Please update the changes to only show your changes.

2017-04-09 06:28 UTC, dirk-thomas commented
I will close this due to no response. Please either update the branch and comment here and the PR can be reopened or create a new PR.

2017-04-09 06:28 UTC, closed without merging