Added Python-argh to available packages
ros/rosdistro pull request #14959
Opened 2017-05-10 00:56 UTC by yotabits

This package is needed for the further release of python-watchdog R.O.S. package

2017-05-10 01:02 UTC, tfoote requested changes
If you want to make a release a debian rule will be necessary: https://packages.debian.org/search?keywords=python-argh

As well as a fedora rule: https://admin.fedoraproject.org/pkgdb/package/rpms/python-argh/

And the ubuntu rule can be collapsed to a single line for easier reading and maintenance.

2017-05-10 01:02 UTC, tfoote commented on rosdep/python.yaml
> +  ubuntu:
It looks like python-argh is generally available on all versions. Could you change this rule to not call out specific versions: http://packages.ubuntu.com/search?keywords=python-argh

2017-05-10 01:08 UTC, tfoote commented
Note that python-watchdog is already available upstream, https://packages.debian.org/search?keywords=python-watchdog. If you want to use that you don't need to add rules for all the dependent packages.

2017-05-10 01:51 UTC, yotabits commented
@tfoote Updated :)

2017-05-12 02:12 UTC, tfoote approved these changes

2017-05-12 02:13 UTC, tfoote commented
This looks better now. However I need to ask how you are planning to release python-watchdog for trusty. We don't support releasing arbitrary generic python packages. They need to be ros packages in a rosdistro.

2017-05-12 07:19 UTC, yotabits commented
Actually I already have a functional ROS package of watchdog and one his specific dependency not available as a ROS package for now.

To make it I used [catkin_pip](https://github.com/asmodehn/catkin_pip), for now it works like a charm.

2017-05-12 18:00 UTC, tfoote commented
Ok great. We need a 2nd review/merger from @ros/rosdistro-maintainers

2017-05-12 18:00 UTC, merged