Add Voluptuous, a python data validation library
ros/rosdistro pull request #14990
Opened 2017-05-15 22:57 UTC by gordonbrander

This adds [Voluptuous](https://pypi.python.org/pypi/voluptuous) pip package. Voluptuous is a Python data validation library for deeply validating JSON and YAML structures according to strict schemas.

2017-05-15 23:00 UTC, tfoote approved these changes
lgtm. There doesn't seem to be any packaged versions yet.

2017-05-19 07:19 UTC, mikaelarguedas commented
> There doesn't seem to be any packaged versions yet.

rmadison returns:
```
 python-voluptuous | 0.8.2-1        | trusty/universe | all
 python-voluptuous | 0.8.2-1        | vivid/universe  | all
 python-voluptuous | 0.8.8-1ubuntu1 | xenial          | all
 python-voluptuous | 0.9.3-1        | yakkety         | all
 python-voluptuous | 0.9.3-1        | zesty           | all
 python-voluptuous | 0.9.3-1        | artful          | all
```

looks like it's available on debian since jessie: https://packages.debian.org/search?keywords=+python-voluptuous&searchon=names&suite=all&section=all

@gordonbrander Is it possible to use the system version rather than the pip one ?

2017-05-19 08:17 UTC, tfoote commented
Good catch @mikaelarguedas I must have misstyped when I searched. It definitely appears to be packaged. Since it's packaged we should use that version.

2017-05-24 05:56 UTC, mikaelarguedas requested changes
As mentioned in https://github.com/ros/rosdistro/pull/14990#issuecomment-302628830, this package is available upstream on most platforms. @gordonbrander can you please update this PR accordingly?
https://packages.debian.org/search?keywords=python-voluptuous&searchon=names&suite=all&section=all
https://admin.fedoraproject.org/pkgdb/package/rpms/python-voluptuous/
https://packages.ubuntu.com/search?keywords=python-voluptuous&searchon=names&suite=all&section=all

2017-05-28 09:32 UTC, Alessandro-Barbieri commented
`dev-python/voluptuous` in gentoo

2017-06-28 15:38 UTC, dirk-thomas commented
Closing due to no response to review comments.

2017-06-28 15:38 UTC, closed without merging