remove python-* in base.yaml, which already defined in python.yaml
ros/rosdistro pull request #15258
Opened 2017-06-16 06:33 UTC by k-okada

rewrited version of https://github.com/ros/rosdistro/pull/15257

some of rosdep keys is multiply defiend, and that sometime confuse useres.

- This just to remove duplicates entry from base.yaml, no regressions.

2017-06-16 06:42 UTC, tfoote approved these changes

2017-06-16 11:52 UTC, ipa-mdl commented
To avoid further confusion, what about moving all `python-*` keys into python.yaml by policy?

2017-06-16 15:14 UTC, mikaelarguedas requested changes
One rule is removed here and doesn't exist in the python.yaml file.

2017-06-16 15:14 UTC, mikaelarguedas commented on rosdep/base.yaml
> -  arch: [python-tornado]
Please add the arch key to the python.yaml file

2017-06-17 00:39 UTC, k-okada commented on rosdep/base.yaml
> -  arch: [python-tornado]
thanks for catch! done

2017-06-17 01:17 UTC, mikaelarguedas approved these changes
lgtm, thanks for iterating

2017-06-17 01:18 UTC, merged