pocketsphinx is already taken by ros package(http://wiki.ros.org/pock…
ros/rosdistro pull request #15260
Opened 2017-06-16 06:40 UTC by k-okada

…etsphinx) and that different from pocketsphinx system package, libshphinxbase is library and pocketsphinx installs some application binaries, so they are differnet too

rewrited version of #15257

some of rosdep keys is multiply defined, and that sometime confuse users.

pocketsphinx is already taken by ros package(http://wiki.ros.org/pocketsphinx)
and that different from pocketsphinx system package,
libshphinxbase is library and pocketsphinx installs some application binaries, so they are differnet too
this changes pocketsphinx key in base.yaml to pocketsphinx-bin, this also breaks compatibility, but that was added just a few month ago

~~~
ubuntu-14:~$ dpkg -L libsphinxbase1
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libsphinxbase1
/usr/share/doc/libsphinxbase1/copyright
/usr/share/doc/libsphinxbase1/changelog.Debian.gz
/usr/lib
/usr/lib/libsphinxbase.so.1.1.1
/usr/lib/libsphinxad.so.0.0.1
/usr/lib/libsphinxbase.so.1
/usr/lib/libsphinxad.so.0
ubuntu-14:~$ dpkg -L libpocketsphinx1/.
/usr
/usr/lib
/usr/lib/libpocketsphinx.so.1.1.0
/usr/share
/usr/share/doc
/usr/share/doc/libpocketsphinx1
/usr/share/doc/libpocketsphinx1/copyright
/usr/share/doc/libpocketsphinx1/changelog.Debian.gz
/usr/lib/libpocketsphinx.so.1

ubuntu-16:~$ dpkg -L pocketsphinx
/.
/usr
/usr/bin
/usr/bin/pocketsphinx_mdef_convert
/usr/bin/pocketsphinx_continuous
/usr/bin/pocketsphinx_batch
/usr/share
/usr/share/doc
/usr/share/doc/pocketsphinx
/usr/share/doc/pocketsphinx/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/pocketsphinx_batch.1.gz
/usr/share/man/man1/pocketsphinx_continuous.1.gz
/usr/share/man/man1/pocketsphinx_mdef_convert.1.gz
/usr/share/doc/pocketsphinx/changelog.Debian.gz

ubuntu-16:~$ dpkg -L libpocketsphinx3
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libpocketsphinx.so.3.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libpocketsphinx3
/usr/share/doc/libpocketsphinx3/copyright
/usr/share/doc/libpocketsphinx3/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libpocketsphinx.so.3
```

2017-06-28 15:32 UTC, dirk-thomas commented
This needs to be rebased.

2017-06-28 22:45 UTC, k-okada commented
@dirk-thomas ok, done.

2017-06-28 23:43 UTC, tfoote requested changes
+1 for renaming the colliding key.

However we should not remove all those older rules as some are note even EOL and there's not much value in collapsing only some of them.

2017-06-28 23:49 UTC, k-okada commented
ok, now we just changed key name

2017-06-29 00:01 UTC, tfoote approved these changes
+1 with announcement mentioned in #15259

2017-06-29 15:28 UTC, tfoote commented
Thanks @k-okada [the post](https://discourse.ros.org/t/proposed-rename-of-rosdep-keys-pocketsphinx-and-xdot/1959) and [grepping for the keys](https://github.com/ros/rosdistro/pull/15259#issuecomment-311855228) is about all we can do.

@ros/rosdistro-maintainers all set for merge.

2017-06-29 15:50 UTC, dirk-thomas commented
No released ROS packages seem to use this key. So I am ok with merging this.

2017-06-29 15:50 UTC, merged