Add jq command line utility for parsing JSON
ros/rosdistro pull request #15333
Opened 2017-06-23 03:27 UTC by RahmanQureshi

jq is a command line tool for parsing JSON files.

2017-06-23 22:05 UTC, tfoote requested changes
Could you add debian and fedora rules too. They're all the same key.

https://packages.ubuntu.com/xenial/jq
https://packages.debian.org/buster/jq
https://admin.fedoraproject.org/pkgdb/package/rpms/jq/

2017-06-23 22:28 UTC, Alessandro-Barbieri commented
`app-misc/jq` on gentoo

2017-06-26 02:42 UTC, Alessandro-Barbieri requested changes

2017-06-26 02:42 UTC, Alessandro-Barbieri commented on rosdep/base.yaml
> +  fedpra: [jq]
fedora

2017-06-26 07:47 UTC, RahmanQureshi commented
Done!

2017-06-26 07:49 UTC, RahmanQureshi commented
Oops, done!

2017-06-26 16:06 UTC, mikaelarguedas approved these changes
lgtm

2017-06-26 16:15 UTC, merged