debian dependencies
ros/rosdistro pull request #15349
Opened 2017-06-24 00:04 UTC by Alessandro-Barbieri

2017-06-24 00:15 UTC, tfoote requested changes
Overall this looks good. I had a few comments, and pointed out a bunch of places with sid keys. We don't target sid because it's a rolling release that changes over time. Now that buster has been announced we can begin to converge on that for new keys.

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    wheezy: [chromium-browser]
It looks like they've taken over the `chromium` key on debian. https://packages.debian.org/stretch/chromium

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [clang-format]
Please don't add sid rules. We don't set them since it's a moving target.

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libcollada-dom2.4-dp-dev]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [gazebo7]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [gazebo7]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [gradle]
gradle appears to be available on all versions: https://packages.debian.org/stretch/gradle

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [openjdk-7-jdk]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libceres-dev]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libcoin80-dev]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libfcl-dev]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libftdipp1-dev]
-sid

2017-06-24 00:15 UTC, tfoote commented on rosdep/base.yaml
> +    sid: [libgazebo7-dev]
-sid

2017-06-24 23:39 UTC, Alessandro-Barbieri commented
finished

2017-06-26 06:31 UTC, tfoote approved these changes

2017-06-28 15:28 UTC, merged