Ds4drv rosdep
ros/rosdistro pull request #15371
Opened 2017-06-26 19:20 UTC by cratliff

Adding a ds4drv rule to rosdep.  The wheel rule is included in this pull request as ds4drv does not install without wheel being installed too.  
I'm using ds4drv to control a robot from a Sony controller and need to be able to install these dependencies.

ds4drv
A Sony DualShock 4 userspace driver for Linux
https://pypi.python.org/pypi/ds4drv/0.5.1

wheel
A built-package format for Python
https://pypi.python.org/pypi/wheel/0.30.0a0

2017-06-26 19:28 UTC, tfoote requested changes

2017-06-26 19:28 UTC, tfoote commented on rosdep/python.yaml
> +ds4drv:
If this is pip only it should have `-pip` at the end.

2017-06-26 19:28 UTC, tfoote commented on rosdep/python.yaml
> +wheel:
Wheel is available from native packages we prefer those than pip versions. 

https://packages.ubuntu.com/xenial/python-wheel
https://packages.debian.org/stretch/python-wheel
https://admin.fedoraproject.org/pkgdb/package/rpms/python-wheel/
https://packages.gentoo.org/packages/dev-python/wheel

2017-06-26 20:13 UTC, cratliff commented on rosdep/python.yaml
> +wheel:
I changed the rule to use the packages you listed instead of pip.  Did I miss where these preferences are documented or would it be good to do so?

2017-06-26 21:10 UTC, tfoote commented on rosdep/python.yaml
> +wheel:
Thanks. Unfortunately it's not well documented. I've added a few simple things here: https://github.com/ros/rosdistro/pull/15373

2017-06-26 21:45 UTC, tfoote approved these changes

2017-06-26 21:45 UTC, merged

2017-06-27 00:22 UTC, mikaelarguedas commented
What about the `ds4drv` pip entries for debian ? (and other platforms?)

2017-06-27 13:37 UTC, cratliff commented
I would be fine to add that if you want.  I noticed a number of other rules only had one OS entry and thought they might just be getting added as needed.

2017-06-27 19:07 UTC, tfoote commented
Having the full spread across platforms is less important for pip rules since they cannot be used for packaging. They only need to be available in the expected development environments. But in general they're good to have.