Added [python-crypto] & [python3-crypto] keys for OSs
ros/rosdistro pull request #15389
Opened 2017-06-27 23:52 UTC by zarecor60

Added [python-crypto] & [python3-crypto] keys for OSs [yakkety] & [artful]

2017-06-27 23:56 UTC, tfoote approved these changes

2017-06-27 23:57 UTC, tfoote requested changes
This is out of alphabetical order, and looking at it now we're missing zesty in the middle too.

2017-06-28 00:21 UTC, zarecor60 commented
Ah, didn't realize these were by alphabetical instead of release order. Updated as requested.

2017-06-28 00:29 UTC, mikaelarguedas commented
The check fail because of trailing whitespaces on the [xenial_python3](https://github.com/ros/rosdistro/pull/15389/files#diff-701c2f61a9f7ac8fc393ccc6630c8fa5R634) entry

2017-06-28 00:33 UTC, closed without merging