Add pip key for pylint and deb key for uncrustify
ros/rosdistro pull request #15480
Opened 2017-07-11 20:45 UTC by jlack1987

2017-07-11 21:19 UTC, tfoote requested changes

2017-07-11 21:19 UTC, tfoote commented on rosdep/python.yaml
> +pylint-pip:
We already have python-pylint. If a native packaged version is available we generally use that following our guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

2017-07-11 21:19 UTC, tfoote commented on rosdep/base.yaml
> +  debian: [uncrustify]
Please add: 

Fedora: https://apps.fedoraproject.org/packages/uncrustify
Gentoo: https://packages.gentoo.org/packages/dev-util/uncrustify

2017-07-12 15:56 UTC, jlack1987 commented on rosdep/base.yaml
> +  debian: [uncrustify]
Done, thanks!

2017-07-12 17:23 UTC, tfoote approved these changes

2017-07-12 17:36 UTC, merged