Add python-tqdm dependency for progress bars
ros/rosdistro pull request #15562
Opened 2017-07-18 16:40 UTC by cglwn

See corresponding issue #15561 for motivation, use cases, and links to web listings for this package.

This is my first pull request into this repo. Please let me know if there's any changes or more information needed as I would like to get this in soon. :smile:

2017-07-18 16:49 UTC, mikaelarguedas commented
this looks good!

A few remarks:
- ros packages can be released only if its dependencies are available via the default package manager (e.g. apt for ubuntu and debian). As it stands, tqdm being available in apt only since yakkety, you will not be able to release a package depending on this in any of the existing ROS distributions (please see [REP3](http://www.ros.org/reps/rep-0003.html) for the list of targeted platform for each ROS diistribution)
  - Though you will be able to use this key to build from source

- We don't have any "alive" ROS Distribution targetting ubuntu versions older than Ubuntu Saucy (Indigo), if you are not planning on building from source on platform older than Saucy there is no need to add a rule for it

2017-07-18 18:34 UTC, Alessandro-Barbieri requested changes

2017-07-18 18:34 UTC, Alessandro-Barbieri commented on rosdep/python.yaml
> +    yakkity: [python-tqdm]
`yakkety`

2017-07-18 18:36 UTC, cglwn commented on rosdep/python.yaml
> +    yakkity: [python-tqdm]
Fixed, thanks for catching :+1:!

2017-07-18 18:38 UTC, cglwn commented
@mikaelarguedas I only added python-tqdm to make dependency management easier for source building and currently don't have any plans to release binaries in the near-term. The lack of ability to distribute it in binaries should be fine for my use case.

I've deleted the key-value pairs for the old Ubuntu versions in b92447c.

2017-07-18 18:44 UTC, Alessandro-Barbieri requested changes

2017-07-18 18:44 UTC, Alessandro-Barbieri commented on rosdep/python.yaml
> +  debian: [python-tqdm]
can you specify `stretch` and `buster`?

2017-07-18 18:50 UTC, cglwn commented on rosdep/python.yaml
> +  debian: [python-tqdm]
:+1:

2017-07-18 21:46 UTC, mikaelarguedas approved these changes
lgtm, thanks @cglwn for the quick iteration

2017-07-19 12:05 UTC, cglwn commented
Could this go in? I'm setting up CI for my project now which would be a lot simpler if this were in.

2017-07-19 15:43 UTC, mikaelarguedas commented
Rosdep keys need 2 approvals to get merged, a member of the team will review and 'squash and merge' this PR soon

2017-07-19 15:56 UTC, merged

2017-07-19 16:00 UTC, cglwn commented
Thanks for showing me the ropes and for the quick turnaround times @mikaelarguedas and @dirk-thomas!