[rosdep] Add lzma compression library
ros/rosdistro pull request #16351
Opened 2017-11-13 10:41 UTC by ipa-fez

Adds the lzma compression library

Debian: https://packages.debian.org/en/sid/liblzma-dev
Ubuntu: https://packages.ubuntu.com/en/trusty/liblzma-dev

2017-11-13 13:40 UTC, dirk-thomas approved these changes

2017-11-13 16:24 UTC, mikaelarguedas requested changes
please use `liblzma-dev` as the key name as the packages `lzma` and `lzma-dev` also exist in ubuntu/debian (https://packages.ubuntu.com/search?keywords=liblzma-dev&searchon=names&suite=all&section=all, https://packages.ubuntu.com/search?keywords=lzma-dev&searchon=names&suite=all&section=all

2017-11-13 20:55 UTC, tfoote commented
It looks like there's a fedora package: https://apps.fedoraproject.org/packages/lzma/overview/

2017-11-14 08:05 UTC, mikaelarguedas approved these changes

2017-11-14 15:49 UTC, merged