Adding ros_yesense_imu to documentation index for kinetic
ros/rosdistro pull request #16527
Opened 2017-12-03 13:24 UTC by wangzhecoder

I'd like my ros_yesense_imu to be indexed and documented on ros.org

2017-12-03 19:13 UTC, dirk-thomas commented on kinetic/distribution.yaml
> +      url: https://github.com/ros-industrial/abb.git
Please revert this unrelated change.

2017-12-03 19:13 UTC, dirk-thomas commented on kinetic/distribution.yaml
> +      url: https://github.com/wangzhecoder/ros_yesense_imu.git
Same here.

2017-12-03 19:14 UTC, dirk-thomas requested changes
See other comments.

2017-12-11 08:32 UTC, tfoote commented
Closing due to no response in over a week. Please comment back here and we can reopen if you remove the unrelated changes from the PR. We'd be happy to index your project but your PR is mutating other packages.

2017-12-11 08:32 UTC, closed without merging