base: add RPi.GPIO as pip dependency
ros/rosdistro pull request #16545
Opened 2017-12-06 20:53 UTC by kyrofa

I didn't see any other examples in base.yaml that capitalizes the dependency names, so I kept it lower-case, even though the pip package itself is not. Please let me know if that should be changed.

2017-12-06 21:32 UTC, tfoote commented
This looks to be in ubuntu as of zesty: https://packages.ubuntu.com/zesty/python-rpi.gpio and debian as of buster: https://packages.debian.org/source/buster/rpi.gpio we should target those versions and keys. Also Fedora as of 26: https://admin.fedoraproject.org/pkgdb/package/rpms/python-rpi-gpio

2017-12-06 22:05 UTC, kyrofa commented
Updated.

2017-12-06 22:18 UTC, tfoote commented
Same yakkety and alphabetic requests here too.

2017-12-06 22:25 UTC, kyrofa commented
Fixed, thank you!

2017-12-06 23:29 UTC, tfoote approved these changes

2017-12-06 23:31 UTC, tfoote requested changes
Sorry I missed the key should be python-rpi.gpio here too.

2017-12-06 23:32 UTC, mikaelarguedas commented
bionic should be added here too

2017-12-07 00:50 UTC, kyrofa commented
Renamed and added bionic. Thanks you two!

2017-12-07 00:59 UTC, tfoote commented on rosdep/python.yaml
> +python-rpi.gpio:
Sorry one more tweak, with the rename it's out of alphabetical order now.

2017-12-07 01:04 UTC, kyrofa commented
Ugh, duh, fixed, so sorry.

2017-12-07 01:28 UTC, tfoote approved these changes

2017-12-07 03:00 UTC, mikaelarguedas approved these changes

2017-12-07 03:01 UTC, merged

2020-04-20 16:27 UTC, mikaelarguedas commented
Apparently these apt packages are not available on non-arm platform.
https://packages.ubuntu.com/bionic/python-rpi.gpio
This makes rosdep fail on amd if a workspace contains a package declaring a dependency on this key.
<details><summary> Error message </summary>

```
executing command [apt-get install python-rpi.gpio]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-rpi.gpio
E: Couldn't find any package by glob 'python-rpi.gpio'
E: Couldn't find any package by regex 'python-rpi.gpio'
ERROR: the following rosdeps failed to install
  apt: command [apt-get install python-rpi.gpio] failed
```
</details>

Pip seems happy to install regardless of the architecture.

@tfoote @kyrofa WDYT ? should we change this key to be a pip only key ? (I doubt any package is released using this as it would fail on all non-arm archs)

2020-04-20 16:39 UTC, kyrofa commented
I'm still only using the pip version, so I don't have strong feelings either way.