Update python.yaml
ros/rosdistro pull request #16678
Opened 2018-01-03 10:09 UTC by reinzor

Added pypozyx pip candidate

2018-01-03 19:27 UTC, tfoote requested changes
I see the package here: https://pypi.python.org/pypi/pypozyx

Since it's pip only please add the `-pip` suffix to the rosdep key.  Do you expect it to work on platforms other than ubuntu if so adding rules for them might make sense too.

2018-01-04 08:56 UTC, reinzor commented
I added the -pip suffix. I have not tested the library on other platforms .

2018-01-09 13:00 UTC, reinzor commented
ping

2018-01-09 15:29 UTC, wjwwood approved these changes

2018-01-09 20:07 UTC, tfoote approved these changes

2018-01-09 20:08 UTC, merged