Added pyrebase to rosdep/python.yaml
ros/rosdistro pull request #16785
Opened 2018-01-19 06:24 UTC by rdelfin

This package provides a firebase client on python. It is useful for robots that use firebase as external storage.
Package: [https://pypi.python.org/pypi/Pyrebase](https://pypi.python.org/pypi/Pyrebase)

2018-01-19 07:26 UTC, tfoote requested changes
If this is pip only please use `-pip` as a suffix for the key.

Also note that it will not be available for packaging and release into debian packages as a dependency.

2018-01-19 16:25 UTC, rdelfin commented
Understood. The key name should be fixed now

2018-01-19 18:50 UTC, tfoote approved these changes

2018-01-20 16:15 UTC, mikaelarguedas approved these changes
lgtm

2018-01-20 16:15 UTC, merged