Add werkzeug to base.yaml
ros/rosdistro pull request #17279
Opened 2018-03-26 12:55 UTC by tdenewiler

Web development package used for creating simple web-based operator interfaces.

Package exists for arch, debian, fedora, gentoo, and ubuntu. I tested with `rosdep resolve werkzeug --os=<OS:version>` for all of those distributions. The `nosetests` all pass.

2018-03-26 13:12 UTC, tdenewiler commented
Arch: https://www.archlinux.org/packages/community/any/python-werkzeug/
Debian: https://packages.debian.org/search?keywords=python-werkzeug
Fedora: https://www.tenable.com/plugins/nessus/104941
Gentoo: https://packages.gentoo.org/packages/dev-python/werkzeug
Ubuntu: https://packages.ubuntu.com/search?keywords=python-werkzeug

I am not familiar with, and could not find packages for, the following:
osx, freebsd, opensuse, cygwin, slackware, rhel

2018-03-26 15:39 UTC, mikaelarguedas requested changes
Thanks @tdenewiler for providing the links and descroption.

As this is a Python package, it should be added to the python.yaml file and the name of the key should match the debian name aka `python-werkzeug`

2018-03-27 02:40 UTC, tdenewiler commented
I was under the wrong impression that `python.yaml` was for pip packages only. The `werkzeug` packages were listed already, except for the `arch` OS. I have added that one only now.

2018-03-27 03:03 UTC, mikaelarguedas approved these changes
lgtm, thanks @tdenewiler !

2018-03-27 22:37 UTC, tfoote approved these changes

2018-03-27 22:37 UTC, merged