Adding my_repo_name to documentation index for distro
ros/rosdistro pull request #17586
Opened 2018-04-23 19:41 UTC by GunnerPatterson

I'd like my repo to be indexed and documented on ros.org.

2018-04-23 21:39 UTC, tfoote requested changes
There's some formatting issues with this that I commented on inline. However at bigger issue is that I looked into the repository and saw that the repository does not have any ROS packages in it. For the indexing to work it needs to have the formal structure of a ROS package such as a `package.xml` to be able to generate the metadata for indexing. http://wiki.ros.org/ROS/Tutorials/CreatingPackage

2018-04-23 21:39 UTC, tfoote commented on indigo/distribution.yaml
> +        -openni
You need a space after the `-`s

2018-04-23 21:39 UTC, tfoote commented on indigo/distribution.yaml
> +        depends:
This key is out of alphabetical order, it should be first.

2018-04-23 21:39 UTC, tfoote commented on indigo/distribution.yaml
> +        url: https://github.com/GunnerPatterson/ROS-Kinect-Autonomy
The url needs to end in `.git`

2018-04-23 21:39 UTC, tfoote commented on indigo/distribution.yaml
> +        version: indigo
There's no `indigo` branch only a `master` branch.

2018-05-25 09:50 UTC, mikaelarguedas commented
@GunnerPatterson friendly ping

2018-05-30 12:36 UTC, mikaelarguedas commented
Closing due to no response. @GunnerPatterson feel free to open a new PR once the comments have been addressed.

2018-05-30 12:36 UTC, closed without merging