Added python-boltons-pip
ros/rosdistro pull request #18268
Opened 2018-06-25 22:14 UTC by agdespopoulos

2018-06-25 23:05 UTC, tfoote requested changes
Because this has been packaged upstream we should target that version and possibly use pip for older distros only or explicitly backport it.

Ubuntu since Artful (also found in zesty manually)
https://packages.ubuntu.com/artful/python-boltons
Debian since Stretch
https://packages.debian.org/stretch/python-boltons

2018-06-26 20:30 UTC, agdespopoulos commented
Added packages for OS distributions that have it. Let me know if that's better.

2018-06-27 00:43 UTC, tfoote approved these changes

2018-06-27 01:30 UTC, mikaelarguedas approved these changes

2018-06-27 01:30 UTC, merged