added libmongoclient-dev
ros/rosdistro pull request #18483
Opened 2018-07-14 22:58 UTC by bbferka

C++ mongo client  legacy version added to base.yaml for Ubuntu bionic

2018-07-24 23:33 UTC, tfoote requested changes
Please add at least artful and cosmic. At some level I'd like to actually just add the generic rule not calling out the specific version as it's not going to break anyone on an older platform and will be future compatible. 

Following the contributing guide please add debian and fedora rules if you're planning to make a release in the future. 
I see https://packages.debian.org/stretch/libmongoclient-dev

2018-07-26 13:00 UTC, bbferka commented
Done. 

arful: https://packages.ubuntu.com/artful/libmongoclient-dev
cosmic: https://packages.ubuntu.com/cosmic/libmongoclient-dev

debian: https://packages.debian.org/stretch/libmongoclient-dev
fedora: https://apps.fedoraproject.org/packages/mongo-cxx-driver

Should I merge the ubuntu packages into as single entry then?

2018-07-26 21:57 UTC, tfoote commented
If you could make the ubuntu ones use the simpler rule that would be great. There's already a typo in the cosmic line.

2018-07-27 18:21 UTC, tfoote approved these changes
We don't keep an authoritative set of versions, we just syntax check them to make sure that the formatting is right.

2018-07-30 19:48 UTC, mikaelarguedas commented
@tfoote while this is released as a ros package on indigo and kinetic. Won't we have conflicts between rosdep keys and ros package if the package has a match in both?

I think we faced this in the past:
https://github.com/ros/rosdistro/pull/17461
https://github.com/ros/rosdistro/pull/17464

So my understanding is that the ubuntu rule added here should be modified to not match trusty or xenial

2018-08-24 15:56 UTC, dirk-thomas commented
> while this is released as a ros package on indigo and kinetic. Won't we have conflicts between rosdep keys and ros package if the package has a match in both?

@mikaelarguedas  Can you where you see the conflict? The ROS distros don't contain a package with `libmongoclient` in the name.

2018-08-24 15:56 UTC, dirk-thomas approved these changes

2018-08-27 22:35 UTC, dirk-thomas commented
I will go ahead and merge this as is.

@mikaelarguedas Please feel free to comment after the fact regarding the above question.

2018-08-27 22:35 UTC, merged