Adding python-imaging-imagetk
ros/rosdistro pull request #18538
Opened 2018-07-18 13:42 UTC by Minipada

Here is a link to ubuntu: packages:
https://packages.ubuntu.com/trusty/python-pil.imagetk

We have some display hardware  on which we load different screens. For tests purpose, we want to load those screens in simulation too and that's how we use this package

2018-07-25 01:33 UTC, tfoote requested changes
Following the Contributing guideline: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

Please also add the debian rules it's also available on all targets: https://packages.debian.org/stretch/python-pil.imagetk

If you have a moment to look for Fedora or Gentoo that would be great too.

2018-07-25 01:33 UTC, tfoote commented on rosdep/python.yaml
> +      artful: [python-pil.imagetk]
This indentation is incorrect. And please use the generic `ubuntu: [python-pil.imagetk]` since all versions are the same.

2018-07-25 23:56 UTC, tfoote commented
It should only be 2 indents per layer. Also please add the debian rule too.

2018-07-26 21:55 UTC, tfoote approved these changes

2018-07-26 21:56 UTC, tfoote commented
Thanks for iterating! lgtm

2018-07-26 21:59 UTC, Minipada commented
Sorry for the errors ... I don't know where my mind was ...

2018-07-26 22:01 UTC, merged