added python-termcolor for bionic for python 2 and 3
ros/rosdistro pull request #18809
Opened 2018-08-11 10:36 UTC by veimox

- https://packages.ubuntu.com/bionic/python-termcolor
- https://packages.ubuntu.com/bionic/python3-termcolor

- [x] rosdistro_reformat
- [x] nosetests

2018-08-13 23:00 UTC, tfoote commented
Same here please add zesty, artful and cosmic.

2018-08-20 14:30 UTC, mikaelarguedas requested changes

2018-08-20 14:30 UTC, mikaelarguedas commented on rosdep/python.yaml
> +    '*': [python-pyudev]
Copy-n-paste: this should be `python-termcolor`

2018-08-20 14:33 UTC, mikaelarguedas commented
> is just a coincidence or is there something against debian unstable?

As `sid` is a moving target it makes keeping the database up-to-date challenging.
From [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules):

`If there's a new distro in prerelease adding a rule for it is fine. However please don't target 'sid' as it's a rolling target and when the keys change our database gets out of date.`

2018-08-20 16:30 UTC, mikaelarguedas approved these changes
lgtm thanks @veimox for iterating

2018-08-21 01:11 UTC, merged