Add python subprocess32 package
ros/rosdistro pull request #18914
Opened 2018-08-21 20:59 UTC by bobhenz-jabil

https://packages.debian.org/stretch/python-subprocess32
https://apps.fedoraproject.org/packages/python-subprocess32
https://packages.gentoo.org/packages/dev-python/subprocess32
https://packages.ubuntu.com/bionic/python-subprocess32

2018-08-21 21:43 UTC, mikaelarguedas requested changes
@bobhenz-jabil thanks for contributing. Can you please provide a description of the package as well a the use cases you need it for as per [contribution guildelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions).

2018-08-21 21:43 UTC, mikaelarguedas commented on rosdep/python.yaml
> +  ubuntu: [python-subprocess32]
This package is not available on trusty, so we should explicitely set the rule to `null` for that platform

2018-08-21 21:43 UTC, mikaelarguedas commented on rosdep/python.yaml
> +  debian: [python-subprocess32]
This package is not available on jessie, so we should explicitely set the rule to `null` for that platform

2018-08-23 14:03 UTC, bobhenz-jabil commented
Brief Description: subprocess32 is a backport of the Py3 stdlib subprocess module for Py2. 

Use case: One of the very valuable features of this package is the ability to add a "timeout" parameter to various subprocess methods preventing calls to the system from hanging nodes indefinitely.

2018-08-23 16:48 UTC, mikaelarguedas approved these changes
lgtm thanks @bobhenz-jabil for iterating

2018-08-24 16:01 UTC, merged