[odb] added odb in base.yaml
ros/rosdistro pull request #19168
Opened 2018-09-23 16:09 UTC by veimox

Added for Ubuntu, Debian and Fedora.  

- [X] rosdistro_reformat
- [X] nosetests

- [Ubuntu](https://packages.ubuntu.com/search?keywords=odb)
- [Debian](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=odb)
- [Fedora](https://apps.fedoraproject.org/packages/s/odb)
- [Just in case](https://pkgs.org/download/odb)

2018-09-24 15:22 UTC, nuclearsandwich approved these changes

2018-09-24 17:35 UTC, mikaelarguedas requested changes
As this package is not available on Ubuntu Trusty (platform targeted by ROS Indigo that is still an active ROS distribution), we need to make a null entry for that platform as the dependency cannot be satisfied

2018-09-25 06:51 UTC, veimox commented
@mikaelarguedas I used wildcard for ubuntu and null trusty as in [here](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L407)

2018-09-25 18:30 UTC, tfoote approved these changes

2018-09-25 19:37 UTC, mikaelarguedas approved these changes
lgtm, thanks @veimox for iterating :+1:

2018-09-25 19:38 UTC, merged