Rosdep: Add libopenvdb for Bionic.
ros/rosdistro pull request #19198
Opened 2018-09-28 18:14 UTC by JWhitleyAStuff

2018-10-03 01:35 UTC, tfoote requested changes
Please link to the packages in the ubuntu repository for easier review and also fill in the other intermediate distros.

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions

2018-10-03 15:04 UTC, JWhitleyAStuff commented
Sorry about that, @tfoote. Ubuntu packages:

Artful: https://packages.ubuntu.com/artful/libopenvdb3.2
Bionic: https://packages.ubuntu.com/bionic/libopenvdb5.0

2018-10-11 00:40 UTC, tfoote approved these changes
Thanks that's frustrating how they change names each release. The source packages is at least the same: https://packages.ubuntu.com/source/bionic/openvdb

2018-10-16 14:12 UTC, mjcarroll approved these changes

2018-10-16 14:12 UTC, merged