Added ipython-notebook
ros/rosdistro pull request #19300
Opened 2018-10-18 07:08 UTC by reinzor

For analysis of bag data

2018-10-20 00:28 UTC, tfoote requested changes
This is not passing CI due to formatting. Please also add links for the package listed online. We also need at least a debian rule as well.

For guidance see https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

2018-10-22 13:29 UTC, reinzor commented
Added debian rule, cannot really figure out what is wrong with the formatting ..

2018-10-22 17:49 UTC, tfoote commented
It looks like the CI ran on the old commit again. Likely part of github's data consistency problems 
![image](https://user-images.githubusercontent.com/447804/47308977-0e122800-d5e8-11e8-814d-27384eea0d58.png)

I've retriggered the build: https://status.github.com/messages

2018-10-22 18:07 UTC, tfoote commented
I looked up the packages in the database and noticed that these names are only on older distros:

https://packages.ubuntu.com/search?keywords=ipython-notebook
https://packages.debian.org/search?keywords=ipython-notebook

The project has been renamed to jupyter and has been released as `jupyter-notebook` on all the newer platforms.
https://packages.ubuntu.com/search?keywords=jupyter-notebook
https://packages.debian.org/sid/jupyter-notebook

To that end we should use that key and add backwards compatibility for the older distros like this:
```
jupyter-notebook:
  ubuntu:
    '*': [jupyter-notebook]
    trusty: [ipython-notebook]
    xenial: [ipython-notebook]
```

On debian the legacy platform would similarly be jessie.

2018-10-23 22:23 UTC, tfoote approved these changes
Thanks for the update, lgtm.

2018-10-31 16:00 UTC, reinzor commented
Can this be merged?

2018-11-09 00:37 UTC, cottsay commented
If this key specifically targeting the executables and not the python library, please add:
```yaml
  fedora: [python3-notebook]
```
per https://apps.fedoraproject.org/packages/python3-notebook

2018-11-09 01:01 UTC, cottsay requested changes

2018-11-09 01:01 UTC, cottsay commented on rosdep/python.yaml
> +  ubuntu:
```suggestion
  fedora: [python3-notebook]
  ubuntu:
```

2018-11-09 20:50 UTC, cottsay approved these changes

2018-11-09 20:51 UTC, merged