Add libqwt6 package for ubuntu/bionic
ros/rosdistro pull request #19329
Opened 2018-10-23 13:20 UTC by pgorczak

Not sure about using *libqwt-dev* as suggested in #19327 since ROS melodic uses Qt5.

2018-10-23 22:58 UTC, tfoote commented
Hmm this needs to be homogenized with #19327 do we need a second key? @yotabits fyi

2018-10-25 09:33 UTC, pgorczak commented
Changed for backwards compatibility.

2018-10-30 02:01 UTC, tfoote requested changes
Thanks this looks good. Could you subsume #19327 switch to just use 'libqwt-dev' in a generic rule. Since all versions will be the same. It will make this much simpler overall.  And the qt5 version can be added as a separate key for side by side installation.

2018-11-01 11:00 UTC, pgorczak commented
Done that. Just linking back to 11593—that initially added the keys—for future reference.

2018-11-01 15:16 UTC, tfoote approved these changes

2018-11-27 14:30 UTC, clalancette approved these changes

2018-11-27 14:30 UTC, merged