Add python-graphitesend-pip and python-statsd
ros/rosdistro pull request #19365
Opened 2018-10-29 10:32 UTC by v-lopez

https://pypi.org/project/graphitesend/

2018-10-29 17:37 UTC, tfoote approved these changes

2018-11-09 00:57 UTC, cottsay commented
Looks like `python-statsd` exists on Fedora as well: https://apps.fedoraproject.org/packages/python-statsd
```yaml
  fedora: [python-statsd]
```
...should do the trick.

2018-11-09 00:59 UTC, cottsay requested changes

2018-11-09 00:59 UTC, cottsay commented on rosdep/python.yaml
> +  debian: [python-statsd]
```suggestion
  debian: [python-statsd]
  fedora: [python-statsd]
```

2018-11-09 01:00 UTC, cottsay commented on rosdep/python.yaml
> +  debian: [python-statsd]
I wish the suggestions UI had a better way to suggest additional lines, but this works...

2018-12-06 21:16 UTC, tfoote commented
@v-lopez could you accept the suggestion from cottsay and then we can merge this?

2018-12-06 21:22 UTC, v-lopez commented
Done

2018-12-06 21:24 UTC, cottsay approved these changes
Thanks!

2018-12-06 22:36 UTC, merged