Add bionic key for libvtk
ros/rosdistro pull request #19599
Opened 2018-12-04 20:43 UTC by pjreed

See https://packages.ubuntu.com/bionic/libvtk6-dev .

2018-12-05 13:48 UTC, nuclearsandwich approved these changes
I checked in and it doesn't appear that libvtk5 is packaged for Bionic so the version bump here is both warranted and the only option for carrying the key forward.

2018-12-06 11:00 UTC, tfoote requested changes
This would be another good candiate for wildcard syntax. It looks like everything after xenial can be covered using libvtk6-dev 

```
tfoote@snowman:~ Last: [0] (5s Seconds)
$ rmadison libvtk5-dev
 libvtk5-dev | 5.8.0-5               | precise/universe | amd64, armel, armhf, i386, powerpc
 libvtk5-dev | 5.8.0-14.1ubuntu3     | trusty/universe  | amd64, arm64, armhf, i386, powerpc, ppc64el
 libvtk5-dev | 5.10.1+dfsg-2.1build1 | xenial/universe  | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
tfoote@snowman:~ Last: [0] (5s Seconds)
$ rmadison libvtk6-dev
 libvtk6-dev | 6.0.0-6              | trusty/universe | amd64, arm64, i386, powerpc, ppc64el
 libvtk6-dev | 6.2.0+dfsg1-10build1 | xenial/universe | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
 libvtk6-dev | 6.3.0+dfsg1-11build1 | bionic/universe | amd64, arm64, armhf, i386, ppc64el, s390x
 libvtk6-dev | 6.3.0+dfsg2-2build4  | cosmic/universe | amd64, arm64, armhf, i386, ppc64el, s390x
 libvtk6-dev | 6.3.0+dfsg2-2build4  | disco/universe  | amd64, arm64, armhf, i386, ppc64el, s390x
```

2018-12-06 14:30 UTC, pjreed commented
I've also updated this one, and I updated the other `libvtk`-related rules while I was at it.

Note that xenial has both libvtk 5 and 6 packages.  `libvtk` and `libvtk-qt` were both set to 6, while `libvtk-java` was set to 5.  That seems a little weird, but I've updated it with the wildcard to preserve that behavior.

2018-12-06 20:27 UTC, tfoote approved these changes

2018-12-06 20:27 UTC, merged