Add bionic key for python-qt-bindings
ros/rosdistro pull request #19600
Opened 2018-12-04 20:47 UTC by pjreed

https://packages.ubuntu.com/bionic/libpyside-dev
https://packages.ubuntu.com/bionic/libshiboken-dev
https://packages.ubuntu.com/bionic/python-pyside
https://packages.ubuntu.com/bionic/python-qt4
https://packages.ubuntu.com/bionic/python-qt4-dev
https://packages.ubuntu.com/bionic/python-sip-dev
https://packages.ubuntu.com/bionic/shiboken
                                                                                                                                                                                                         ~

2018-12-05 13:46 UTC, nuclearsandwich approved these changes

2018-12-06 10:57 UTC, tfoote requested changes
It would be great to use the wildcard syntax to get all the recent versions and potentially future versions for this change too. See #19614 for a recent discussion and syntax so we can get better coverage from this rule.

2018-12-11 15:18 UTC, pjreed commented
Is there anything else that needs to be done for this and #19607?

2018-12-12 02:24 UTC, tfoote approved these changes

2018-12-12 02:26 UTC, merged