neonavigation_rviz_plugins: 0.3.0-0 in 'indigo/distribution.yaml' [bloom]
ros/rosdistro pull request #19827
Opened 2018-12-26 03:15 UTC by at-wat

Increasing version of package(s) in repository `neonavigation_rviz_plugins` to `0.3.0-0`:

- upstream repository: https://github.com/at-wat/neonavigation_rviz_plugins.git
- release repository: https://github.com/at-wat/neonavigation_rviz_plugins-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.6.9`
- previous version for package: `null`

## neonavigation_rviz_plugins

```
* Add trajectory_tracker_msgs plugin (#1 <https://github.com/at-wat/neonavigation_rviz_plugins/issues/1>)
  
    * Initial drop
    * Add CI
    * Fix build errors and warnings
    * Disable quaternion validation on indigo
    * Don't validate linear_velocity field
    * Add package README
    * Cleanup code
  
* Contributors: Atsushi Watanabe
```

## trajectory_tracker_rviz_plugins

```
* Add trajectory_tracker_msgs plugin (#1 <https://github.com/at-wat/neonavigation_rviz_plugins/issues/1>)
  
    * Initial drop
    * Add CI
    * Fix build errors and warnings
    * Disable quaternion validation on indigo
    * Don't validate linear_velocity field
    * Add package README
    * Cleanup code
  
* Contributors: Atsushi Watanabe
```

2019-01-03 15:07 UTC, clalancette requested changes
Needs changes as specified in https://github.com/ros/rosdistro/pull/19827#issuecomment-450875906

2019-01-07 02:43 UTC, at-wat commented
@clalancette thanks for looking into the package.

> If the files are heavily derived from existing code, then a pointer to that existing code would let us know where it is derived from.

Some of the files are derived from the rviz default plugin. It is noted in [the package's README](https://github.com/at-wat/neonavigation_rviz_plugins/blob/master/trajectory_tracker_rviz_plugins/README.md).
It would be better to also notify it in the top-level (meta-package's) README.

2019-01-07 21:47 UTC, clalancette approved these changes
Thanks for the update, this looks good to me now.  I'd just like one other review, then we can merge.

2019-01-08 06:43 UTC, tfoote commented
Thanks for iterating @at-wat

2019-01-08 06:43 UTC, merged

2019-01-08 06:59 UTC, at-wat commented
Thanks!