Add python-parameterized
ros/rosdistro pull request #19887
Opened 2019-01-09 05:39 UTC by agdespopoulos

2019-01-09 21:51 UTC, tfoote requested changes
This looks to be available in debian and ubuntu:

https://packages.debian.org/buster/python-parameterized
https://packages.ubuntu.com/bionic/python/python-parameterized

We should use those. Can you link to the other projects for example I'd expect fedora to use `python-parameterized` too. I found a reference here: https://src.fedoraproject.org/rpms/python-parameterized/blob/master/f/python-parameterized.spec

2019-01-09 21:52 UTC, tfoote commented
PS when you submit new rules please state your use case and link to the package listings to make checking them easier. https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

2019-01-09 22:39 UTC, agdespopoulos commented
Clearly my package searching skills need improvement, sorry about that. I've pushed with updates for using more native packages where possible.

In addition to the Debian and Ubuntu packages you linked, here's Fedora https://apps.fedoraproject.org/packages/python-parameterized

The python package being added is [Parameterized](https://github.com/wolever/parameterized), which makes writing parameterized tests in unittest/nose possible, making it easier to run test cases across a wide set of inputs and expected outputs.

2019-01-09 22:56 UTC, tfoote approved these changes
That looks like a great package to leverage for testing. 

Thanks for the update. I made a couple of tweaks to simplify the rules and make it future compatible using wildcard syntax.

2019-01-10 02:15 UTC, agdespopoulos commented on rosdep/python.yaml
> +  fedora: [python-arameterized]
Ugh. Good catch, thanks. Fixed.

2019-01-11 00:49 UTC, sloretz commented
@tfoote I notice there are also `python3-parameterized` packages in debian/ubuntu/fedora. Are `bionic_python3:` entries required for new rosdep keys?

2019-01-15 06:35 UTC, tfoote commented
@sloretz If python3 support is desired a new key should be created with `python3-parameterized` as the key and python3 package names. The python3_trusty was used in an early attempt to test with python3 but it requires you to use an os_override flag to change your distro detection to be used. We decided not to follow that route but left the legacy keys there to not break anyone who might still be using it. New rules shouldn't follow that pattern.

2019-01-15 16:36 UTC, agdespopoulos commented
I can add the python3 rules if you like, but I didn't because I don't use python3.

Is there anything else that I should do to get this ready to be merged?

2019-01-15 22:47 UTC, sloretz approved these changes

2019-01-15 22:48 UTC, merged