Fix libgtkmm install error on Ubuntu
ros/rosdistro pull request #20738
Opened 2019-03-28 08:15 UTC by Tiryoh

Fix libgtkmm install error on Ubuntu on the current rosdep rule.
This PR is related to the issue #20591.

2019-03-28 12:57 UTC, nuclearsandwich requested changes
The Debian package `libgtkmm-dev` doesn't exist either.
Of the listed packages, only Gentoo's package provides gtkmm2.4 or 3.x. I'd suggest renaming this rosdep key to libgtkmm-2.4-dev which matches our current practice of naming keys for Debian/Ubuntu packages. Aside from Debian, (and Gentoo as a special case) all other platforms resolve this key to the 2.x version of gtkmm. (Archlinux uses a separate gtkmm3 package for the 3.x)

2019-03-28 14:19 UTC, Tiryoh commented
> Aside from Debian, (and Gentoo as a special case) all other platforms resolve this key to the 2.x version of gtkmm.

Thanks for the information.
I don't have a Debian environment so I can't test the rosdep rule for Debian.
Is it OK for just editing without running test described [here](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)?

2019-03-28 16:42 UTC, nuclearsandwich commented
> I don't have a Debian environment with ROS installed, so I can't test the rosdep rule for Debian OS.
> Is it OK for just editing without running test described [here](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)?

As long as the package the key targets is linked for review (https://packages.debian.org/stretch/libgtkmm-2.4-dev for Debian stable) that should be sufficient.

2019-03-28 17:57 UTC, tfoote commented
Yeah, it does make sense to update it to use the standard key which matches the debian/ubuntu rule. And we should do a best effort to fill in the other platforms based on online listings.

2019-03-29 02:33 UTC, Tiryoh commented
I'll update the Debian rule too.

2019-03-29 12:49 UTC, nuclearsandwich commented
> I thought I needed to do an installation test after updating the rules...

It's always a good idea to test what you can easily test. But where it's not easy to test I have a lot of trust in the web-based package databases for Debian and Ubuntu. Thanks for doing your best!

2019-03-29 12:49 UTC, nuclearsandwich approved these changes

2019-03-29 23:17 UTC, merged