Python3-pip
ros/rosdistro pull request #20779
Opened 2019-04-01 06:43 UTC by Vuwij

Not completely sure about this one

https://packages.ubuntu.com/xenial/python3-pip
https://apps.fedoraproject.org/packages/python3-pip
https://packages.debian.org/stretch/python3-pip

2019-04-01 23:11 UTC, tfoote commented
What are you not sure about?

2019-04-02 03:01 UTC, Vuwij commented
> What are you not sure about?

Whether Is it ok to install python3 in rosdep

2019-04-02 18:53 UTC, tfoote requested changes
It's fine to install python3 system dependencies. Eventually all of them will be python3. 

Though there is a separate python.yaml where we've been putting python dependencies. Could you move the key into that file for consistency. Otherwise this looks fine.

2019-04-03 20:07 UTC, tfoote approved these changes

2019-04-03 20:38 UTC, cottsay approved these changes

2019-04-03 20:39 UTC, merged