rosdep/python: add python-bitarray
ros/rosdistro pull request #20788
Opened 2019-04-03 12:48 UTC by mgruhler

Description: Citing the [pypi doc](https://pypi.org/project/bitarray/):

> This module provides an object type which efficiently represents an array of booleans. Bitarrays are sequence types and behave very much like usual lists. Eight bits are represented by one byte in a contiguous block of memory. The user can select between two representations: little-endian and big-endian. All of the functionality is implemented in C. Methods for accessing the machine representation are provided. This can be useful when bit level access to binary files is required, such as portable bitmap image files (.pbm). Also, when dealing with compressed data which uses variable bit length encoding, you may find this module useful.

Provided as native builds for:

- [arch](https://aur.archlinux.org/packages/?O=0&K=python-bitarray)
- [debian](https://packages.debian.org/en/stretch/python-bitarray)
- [fedora](https://apps.fedoraproject.org/packages/python-bitarray)
- [gentoo](https://packages.gentoo.org/packages/dev-python/bitarray)
- [ubuntu](https://packages.ubuntu.com/search?lang=en&keywords=python-bitarray)

2019-04-03 20:14 UTC, tfoote approved these changes

2019-04-03 20:33 UTC, cottsay approved these changes

2019-04-03 20:35 UTC, cottsay requested changes
I believe that the AUR rule needs to be removed, as AUR packages are not actually system packages.

2019-04-04 14:42 UTC, mgruhler commented
@cottsay I removed the AUR rule. I'm not familiar with arch, so if you could direct me to where find arch system package, I'd be happy to add this.

On the other hand, I'm totally fine with only having ubuntu and debian taken care of :grin:

2019-04-08 18:59 UTC, cottsay approved these changes
This looks good now. Thanks!

2019-04-08 18:59 UTC, merged