Add frozendict
ros/rosdistro pull request #20781
Opened 2019-04-02 09:14 UTC by DaikiMaekawa

2019-04-02 15:21 UTC, nuclearsandwich commented
@DaikiMaekawa can you please update this pull request to comply with our contribution guidelines. Specifically can you please include links to the web listing for the added package in your pull request description.

2019-04-02 18:58 UTC, tfoote requested changes
In addition to adding links to the packages mentioned by @nuclearsandwich 

We also would like to make sure to at least cover debian and preferably fedora as well. And you can use the more compact format without adding a line for `packages`.

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

2019-04-03 06:29 UTC, DaikiMaekawa commented
Thanks for your quickly reply. 
I addressed your review comments. Please take a look at it.

2019-04-03 20:08 UTC, tfoote approved these changes

2019-04-03 20:37 UTC, cottsay approved these changes

2019-04-03 20:37 UTC, merged