toposens: 0.9.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #20948
Opened 2019-04-17 10:14 UTC by ts-adi

Increasing version of package(s) in repository `toposens` to `0.9.2-1`:

- upstream repository: https://gitlab.com/toposens/ros-projects/ts-ros.git
- release repository: https://gitlab.com/toposens/ros-projects/toposens-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.7.2`
- previous version for package: `null`

## toposens

```
* Fixed package versions
* Contributors: Adi Singh
```

## toposens_driver

```
* Fixed package versions
* Contributors: Adi Singh
```

## toposens_markers

```
* Fixed package versions
* Contributors: Adi Singh
```

## toposens_msgs

```
* Fixed package versions
* Contributors: Adi Singh
```

## toposens_pointcloud

```
* Fixed package versions
* Contributors: Adi Singh
```

2019-04-17 19:35 UTC, tfoote requested changes
It looks like both your source repository and release repositories are private. As such we cannot index them. Please make them public for us to be able to index them and build them. 

Also please take a moment to clean up the urls that I commented on. I suspect that the extra space will confuse some of our tools.

2019-04-17 19:35 UTC, tfoote commented on melodic/distribution.yaml
> +      url: 'https://gitlab.com/toposens/ros-projects/ts-ros.git '
This url is quoted with an extra space at the end which likely isn't going to work well.

2019-04-17 19:35 UTC, tfoote commented on melodic/distribution.yaml
> +      url: 'https://gitlab.com/toposens/ros-projects/ts-ros.git '
This url has an invalid space at the end too.

2019-04-26 14:28 UTC, clalancette commented
@ts-adi Please look at the review from Tully and make changes.  If we don't hear back from you in the near future, we'll close this pull request.  Thanks.

2019-04-29 09:09 UTC, ts-adi commented
Thanks for the feedback. I'll move everything to a public Github repo and will issue a new merge request from there. Closing this one.

2019-04-29 09:09 UTC, closed without merging