Adding cnn_bridge to documentation index for distro
ros/rosdistro pull request #21092
Opened 2019-05-06 14:08 UTC by wew84

2019-05-07 09:23 UTC, tfoote requested changes
Please see the link about making a release. If you only want to be indexed please just remove the release stanzas.

2019-05-07 09:23 UTC, tfoote commented on kinetic/distribution.yaml
> +      url: https://github.com/wew84/cnn_bridge.git
This is not a release repository. Did you intend to make a binary release? If so please follow: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

2019-05-07 09:23 UTC, tfoote commented on melodic/distribution.yaml
> +      url: https://github.com/wew84/cnn_bridge.git
This is also not a release repository. Note that if you use bloom then it will generate the PRs for you.

2019-05-10 12:14 UTC, wew84 commented
Created a proper release repo for release will rerelease

2019-05-10 12:14 UTC, closed without merging