fiducials: 0.11.0-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #21177
Opened 2019-05-09 22:26 UTC by rohbotics

Increasing version of package(s) in repository `fiducials` to `0.11.0-1`:

- upstream repository: https://github.com/UbiquityRobotics/fiducials
- release repository: https://github.com/UbiquityRobotics-release/fiducials-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.8.0`
- previous version for package: `null`

## aruco_detect

```
* Compatibilty with Melodic
  
  remove opencv3 dependancy, opencv3 is no longer a package in melodic, so we use cv_bridge
  
  Fix build on OpenCV 3.2
* Import empy with full path to avoid pip conflict
* Use subprocess for cairosvg to avoid lack of python2 support
* call genMarker with correct arguments with no joblib
* Check ignoreID's in TF publishing
* Added topic that enables/disables Aruco detections
* Added rosdeps for cairo and joblib
* Add params for determining weighting of observations; prevent compiler warnings
* add cli argument for paper size to create markers
* Contributors: Jack Kilian, Jim Vaughan, Rohan Agrawal, Tim Übelhör, jack
```

## fiducial_msgs

- No changes

## fiducial_slam

```
* Compatibilty with Melodic, remove opencv3 dependancy
  opencv3 is no longer a package in melodic, so we use cv_bridge
  to get the correct opencv transitively
* New fusion with planar-based error estimation
  * Estimate variance of fiducial obsevations based on how well they place the robot on the floor upright
  * use Kalman + David method of fusing estimates
  * split out Transform with Variance, do some cleanup
  * Simple unit tests for core fusion code
  * remove hokey outlier rejection
* Add support for overriding covariance diagonal
* Add fiducial transform array stamp (#156 <https://github.com/UbiquityRobotics/fiducials/issues/156>)
* Add publish_tf rosparam functionality and updated launch file accordingly (#154 <https://github.com/UbiquityRobotics/fiducials/issues/154>)
  * Added publish_tf rosparam to disable publishing pose tf
  * Change default publish_tf to True and fix 'if' formatting
* Contributors: Jack Kilian, Jim Vaughan, Rohan Agrawal
```

## fiducials

- No changes

2019-05-10 02:09 UTC, tfoote commented
Holding for sync: https://discourse.ros.org/t/preparing-for-melodic-sync-2019-05-09/9095

2019-05-14 14:17 UTC, clalancette requested changes
Source, doc, and status are optional but encouraged.

2019-05-14 14:17 UTC, clalancette commented on melodic/distribution.yaml
> +    release:
Do you want to add a source, doc, and status, similar to what is done in Kinetic?

2019-05-19 17:15 UTC, closed without merging

2019-05-19 17:17 UTC, rohbotics commented
Replaced by https://github.com/ros/rosdistro/pull/21264