Add mesa-utils
ros/rosdistro pull request #21205
Opened 2019-05-10 13:15 UTC by BMarchi

2019-05-14 18:15 UTC, nuclearsandwich requested changes
Please review the [contribution guidelines for rosdep rules](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) and update your PR to conform with them.

2019-05-17 23:10 UTC, sloretz commented
Looks like the gentoo equivalent would be `x11-apps/mesa-progs` https://packages.gentoo.org/packages/x11-apps/mesa-progs  and the fedora equivalent is `glx-utils` https://apps.fedoraproject.org/packages/glx-utils . Mind adding these to your PR?

2019-05-20 19:24 UTC, BMarchi commented
Will do, thanks for the correction

2019-05-28 12:17 UTC, clalancette approved these changes

2019-05-28 22:51 UTC, sloretz approved these changes

2019-05-28 22:51 UTC, merged