Add python-pycodestyle
ros/rosdistro pull request #21203
Opened 2019-05-10 13:06 UTC by BMarchi

2019-05-14 18:16 UTC, nuclearsandwich requested changes
Please review the [contribution guidelines for rosdep rules](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) and update your PR to conform with them.

2019-05-17 16:06 UTC, nuclearsandwich commented
Added an Archlinux key https://www.archlinux.org/packages/community/any/python2-pycodestyle/

2019-05-17 16:06 UTC, nuclearsandwich approved these changes
Thanks for updating your PRs @BMarchi!

2019-05-17 17:26 UTC, cottsay approved these changes

2019-05-17 17:27 UTC, merged