[dep] Add pymodbustcp.
ros/rosdistro pull request #21239
Opened 2019-05-15 23:54 UTC by 130s

- Since it's listed on PyPi https://pypi.org/project/pyModbusTCP/ I assume it's available on some following distros that seem to be commonly registered on this python.yaml.
  - debian
  - fedora
  - ubuntu
- Manually confirmed:
  - osx

2019-05-16 00:00 UTC, 130s commented
I have a question after reviewing [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions).

> - If a package is only available via pip use the -pip extension.

I'm not sure if this is possible, but if a package that used to be only available via `pip` becomes available from non-pip repository, wouldn't -pip suffix be confusing?

I didn't add -pip without knowing this requirement. I'm fine to update but would like to hear the thoughts first.

2019-05-17 01:04 UTC, tfoote requested changes
If the package becomes available via non-pip packaging paths then we will create a new key. Usually the alternative packaging approach will be a downgrade from the latest in pip and those expecting the version in pip could get broken by switching the requirement.

2019-05-17 06:54 UTC, 130s commented
I see. Updated with `-pip` suffix.

2019-05-20 23:55 UTC, tfoote approved these changes
Thanks for the update lgtm

2019-05-28 12:35 UTC, clalancette approved these changes

2019-05-28 12:35 UTC, merged