Add installation of librealsense2
ros/rosdistro pull request #21430
Opened 2019-06-02 11:20 UTC by doronhi

realsense2_camera depend on librealsense2 installation.
librealsense2 is not available yet in ubuntu's official release.
Therefor, to promote the release of realsense2_camera package I propose to add a script for librealsense2's installation here.

2019-06-10 21:49 UTC, tfoote requested changes
Unfortunately rdmanifests only work for source installations. They cannot be used as a dependency for released packages. And they're generally deprecated as they're quite fragile and often don't install/uninstall as cleanly as dependencies are expected to. And they are a pain to maintain on all platforms. (For example, for Melodic we have users on Stretch, Fedora, Gentoo, ...)

Can you give a summary of the packaging state of librealsense2? It's not upstream yet. Is it targeted for upstream? Is it in a PPA? What is the state of support on other platforms?

2019-06-11 10:56 UTC, doronhi commented
Hi,
librealsense2 is targeted for upstream but not in the foreseeable future.
In the meanwhile it is hosted on a PPA here: http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo
as described in the [installation guide](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md) 
What is the minimum requirements set for the installation to be part of rosdistro? Current location of debian package is enough? Adding it to Ubuntu PPA will be enough?

About the other platforms, I'm not sure I understand what you mean. librealsense2 is distributed for debians only (i.e. ubuntu)

2019-06-15 08:16 UTC, tfoote commented
Is this superseded by #21522

2019-06-15 19:18 UTC, cottsay commented
> librealsense2 is distributed for debians only (i.e. ubuntu)

librealsense 1.X and 2.X are both packaged in Fedora: https://apps.fedoraproject.org/packages/s/realsense. When the packages make it to Ubuntu, please include Fedora rules when you add rosdep keys.

2019-06-16 03:45 UTC, doronhi commented
This is superseded by #21522.

2019-06-16 03:45 UTC, closed without merging