Added geoalchemy2
ros/rosdistro pull request #21457
Opened 2019-06-04 17:37 UTC by agyoungs

This python module appears to be a debian binary in python 3, but not python 2

2019-06-06 16:05 UTC, cottsay requested changes
Hi! Please see the [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules) and update this change based on those guidelines. Off the top of my head, I can see that the key should end in `-pip`, and a link to the PyPI page in the change description would be appreciated.

Thanks!

2019-06-06 22:14 UTC, agyoungs commented
Just added `-pip` to the end of the tag.

[geoalchemy2](https://pypi.org/project/GeoAlchemy2/)

I needed this in a package that I'm working on that uses a SpatiaLite extended SQLite database. This library works with SQLAlchemy which is already included as a rosdep. It looks like it is available in 19.04 as a debian package, but only for python3 at the moment.

Thanks!

2019-06-06 22:16 UTC, agyoungs reviewed
Addressed changes from review (i.e. adding `-pip` to the end)

2019-06-21 13:20 UTC, clalancette requested changes
Small changes to the key.

2019-06-21 13:20 UTC, clalancette commented on rosdep/python.yaml
> +  ubuntu:
If we're doing a `-pip` package, we may as well add support for fedora and osx as well (like https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L157).  Thanks.

2019-07-16 12:54 UTC, clalancette commented
No response for almost a month, so I'm closing this.  If you'd still like to get this key in, feel free to reopen this PR and make the changes requested.  Thanks for the contribution.

2019-07-16 12:54 UTC, closed without merging