doosan_robot: 0.9.8-1 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #21572
Opened 2019-06-18 05:33 UTC by doosan-robotics

Increasing version of package(s) in repository `doosan_robot` to `0.9.8-1`:

- upstream repository: https://github.com/doosan-robotics/doosan-robot.git
- release repository: https://github.com/doosan-robotics/doosan-robot-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.8.0`
- previous version for package: `0.9.6-1`

## doosan_robot

- No changes

## doosan_robotics

- No changes

## dsr_control

- No changes

## dsr_description

- No changes

## dsr_example_py

```
* change dsr_example_py dir
* Contributors: doosan-robotics
```

## dsr_gazebo

- No changes

## dsr_launcher

- No changes

## dsr_msgs

- No changes

## moveit_config_m0609

- No changes

## moveit_config_m0617

- No changes

## moveit_config_m1013

- No changes

## moveit_config_m1509

- No changes

## robotiq_gazebo

- No changes

## serial_node_example

- No changes

2019-06-18 12:41 UTC, clalancette commented on kinetic/distribution.yaml
> -      - dsr_example_cpp
This is going to represent a regression for the users of the debian packages.  In particular, if they installed this package *before* this is synced, then they'll have access to the package, but nobody else will.  Is this what you mean to do?

2019-06-18 12:48 UTC, clalancette requested changes
Need a response about removing an already released package.

2019-06-19 06:41 UTC, doosan-robotics commented
How can I delete released package?

I want to release a newest version of our project.

2019-06-25 00:01 UTC, tfoote commented
We just want a confirmation that you're expecting this package to be deleted.

2019-07-09 06:25 UTC, closed without merging