Adding pipeline_planner to documentation index for distro
ros/rosdistro pull request #21612
Opened 2019-06-25 06:25 UTC by t-ogataseaos

I'd like my pipeline planner package to be indexed and documented on ros.org.

2019-06-25 13:15 UTC, clalancette requested changes
Probably needs changes for documentation, and holding for [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-06-24/9663)

2019-06-25 13:15 UTC, clalancette commented on kinetic/distribution.yaml
> +    source:
We can add this, but this does not add it to the documentation index.  If you want that, you need to add a `doc` section as well; see the `platform_automation_msgs` package just below for an example.

2019-06-26 01:06 UTC, t-ogataseaos commented
I've added doc section.
I'd like my pipeline planner package to be indexed and documented on ros.org.

2019-06-28 13:11 UTC, clalancette approved these changes

2019-06-28 13:12 UTC, merged