Adding libcereal-dev for non-boost serialization needs
ros/rosdistro pull request #21639
Opened 2019-06-28 00:33 UTC by pbeeson

We use serialization for some storage of large data types, but are trying to move away from Boost depends.  Cereal is a substitute for boost serialization that is lightweight and beats boost in benchmarks.

2019-06-28 13:29 UTC, clalancette requested changes
Can you please add in the links to the packages as requested in [CONTRIBUTING](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md)?  This just makes it easier for us to track the packages in the future.  Thanks.

2019-06-28 15:14 UTC, pbeeson commented
CONTRIBUTING doesn't specific WHERE to add such links.  Presumably not in
the yaml.

On Fri, Jun 28, 2019 at 8:29 AM Chris Lalancette <notifications@github.com>
wrote:

> *@clalancette* requested changes on this pull request.
>
> Can you please add in the links to the packages as requested in
> CONTRIBUTING
> <https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md>? This just
> makes it easier for us to track the packages in the future. Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros/rosdistro/pull/21639?email_source=notifications&email_token=AA5N7RXNC22VTMAISAG5BMLP4YG2ZA5CNFSM4H4BFQ52YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB47LQCQ#pullrequestreview-255768586>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5N7RURHJ2QNX7CPHQNI7DP4YG2ZANCNFSM4H4BFQ5Q>
> .
>

2019-06-28 15:18 UTC, pbeeson commented
https://packages.ubuntu.com/xenial/libcereal-dev
https://packages.debian.org/stretch/libcereal-dev
https://apps.fedoraproject.org/packages/cereal-devel

2019-06-28 15:20 UTC, clalancette commented
> CONTRIBUTING doesn't specific WHERE to add such links. Presumably not in the yaml.

Yeah, just in the description of the PR is where we expect it.  An update to CONTRIBUTING to specify where to add the links would be appreciated.

2019-06-28 15:21 UTC, clalancette approved these changes

2019-07-01 16:41 UTC, pbeeson commented
Just checking to see if there was anything else you were waiting on from me before this can get merged.  Thanks!

2019-07-01 17:14 UTC, clalancette commented
> Just checking to see if there was anything else you were waiting on from me before this can get merged. Thanks!

Nope, just waiting for a second approval, then we can merge.

2019-07-03 14:55 UTC, pbeeson commented
Not trying to be a jerk, but bumping this.  I have multiple entities waiting on a new feature, but I can't push to them until their install procedure automatically will install this system dep.

2019-07-03 16:26 UTC, jacobperron approved these changes

2019-07-03 16:26 UTC, merged

2019-07-03 19:45 UTC, pbeeson commented
I appreciate the help.  Thanks