Librabbitmq
ros/rosdistro pull request #21700
Opened 2019-07-05 10:04 UTC by Vuwij

https://pypi.org/project/librabbitmq/

2019-07-09 21:43 UTC, tfoote requested changes
This is a common library that's already packaged upstream, we should not use the pip version but the apt version: https://packages.ubuntu.com/search?keywords=librabbitmq

2019-07-10 04:06 UTC, Vuwij commented
Ah but i think there is a difference between the python pip version and the apt-get one. Think the python one has something like this

from librabbitmq import Connection

2019-07-10 14:00 UTC, clalancette commented
> Ah but i think there is a difference between the python pip version and the apt-get one. Think the python one has something like this

We highly prefer apt packages if possible.  When we go to build debian packages on the buildfarm, we can only properly resolve apt-installable packages (pip ones can't be installed by `apt-get` later on).

So that leads to the question: why is the `apt` one and the `pip` different?  Is it a matter of versioning, or are they packages from different authors?

2019-07-11 03:54 UTC, Vuwij commented
I think the files are different.
- librabbitmq is written for c in the apt-get update version
- pip install librabbitmq is written for python

drwxrwxr-x 5 common common   4096 Jul 11 12:51 .
drwxr-xr-x 9 common common   4096 Jul 11 12:51 ..
drwxrwxr-x 3 common common   4096 Jul 11 12:51 funtests
drwxrwxr-x 2 common common   4096 Jul 11 12:51 librabbitmq
drwxrwxr-x 2 common common   4096 Jul 11 12:51 librabbitmq-2.0.0.dist-info
-rwxr-xr-x 1 common common 642046 May 30  2018 _librabbitmq.so

./funtests:
total 28
drwxrwxr-x 3 common common 4096 Jul 11 12:51 .
drwxrwxr-x 5 common common 4096 Jul 11 12:51 ..
-rw-r--r-- 1 common common 1519 Mar  8  2018 config.py
-rw-r--r-- 1 common common  533 Mar  8  2018 disabled_basic_get_leak.py
-rw-r--r-- 1 common common   84 Mar  8  2018 __init__.py
-rw-r--r-- 1 common common 1425 Mar  8  2018 setup.py
drwxrwxr-x 2 common common 4096 Jul 11 12:51 tests

./funtests/tests:
total 16
drwxrwxr-x 2 common common 4096 Jul 11 12:51 .
drwxrwxr-x 3 common common 4096 Jul 11 12:51 ..
-rw-r--r-- 1 common common  149 Mar  8  2018 __init__.py
-rw-r--r-- 1 common common  504 Mar  8  2018 test_channel_errors.py

./librabbitmq:
total 20
drwxrwxr-x 2 common common 4096 Jul 11 12:51 .
drwxrwxr-x 5 common common 4096 Jul 11 12:51 ..
-rw-r--r-- 1 common common 8903 Mar  8  2018 __init__.py

./librabbitmq-2.0.0.dist-info:
total 24
drwxrwxr-x 2 common common 4096 Jul 11 12:51 .
drwxrwxr-x 5 common common 4096 Jul 11 12:51 ..
-rw-r--r-- 1 common common 3893 May 30  2018 METADATA
-rw-r--r-- 1 common common  971 May 30  2018 RECORD
-rw-r--r-- 1 common common   34 May 30  2018 top_level.txt
-rw-r--r-- 1 common common  109 May 30  2018 WHEEL

2019-07-11 07:23 UTC, Vuwij commented
The difference is I think, one is written for c only and the other contains python interfaces

2019-07-11 19:43 UTC, clalancette commented
> The difference is I think, one is written for c only and the other contains python interfaces

Ah, I see.  That's confusing, thanks for doing the digging.

In that case, and given the fact that this isn't available as apt packages, we'll want to make this pip-only then.  Please change the key name to end with `-pip`, and also add entries for fedora and osx.  Thanks!

2019-07-11 19:58 UTC, tfoote commented
Looking into the source repository description it appers to be python bindings for the c library: "Python bindings to librabbitmq-c" 

As such it should not be librabbitmq-pip but likely something like python-librabbitmq-pip and it likely also need a cross installer dependency on the c based librabbitmq unless the pip package vendors the c implementation.

2019-07-12 02:48 UTC, Vuwij commented
I am not 100% sure, I just tested it at it seems like it does not vendor so I added the base.yaml packages as well

rr@aragorn ~/ws/src/sootballs/applications/robot (jw_deployment_docker) $ sudo apt-get install librabbitmq-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  librabbitmq4
The following NEW packages will be installed:
  librabbitmq-dev librabbitmq4
0 upgraded, 2 newly installed, 0 to remove and 49 not upgraded.
Need to get 59.4 kB of archives.
After this operation, 267 kB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
rr@aragorn ~/ws/src/sootballs/applications/robot (jw_deployment_docker) $ pip install librabbitmq
Collecting librabbitmq
  Downloading https://files.pythonhosted.org/packages/cc/60/21de22227f7b15637010614498844311c6baef319913b03fcc4cc6728d34/librabbitmq-2.0.0-cp27-cp27mu-manylinux1_x86_64.whl (214kB)
    100% |████████████████████████████████| 215kB 1.9MB/s 
Collecting amqp>=1.4.6 (from librabbitmq)
  Downloading https://files.pythonhosted.org/packages/45/91/877ea2d1c3234dbb32e818d281615232468ff8a4a783a8fc264862b9f77b/amqp-2.5.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 6.3MB/s 
Collecting six>=1.0.0 (from librabbitmq)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting vine<5.0.0a1,>=1.1.3 (from amqp>=1.4.6->librabbitmq)
  Downloading https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Installing collected packages: vine, amqp, six, librabbitmq
Successfully installed amqp-2.5.0 librabbitmq-2.0.0 six-1.12.0 vine-1.3.0
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
rr@aragorn ~/ws/src/sootballs/applications/robot (jw_deployment_docker) $ sudo apt-get install librabbitmq-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  librabbitmq4
The following NEW packages will be installed:
  librabbitmq-dev librabbitmq4
0 upgraded, 2 newly installed, 0 to remove and 49 not upgraded.
Need to get 59.4 kB of archives.
After this operation, 267 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://jp.archive.ubuntu.com/ubuntu xenial/universe amd64 librabbitmq4 amd64 0.7.1-1 [33.7 kB]
Get:2 http://jp.archive.ubuntu.com/ubuntu xenial/universe amd64 librabbitmq-dev amd64 0.7.1-1 [25.7 kB]
Fetched 59.4 kB in 0s (803 kB/s)          
Selecting previously unselected package librabbitmq4:amd64.
(Reading database ... 330016 files and directories currently installed.)
Preparing to unpack .../librabbitmq4_0.7.1-1_amd64.deb ...
Unpacking librabbitmq4:amd64 (0.7.1-1) ...
Selecting previously unselected package librabbitmq-dev:amd64.
Preparing to unpack .../librabbitmq-dev_0.7.1-1_amd64.deb ...
Unpacking librabbitmq-dev:amd64 (0.7.1-1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Setting up librabbitmq4:amd64 (0.7.1-1) ...
Setting up librabbitmq-dev:amd64 (0.7.1-1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
rr@aragorn ~/ws/src/sootballs/applications/robot (jw_deployment_docker) $

2019-07-12 04:15 UTC, tfoote commented on rosdep/python.yaml
> +      packages: [librabbitmq]
You should add a depends tag onto the c implementation so that rosdep knows to install it first via apt.  Here and the other 2 distros below too.

2019-08-07 22:04 UTC, tfoote approved these changes

2019-08-09 15:41 UTC, clalancette approved these changes

2019-08-09 15:41 UTC, merged