added pymap3d pip package
ros/rosdistro pull request #21760
Opened 2019-07-15 10:24 UTC by ejalaa12

Added a new PIP package: **pymap3d** that contains various 3-D geographic coordinate conversions.

The pip package can be found here: https://pypi.org/project/pymap3d/

> Pure Python (no prerequistes beyond Python itself) 3-D geographic coordinate conversions. API similar to popular $1000 Matlab Mapping Toolbox routines for

2019-07-16 13:20 UTC, clalancette requested changes
Can you add entries for fedora and osx as well?  Thanks.

2019-07-17 18:11 UTC, ejalaa12 commented
sure ! Just did it :)

2019-07-17 21:58 UTC, nuclearsandwich approved these changes

2019-07-22 23:11 UTC, sloretz approved these changes

2019-07-22 23:11 UTC, merged