Adding new repository for indexing: amcl3d
ros/rosdistro pull request #22091
Opened 2019-08-26 10:26 UTC by pcarrascof

Adaptative Monte Carlo Localization (AMCL) in 3D.
Amcl3d is a probabilistic algorithm to localizate a robot moving in 3D.
It use a Monte-Carlo method, a particle filter. 
This package use a laser sensor and range sensor to localizate the UAV in a know map.

2019-08-26 23:54 UTC, tfoote requested changes
This repository appears to be empty

![Screenshot from 2019-08-26 16-53-12](https://user-images.githubusercontent.com/447804/63730897-0a5fbb00-c822-11e9-8bd8-ad932402ec54.png)

Please either release the code there or close this PR.

2019-08-27 11:19 UTC, pcarrascof commented
The code has been released on GitHub!

2019-08-27 11:34 UTC, clalancette requested changes
Needs two changes to pass CI.

2019-08-27 13:41 UTC, pcarrascof commented on kinetic/distribution.yaml
> +      version: 1.0
It has been changed

2019-08-28 05:33 UTC, pcarrascof commented on kinetic/distribution.yaml
> +      url: https://github.com/fada-catec/amcl3d.git
It's done!

2019-08-28 12:03 UTC, merged