add python-jmespath
ros/rosdistro pull request #22093
Opened 2019-08-27 10:22 UTC by jimmyshe

add rosdep rule for python-jmespath
It will be useful when robot need handle complicated json data.

2019-08-27 11:41 UTC, clalancette requested changes

2019-08-27 12:13 UTC, jimmyshe commented on rosdep/python.yaml
> +python-jmespath:
Should be alright now.

2019-08-27 12:30 UTC, clalancette approved these changes
Thanks for the changes, looks good to me now.

2019-08-28 12:09 UTC, nuclearsandwich approved these changes
Thanks for iterating!

2019-08-28 12:09 UTC, merged