hebi_description: 0.1.0-1 in 'melodic/distribution.yaml'
ros/rosdistro pull request #22214
Opened 2019-09-09 21:12 UTC by iamtesch

Increasing version of package(s) in repository hebi_description to 0.1.0-1:

upstream repository: https://github.com/HebiRobotics/hebi_description.git
release repository: https://github.com/HebiRobobitcs/hebi_description-release.git
distro file: melodic/distribution.yaml
bloom version: 0.8.0
previous version for package: null

## hebi_description
```
* Moved the hebiros_description package contents to new package
* Cleaned up contents and added robots
* Contributors: Matthew Tesch
```

2019-09-10 12:24 UTC, clalancette requested changes
Need to fix CI.

2019-09-10 12:24 UTC, clalancette commented on melodic/distribution.yaml
> +    status: developed
This is failing CI because there is trailing whitespace after "developed".  Please fix and we can proceed.

2019-09-10 16:05 UTC, iamtesch commented
apologies -- fixing now. Thanks for the quick review.

2019-09-11 19:34 UTC, clalancette approved these changes

2019-09-11 19:34 UTC, merged