Add rosdep rules for python3-bson
ros/rosdistro pull request #22333
Opened 2019-09-23 15:53 UTC by hidmic

Added rules for:

- [Debian](https://packages.debian.org/search?keywords=python3-bson)
- [Fedora](https://pkgs.org/download/python3-bson)
- [Gentoo](https://packages.gentoo.org/packages/dev-python/pymongo)
- [OSX](https://pypi.org/project/bson/)
- [Ubuntu](https://packages.ubuntu.com/search?keywords=python3-bson)

to match `python-bson` platform coverage. For Gentoo and OSX, the keys are the same as IIUC the Python version being targeted depends on OS configuration and package manager respectively, but I don't have boxes at hand to try this out.

2019-09-23 21:18 UTC, tfoote approved these changes
The gentoo ones looks odd, but matches the existing rule so I'll assum it's fine. @allenh1 FYI

2019-09-24 13:17 UTC, allenh1 requested changes
The Gentoo version is actually a custom ebuild we have in the overlay, `dev-python/bson`.

Added in ros/ros-overlay#574.

2019-09-24 14:18 UTC, hidmic commented
@allenh1 I see `dev-python/bson` made it here before and was shortly dropped in favor of `dev-python/pymongo` in https://github.com/ros/rosdistro/pull/17593, days after https://github.com/ros/ros-overlay/pull/574. I presume you mean that `dev-python/bson` is the right version for Python3+ installations. Can you confirm?

2019-09-24 21:58 UTC, allenh1 commented
@hidmic I'm honestly not sure myself at this point... Let's leave it at `dev-python/pymongo` and just see if things break, I think. I'll definitely hear about it shortly if things aren't working. ;)

2019-09-24 22:00 UTC, dirk-thomas approved these changes

2019-09-24 22:00 UTC, merged