Add pycollada to python dependencies
ros/rosdistro pull request #22475
Opened 2019-10-01 10:33 UTC by DavidMansolino

Add pycollada to python dependencies

2019-10-03 23:31 UTC, tfoote requested changes
Please read through the CONTRIBUTING.md file for guidelines for contributing rosdep rules.

A quick read through suggests the key name is inconsistent with pip entries. I think that there is likely native packages for this software that should be used instead of pip. And please provide links to the research you've done to identify the packages as well as identify your use case for a better understanding.

2019-10-04 08:18 UTC, DavidMansolino commented
@tfoote thank you for the constructive comment and pointers.

I think I have adressed all of them (description of the PR updated).

2019-10-04 17:25 UTC, cottsay commented
> ...please provide links to the research you've done to identify the packages...

We'd still like to see links to show that the package names are correct (again, see [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)). Thanks!

2019-10-04 20:51 UTC, DavidMansolino commented
Sorry for the missing links.

- **python-collada**
   - **debian**: https://packages.debian.org/search?keywords=python-collada
   - **ubuntu**: https://packages.ubuntu.com/search?keywords=python-collada&searchon=names
   - **fedora**: https://apps.fedoraproject.org/packages/python-collada
- **urdf2webots**
   - **all**: https://pypi.org/project/urdf2webots/

2019-10-04 20:56 UTC, cottsay commented
Thanks, @DavidMansolino.

It looks like the Debian and Ubuntu packages are Python 2, and the Fedora package is Python 3. Which Python version do you want for `collada`?

Either way, they should be consistent. If you want python 2, you'll have to drop the Fedora rule, since Fedora is no longer packaging Python 2 packages.

2019-10-04 21:11 UTC, DavidMansolino commented
Actually, I would need both (as I will use them for ROS melodic and ROS Dashing). But that's fine if I only have Python2  for Fedora.
But about Python3 for Ubuntu and Debian, should I fallback to pip?

2019-10-04 21:27 UTC, cottsay commented
> Actually, I would need both...

Since you still want a `python-collada` that targets Python 2, you should just drop the Fedora rule from that key.

> ...about Python3 for Ubuntu and Debian, should I fallback to pip?

Since Ubuntu and Debian may someday get an official Python 3 package, I think it would be best to introduce a separate `python3-collada-pip` key (covering Debian, Fedora and Ubuntu).

2019-10-07 08:25 UTC, DavidMansolino commented
@cottsay thank you for your suggestions that perfectly make sense. I have modified the packages as you suggested and updated the links in the description of the PR.

2019-10-08 00:14 UTC, sloretz approved these changes

2019-10-08 01:18 UTC, tfoote approved these changes

2019-10-08 01:18 UTC, merged