jderobot-colortuner: 0.0.3-2 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #22480
Opened 2019-10-01 15:15 UTC by fqez

Increasing version of package(s) in repository `jderobot-colortuner` to `0.0.3-2`:

- upstream repository: https://github.com/JdeRobot/ColorTuner.git
- release repository: https://github.com/JdeRobot/ColorTuner-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.8.0`
- previous version for package: `null`

## jderobot_color_tuner

- No changes

2019-10-02 14:25 UTC, clalancette requested changes

2019-10-02 14:25 UTC, clalancette commented on kinetic/distribution.yaml
> +  jderobot-colortuner:
All packages should use `_`, rather than `-` in the name.

2019-10-03 13:08 UTC, clalancette commented
This is failing CI because it is not in alphabetical order; this should be after `jderobot_assets`.

While you are in there, I noticed that the name of the package inside here is `jderobot_color_tuner`, while the top-level name you've selected is `jderobot_colortuner`.  While this is allowed, it seems to make more sense to have those be the same.

2019-10-29 00:11 UTC, tfoote commented
@fqez I saw your reference from the upstream source. You only need to add an underscore and edit this file to insert it in the right alphabetical order to resolve the issues raised above. 

If you're not going to do that soon we'll close this out due to inactivity soon.

2019-11-05 19:25 UTC, clalancette commented
No activity in over a month, so I'll close this out.  If you still want to get this in, please respond to the review comments and re-open.  Thanks.

2019-11-05 19:25 UTC, closed without merging