Add python3-pyaudio
ros/rosdistro pull request #22623
Opened 2019-10-10 20:39 UTC by timrobotson

Add python3-pyaudio for all recent ubuntu distributions. Keep python-pyaudio as is.

This is necessary for the ROS2 branch of https://github.com/aws-robotics/aws-robomaker-sample-application-voiceinteraction/tree/ros2 

Package details: https://packages.ubuntu.com/bionic/python3-pyaudio

2019-10-22 12:59 UTC, nuclearsandwich requested changes
The `_python3` rosdep format is a remnant from an earlier attempt to share keys between python2 and python3 dependencies. Please add a new python3-pyaudio rodsep key instead. Then the ros2 branch of your package can use the python3 key and the ROS 1 branch can use a conditional dependency to support either python2 or python3 based on which is used by that distribution.

2019-10-22 17:49 UTC, timrobotson commented
Fixed. Links to pyaudio packages in this PR:

- Arch: https://www.archlinux.org/packages/community/x86_64/python-pyaudio/
- Debian: https://packages.debian.org/stretch/python3-pyaudio
- Fedora: https://fedora.pkgs.org/29/fedora-updates-x86_64/python3-pyaudio-0.2.11-1.fc29.x86_64.rpm.html
- Gentoo: https://packages.gentoo.org/packages/dev-python/pyaudio
- RHEL: https://www.rpmfind.net/linux/rpm2html/search.php?query=python3-pyaudio
- Ubuntu: https://packages.ubuntu.com/bionic/python3-pyaudio

2019-10-22 18:46 UTC, nuclearsandwich approved these changes

2019-10-23 13:50 UTC, clalancette approved these changes

2019-10-23 13:50 UTC, merged