cpswarm_msgs: 1.1.0-1 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #22875
Opened 2019-11-04 14:37 UTC by tropappar

Increasing version of package(s) in repository `cpswarm_msgs` to `1.1.0-1`:

- upstream repository: https://github.com/cpswarm/cpswarm_msgs.git
- release repository: https://github.com/cpswarm/cpswarm_msgs-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.9.0`
- previous version for package: `null`

## cpswarm_msgs

```
* Added: State event
* Added: Area division event
* Added: Target action
* Changed: Use stamped pose for actions
* Removed: Assigned CPS from tracking action
* Added: Valid flag for get waypoint service
* Fixed: Rename service files according to ROS best practices
* Contributors: Micha Sende
```

2019-11-05 19:44 UTC, clalancette requested changes
This repository seems to have a dependency on `swarmros`, but no such package seems to exist in Kinetic.  Is there a missing dependency here?

2019-11-06 15:53 UTC, tropappar commented
@amilankovich-slab: Could you resolve this issue?

2019-11-14 01:26 UTC, tfoote commented
Since this appears to be blocked, I'm going to close this for now. It can be reopened when the dependency is resolved.

2019-11-14 01:26 UTC, closed without merging

2019-11-22 13:01 UTC, tropappar commented
The dependency should be resolved now: https://github.com/ros/rosdistro/pull/23115
Could you please reopen the pull request?
Thanks!