Add objectpath dependency
ros/rosdistro pull request #22959
Opened 2019-11-11 15:46 UTC by joseluis12

Link: https://pypi.org/project/objectpath/

The agile query language for semi-structured data. #JSON

2019-11-13 23:00 UTC, tfoote commented
As in the [contributing guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md), can you explain what your use case is and why you need this particular library? Is this something that you expect many others to also need or want to deploy?

2019-11-27 14:58 UTC, nuclearsandwich requested changes
Please address @tfoote's comments.

2019-12-03 13:36 UTC, nuclearsandwich approved these changes

2019-12-04 13:43 UTC, clalancette approved these changes

2019-12-04 13:43 UTC, merged