wireless-tools
ros/rosdistro pull request #23060
Opened 2019-11-18 16:42 UTC by reinzor

Required for `wireless_monitor` https://github.com/ros-drivers/linux_peripheral_interfaces/pull/17

2019-11-19 01:04 UTC, tfoote requested changes
Please link to the upstream packages for contributed rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

2019-11-19 07:09 UTC, reinzor commented
Debian: https://packages.debian.org/stretch/wireless-tools
Fedora: https://rpmfind.net/linux/rpm2html/search.php?query=wireless-tools
Gentoo: https://packages.gentoo.org/packages/net-wireless/wireless-tools
Ubuntu: https://packages.ubuntu.com/bionic/wireless-tools

2019-11-22 11:10 UTC, tfoote approved these changes

2019-11-27 14:16 UTC, nuclearsandwich commented
> [](https://packages.debian.org/stretch/wireless-tools)
> Fedora: [rpmfind.net/linux/rpm2html/search.php?query=wireless-tools](https://rpmfind.net/linux/rpm2html/search.php?query=wireless-tools)

My only concern is that the rpmfind query wasn't scoped to just Fedora. It's also not clear to me whether a distribution of "fedora" is enough to tell us that the package is available in Fedora upstream or if it's in a third party repository like RPMFusion. @cottsay do you know whether a url like https://rpmfind.net/linux/rpm2html/search.php?query=wireless-tools&submit=Search+...&system=fedora&arch= is comparable to 
https://apps.fedoraproject.org/packages/wireless-tools/ ?

2019-11-27 14:16 UTC, nuclearsandwich approved these changes

2019-11-27 14:16 UTC, merged