[dep] Add rsyslog.
ros/rosdistro pull request #23141
Opened 2019-11-24 02:07 UTC by 130s

`rsyslog` is an [alternative to `syslog` etc.](https://serverfault.com/questions/692309/what-is-the-difference-between-syslog-rsyslog-and-syslog-ng) and system monitoring tool can utilize its api.   

debian https://wiki.debian.org/Rsyslog
fedora https://rpmfind.net/linux/rpm2html/search.php?query=rsyslog&submit=Search+...&system=&arch=
gentoo https://wiki.gentoo.org/wiki/Rsyslog
macports [none](https://www.macports.org/ports.php?by=name&substr=rsyslog)
ubuntu https://packages.ubuntu.com/xenial/rsyslog

2019-11-25 13:39 UTC, clalancette requested changes
@130s can you please update the links in the description to point to the packages in the respective distributions, rather than just the wiki pages?  There are links in https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions to those package repositories.  Thanks.

2019-12-14 05:51 UTC, 130s commented
Sure. Entries in OP updated as following. I removed `gentoo` as I'm way too unfamiliar with it so I have no idea which web page it should list.

debian https://packages.debian.org/buster/rsyslog
fedora https://rpmfind.net/linux/rpm2html/search.php?query=rsyslog&submit=Search+...&system=&arch=
macports [none](https://www.macports.org/ports.php?by=name&substr=rsyslog)
ubuntu https://packages.ubuntu.com/xenial/rsyslog

2019-12-16 18:18 UTC, cottsay approved these changes
Here's the official Fedora package link: https://apps.fedoraproject.org/packages/rsyslog

2019-12-17 15:25 UTC, clalancette approved these changes

2019-12-17 15:25 UTC, merged