Add Python 3 entry for imageio
ros/rosdistro pull request #23169
Opened 2019-11-27 10:23 UTC by sgvandijk

Python 3 entry for imageio, the library to for reading and writing image, video, scientific, and volumetric data formats.

* Debian: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-imageio

    This package is only available since Buster, should it cater for older versions as well? I assume that for those the Python 2 version is more relevant

* Fedora and Gentoo: use same as original Python 2 entry which should install the Python 3 versions

* Ubuntu: https://packages.ubuntu.com/search?keywords=python3-imageio&searchon=names&suite=all&section=all

    Similar question as for Debian, only available since Bionic

2019-11-27 14:09 UTC, nuclearsandwich requested changes
>     * This package is only available since Buster, should it cater for older versions as well?

If the package isn't available in the platform repository it can't be released onto the buildfarm. As long as your use case is covered by the support platforms I don't think we need to backfill with pip keys. Leaving the earlier distros undefined makes sense to me.

Let's avoid mixing pip keys with platform keys and remove the Fedora entry since the package isn't available there.

2019-11-27 14:19 UTC, sgvandijk commented
Thanks for the feedback :+1: I removed the Fedora entry

2019-11-27 14:47 UTC, nuclearsandwich approved these changes

2019-12-05 15:08 UTC, clalancette approved these changes

2019-12-05 15:08 UTC, merged