duckbot-ros: 0.0.1-2 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #23275
Opened 2019-12-11 05:59 UTC by sachinkum0009

Increasing version of package(s) in repository `duckbot-ros` to `0.0.1-2`:

- upstream repository: https://github.com/sachinkum0009/duckbot-ros.git
- release repository: https://github.com/sachinkum0009/duckbot-ros.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.9.0`
- previous version for package: `null`

## duckbot

```
* bug 0 algo
* changed the dockerfile
* no check
* ubuntu 16
* few changes
* again
* let's try with 18.04
* remove q
* added y
* added git
* removed git
* few changes
* added the git install
* added ubuntu
* added ubuntu 16:0
* added docker file
* some minor changes
* obstacle avoidance
* Added the left front and right front wheels.
* Working fine
* some major changes
* Merge branch 'master' of https://github.com/SACHINKUMARHACKER/duckbot-ros
* added travis
* Added the image for demonstration
* added image of duckbot
* first commit
* initial commit
* Contributors: SACHINKUMARHACKER, Sachin Kumar
```

2019-12-17 01:40 UTC, tfoote requested changes
http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Creating_a_Release_Repository

2019-12-17 01:40 UTC, tfoote commented on kinetic/distribution.yaml
> +      url: https://github.com/sachinkum0009/duckbot-ros.git
It looks like you have used the same repository for the upstream as well as the release repository. This is highly not recommeded. The release repositories snapshot the upstream repositories and create a lot of tags and branches that are distracting for development and significantly slow down development by significantly increasing the repository size each release. Please redo this following the instructions carefully about setting up a separate release repository.

2019-12-17 02:34 UTC, sachinkum0009 commented
Okay
I will definitely do it

On Tue, Dec 17, 2019 at 7:10 AM Tully Foote <notifications@github.com>
wrote:

> *@tfoote* requested changes on this pull request.
>
>
> http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Creating_a_Release_Repository
> ------------------------------
>
> In kinetic/distribution.yaml
> <https://github.com/ros/rosdistro/pull/23275#discussion_r358558941>:
>
> > @@ -2678,6 +2678,14 @@ repositories:
>        url: https://github.com/naoki-mizuno/ds4_driver.git
>        version: master
>      status: maintained
> +  duckbot-ros:
> +    release:
> +      packages:
> +      - duckbot
> +      tags:
> +        release: release/kinetic/{package}/{version}
> +      url: https://github.com/sachinkum0009/duckbot-ros.git
>
> It looks like you have used the same repository for the upstream as well
> as the release repository. This is highly not recommeded. The release
> repositories snapshot the upstream repositories and create a lot of tags
> and branches that are distracting for development and significantly slow
> down development by significantly increasing the repository size each
> release. Please redo this following the instructions carefully about
> setting up a separate release repository.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros/rosdistro/pull/23275?email_source=notifications&email_token=AETCLCQLZFDWJDJS4CUYX3DQZAUXPA5CNFSM4JZJUBA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCPMOHQY#pullrequestreview-332981187>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETCLCTEQNWJW7HCGA5P3LTQZAUXPANCNFSM4JZJUBAQ>
> .
>

2020-01-08 19:25 UTC, tfoote commented
@sachinkum0009 Since you're planning to make a new release repository that will likely involve rerunning bloom and which will create a new PR here. As such I'm going to close this PR to clear up the clutter.

2020-01-08 19:25 UTC, closed without merging