Feature/liobgrpc
ros/rosdistro pull request #23437
Opened 2020-01-08 02:43 UTC by hakuturu583

add libgrpc package to the rosdistro

2020-01-08 02:45 UTC, hakuturu583 commented
I want to make GRPC-ROS bridge.
I want to add these packages below.

debian package is here : https://packages.debian.org/sid/libgrpc-dev
ubuntu package is here : https://packages.ubuntu.com/ja/bionic/arm64/libgrpc-dev
arch package is here : https://www.archlinux.org/packages/community/x86_64/grpc/
fedora package is here : https://apps.fedoraproject.org/packages/grpc-devel

2020-01-08 02:46 UTC, hakuturu583 commented
Oh ! I found it includes another commit, so I remove this change.(https://github.com/ros/rosdistro/pull/23437/commits/63e86b75f61428c47ec54b396e81583bc5a3b012)

2020-01-08 02:49 UTC, hakuturu583 commented
I removed mdrec
Please check it from file changed. (https://github.com/ros/rosdistro/pull/23437/files)

2020-01-08 08:06 UTC, tfoote approved these changes
Thanks for the PR and adding the links for reference. 

A more generic ubuntu link for review is here: https://packages.ubuntu.com/bionic/libgrpc-dev

2020-01-08 13:49 UTC, clalancette requested changes
The one slight problem here is that the `libgrpc-dev` package is only available on Debian for Buster, Sid, and Stretch-backports.  We don't usually allow keys to depend on the debian "backports" repository.  Since stretch is still supported, I think we need to split the debian key up so that it has a 'null' for stretch, and a '*' for everything else.

2020-02-04 15:31 UTC, nuclearsandwich commented
@hakuturu583 are you able to make the changes requested by @clalancette?

2020-02-06 23:49 UTC, tfoote commented on rosdep/base.yaml
> +  debian: [libgrpc-dev]
Filling in Chris' suggestion more concretely.
```suggestion
  debian:
    '*': [libgrpc-dev]
    stretch: null
```

2020-02-14 16:10 UTC, clalancette commented
No response from the original submitter for over a month, so I'm closing this.  @hakuturu583 , if you'd like to see this merged, please fix things according to @tfoote 's suggestion and re-open.

2020-02-14 16:10 UTC, closed without merging