Add google-glob, gazebo, lua52 and ceres-solver for Arch Linux
ros/rosdistro pull request #23528
Opened 2020-01-16 18:40 UTC by jhbruhn

Gazebo was not specified before. It is only available in the AUR, but as other system dependencies also specify gazebo for Arch it is fine.

2020-01-21 13:16 UTC, clalancette requested changes
Can you please edit the description and add links for all of these packages to the appropriate place on https://www.archlinux.org/packages/ ?  Thanks.

2020-01-21 13:42 UTC, jhbruhn commented
I added links to the packages in the description of the PR. About the AUR packages: In the base.yaml, 2 packages which are on the AUR have a arch.aur subkey. Should I specify them like that instead?

2020-01-22 13:24 UTC, clalancette commented
> About the AUR packages: In the base.yaml, 2 packages which are on the AUR have a arch.aur subkey. Should I specify them like that instead?

I honestly don't know what that means, sorry.  Maybe someone with some Arch experience can respond.

2020-01-22 19:48 UTC, tfoote requested changes
Unfortunately AUR packages don't meet our minimum requirement for Arch listings.

From CONTRIBUTING.md
>Packages must be in the official Archlinux core, extra, or community repositories at the time they are contributed.
> Packages in the AUR may not be added directly. Work has been proposed to add a separate installer for AUR packages ros-infrastructure/rosdep#560.

2020-01-29 18:56 UTC, jhbruhn commented
I have removed these dependencies now, but: for a lot of packages there are already dependencies on the AUR set in the base.yaml (e.g. gazebo7 has a arch: [gazebo] key which is on the AUR etc.). How did it come to this if the policy is to not accept AUR packages? IMO, ROS is pretty much unusable on Arch without those AUR packages.

2020-01-30 01:54 UTC, tfoote approved these changes
Yeah it's a little bit more limiting but AUR packages (and installation methods) have had much less stability. See more discussions in the linked thread.

2020-01-30 13:28 UTC, clalancette approved these changes

2020-01-30 13:28 UTC, merged