SwarmROS updated for building
ros/rosdistro pull request #23647
Opened 2020-01-29 08:46 UTC by amilankovich-slab

[Previously ](https://github.com/ros/rosdistro/pull/23586)SwarmROS did not build successfully, as some dependencies were mission. this is an attempt to fix that issue.

2020-01-30 01:40 UTC, tfoote requested changes
I noticed that the package.xml [shows 0.9.3 as the version](https://github.com/amilankovich-slab/swarmros/blob/86179063f45df659f1b5559adb80c17cbad46823/package.xml#L6)  but this PR is for 0.3.1

2020-01-30 01:40 UTC, tfoote commented on kinetic/distribution.yaml
> +  swarmros:
This section should be a subsection of the already existing swarmros entry.

2020-01-30 01:40 UTC, tfoote commented on kinetic/distribution.yaml
> +      url: https://github.com/amilankovich-slab/swarmros-release.git
The doc url should be a branch (preferred, but tag is ok) on the upstream repository. Usually it's the same as the source entry.

2020-02-06 23:41 UTC, tfoote commented on kinetic/distribution.yaml
> +      version: 0.3.1-4
This version needs to be a branch (or tag) in the upstream repo. Usually it's set to the same branch as the source entry above so `master`.
```suggestion
      version: master
```

2020-02-07 21:54 UTC, tfoote approved these changes
Thanks for the updates. this looks good to me now.

2020-02-07 21:55 UTC, tfoote commented
Sorry one last fixup is that the doc block needs to be at the top due to alphabetical ordering constraints.

2020-02-10 14:25 UTC, clalancette commented
Looks good now, but holding for [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-02-07/12677)

2020-02-14 00:12 UTC, merged