ros2_test: 0.0.1-2 in 'dashing/distribution.yaml' [bloom]
ros/rosdistro pull request #23685
Opened 2020-02-05 07:31 UTC by tiffany1994

Increasing version of package(s) in repository `ros2_test` to `0.0.1-2`:

- upstream repository: https://github.com/tiffany1994/ros2_test.git
- release repository: https://github.com/tiffany1994/ros2_test.git
- distro file: `dashing/distribution.yaml`
- bloom version: `0.9.0`
- previous version for package: `null`

## monitortool

- No changes

## mt_loadsimulator

- No changes

## ros2_msg

- No changes

## viewer

- No changes

2020-02-05 15:52 UTC, mjcarroll commented
It looks like, at a minimum, the upstream/release repository does not exist.

I would also generally advise against using the same repository for both purposes.

2020-02-05 18:02 UTC, nuclearsandwich requested changes
Please consider @mjcarroll's suggestions. If you're using bloom for the first time and having difficulty you can also ask questions on https://answers.ros.org

2020-02-05 18:19 UTC, tfoote requested changes
Two of these packages also don't meet our naming guides. `viewer` and `ros2_msg`

https://www.ros.org/reps/rep-0144.html
http://wiki.ros.org/ROS/Patterns/Conventions

2020-02-11 16:49 UTC, clalancette commented
I'm going to close this PR out, as there are enough issues here that a new PR is almost certainly warranted.  As mentioned previously, if you need help with getting this done please look at the documentation at http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease and https://index.ros.org/doc/ros2/Tutorials/Releasing-a-ROS-2-package-with-bloom/, and if you still have questions ask on https://answers.ros.org

2020-02-11 16:49 UTC, closed without merging