Adding new repository for indexing: jason-ros
ros/rosdistro pull request #23751
Opened 2020-02-12 12:48 UTC by Rezenders

2020-02-13 16:05 UTC, clalancette requested changes

2020-02-13 16:05 UTC, clalancette commented on melodic/distribution.yaml
> +  jason-ros:
We generally prefer underscores, so this should be: `jason_ros`.

2020-02-13 16:05 UTC, clalancette commented on melodic/distribution.yaml
> +      url: https://github.com/jason-lang/jason-ros
This is failing CI because it needs to end in `.git`.

2020-02-26 14:33 UTC, nuclearsandwich commented
@Rezenders do you intend to follow up on the requested changes or can we close this PR for now?

2020-03-04 16:19 UTC, nuclearsandwich commented
Closing the PR for now but feel free to re-open when you're ready to update it @Rezenders

2020-03-04 16:19 UTC, closed without merging

2020-03-08 22:13 UTC, Rezenders commented
Sorry about the delay. I fixed the issues and opened a new PR #23999