ridgeback_cartographer_navigation: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #23895
Opened 2020-02-27 05:07 UTC by tonybaltovski

Increasing version of package(s) in repository `ridgeback_cartographer_navigation` to `0.0.1-1`:

- upstream repository: https://github.com/ridgeback/ridgeback_cartographer_navigation.git
- release repository: https://github.com/clearpath-gbp/ridgeback_cartographer_navigation-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `null`

## ridgeback_cartographer_navigation

```
* Added ridgeback_navigation as run dep.
* Updated maintainer.
* Removed rviz to use ridgeback_viz.
* Merge pull request #3 <https://github.com/ridgeback/ridgeback_cartographer_navigation/issues/3> from ljazzal/master
  Updated dependencies to use cartographer_ros pkg instead of building from source
* minor changes to carto params, install instruction
* changed tracking frame back to imu_link
* updated cartographer demo to run with cartographer_ros
* added cartographer_ros as run_depend
* removed unused file
* added rviz config to launch
* config changes
* Update to use deb release of cartographer_ros
* Added generated map and brief description of Cartographer
* Added config and launch files to use Cartographer on the Ridgeback
* Contributors: Aditya Bhattacharjee, Tony Baltovski, ljazzal
```

2020-02-29 00:09 UTC, tfoote commented
Holding for [pending sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2020-02-26/12999?u=tfoote)

2020-03-02 16:10 UTC, clalancette requested changes

2020-03-02 16:10 UTC, clalancette commented on melodic/distribution.yaml
> +      url: https://github.com/ridgeback/ridgeback_cartographer_navigation.git
Can you please add a LICENSE file to the source repository?

2020-03-03 14:41 UTC, clalancette approved these changes

2020-03-03 14:41 UTC, merged