husky_cartographer_navigation: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #23894
Opened 2020-02-27 05:04 UTC by tonybaltovski

Increasing version of package(s) in repository `husky_cartographer_navigation` to `0.0.2-1`:

- upstream repository: https://github.com/husky/husky_cartographer_navigation.git
- release repository: https://github.com/clearpath-gbp/husky_cartographer_navigation-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `null`

## husky_cartographer_navigation

```
* Updated to package.xml format 2.
* Added husky_navigation as run dep.
* Contributors: Tony Baltovski
```

2020-02-29 00:09 UTC, tfoote commented
Holding for [pending sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2020-02-26/12999?u=tfoote)

2020-03-02 16:08 UTC, clalancette requested changes

2020-03-02 16:08 UTC, clalancette commented on melodic/distribution.yaml
> +      url: https://github.com/husky/husky_cartographer_navigation.git
Can you please add a LICENSE file to the source repository?

2020-03-03 14:40 UTC, clalancette approved these changes

2020-03-03 14:40 UTC, merged