Added rosdep entry for libnewmat10-dev
ros/rosdistro pull request #24023
Opened 2020-03-10 16:55 UTC by marioney

Modified rosdep/base.yaml file to add ubuntu and debian entries for libnewmat10-dev

2020-03-10 21:11 UTC, tfoote requested changes
Please link to the upstream packages for contributed rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md As well as look for other cross platform targets.

2020-03-11 14:42 UTC, marioney commented
The library is Available only on Debian and Ubuntu

- Alpine: [Not found](https://pkgs.alpinelinux.org/packages?name=*newmat*&branch=edge)
- Arch: [Not found](https://www.archlinux.org/packages/?sort=&arch=any&q=*newmat*&maintainer=&flagged=)
- Debian: [https://packages.debian.org/sid/libnewmat10-dev](https://packages.debian.org/sid/libnewmat10-dev)
- Fedora: [Not found](https://apps.fedoraproject.org/packages/s/*newmat*)
- Gentoo: [Not found](https://packages.gentoo.org/packages/search?q=*newmat*)
- Ubuntu: [https://packages.ubuntu.com/bionic/libnewmat10-dev](https://packages.ubuntu.com/bionic/libnewmat10-dev)

2020-03-12 13:33 UTC, clalancette approved these changes
Thanks for looking for at the other distributions.  Curious that it is only available on Debian derivatives, but c'est la vie.  Looks good to me.

2020-03-12 18:35 UTC, tfoote approved these changes

2020-03-12 18:35 UTC, merged