Adding remote_rosbag_record to documentation index for kinetic & melodic
ros/rosdistro pull request #24092
Opened 2020-03-16 02:04 UTC by yoshito-okada

2020-03-17 23:07 UTC, tfoote requested changes
Please check over the metadata you're hoping to index. I see the license is still listed as TODO in the package.xml

2020-03-17 23:29 UTC, yoshito-okada commented
@tfoote Sorry, I just fixed the problem.

2020-03-18 01:13 UTC, tfoote approved these changes
Thanks for the cleanup.

2020-03-19 21:54 UTC, sloretz approved these changes

2020-03-19 21:54 UTC, merged