add focal version for some base packages
ros/rosdistro pull request #24193
Opened 2020-03-22 17:48 UTC by flixr

Add ubuntu distro `focal` for some base packages:
* libfcl-dev
* libgsl
* libpng-dev
* protobuf

2020-03-22 23:59 UTC, tfoote requested changes
These all look like they have been stable across the last 2-3 LTS releases. To that end lets switch to use a wildcard notation for everything that's the same as the current release and only call out the older ones on the expectation that they will continue to remain static and will save us future maintenance.

2020-03-23 19:30 UTC, flixr commented
good idea, done...

2020-03-25 00:13 UTC, tfoote approved these changes
Thanks for the update. lgtm

2020-03-30 13:15 UTC, clalancette approved these changes

2020-03-30 13:15 UTC, merged