Add a rosdep rule for libopenal-soft
ros/rosdistro pull request #24275
Opened 2020-03-28 14:58 UTC by sktometometo

add libopenal-soft rule for arch, debian, fedora, gentoo and ubuntu.
- arch: https://www.archlinux.org/packages/extra/x86_64/openal/
- debian: https://packages.debian.org/ja/sid/libopenal-dev
- fedora: https://apps.fedoraproject.org/packages/openal-soft
- gentoo: https://packages.gentoo.org/packages/media-libs/openal
- ubuntu: https://packages.ubuntu.com/ja/xenial/libopenal-dev

This library is for playing spatial audio, and I am developing a ROS interface to it.

2020-03-31 13:44 UTC, clalancette requested changes
One change, then I'm happy to approve.

2020-03-31 13:44 UTC, clalancette commented on rosdep/base.yaml
> +  fedora: [openal-soft]
For Fedora, I think you want `openal-soft-devel` to get the development packages.

2020-03-31 22:17 UTC, tfoote requested changes
Same comment as @clalancette

2020-04-01 03:20 UTC, sktometometo commented
changed fedora entry to openal-soft-devel. Thank you for reviewing.

2020-04-01 12:17 UTC, clalancette approved these changes
You may want to consider adding a `libopenal` key that just has the runtime library.  That way your package can do a `<build_depend>` on `libopenal-dev`, and an `<exec_depend>` on `libopenal`.  But that doesn't block this change from going in, so approving.  Thanks.

2020-04-02 17:46 UTC, tfoote approved these changes

2020-04-02 17:46 UTC, merged