robosense_simulator: 1.0.0-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #24325
Opened 2020-04-02 09:47 UTC by tomlogan501

Increasing version of package(s) in repository `robosense_simulator` to `1.0.0-1`:

- upstream repository: https://github.com/tomlogan501/robosense_simulator.git
- release repository: https://github.com/tomlogan501/robosense_simulator_release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.3`
- previous version for package: `null`

2020-04-02 14:45 UTC, clalancette commented
CI failed here because the source entry version has to be a branch, not a tag.

2020-04-02 14:47 UTC, clalancette commented
Also, how does this relate to #24293 ?  They look to be the same package.  If that's the case, please close one in favor of the other.

2020-04-03 22:21 UTC, tfoote requested changes

2020-04-03 22:21 UTC, tfoote commented on melodic/distribution.yaml
> +      version: 1.0.0
This has to be a branch for the CI to be able to check it out.

2020-04-03 22:21 UTC, tfoote commented on melodic/distribution.yaml
> +  robosense_simulator:
You lost the doc section compared to #24293 I think it would make sense to add that back.

2020-04-06 07:34 UTC, tomlogan501 reviewed
It's updated

2020-04-06 12:33 UTC, clalancette requested changes

2020-04-06 12:33 UTC, clalancette commented on melodic/distribution.yaml
> +      url: https://github.com/tomlogan501/robosense_simulator_release.git
This should point to the source repository, not the release repository.

2020-04-08 16:34 UTC, merged