novatel_oem7_driver: 1.0.0-1 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #24520
Opened 2020-04-21 04:46 UTC by novatel-applications-engineering

Increasing version of package(s) in repository `novatel_oem7_driver` to `1.0.0-1`:

- upstream repository: https://github.com/novatel/novatel_oem7_driver.git
- release repository: https://github.com/novatel-gbp/novatel_oem7_driver-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.9.3`
- previous version for package: `null`

2020-04-22 13:57 UTC, clalancette requested changes

2020-04-22 13:57 UTC, clalancette commented on kinetic/distribution.yaml
> +      version: 1.0.0
This should be a branch, not a tag (so 'master' in this case).  Our CI usually catches this, but for some reason didn't this time.

2020-04-22 15:47 UTC, novatel-applications-engineering reviewed
Revised as per recommendations. Thank you.

2020-04-27 17:26 UTC, clalancette approved these changes

2020-04-27 17:26 UTC, merged