rosdep: added python3-grpc-tools and python3-grpcio
ros/rosdistro pull request #24742
Opened 2020-05-06 14:19 UTC by atiderko

Added python3 dependency for
Debian buster:
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-grpc-tools
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-grpcio

Ubuntu focal:
  https://packages.ubuntu.com/focal/python3-grpc-tools
  https://packages.ubuntu.com/focal/python3-grpcio

2020-05-14 21:15 UTC, clalancette requested changes

2020-05-14 21:15 UTC, clalancette commented on rosdep/python.yaml
> +    focal: [python3-grpc-tools]
To make this a bit more future-proof, I'll suggest the following:

```
python3-grpc-tools:
  debian:
    '*': [python3-grpc-tools]
    stretch: null
  ubuntu:
    '*': [python3-grpc-tools]
    bionic: null
    xenial: null
    
```

2020-05-14 21:15 UTC, clalancette commented on rosdep/python.yaml
> +    focal: [python3-grpcio]
Ditto here.

2020-05-15 06:33 UTC, atiderko commented
Thank you for change suggestions. I applied these!

2020-05-15 13:09 UTC, clalancette approved these changes

2020-05-16 00:04 UTC, merged