rosdep: add key for Python3 scikit-image (skimage)
ros/rosdistro pull request #24743
Opened 2020-05-06 16:20 UTC by JulianKu

Debian: https://packages.debian.org/search?lang=de&searchon=names&keywords=python3-skimage
Fedora: https://fedora.pkgs.org/31/fedora-x86_64/python3-scikit-image-0.14.2-2.fc31.x86_64.rpm.html
Gentoo: https://packages.gentoo.org/packages/sci-libs/scikits_image
PyPi: https://pypi.org/project/scikit-image/
Ubuntu: https://packages.ubuntu.com/search?lang=de&keywords=python3-skimage&searchon=names

2020-05-14 21:16 UTC, clalancette requested changes

2020-05-14 21:16 UTC, clalancette commented on rosdep/python.yaml
> +    stretch: [python3-skimage]
```
debian: [python3-skimage]
```

Should be sufficient and future-proof.

2020-05-14 21:16 UTC, clalancette commented on rosdep/python.yaml
> +    xenial: [python3-skimage]
```
ubuntu: [python3-skimage]
```

Should work and be future-proof.

2020-05-15 13:09 UTC, clalancette approved these changes

2020-05-16 00:03 UTC, tfoote commented
@JulianKu can you rebase this it conflicts with #24725

2020-05-16 15:04 UTC, JulianKu commented
Sorry, somehow I messed up the rebase in between.
Fixed it though, so that merging should be possible now

2020-05-18 17:48 UTC, jacobperron approved these changes

2020-05-19 00:43 UTC, merged