rosdep: added python3-ruamel.yaml
ros/rosdistro pull request #24741
Opened 2020-05-06 14:05 UTC by atiderko

Added rosdep for Ubuntu focal:
https://packages.ubuntu.com/focal/python3-ruamel.yaml

2020-05-14 21:11 UTC, clalancette requested changes

2020-05-14 21:11 UTC, clalancette commented on rosdep/python.yaml
>      zesty: [python3-ruamel.yaml]
Given that this is supported on all of our supported platforms with the same name, I'll suggest changing this to:

```
ubuntu: [python3-ruamel.yaml]
```

2020-05-15 13:19 UTC, atiderko commented
Applied suggestion from Chris

2020-05-15 13:25 UTC, clalancette approved these changes

2020-05-16 00:07 UTC, merged