Added libglew-dev for ubuntu:focal to the rosdep base rules
ros/rosdistro pull request #24916
Opened 2020-05-14 23:23 UTC by suddrey-qut

This is needed to build tools such as the MoveIt Perception pipeline.

Signed-off-by: Gavin Suddrey <g.suddrey@qut.edu.au>

2020-05-15 13:13 UTC, clalancette requested changes

2020-05-15 13:13 UTC, clalancette commented on rosdep/base.yaml
>      quantal: [libglew-dev]
I know you are just adding a new key here, but I think we can simplify this given the current supported Ubuntu releases.  That is, I think we can remove this whole block and replace it with:

```
ubuntu: [libglew-dev]
```

Which should work on Xenial and newer, and also make us future-proof.

2020-05-16 06:43 UTC, suddrey-qut commented
I thought the same thing, but did not want to assume on whether precise and earlier would no longer be supported.

2020-05-17 14:41 UTC, clalancette approved these changes

2020-05-19 00:42 UTC, merged