rosdep: Add libgeographic for ubuntu eouan and focal (noetic)
ros/rosdistro pull request #25016
Opened 2020-05-22 13:45 UTC by vooon

Links to Ubuntu packages:

- https://packages.ubuntu.com/en/eoan/libgeographic-dev
- https://packages.ubuntu.com/en/focal/libgeographic-dev

Required for Mavros.

2020-05-22 18:47 UTC, tfoote requested changes
These all look to be the same so there's no reason for us to call out the specific version. Could you just collapse it into a generic ubuntu rule and then we won't have to worry about this in the future.

Otherwise we'd want fill in cosmic and disco as well

2020-05-22 19:06 UTC, vooon commented
Before vivid it called libgeographic**lib**-dev, but since all of ros released targeted to 14.04 EOLed, it think it's ok to collapse to libgeographic-dev.

2020-05-22 21:52 UTC, tfoote approved these changes
Yeah, we don't worry about tracking differences into significantly EOL'd platforms.

Thanks for the update. LGTM.

2020-05-26 03:25 UTC, sloretz approved these changes

2020-05-26 03:26 UTC, merged