nmc_nlp_lite-release: 0.0.6-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #25049
Opened 2020-05-24 23:37 UTC by nmcbins

Increasing version of package(s) in repository `nmc_nlp_lite-release` to `0.0.6-1`:

- upstream repository: https://github.com/nmcbins/nmc_nlp_lite_ros.git
- release repository: https://github.com/nmcbins/nmc_nlp_lite-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.7`
- previous version for package: `null`

2020-05-27 01:15 UTC, tfoote commented
Holding for [sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2020-05-22/14241?u=tfoote)

2020-05-27 01:18 UTC, tfoote requested changes
I noticed that your package.xml declares BSD as the license but your LICENSE file contains the MIT license and none of your source files have the license headers or copyright headers in them necessary for either of those licenses.

I'd also recommend that your description be expanded to at least expand the acronyms that you're using in the name of this package. And preferably link to further documentation of the product to which it's bridging.

2020-05-29 01:47 UTC, nmcbins commented
Thanks a lot tfoote! 

What's the best/common practice from here on -- should I close this PR and fix things you pointed out, then try to release another version (0.0.7)? or is there a way to fix things in place and keep this PR? 

Thanks again!

2020-05-29 13:06 UTC, clalancette commented
> What's the best/common practice from here on -- should I close this PR and fix things you pointed out, then try to release another version (0.0.7)? or is there a way to fix things in place and keep this PR?

Yes, that's the best thing to do, especially when you make source changes.  bloom will automatically open a new PR.

2020-05-29 13:39 UTC, closed without merging