Add rosdep rule for python3-argcomplete
ros/rosdistro pull request #25204
Opened 2020-05-29 20:20 UTC by kyrofa

2020-05-29 20:46 UTC, cottsay requested changes
From the rosdistro [`CONTRIBUTING.md`](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions):
> For convenience in reviewing, please comment in the PR with links to the web listings of packages

Please add those links to make it easier to verify the rules you're suggesting.

2020-05-29 20:46 UTC, cottsay commented on rosdep/python.yaml
> +  gentoo: [dev-python/argcomplete]
rosdep aliases `centos` to `rhel`, so we should use that instead. Also, the package for RHEL 7 comes from EPEL and is called `python36-argcomplete`. We can use the `%{python3_pkgversion}` RPM macro to resolve to the system default package suffix, `36` on RHEL 7 and `3` on RHEL 8.

```suggestion
  debian: [python3-argcomplete]
  fedora: [python3-argcomplete]
  freebsd: [py37-argcomplete]
  gentoo: [dev-python/argcomplete]
  rhel: ['python%{python3_pkgversion}-argcomplete']
```

2020-05-29 21:02 UTC, kyrofa commented
> Please add those links to make it easier to verify the rules you're suggesting.

Sure, done.

2020-05-29 21:38 UTC, cottsay approved these changes

2020-05-29 23:05 UTC, Arnatious approved these changes

2020-06-01 14:08 UTC, clalancette approved these changes

2020-06-01 14:08 UTC, merged