added python3-jsonpickle for ubuntu focal / ros noetic
ros/rosdistro pull request #25296
Opened 2020-06-03 13:29 UTC by hikinggrass

see https://packages.ubuntu.com/focal/python3-jsonpickle

2020-06-03 17:24 UTC, sloretz requested changes
Please create a separate `python3-jsonpickle` key for the Python 3 version. See https://github.com/ros/rosdistro/pull/21846 for an example.

You might be interested in [REP 151 -- Python 3 Support](https://ros.org/reps/rep-0151.html#rosdep-keys)

2020-06-03 17:41 UTC, hikinggrass commented
I performed the requested change and added a new python3-jsonpickle rosdep key.
Corresponding packages:
arch: https://www.archlinux.org/packages/community/any/python-jsonpickle/
debian: https://packages.debian.org/stretch/python3-jsonpickle
fedora: https://fedora.pkgs.org/32/fedora-aarch64/python3-jsonpickle-1.2-3.fc32.noarch.rpm.html
gentoo: https://packages.gentoo.org/packages/dev-python/jsonpickle
ubuntu: https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/python3-jsonpickle_1.2-1_all.deb.html

2020-06-03 18:13 UTC, sloretz approved these changes

2020-06-04 13:06 UTC, clalancette approved these changes

2020-06-04 13:06 UTC, merged