oxford_gps_eth: 1.1.1-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #25348
Opened 2020-06-05 20:32 UTC by kmhallen

Increasing version of package(s) in repository `oxford_gps_eth` to `1.1.1-1`:

- upstream repository: https://bitbucket.org/DataspeedInc/oxford_gps_eth.git
- release repository: https://github.com/DataspeedInc-release/oxford_gps_eth-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.9.7`
- previous version for package: `null`

## oxford_gps_eth

```
* Install Python script
* Add missing rospy dependency
* Contributors: Kevin Hallenbeck, Micho Radovnikovich
```

2020-06-08 16:27 UTC, sloretz requested changes
@kmhallen I noticed a couple issues while reviewing this package, one of which *might* prevent this package from building on the build farm. Mind fixing and creating another release?

https://bitbucket.org/DataspeedInc/oxford_gps_eth/issues/12/distuils-and-cmake-version-issues-in-ros

2020-06-12 00:26 UTC, sloretz commented
@kmhallen friendly ping :)

2020-06-12 14:19 UTC, kmhallen commented
I'll look into it

2020-06-17 17:13 UTC, sloretz commented
@kmhallen friendly ping :)

2020-06-17 18:39 UTC, sloretz commented
@kmhallen I'll close this one for now, assuming the solution is a new release.

2020-06-17 18:39 UTC, closed without merging