add rosdep key for python3-shapely
ros/rosdistro pull request #25369
Opened 2020-06-08 18:16 UTC by tdenewiler

Used for geometry operations. For example, finding the coordinates of the closest point on a polygon:
https://stackoverflow.com/questions/33311616/find-coordinate-of-the-closest-point-on-polygon-in-shapely

* Arch: https://www.archlinux.org/packages/?sort=&q=shapely&maintainer=&flagged=
* Debian: https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=shapely
* Fedora: not found so no rule added (https://apps.fedoraproject.org/packages/s/shapely)
* Gentoo: https://packages.gentoo.org/packages/search?q=shapely
* PyPI: https://pypi.org/search/?q=shapely
* Ubuntu: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=shapely&searchon=names

Local testing with forked repository showed rosdep key resolves to expected package.

2020-06-09 15:19 UTC, clalancette requested changes

2020-06-09 15:19 UTC, clalancette commented on rosdep/python.yaml
> +  debian: [python3-shapely]
The `fedora` package database seems to be not working at the moment.  I can definitely do `dnf install python3-shapely` on my Fedora box, so I'm guessing they are just having some backend issues at the moment.  Not your fault, but please do add the key for Fedora as well.

2020-06-12 14:10 UTC, clalancette approved these changes

2020-06-15 15:25 UTC, nuclearsandwich approved these changes

2020-06-15 15:25 UTC, merged