add rosdep key for python3-tilestache
ros/rosdistro pull request #25370
Opened 2020-06-08 18:49 UTC by tdenewiler

Useful for serving image tiles, such as overhead imagery from USGS. An example use case is to use the overhead image tiles in a web browser to show where a robot is in the world.

Tilestache does not appear to be released into the latest versions of supported operating systems. Instead, it appears that the only repository source on newer operating systems is PyPI. The links below to OS distributions show that there are no results for tilestache.

* PyPI: https://pypi.org/search/?q=tilestache&o=
* Arch: https://www.archlinux.org/packages/?sort=&q=tilestache&maintainer=&flagged=
* Debian: https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=tilestache
* Fedora: https://apps.fedoraproject.org/packages/s/tilestache
* Gentoo: https://packages.gentoo.org/packages/search?q=tilestache
* Ubuntu: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=tilestache&searchon=names

Local testing with forked repository showed rosdep key resolves to expected package.

2020-06-09 15:14 UTC, clalancette requested changes

2020-06-09 15:14 UTC, clalancette commented on rosdep/python.yaml
> +python3-tilestache:
For a pip-only key like this, please suffix this with `-pip`.

2020-06-12 14:09 UTC, clalancette approved these changes

2020-06-15 15:26 UTC, nuclearsandwich approved these changes

2020-06-15 15:27 UTC, merged