add rosdep key for pika-pip
ros/rosdistro pull request #25395
Opened 2020-06-10 15:00 UTC by tdenewiler

Pika is a RabbitMQ client library for Python, useful for interacting with devices and systems that use the AMQP protocol. The version available from the existing `pika` key on Ubuntu Bionic is `0.11.0-1`. The version from PyPI is `1.1.0`. There are many systems using the newer version.

* PyPI: https://pypi.org/project/pika/
* Ubuntu: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=python-pika&searchon=names

2020-06-12 13:59 UTC, clalancette approved these changes

2020-06-15 14:38 UTC, reinzor commented
Related PR https://github.com/ros/rosdistro/pull/18840

2020-06-15 15:07 UTC, nuclearsandwich requested changes
When packages are available via distribution package manager those packages should be used rather than adding additional pip keys.

Although it doesn't appear that the contribution guidelines were updated, the rationale in https://github.com/ros/rosdistro/pull/18840#issuecomment-426483773 still applies. Keys from pip cannot be used in ROS packages released via Bloom to the official ROS distributions or alternative ones.

I believe our recommendation for those who wish to use pip keys rather than system keys knowing the trade-offs is to add a custom rosdep source on systems where you want to use the pip keys.

2020-06-15 15:11 UTC, tdenewiler commented
I agree with the approach @tfoote is advocating for. I'll close this PR and add pika via pip in our Dockerfile or with a custom rosdep source. Thanks for the reviews.

2020-06-15 15:11 UTC, closed without merging