sick_scan: 1.6.0-2 in 'kinetic/distribution.yaml' [bloom]
ros/rosdistro pull request #25422
Opened 2020-06-11 14:21 UTC by michael1309

Increasing version of package(s) in repository `sick_scan` to `1.6.0-2`:

- upstream repository: https://github.com/SICKAG/sick_scan.git
- release repository: https://github.com/SICKAG/sick_scan-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.9.3`
- previous version for package: `1.6.0-1`

## sick_scan

```
* NAV 210+NAV245 support added code reformated
* NAV310 added
* Contributors: Michael Lehning
```

2020-06-11 17:24 UTC, tfoote commented
Holding for [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-06-10/14614?u=tfoote)

2020-06-12 13:54 UTC, clalancette commented
Holding for Kinetic [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-06-10/14614).

2020-06-12 19:22 UTC, tfoote commented
I just looked a little close at this and noticed that it only has a debian increment release which is what you want to use if you're just patching something in the release repository but not in the source code. However I looked at the repository and see several recent commits on master. Were those intended to be released? If so you need to tag the new release in the source branch before running bloom-release to get it to release that content correctly. Can you confirm that you wanted to do a debian increment and not release the new content from the upstream repository?

2020-06-12 19:23 UTC, tfoote requested changes
Marking this as needs changes until my comment/question is resolved.

2020-07-01 23:13 UTC, tfoote commented
@michael1309 we're waiting for your response to the above questions. With no response we'll close this issue in a little bit.

2020-07-02 04:44 UTC, michael1309 commented
Hi Tully,

 

Thanks for you reminder. We plan to start a new bloom release today, which supports also noetic, and integrate the mentioned issue in this process.

 

Best regards,

Michael

 

Viele Grüße

Michael Lehning

 

Ing.-Büro Dr. Michael Lehning

Dr.-Ing. Michael Lehning

Schulstr. 21B

D-31137 Hildesheim

T: +49 5121 645 70

M: +49 173 37 69 242

E:  <mailto:michael.lehning@lehning.de> michael.lehning@lehning.de

 <http://www.lehning.de/> www.lehning.de

 



 



 

Ihr Spezialist für Digitale Bild- und Signalverarbeitung

 

 

Von: Tully Foote <notifications@github.com> 
Gesendet: Donnerstag, 2. Juli 2020 01:14
An: ros/rosdistro <rosdistro@noreply.github.com>
Cc: Michael Lehning <michael.lehning@lehning.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ros/rosdistro] sick_scan: 1.6.0-2 in 'kinetic/distribution.yaml' [bloom] (#25422)

 

@michael1309 <https://github.com/michael1309>  we're waiting for your response to the above questions. With no response we'll close this issue in a little bit.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/ros/rosdistro/pull/25422#issuecomment-652689983> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AH6A5MJU746DYVTOOCGFO23RZO7KJANCNFSM4N3OVUKA> .  <https://github.com/notifications/beacon/AH6A5MKSHGRX5TDDCT75KQ3RZO7KJA5CNFSM4N3OVUKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOE3TUEPY.gif>

2020-07-05 05:39 UTC, michael1309 commented
@tfoote

After setting up noetic and further code adaptations, we have now released the new version 1.7.6-1, which builds error-free in the Bloom process, and are waiting for the integration into the distribution. The version 1.6.0-2 is therefore obsolete. Thanks for your support.

2020-07-06 08:28 UTC, tfoote commented
replaced by #25661

2020-07-06 08:28 UTC, closed without merging