Add python3-collada
ros/rosdistro pull request #25533
Opened 2020-06-19 07:28 UTC by DavidMansolino

My package (webots_ros2_importe: https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_importer/package.xml#L16) currently depends on `python3-collada-pip` but I would prefer to avoid adding pip dependencies.

2020-06-19 14:00 UTC, clalancette requested changes

2020-06-19 14:00 UTC, clalancette commented on rosdep/python.yaml
> +  debian: [python3-collada]
It looks like this is only available on bullseye and later.  Thus, to maintain compatibility with our older distributions, I suggest the following:

```
debian:
  '*': [python3-collada]
  buster: null
  stretch: null
```

2020-06-19 14:00 UTC, clalancette commented on rosdep/python.yaml
> +  ubuntu: [python3-collada]
It looks like this is only available on focal and later.  Thus, to maintain compatibility with our older distributions, I suggest the following:

```
ubuntu:
  '*': [python3-collada]
  bionic: null
  xenial: null
```

2020-06-19 14:16 UTC, DavidMansolino commented
Thank you @clalancette for your pertinent comments, it should be fixed now.

2020-06-19 14:17 UTC, clalancette approved these changes

2020-06-26 07:42 UTC, DavidMansolino commented
Any news about the merge of this PR?

2020-06-30 13:29 UTC, omichel commented
@clalancette: when can we expect to see this PR merged?

2020-06-30 13:38 UTC, nuclearsandwich approved these changes

2020-06-30 13:38 UTC, merged