Add python3 rosdep for msgpack
ros/rosdistro pull request #25610
Opened 2020-06-26 20:12 UTC by bjin2364

Adding `python3-msgpack` to rosdep for:
- `ubuntu`: https://packages.ubuntu.com/search?keywords=python3-msgpack&searchon=names
- `debian`: https://packages.debian.org/search?keywords=python3-msgpack&searchon=names&suite=buster&section=all

2020-06-30 13:16 UTC, clalancette requested changes

2020-06-30 13:16 UTC, clalancette commented on rosdep/python.yaml
> +  debian: [python3-msgpack]
It looks like this is only available in Debian as of Buster.  Please modify this to:

```
debian:
  '*': [python3-msgpack]
  stretch: null
```

2020-07-14 16:35 UTC, nuclearsandwich approved these changes

2020-07-22 20:24 UTC, tfoote approved these changes

2020-07-22 20:25 UTC, merged