Add libpqxx rosdeps for focal
ros/rosdistro pull request #25718
Opened 2020-07-08 19:23 UTC by nickswalker

Key listing on Ubuntu packages: https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=libpqxx

2020-07-09 13:37 UTC, clalancette requested changes

2020-07-09 13:37 UTC, clalancette commented on rosdep/base.yaml
> +    focal: [libpqxx-dev]
It looks like this has been `libpqxx-dev` all the way back to trusty.  With that in mind, I'll suggest that for future compatibility we change this entire block to:

```
ubuntu: [libpqxx-dev]
```

2020-07-22 20:26 UTC, tfoote approved these changes

2020-07-23 15:45 UTC, clalancette approved these changes

2020-07-23 15:45 UTC, merged