Added boston dynamic sdks
ros/rosdistro pull request #25757
Opened 2020-07-10 17:48 UTC by dniewinski

2020-07-14 16:41 UTC, nuclearsandwich commented
@dniewinski can you please add links to these packages on pypi to your PR description as requested in our [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions).

2020-07-16 00:29 UTC, tfoote requested changes
Please update the PR to include a description. Since these are pip rules they need to be prefixed with `python3-` and postfixed with `-pip` Please review the contributing guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions

2020-08-10 21:27 UTC, sloretz requested changes

2020-08-10 21:27 UTC, sloretz commented on rosdep/python.yaml
> +  ubuntu: [python3-bosdyn-api]
This key says there is a debian package named `python3-bosdyn-mission`, but I wasn't able to find one. If these are only available on PyPI then I think what @tfoote is asking for is an end result like:

```yaml
python3-bosdyn-api-pip:
  debian:
    pip:
      packages: [bosdyn-api]
  ubuntu:
    pip:
      packages: [bosdyn-api]
```

That is, please replace the `python3-bosdyn-*` keys and `bosdyn-*` keys with `python3-bosdyn-*-pip` keys using the content from the `bosdyn-*` keys.

2020-08-11 19:43 UTC, clalancette approved these changes

2020-08-13 17:49 UTC, tfoote approved these changes

2020-08-13 17:52 UTC, sloretz approved these changes

2020-08-13 17:52 UTC, merged

2020-08-17 18:08 UTC, dniewinski commented
Hi @sloretz .  Thanks for accepting the PR.  I tried it today and it installed with pip2.  I need it to install with pip3.  Isn't what why it is prefixed with "python3"?

2020-08-17 18:21 UTC, sloretz commented
@dniewinski Which ROS distro? Are you trying to use Python 3 in a ROS distro that only supports Python 2?

> I tried it today and it installed with pip2. I need it to install with pip3. Isn't what why it is prefixed with "python3"

Pip keys can be installed with either Python 3 or Python 2. Which one is used depends on the environment variable `ROS_PYTHON_VERSION`, which is set for each distro. See [this section in REP 151](https://www.ros.org/reps/rep-0151.html#ros-python-version).

The `python3` prefix is just in case upstream Debian or Ubuntu adds these as apt packages. If they do, they'll likely name them `python3-bosdyn` etc. It's easier for rosdep key reviewers to catch that pip keys need to be replaced with upstream ones because they'll be next to each other alphabetically.

2020-08-17 20:00 UTC, dniewinski commented
I'm working with melodic.  The package works with python3.  I guess i assumed the prefix just took care of it