adding graphql client library as pip to rosdep
ros/rosdistro pull request #26226
Opened 2020-08-18 13:45 UTC by bbferka

new entry for the graphql python client library
- GIT:  https://github.com/graphql-python/gql
- pypi: https://pypi.org/project/gql/

2020-08-20 04:40 UTC, tfoote requested changes
please update the prefix. Note that you'll have to move it to maintain alphabetization.

2020-08-20 04:40 UTC, tfoote commented on rosdep/python.yaml
> +python-gql-pip:
Our new policy is to make new rules prefixed with python3 not python as that's the new default.

2020-08-22 07:35 UTC, tfoote approved these changes
No problem. Thanks for iterating. lgtm

2020-08-26 22:59 UTC, jacobperron approved these changes

2020-08-26 23:00 UTC, merged