[rosdep/base] Added rosdep keys for individual pcl packages
ros/rosdistro pull request #26448
Opened 2020-09-03 16:31 UTC by YoshuaNava

This PR aims to resolve #26438.

For now I have just added Debian and Ubuntu dependencies. An open question: For completeness, should I also add the rest of the existing pcl PPA packages? (i.e. apps, keypoints, ml, octree, outofcore, people, recognition, registration, sample-consensus, search, stereo, surface, tracking and visualization).

PS: As mentioned in the issue, I couldn't find information about pcl modules for OS != {ubuntu, debian}. Thus, we can't depend on individual packages in perception_pcl until we can link against the correct modules.

Best,
Yoshua Nava

2020-09-07 21:56 UTC, hidmic reviewed
> For completeness, should I also add the rest of the existing pcl PPA packages?

The more rules the better :smiley: 

Having said that, I'm a bit wary about what you mean by _pcl PPA_. Which PPA are you talking about? [CONTRIBUTING](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#expected-rosdep-sources) guidelines are very explicit about which package sources are allowed.

2020-09-07 21:56 UTC, hidmic commented on rosdep/base.yaml
> +    focal: [libpcl-common1.8]
@YoshuaNava hmm, a quick apt cache search shows `libpcl-common1.8` is missing from `universe` and `multiverse` in Focal.

2020-09-07 21:56 UTC, hidmic commented on rosdep/base.yaml
> +    trusty: [libpcl-1.7-common1.8]
@YoshuaNava hmm, I can't seem to even find these fine grained PCL releases on `trusty`.

2020-09-15 22:28 UTC, tfoote requested changes
Please be clearer about where and how these new packages are coming from. And in particular, please link to the packages on packages.debian.org and packages.ubuntu.com for us to be able to review in your PR description. 

Since you're trying to optimize dependencies for other platforms you should provide the less optimized solution or depending on the lightest weight package which provides the equivalent functionality. If Fedora as libraries A B and C in one packages you can have a rule for A, B and C separately all depend on the ABC package on that platform.

2020-09-21 18:51 UTC, mjcarroll commented
@YoshuaNava Friendly ping.

2020-10-09 18:52 UTC, ivanpauno commented
@YoshuaNava friendly ping

2020-10-12 13:26 UTC, clalancette commented
There's been no response to the original comments in over a month, so I'm going to close this out.

If you'd like to continue with this PR, please respond to the comment and feel free to reopen the PR.  Thanks for the contribution.

2020-10-12 13:26 UTC, closed without merging