add xml_plain
ros/rosdistro pull request #26551
Opened 2020-09-14 00:48 UTC by taikitanaka3

### BreafExplanation

This module is a set of utility functions for parsing self-contained XML input into plain list/dict/string types and emitting to/reading from XML or YAML formats.

### Compatibility
The module is compatible with python 2.6/2.7 and python 3.x.

https://pypi.org/project/xmlplain/

2020-09-14 17:25 UTC, cottsay requested changes
A couple of things:
1. Since this is a pip-only package, it should have a `-pip` suffix. This is described in the [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1).
2. The CI is complaining because the entry is not in alphabetical order, so that should be corrected.

2020-09-15 00:39 UTC, taikitanaka3 commented
@cottsay 
-pip suffix. and alphabetical order is corrected at https://github.com/ros/rosdistro/pull/26551/commits/002f6b0200181a1538abc7d5c0f2558f42b2dfb9

2020-09-15 00:46 UTC, cottsay commented on rosdep/python.yaml
> +
CI is upset about this blank line now.

```suggestion
```

2020-09-15 00:52 UTC, taikitanaka3 commented
@cottsay 
Thanks for change requests I removed line at https://github.com/ros/rosdistro/pull/26551/commits/478b54cbfd2e915d21b94b687cde6c38237ecc89

2020-09-15 17:42 UTC, cottsay approved these changes

2020-09-21 18:47 UTC, mjcarroll approved these changes

2020-09-21 18:47 UTC, merged