Add yamllint for focal and others
ros/rosdistro pull request #26779
Opened 2020-10-01 14:05 UTC by Rayman

https://packages.ubuntu.com/search?suite=all&keywords=yamllint

2020-10-02 21:02 UTC, jacobperron approved these changes

2020-10-02 21:36 UTC, jacobperron commented on rosdep/base.yaml
> +    '*': [yamllint]
I think this can be reduced to:

```yaml
ubuntu: [yamllint]
```

2020-10-06 23:07 UTC, tfoote requested changes
Yes it can be reduced. Please bring it down to the slightly shorter version mentioned by @jacobperron You didn't grant edit permissions so I can't do it for you.

2020-10-07 08:36 UTC, Rayman commented on rosdep/base.yaml
> +    '*': [yamllint]
I've implemented your change

2020-10-07 14:37 UTC, ivanpauno approved these changes

2020-10-07 16:45 UTC, jacobperron approved these changes

2020-10-07 16:45 UTC, merged