add xmlschema to rosdistro
ros/rosdistro pull request #26913
Opened 2020-10-12 01:02 UTC by hakuturu583

I want to add xmlschema to rosdistro.

Pypy package: https://pypi.org/project/xmlschema/

2020-10-12 19:00 UTC, tfoote requested changes
Looking at this we generally prefer to use mature natively packaged libraries so that they can be released and used in packages. Pip entries are only useful for from source builds. Is there any more formally packaged alternative?

2020-10-12 19:00 UTC, tfoote commented on rosdep/python.yaml
> +python-xmlschema:
If this is a pip only package it should have the `-pip` suffix. 

And while we're at it these days most platforms are on python3 now so we should make this rule more future consistent using python3 in the key as pip will choose the local environment anyway.

```suggestion
python3-xmlschema-pip:
```

2020-10-14 18:05 UTC, hidmic commented
@hakuturu583 friendly ping

2020-10-20 17:28 UTC, dirk-thomas commented
Closing to due no response from the author @hakuturu583.

2020-10-20 17:28 UTC, closed without merging