add python3-influxdb-client-pip
ros/rosdistro pull request #27037
Opened 2020-10-19 16:38 UTC by jstiefel

I would like to add the InfluxDB 2.0 Python Client pip package. This is the recent version of influxdb-python, which is already in the deps. This package only exists in pip and requires at least python 3.6.

2020-10-19 19:26 UTC, hidmic requested changes
@jstiefel please check failing jobs. It appears your patch has formatting issues.

Also, it seems that for other platforms like `gentoo`, [`influxdb-client` has been packaged](https://packages.gentoo.org/packages/dev-python/influxdb). Would you consider providing keys for `gentoo`, `arch`, and `osx` as well? Links to package managers lists would help the review.

2020-10-20 10:45 UTC, jstiefel commented
> @jstiefel please check failing jobs. It appears your patch has formatting issues.

My bad, wrong alphabetic order. 

> Also, it seems that for other platforms like `gentoo`, [`influxdb-client` has been packaged](https://packages.gentoo.org/packages/dev-python/influxdb). Would you consider providing keys for `gentoo`, `arch`, and `osx` as well? Links to package managers lists would help the review.

This is the previous client I was referring to: https://github.com/influxdata/influxdb-python (vs. https://github.com/influxdata/influxdb-client-python). The apt package of this one is already in the deps.

2020-10-20 14:16 UTC, hidmic approved these changes
I see. Thanks for the clarification. 

Still, I'd like to see `arch`, `gentoo`, and `osx` rules in there, but it's not mandatory.

2020-10-20 14:22 UTC, clalancette approved these changes

2020-10-20 14:22 UTC, merged