Add python3-cantools-pip
ros/rosdistro pull request #27189
Opened 2020-10-29 16:01 UTC by sebgiles

2020-10-29 16:06 UTC, sebgiles commented
If this gets approved will it immediately be effective after a `rosdep update` ?

2020-10-29 16:36 UTC, nuclearsandwich commented
@sebgiles can you please update your pull request to comply with our contribution guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions
Specifically your description should be updated with links to the package on pypi.

> If this gets approved will it immediately be effective after a `rosdep update` ?

When fetching files directly via GitHub's http servers there can be a period where their cache returns an older version of the file but within several minutes of being merged changes are usually available to rosdep update.

2020-10-29 16:36 UTC, nuclearsandwich requested changes
Please update your pull request to comply with our contribution guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions
Specifically your description should be updated with links to the package on pypi.

2020-10-29 21:53 UTC, sebgiles commented
@nuclearsandwich Thanks. Description updated!

2020-10-30 23:49 UTC, nuclearsandwich approved these changes

2020-10-30 23:50 UTC, nuclearsandwich commented
Will still need a second rosdep reviewer per our review policy.

2020-10-31 00:04 UTC, cottsay approved these changes

2020-10-31 00:16 UTC, merged