Add 'conan' rosdep key to be resolved using pip
ros/rosdistro pull request #27243
Opened 2020-11-04 12:59 UTC by miguelprada

This enables using [conan](https://conan.io/) ([pypi package](https://pypi.org/project/conan/)) package manager to resolve dependencies (e.g. using [conan-cmake](https://github.com/conan-io/cmake-conan)) which may not be available via the usual rosdep sources, while respecting the usual workflow to build packages from source.

I reckon this may not be desired for packages to be released as binaries using the buildfarm, but it would be very helpful for packages which are never intended to go through the binary release process.

2020-11-05 06:03 UTC, nuclearsandwich requested changes
Other discussions notwithstanding the rosdep key should conform to our guidelines for pip packages https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1

2020-11-05 08:33 UTC, miguelprada commented
Apologies for missing that one. I believe this now conforms to the rules.

Isn't it a bit confusing to prepend the key with `python3-` even though the same dependency is available for Python2 as well? This should even resolve to the Python2 version in systems where `ROS_PYTHON_VERSION` is set to 2, shouldn't it?

2020-11-05 19:12 UTC, wjwwood approved these changes
> I reckon this may not be desired for packages to be released as binaries using the buildfarm, but it would be very helpful for packages which are never intended to go through the binary release process.

This is fine, and an already understood limitation of pip based rosdep rules, you cannot use them with released packages since we cannot include those in our debian packages.

2020-11-10 15:29 UTC, nuclearsandwich approved these changes

2020-11-10 16:20 UTC, merged

2020-11-10 20:46 UTC, miguelprada commented
Thanks all!