toposens: 2.1.0-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #27252
Opened 2020-11-05 08:10 UTC by toebgen

Increasing version of package(s) in repository `toposens` to `2.1.0-1`:

- upstream repository: https://gitlab.com/toposens/public/ros-packages.git
- release repository: https://gitlab.com/toposens/public/toposens-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.0`
- previous version for package: `null`

## toposens

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_bringup

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_description

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_driver

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_markers

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_msgs

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_pointcloud

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

## toposens_sync

```
* Introduce bringup package and general updates.
* Prepare for Noetic release
* Run separate CI stages for melodic+noetic. Bump up CMake version to 3.0.2.
* Contributors: Tobias Roth
```

2020-11-05 19:15 UTC, wjwwood requested changes
Looks like CI is failing like this:

```
 ....E..
======================================================================
ERROR: test.test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/rosdistro/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
    raise RuntimeError('\n'.join(errors))
RuntimeError: noetic: missing package.xml file for package "toposens_msgs"
-------------------- >> begin captured logging << --------------------
```

You may want to check into that error. I don't think it's on our end, but if you think it is I can dig deeper myself.

2020-11-06 07:35 UTC, toebgen commented
Hi @wjwwood,

2020-11-06 07:45 UTC, toebgen commented
Hi @wjwwood,
thanks for your feedback.

I looked into the issue, however, I am not sure where it comes from.
The package in question contains a `package.xml` file, as can be seen here: [toposens_msgs](https://gitlab.com/toposens/public/ros-packages/-/tree/master/toposens_msgs). The package actually is contained in the very repository, that is supposed to be released for Noetic: [ros-packages](https://gitlab.com/toposens/public/ros-packages).
I also ran the Prerelease script locally again, every thing went through here as well.

Since this is a first time release for Noetic, maybe I missed something in setting up the track correctly? I followed the steps described in [bloom/Tutorials/FirstTimeRelease](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease).

I would highly appreciate if you could have a look as well.
Please bear with me, if it turns out there is an obvious mistake, I am still very new as a package maintainer.
Thank you!

2020-11-10 15:21 UTC, mjcarroll commented
This also passed the checks in the [kinetic PR](https://github.com/ros/rosdistro/pull/27274), perhaps it was spurious?

2020-11-10 15:31 UTC, mjcarroll commented
Rerunning the checks shows no issues.   I think we are good here.

2020-11-10 15:31 UTC, mjcarroll approved these changes

2020-11-10 15:31 UTC, merged

2020-11-10 15:33 UTC, toebgen commented
Thanks @mjcarroll for checking again! :slightly_smiling_face: