Rename python-pymongo to python3-pymongo in Ubuntu focal
ros/rosdistro pull request #27356
Opened 2020-11-17 12:14 UTC by gurbain

python-pymongo cannot be found in Ubuntu focal packages and is named _python3-pymongo_ instead: https://packages.ubuntu.com/focal/python3-pymongo

2020-11-20 20:10 UTC, tfoote requested changes, later dismissed
Instead of aliasing this rule to be partially python2 and partially python3 please make a new one for `python3-mongodb`

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#python-3

2020-11-30 15:03 UTC, gurbain commented
Hi @tfoote,

Thank you for your input! This is my first PR in this repo, so I was not aware of this rule, I should have read the documentation further.

My concern was that the _python-pymongo_ entry was already partly aliased for several Ubuntu distros back to trusty_python3. I took the liberty to replace this with a single package name and create the __python3-pymongo__ entry as you suggested (see 9259bfc00aaa4f1cdc4265df81c7442b884029b8). I also checked the corresponding package names for other Linux distros.

Please, tell me if anything is missing!

2020-12-01 18:20 UTC, tfoote commented
Thanks for cleaning that up. But we keep those old rudundant rules in place to make sure not to break people who might still be using them. Please just add the new key so that it's available and not potentially breaking people already using the existing keys. The old keys won't effect people who choose to use the newer version.

2020-12-01 18:31 UTC, gurbain commented
Ok, it makes sense!

2020-12-01 20:36 UTC, clalancette approved these changes

2020-12-01 22:50 UTC, sloretz approved these changes
* arch https://www.archlinux.org/packages/community/x86_64/python-pymongo/
* debian https://packages.debian.org/stretch/python3-pymongo
* Fedora https://src.fedoraproject.org/rpms/python-pymongo/blob/master/f/python-pymongo.spec#_47 ( I think )
* gentoo https://packages.gentoo.org/packages/dev-python/pymongo

2020-12-01 22:52 UTC, merged