Add touchegg to rosdep base.yaml
ros/rosdistro pull request #27395
Opened 2020-11-20 12:30 UTC by 708yamaguchi

I add `touchegg` (Multitouch gesture recognizer) to rosdep base.yaml

I looked for debian, gentoo, fedra packages, but I did not find them...

Links:
arch: https://aur.archlinux.org/packages/touchegg/
ubuntu: https://packages.ubuntu.com/bionic/touchegg

2020-11-20 20:04 UTC, tfoote requested changes
I see ubuntu: https://packages.ubuntu.com/bionic/touchegg could you please add that.

2020-11-20 20:54 UTC, 708yamaguchi commented
I am sorry, but I do not understand what you are referring to.
I have already added the rosdep key for ubuntu.
```
touchegg:
  arch: [touchegg]
  ubuntu: [touchegg]
```

2020-11-21 00:16 UTC, tfoote approved these changes
Sorry I didn't read it close enough. I'm used to seeing arch and gentoo PRs come in together.

2020-11-30 15:51 UTC, mjcarroll approved these changes

2020-11-30 15:51 UTC, merged