Xmlschema
ros/rosdistro pull request #27496
Opened 2020-11-26 04:03 UTC by hakuturu583

Fix problems described in this PR.
Sorry for missing ping.
https://github.com/ros/rosdistro/pull/26913

I want to add xmlschema to rosdistro.

Pypy package: https://pypi.org/project/xmlschema/

2020-11-28 02:31 UTC, tfoote requested changes
This PR needs a little bit of cleanup to just be inserting the new rule mentioned in the description.

2020-11-28 02:31 UTC, tfoote commented on rosdep/python.yaml
> +python-xmlschema:
you seem to be removing an existing key here and overwriting it.

2020-11-28 02:31 UTC, tfoote commented on rosdep/python.yaml
> +      packages: [xmlplain]
This looks like the new set of rules that you're adding, but they appear to be referencing  a different packge.

2020-12-01 18:33 UTC, tfoote commented on rosdep/python.yaml
> +python-xmlschema:
You're still removing the python-xmlplain-pip. Please maintain that key and add the new keys.

2020-12-02 06:43 UTC, hakuturu583 commented
I add python-xmlplain-pip package

2020-12-02 13:47 UTC, clalancette commented on rosdep/python.yaml
> +python-xmlschema:
Since this is a pip-only package, it should be: `python3-xmlschema-pip`

2020-12-03 04:34 UTC, hakuturu583 commented
Sorry, I took a lot of mistakes in this branch, so I re-create PR about xmlschema package.

2020-12-03 04:34 UTC, closed without merging