realsense2_camera: 2.2.20-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #27503
Opened 2020-11-26 20:20 UTC by doronhi

Increasing version of package(s) in repository `realsense2_camera` to `2.2.20-1`:

- upstream repository: https://github.com/IntelRealSense/realsense-ros.git
- release repository: https://github.com/IntelRealSense/realsense-ros-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.0`
- previous version for package: `null`

## realsense2_camera

```
* Add Support - Noetic
* Add demo for using intrinsics from camera_info (show_center_depth.py).
* Add launch option: send logs to ros log file.
* Add feature: get rgb stream from infrared sensor (applies to D415)
* Add feature: Add notification if connected using USB2.1 port.
* Fix bug: Avoid z16h format
* Fix bug: monitor streams frequency without subsribing.
* Fix bug: extrinsincs for right stereo camera refers to the left stereo camera.
* Contributors: Abhijit Majumdar, Isaac I. Y. Saito, Jakub, M-frctrl, Thomas Jespersen, doronhi
```

## realsense2_description

```
* Add urdf file for l515
* Contributors: doronhi
```

2020-11-28 02:15 UTC, tfoote commented
holding for the [upcoming Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2020-11-30/17574)

2020-11-30 22:03 UTC, mjcarroll approved these changes

2020-11-30 22:04 UTC, mjcarroll requested changes

2020-11-30 22:04 UTC, mjcarroll commented on noetic/distribution.yaml
> +      url: https://github.com/intel-ros/realsense.git
This probably needs to be updated to the redirected address.

2020-11-30 22:33 UTC, mjcarroll commented on noetic/distribution.yaml
> +      url: https://github.com/intel-ros/realsense.git
https://github.com/IntelRealSense/realsense-ros

2020-12-01 16:19 UTC, mjcarroll approved these changes

2020-12-01 16:19 UTC, merged