plotjuggler: 3.0.3-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #27524
Opened 2020-11-29 10:01 UTC by facontidavide

Increasing version of package(s) in repository `plotjuggler` to `3.0.3-1`:

- upstream repository: https://github.com/facontidavide/PlotJuggler.git
- release repository: https://github.com/facontidavide/plotjuggler-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.0`
- previous version for package: `3.0.1-1`

2020-11-30 22:01 UTC, mjcarroll requested changes
Looks like upstream `master`->`main` is breaking CI here.

2020-12-01 08:20 UTC, facontidavide commented
"Change the name of your branch" they said, be "politically correct" they said.  :angry: 

As a workaround I have two identical branches now, "master" and "main". Is it possible to trigger the CI again and see if it solves the issues?

2020-12-01 14:45 UTC, mjcarroll commented
> As a workaround I have two identical branches now, "master" and "main".

I was going to suggest just updating the branches in your source and documentation entries, but that works too

2020-12-01 20:53 UTC, clalancette commented
> > 
> 
> I was going to suggest just updating the branches in your source and documentation entries, but that works too

I'm going to suggest you do this anyway; while this PR passed CI, I think it will break the next time around since the `master` branch doesn't exist anymore.

2020-12-01 22:42 UTC, sloretz commented
@facontidavide I made the `master -> main` change in https://github.com/ros/rosdistro/pull/27524/commits/5e0486ee13b0b7a7cc23e3da49813201c60a87fe and pushed it to your branch, let me know if it looks correct

2020-12-01 22:47 UTC, facontidavide commented
thanks

2020-12-02 13:50 UTC, merged