add flask-restplus from pip
ros/rosdistro pull request #27702
Opened 2020-12-09 15:07 UTC by Minipada

**Added package**: flask-restplus
**Pypi Link**: https://pypi.org/project/flask-restplus/
**Description**: Fully featured framework for fast, easy and documented API development with Flask
**Usage**: Making an API interacting with ROS. Flask is quite famous but for APIs, restplus gives some nice features such as integrated modelling, marshalling, swaggers and more. It is very easy to use if you already know some flask.

I added it as pip since there is no deb for it.

2020-12-10 16:54 UTC, nuclearsandwich requested changes
A small change is recommended to conform to contribution guidelines.

2020-12-10 16:54 UTC, nuclearsandwich commented on rosdep/python.yaml
> +python-flask-restplus-pip:
```suggestion
python3-flask-restplus-pip:
```

Per our [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1) this should be changed to `python3-flask-restplus-pip`.

2020-12-10 17:16 UTC, Minipada commented
@nuclearsandwich I get your change, but what about old version. If I want to make it work on melodic for example. Will it install it properly too?

2020-12-10 19:29 UTC, nuclearsandwich commented
> I get your change, but what about old version. If I want to make it work on melodic for example, which use python2. Will it install it properly too?

So the short answer is yes. The pip installer and pip itself does not make any distinction between python2 or python3 when fetching packages from pypi.

2020-12-10 19:29 UTC, nuclearsandwich approved these changes, later dismissed

2020-12-10 19:30 UTC, nuclearsandwich commented
@Minipada it's my fault, I always forget that when I suggest inline it will break the lexical sorting. The definition needs to be moved down with the rest of the python3 definitions and then this will be good to go.

2020-12-10 21:04 UTC, Minipada commented
Thanks for the precision.
It's mine, I just saw the suggestion and went with it. I did PR in the past, so I should have checked too. It should be right now.

2020-12-10 22:14 UTC, nuclearsandwich approved these changes
Thanks for iterating!

2020-12-17 18:54 UTC, jacobperron approved these changes

2020-12-17 18:54 UTC, merged