add opencv-contrib-python package for pip
ros/rosdistro pull request #27719
Opened 2020-12-10 10:46 UTC by hocjordan

This PR adds a rosdep key for the pip package `opencv-contrib-python`. I am using the Charuco checkerboard detection functions in this library to perform robot hand-eye calibration.

2020-12-10 16:49 UTC, nuclearsandwich requested changes
Looking at the project description, this pip package provides a vendored opencv implementation which would likely conflict with the system opencv used by pre-built ROS binaries. Is the facility you need in one of the libopencv-contrib packages already?

2020-12-11 01:45 UTC, hocjordan commented
> Looking at the project description, this pip package provides a vendored opencv implementation which would likely conflict with the system opencv used by pre-built ROS binaries. Is the facility you need in one of the libopencv-contrib packages already?

Thank you for your review. I'll investigate and get back to you.

2020-12-15 17:34 UTC, nuclearsandwich commented
@hocjordan any update here? If not, do you mind if we close this PR and then reopen it when you have an update?

2020-12-23 12:24 UTC, hidmic commented
@hocjordan friendly ping.

2021-01-13 14:10 UTC, clalancette commented
I'm going to close this one out for now.  Please feel free to reopen if you would like to pursue this key further.

2021-01-13 14:10 UTC, closed without merging

2021-01-14 02:59 UTC, hocjordan commented
Thank you very much for the advice and for closing the PR. It looks like I don't need this key ATM so I'll leave it here.