ament_cmake: 1.0.3-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #27734
Opened 2020-12-10 19:33 UTC by clalancette

Increasing version of package(s) in repository `ament_cmake` to `1.0.3-1`:

- upstream repository: https://github.com/ament/ament_cmake.git
- release repository: https://github.com/ros2-gbp/ament_cmake-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.10.0`
- previous version for package: `1.0.2-1`

2020-12-10 21:05 UTC, nuclearsandwich requested changes
Holding to let rolling catch up and get a sync out.

Nothing else is wrong with this just using the big red X to stop myself from merging this by accident later.

2020-12-23 12:27 UTC, hidmic approved these changes
LGTM

2020-12-23 12:28 UTC, hidmic commented
@nuclearsandwich ready to go?

2020-12-23 16:29 UTC, nuclearsandwich commented
Please hold for the upcoming [Rolling sync](https://discourse.ros.org/t/preparing-for-rolling-sync-2020-12-28/18173)

2021-01-04 12:27 UTC, ivanpauno commented
Sync is out, going in!

2021-01-04 12:27 UTC, merged