realsense2_camera version 3.1.3 for foxy
ros/rosdistro pull request #27855
Opened 2020-12-28 23:46 UTC by doronhi

Add realsense2_camera for foxy, version 3.1.3
Remove old name: ros2_intel_realsense
This PR depends on #27854

2021-01-04 13:04 UTC, ivanpauno requested changes
Removing the old key doesn't seem acceptable, as packages using it will start failing.
The new key looks ok.

2021-01-06 19:28 UTC, jacobperron commented
Holding for [sync](https://discourse.ros.org/t/preparing-for-foxy-sync-2020-01-07/18268)

2021-01-12 06:04 UTC, doronhi commented
> Removing the old key doesn't seem acceptable, as packages using it will start failing.
> The new key looks ok.

Restored the previously removed package ros2_intel_realsense.

2021-01-12 12:59 UTC, ivanpauno approved these changes

2021-01-12 13:00 UTC, merged