Add libqt5serialport5-dev
ros/rosdistro pull request #27892
Opened 2021-01-04 18:23 UTC by carebare47

Add support for the dev version of libqt5serialport5

2021-01-05 15:02 UTC, ivanpauno requested changes
Please, provides links to confirm the package names (e.g. https://packages.ubuntu.com/search?keywords=libqt5serialport5), and consider adding gentoo and arch (which together with debian/fedora/ubuntu are the recommended distros)

2021-01-29 00:51 UTC, mabelzhang commented
Looks like
Debian (Jessie to Buster): https://packages.debian.org/bullseye/libqt5serialport5-dev
Ubuntu (Xenial to Focal): https://packages.ubuntu.com/focal/libqt5serialport5-dev
Fedora https://fedora.pkgs.org/32/fedora-x86_64/qt5-qtserialport-devel-5.13.2-2.fc32.i686.rpm.html

In addition, there is a Gentoo package https://packages.gentoo.org/packages/dev-qt/qtserialport
Please confirm and add Gentoo if that's the correct one.

2021-02-01 19:16 UTC, jacobperron commented on rosdep/base.yaml
> +  fedora: [qt5-qtserialport-devel]
```suggestion
  fedora: [qt5-qtserialport-devel]
  gentoo: [dev-qt/qtserialport]
```

2021-02-24 13:29 UTC, clalancette commented
No response in over a month, so I'm going to close this.  Please feel free to respond to the review comments and reopen.  Thanks for the contribution.

2021-02-24 13:29 UTC, closed without merging