Added teleop_legged_robots for noetic
ros/rosdistro pull request #28021
Opened 2021-01-15 16:51 UTC by tarasborov

Added teleop_legged_robots for noetic

2021-01-19 14:15 UTC, clalancette requested changes
There are a few problems with the source package that I saw.

First, I don't think that this package is going to actually work on Noetic.  In particular, https://github.com/SoftServeSAG/teleop_legged_robots/blob/66efb1b9a751db2283402274de796bf01f215840/nodes/teleop_legged_keyboard.py#L1 doesn't work; that needs to be `/usr/bin/env python3` to work properly.

Second, this package uses [tf](https://github.com/SoftServeSAG/teleop_legged_robots/blob/66efb1b9a751db2283402274de796bf01f215840/nodes/teleop_legged_keyboard.py#L17), which is long deprecated; it really should be using `tf2`.

Third, https://github.com/SoftServeSAG/teleop_legged_robots/blob/main/src/teleop_legged_robots/__init__.py isn't actually used as far as I can tell; I would remove that.

Only the first issue is blocking, but it would be good to fix the other two issues as well.

2021-01-19 14:39 UTC, mikeferguson commented
@clalancette it looks like the package uses catkin_install_programs (https://github.com/SoftServeSAG/teleop_legged_robots/blob/66efb1b9a751db2283402274de796bf01f215840/CMakeLists.txt#L12) which, by my understanding actually rewrites the shebangs to python3 when that is the environment, right? (I've been using that elsewhere).

2021-01-19 23:10 UTC, sloretz commented
> that needs to be /usr/bin/env python3 to work properly.

> @clalancette it looks like the package uses catkin_install_programs (https://github.com/SoftServeSAG/teleop_legged_robots/blob/66efb1b9a751db2283402274de796bf01f215840/CMakeLists.txt#L12)

@mikeferguson is correct, [`catkin_install_python()` plus a shebang that says `#!/usr/bin/ev python` is correct](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs).

2021-01-20 16:04 UTC, clalancette commented
Thanks for the heads up about the shebang rewriting.  I couldn't remember if that was part of what we ended up deploying to Noetic; I guess it is.  In that case, the other questions are still outstanding (though they aren't really blocking, it would still be nice to clean them up).

2021-01-20 17:19 UTC, mikeferguson commented
> Second, this package uses [tf](https://github.com/SoftServeSAG/teleop_legged_robots/blob/66efb1b9a751db2283402274de796bf01f215840/nodes/teleop_legged_keyboard.py#L17), which is long deprecated; it really should be using `tf2`.

When did this become a requirement for listing a package in rosdistro? Like, if that's a requirement, we probably gotta delist 25-50% of the things in rosdistro (for example, http://wiki.ros.org/tf shows 290 melodic packages and 66 noetic packages that depend directly on tf. That doesn't even count the transitive dependencies - for instance pcl_ros has an additional 20 packages that depend on it in noetic).

2021-01-20 20:35 UTC, tarasborov commented
Thanks for the comments. I have committed the updated code to the GitHub 

1) I double checked how the code works in all three distributives. Everything runs fine, so I guess that [shebangs](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs) did the trick, as @mikeferguson and @sloretz pointed out. Therefore, I did not do any changes to the code.  

2) Initially I expected that tf should be enough, but I got curious how it will work with [tf2](http://wiki.ros.org/tf2/Tutorials/Quaternions) and updated the code.  

3) Great catch @clalancette I simplified the [package structure]( http://wiki.ros.org/PyStyleGuide#Package.2FModule_Names_.28__init__.py_files.29)  

 

4) I had strange issues with bloom while entering git credentials to create a PR, thus, I created it manually. Perhaps SSH authentication would help, but I didn’t try it.

2021-01-21 01:16 UTC, sloretz commented
holding for the [upcoming Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-01-22/18570)

2021-01-26 13:02 UTC, ivanpauno approved these changes

2021-01-26 13:04 UTC, ivanpauno commented
The comments seem to have been addressed, and based on a [previous comment](https://github.com/ros/rosdistro/pull/28021#issuecomment-763735769) this was already good to go, so merging!

2021-01-26 13:04 UTC, ivanpauno approved these changes

2021-01-26 13:07 UTC, merged