add python-mechanize-pip
ros/rosdistro pull request #28067
Opened 2021-01-23 12:20 UTC by fmessmer

this adds a rosdep key for the pip version of `mechanize` (https://pypi.org/project/mechanize/)

officital `python-mechanize`/`python3-mechanize` are already available, but `python3-mechanize` is not available for `debian:buster` and thus results in problematic release of e.g. https://github.com/ipa320/cob_command_tools
(read more about it in https://github.com/ipa320/cob_command_tools/issues/289

2021-01-25 00:48 UTC, tfoote requested changes
We shouldn't add pip rules that will conflict/override existing debian rules. If any package in the workspace or system depends on the pip rule it will override the version that is available on the system and potentially break anyone using the apt based key. If we want to add this key it should only be valid for platforms where there is no resolution for the conflicting apt/debian based key.

2021-01-25 21:20 UTC, nuclearsandwich commented
In addition to @tfoote's points above about not mixing keys. Pip packages can't be used to resolve dependencies for packages released via bloom. Based on the comment here: https://github.com/ipa320/cob_command_tools/issues/289#issuecomment-766696766 it seems like this dependency has been worked around. If that's the case @fmessmer can we close this PR as unnecessary?

Thanks for iterating on the solution with us!

2021-01-26 08:02 UTC, fmessmer commented
yes, I guess I won't need this anymore once the following PRs are merged:
- https://github.com/ros/rosdistro/pull/28071
- https://github.com/ros/rosdistro/pull/28072
- https://github.com/ros-infrastructure/ros_buildfarm_config/pull/196

2021-01-29 17:49 UTC, fmessmer commented
https://github.com/ros-infrastructure/ros_buildfarm_config/pull/196 is merged and the release does not issue any warnings anymore...so I guess this key is not needed anymore....

2021-01-29 17:49 UTC, closed without merging