add key for GStreamer plugins for GL
ros/rosdistro pull request #28148
Opened 2021-01-27 15:31 UTC by zflat

Provides the library `libgstopengl.so` for gstreamer GL plugins

* Arch: https://archlinux.org/packages/extra/x86_64/gst-plugins-base/
* Debian: https://packages.debian.org/sid/gstreamer1.0-gl
* Fedora: https://src.fedoraproject.org/rpms/gstreamer1-plugins-base
* Ubuntu: https://packages.ubuntu.com/bionic/gstreamer1.0-gl

2021-01-29 01:44 UTC, mabelzhang reviewed
The `ubuntu` entry needs `xenial: null`.

The package used to exist on Gentoo but has been moved to the `bad` category, meaning something is missing. Apparently gstreamer names their plugins in the categories of the good, the bad, and the ugly? So I guess it isn't required to include it.
https://packages.gentoo.org/packages/media-libs/gst-plugins-bad

2021-01-29 18:34 UTC, mabelzhang reviewed
Ehh `xenial` shouldn't have quotes around it. It didn't break the checks, but we should follow the convention.

2021-01-29 21:19 UTC, zflat commented
@mabelzhang thanks for catching the inconsistency with the quotes. fixed in 30527cb

2021-01-29 21:22 UTC, mabelzhang approved these changes

2021-02-01 19:48 UTC, jacobperron requested changes

2021-02-01 19:48 UTC, jacobperron commented on rosdep/base.yaml
> +  debian: [gstreamer1.0-gl]
I think we should add an entry for `stretch`, which is still a supported LTS but does not have `gstreamer1.0-gl`:
```suggestion
  debian:
    '*': [gstreamer1.0-gl]
    stretch: null
```

2021-02-01 20:28 UTC, jacobperron approved these changes

2021-02-01 20:29 UTC, jacobperron commented
@zflat Thanks for iterating!

2021-02-01 20:29 UTC, merged