robotont_gazebo: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #28230
Opened 2021-02-03 10:26 UTC by mmaao

Increasing version of package(s) in repository `robotont_gazebo` to `0.0.2-1`:

- upstream repository: https://github.com/robotont/robotont_gazebo.git
- release repository: https://github.com/robotont-release/robotont_gazebo-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.0`
- previous version for package: `null`

2021-02-03 17:08 UTC, tfoote requested changes
Unfortunately, inserting this at the same spot as robotont_msgs so conflicts and needs a merge resolution.

2021-02-03 21:45 UTC, wjwwood commented
@mmaao you can either open a new pull request with bloom by running the same bloom command and adding the `--pull-request-only` flag, or you can try to fix the merge conflict yourself on this branch.

2021-02-05 01:36 UTC, tfoote approved these changes

2021-02-05 01:36 UTC, tfoote commented
@mmaao thanks for the conflict resolution.

2021-02-05 01:36 UTC, merged