Add rosdep key for python3-ezdxf
ros/rosdistro pull request #28283
Opened 2021-02-10 12:18 UTC by rluqueb

Add python3-ezdxf to rosdep/python.yaml file

ezdxf is a Python package to create new DXF files and read/modify/write existing DXF files

debian: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-ezdxf
ubuntu: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-ezdxf&searchon=names
pip: https://pypi.org/project/ezdxf/

2021-02-11 17:38 UTC, hidmic reviewed
@rluqueb would you mind adding Fedora, Gentoo, and ideally OSX as well (as per [contributing guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules))?

2021-02-12 16:39 UTC, hidmic approved these changes
Leaving a trail of references for Fedora and FreeBSD would be nice.

2021-02-12 16:46 UTC, rluqueb commented
Yes of course!

https://www.freebsd.org/cgi/ports.cgi?query=ezdxf&stype=all
https://fedora.pkgs.org/33/rpm-sphere-noarch/python3-ezdxf-0.8.8-4.1.noarch.rpm.html

Thank you very much for your comments

2021-02-16 06:31 UTC, cottsay requested changes

2021-02-16 06:31 UTC, cottsay commented on rosdep/python.yaml
> +  debian: [python3-ezdxf]
This seems to only be available for Bullseye and newer.

```suggestion
  debian:
    '*': [python3-ezdxf]
    buster:
      pip:
        packages: [ezdxf]
    stretch:
      pip:
        packages: [ezdxf]
```

2021-02-16 06:58 UTC, cottsay approved these changes

2021-02-16 06:58 UTC, merged