rosserial_leonardo_cmake: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #28298
Opened 2021-02-11 14:39 UTC by civerachb-cpr

Increasing version of package(s) in repository `rosserial_leonardo_cmake` to `0.1.4-1`:

- upstream repository: https://github.com/clearpathrobotics/rosserial_leonardo_cmake.git
- release repository: https://github.com/clearpath-gbp/rosserial_leonardo_cmake-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.1`
- previous version for package: `null`

## rosserial_leonardo_cmake

```
* Updated arduino link from google code
* Contributors: Dave Niewinski
```

2021-02-11 18:16 UTC, hidmic reviewed
@civerachb-cpr it'd be good to include a LICENSE file at the root of the source repository.

2021-02-11 18:24 UTC, civerachb-cpr commented
Noted.  I've added the file, but I'm not sure it's worth re-blooming for that single change; the existing Kinetic release is also missing that file.

2021-02-11 18:30 UTC, hidmic commented
Releasing tags that have a LICENSE file would be best :)

2021-02-11 19:07 UTC, civerachb-cpr commented
Given that this is the exact same tag that was previously released for Kinetic, and the Kinetic version is also lacking that file, is the lack of the license file actively going to cause problems for this PR?

2021-02-16 13:26 UTC, hidmic approved these changes
@civerachb-cpr ok, I'll let this one in. Hopefully things fall in place by the time this package gets re-released.

Though I will point out, as @cottsay pointed out to me, that there are MPL-licensed files in https://github.com/clearpathrobotics/rosserial_leonardo_cmake/, not only BSD-licensed ones. Both package.xml and LICENSE file (or several of these) should reflect this.

2021-02-24 13:41 UTC, clalancette requested changes
As @hidmic pointed out, there are both MPL-licensed files and (implicitly) BSD-licensed files in the source repository.  Please add a `<license>MPL</license>` tag to the package.xml, add an additional LICENSE file to the top-level, and do a new release.  That should unblock this package.

2021-03-15 18:44 UTC, ivanpauno commented
@civerachb-cpr friendly ping, could you address the previous review feedback? thanks!

2021-03-15 18:47 UTC, civerachb-cpr commented
Sorry, I've been busy with other tasks.  I've talked to the maintainer of the package in questions and let them know about your request.

2021-03-16 18:03 UTC, civerachb-cpr commented
I think things should be ok now; the license data has been updated & included in the 0.5.1 release.  I've bumped the version in this PR accordingly.

2021-03-16 18:24 UTC, ivanpauno approved these changes

2021-03-16 18:25 UTC, ivanpauno commented
Holding for Melodic [sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2021-03-15/19458).

2021-03-18 19:43 UTC, clalancette approved these changes

2021-03-18 19:43 UTC, merged

2021-03-19 05:59 UTC, furukawahiromi commented
I'm sorry to make a mistake in the link.