scan_tools: 0.3.3-1 in 'melodic/distribution.yaml' [non-bloom]
ros/rosdistro pull request #28331
Opened 2021-02-15 20:06 UTC by 130s

Increasing version of package(s) in repository ros_led to 0.3.3-1:
-    upstream repository: https://github.com/ros-gbp/scan_tools-release.git
-    release repository: https://github.com/ros-gbp/scan_tools-release.git
-    distro file: melodic/distribution.yaml
-    bloom version: 0.10.1
-    previous version for package: null

NOTE: PR is made manually due to the issue [answers.ros.org#371864](https://answers.ros.org/question/371864/bloom-release-fais-aborting-pull-request-http-error-401-unauthorized/).

2021-02-16 19:50 UTC, ahcorde approved these changes

2021-02-16 19:50 UTC, ahcorde requested changes, later dismissed
Something went wrong in the CI, do you mind to have a look ?

2021-02-24 13:38 UTC, 130s commented
I found the following error regarding `zstd_vendor`, which doesn't seem to be a part of the change made in this PR. Not familliar with GHA yet, I can't find a way to restart the CI to see this was just a temporary error.

https://github.com/ros/rosdistro/pull/28331/checks?check_run_id=1933311512#step:6:8349
```
FAILED (failures=1)
.  - updated manifest of package 'zstd_vendor' to version '0.6.0'
```

2021-02-24 15:25 UTC, clalancette commented
It's still failing.  It looks like what is in the release repo may not match what is here?  It's not totally clear to me, but this is the diff that it thinks is a problem:

```
--- file:///home/runner/work/rosdistro/rosdistro/melodic/distribution.yaml
+++ loaded-and-saved
@@ -11796,11 +11796,11 @@
     doc:
-      type: git                              
-      url: https://github.com/ccny-ros-pkg/scan_tools.git                                                                                
-      version: ros1                       
-    release:                                                    
-      packages:                               
-      - laser_ortho_projector                      
+      type: git
+      url: https://github.com/ccny-ros-pkg/scan_tools.git
+      version: ros1
+    release:
+      packages:
+      - laser_ortho_projector
       - laser_scan_matcher
-      - laser_scan_sparsifier                                   
-      - laser_scan_splitter                 
+      - laser_scan_sparsifier
+      - laser_scan_splitter
       - ncd_parser
```

2021-03-15 18:47 UTC, ivanpauno commented
@130s friendly ping

2021-03-22 19:54 UTC, jacobperron commented
@130s Friendly ping

2021-03-23 04:08 UTC, 130s commented
Hm the info in https://github.com/ros/rosdistro/pull/28331#issuecomment-785154648 doesn't click anything in my mind. That said I rebased to the latest `master` and pushed to see if that lets ci pass.

2021-03-23 04:42 UTC, 130s commented
<details><summary>Same issue still occurs.</summary>

I did run `bloom` again locally (hence pkg version is incremented and now it's `0.3.3-2`).

https://github.com/ros/rosdistro/pull/28331/checks?check_run_id=2172214465#step:6:168
```
Checking if the distribution files of 'rolling' contain valid urls for known hosting services.
If this fails you can run 'scripts/check_rosdistro_urls.py file://`pwd`/index.yaml rolling' to perform the same check locally.

...--- file:///home/runner/work/rosdistro/rosdistro/melodic/distribution.yaml
+++ loaded-and-saved
@@ -11968,11 +11968,11 @@
     doc:
-      type: git                              
-      url: https://github.com/ccny-ros-pkg/scan_tools.git                                                                                
-      version: ros1                       
-    release:                                                    
-      packages:                               
-      - laser_ortho_projector                      
+      type: git
+      url: https://github.com/ccny-ros-pkg/scan_tools.git
+      version: ros1
+    release:
+      packages:
+      - laser_ortho_projector
       - laser_scan_matcher
-      - laser_scan_sparsifier                                   
-      - laser_scan_splitter                 
+      - laser_scan_sparsifier
+      - laser_scan_splitter
       - ncd_parser
```
</details>

Locally I also ran (on Ubuntu 20.04 I had to make Python version change manually like this.) but I don't see the same thing above?

```
$ head -n 1 scripts/check_rosdistro_urls.py
#!/usr/bin/env python3

$ ./scripts/check_rosdistro_urls.py file://`pwd`/index.yaml rolling
..................................................................................................................................................................................
```

2021-03-23 21:34 UTC, mabelzhang commented
Looks like it's complaining about the trailing whitespaces.

2021-03-23 23:53 UTC, tfoote commented
Confirmed the trailing whitespace is failing the build here's the CI output highlighted to make the trailing whitespace more visible. 

![Screenshot from 2021-03-23 16-51-47](https://user-images.githubusercontent.com/447804/112233742-30189600-8bf8-11eb-9cd4-cdd24ae6954f.png)

2021-04-08 21:17 UTC, 130s commented
Thanks all. Looks like that was it. How could you tell the whitespace was causing CI to fail...

Whitespace got in likely because I had to manually open this PR due to [answers.ros.org#q371864](https://answers.ros.org/question/371864/bloom-release-fais-aborting-pull-request-http-error-401-unauthorized/).

2021-04-14 19:04 UTC, cottsay approved these changes
Note that this repository is missing a file containing the license text, but this is not a blocker since it has been part of ROS before.

It would still be a good idea to add it for the next release.

2021-04-21 13:57 UTC, merged