Fix python-opencv for Ubuntu focal (20.04)
ros/rosdistro pull request #28419
Opened 2021-02-26 09:28 UTC by marcoesposito1988

As of 20.04, python-opencv is no longer present in the APT repositories, and was superseded by python3-opencv. 

This is also coherent with the switch from python2 to python3 that happened between ROS Melodic and Noetic.

Solves https://github.com/IFL-CAMP/easy_handeye/issues/74

2021-02-26 09:33 UTC, tfoote requested changes
python2 and python3 packages are not interchangeable as they do not provide the same content please create a new key `python3-opencv` for focal and newer so maintainers can be confident about which version they are going to get.

Also for review of rosdep submissions please link to the package listings online for others faster reference.

2021-02-26 09:35 UTC, marcoesposito1988 commented
Alright, thanks!

2021-02-26 09:46 UTC, marcoesposito1988 commented
Apparently it was already present. Sorry for the inconvenience.

2021-02-26 09:46 UTC, closed without merging

2021-03-01 16:51 UTC, tfoote commented
No problem, glad it's already working.

If you need to span a package across distros you can use the the conditional dependency in package.xml https://www.ros.org/reps/rep-0151.html


```
  <depend condition="$ROS_PYTHON_VERSION == 2">python-opencv</depend>
  <depend condition="$ROS_PYTHON_VERSION == 3">python3-opencv</depend>
```