Added pyrr(python3-pyrr) at python.yaml
ros/rosdistro pull request #28461
Opened 2021-03-03 03:10 UTC by blaine141

Just added python3-pyrr rosdep rules for pyrr ( https://pypi.org/project/pyrr/ ).

Test on Ubuntu with:

```
rosdep update && rosdep resolve python3-pyrr
#pip
pyrr
```

2021-03-03 15:08 UTC, clalancette requested changes

2021-03-03 15:08 UTC, clalancette commented on rosdep/python.yaml
> +python3-pyrr:
Since this is a pip-only package, please make this:

```suggestion
python3-pyrr-pip:
```

2021-03-03 15:08 UTC, clalancette commented on rosdep/python.yaml
> +  ubuntu:
Also, can you add at least debian support as well?

2021-03-04 16:03 UTC, clalancette approved these changes

2021-03-09 14:11 UTC, belorenz commented
Could someone please merge this?

2021-03-09 17:16 UTC, sloretz approved these changes

2021-03-09 17:16 UTC, merged

2021-03-10 11:07 UTC, belorenz commented
thanks! <3