ament_cmake: 1.1.3-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #28526
Opened 2021-03-09 21:43 UTC by hidmic

Increasing version of package(s) in repository `ament_cmake` to `1.1.3-1`:

- upstream repository: https://github.com/ament/ament_cmake.git
- release repository: https://github.com/ros2-gbp/ament_cmake-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.10.1`
- previous version for package: `1.1.2-1`

2021-03-09 23:54 UTC, cottsay requested changes
Please hold this for pending re-releases of `rmw_implementation` and `rosidl_typesupport`.

2021-03-10 18:21 UTC, hidmic commented
@cottsay can we move forward with this?

2021-03-10 18:23 UTC, cottsay commented
> @cottsay can we move forward with this?

No, not yet. Please hold - I'll be ready this afternoon.

2021-03-10 23:38 UTC, cottsay approved these changes
Thanks for holding, the other package releases are done.

2021-03-10 23:42 UTC, merged