Adding python3-seaborn for Ubuntu focal
ros/rosdistro pull request #28817
Opened 2021-03-24 14:10 UTC by tylernewnoise

Please add the following dependency for python3-seaborn for Ubuntu Focal 20.04 to the rosdep database.

## Package name:

python3-seaborn

## Package Upstream Source:

https://github.com/mwaskom/seaborn

## Purpose of using this:

This dependency is being used in a www.dlr.de research project. 

Distro packaging links:

## Links to Distribution Package

- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/focal/python3-seaborn

2021-03-24 20:01 UTC, tfoote requested changes
Have you tested and validated that this does what you want? This syntax has been deprecated for years and requires manual environment variable override arguments passed to rosdep.

The correct way to do this is to create a new `python3-seaborn` key in parallel with the existing one. It looks like the ubuntu package has been around for a long time so the equivalent deian package should be available. Gentoo and Arch can use the same package for the py2 and py3 rules. And I'd suggest looking if Fedora has a package for it now however many years later.

2021-03-24 22:20 UTC, tylernewnoise commented
Hm, you're right, for whatever reason it does not what I want, although I tested it before this PR, sry. I also wasn't aware that the syntax is deprecated, as I commited something similar to this one [here](https://github.com/ros/rosdistro/pull/28282) and I couldn't see any difference? :man_shrugging: 

Anyway, I can create the extra entry for the python3 package. Should this be closed here or can I make the changes in this PR?
Thank you.

2021-03-24 22:44 UTC, tfoote commented
You can update this branch and it will update the PR. Just comment back here so we get a notification when you push the updates.

2021-03-24 22:45 UTC, tfoote commented
Note that the difference is between `focal` and `focal_python3` you have to override your system identification to use that key.

2021-03-24 23:08 UTC, tylernewnoise commented
Added the new entry. Not sure if it makes sense to remove the arch and gentoo ones from ``python-seaborn`` as they are for Python3 only?

## Links to Distribution Package

- Debian: https://packages.debian.org/
  -  https://packages.debian.org/buster/python3-seaborn
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/focal/python3-seaborn
- Fedora: https://apps.fedoraproject.org/packages/
  - Service unabailable, checked on  https://fedora.pkgs.org/32/fedora-x86_64/python3-seaborn-0.9.0-9.fc32.noarch.rpm.html instead
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/community/any/python-seaborn/
- Gentoo: https://packages.gentoo.org/packages/
  - https://packages.gentoo.org/packages/dev-python/seaborn

2021-03-25 10:25 UTC, tylernewnoise commented
I'm not sure why the pipeline fails. Couldn't find whitespaces and it's alphabetically ordered - can some please help me out on how to fix it?

2021-03-26 00:00 UTC, tfoote commented
If you scroll up in the console output it says:

`  ERR: list out of alphabetical order line 4283.  'python-selectors2-pip' should come before 'python3-seaborn'`

The python3 rules will not be adjacent to the python rules.

> Added the new entry. Not sure if it makes sense to remove the arch and gentoo ones from python-seaborn as they are for Python3 only?

No you shouldn't remove gentoo and arch rules. THey have been using all the python keys under python3 for a long time. They don't differentiate python2 and python3, it goes with the system.

2021-03-26 00:13 UTC, tylernewnoise commented
Thx @tfoote for clearing things up. :+1:  :nerd_face:

2021-03-30 17:18 UTC, wjwwood approved these changes
lgtm

2021-03-31 22:17 UTC, tfoote approved these changes
Thanks for iterating. I did one small fixup to simplify the ubuntu rule to the minimum too. 

Ready for merge once CI for that fixup passes.

2021-03-31 22:54 UTC, merged