added smbus2 python key
ros/rosdistro pull request #28830
Opened 2021-03-25 12:19 UTC by Prat33k-dev

Added smbus2 key to python.yaml. We need it for our robot's i2c communication. Kindly merge it to master.
`https://pypi.org/project/smbus2/`

@mabelzhang @cottsay @hidmic

2021-03-25 23:54 UTC, tfoote requested changes
Please edit your description using the template that we provide for rosdep keys: https://github.com/ros/rosdistro/blob/master/.github/pull_request_template.md

It should have been presented to you when you opened the PR. 

And please justify why this should be used instead of the python-smbus key. The description for the project is that it's "A drop-in replacement for smbus-cffi/smbus-python in pure Python" as such it would seem that using the packaged version might make more sense.

Also from the [contributing guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md) assuming the above is correct it should have a `python3` prefix

2021-03-26 09:36 UTC, Prat33k-dev commented
> Please edit your description using the template that we provide for rosdep keys: https://github.com/ros/rosdistro/blob/master/.github/pull_request_template.md
> 
> It should have been presented to you when you opened the PR.
> 
> And please justify why this should be used instead of the python-smbus key. The description for the project is that it's "A drop-in replacement for smbus-cffi/smbus-python in pure Python" as such it would seem that using the packaged version might make more sense.
> 
> Also from the [contributing guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md) assuming the above is correct it should have a `python3` prefix

I have iterated the pr description according to the guidelines and provided justification as to why we require this package.

2021-03-31 22:14 UTC, tfoote requested changes
Thanks for adding the justification. That makes sense and I don't see non-pip packaging.

One small syntax fix for the rule though.

2021-03-31 22:14 UTC, tfoote commented on rosdep/python.yaml
> +python-smbus2-pip:
```suggestion
python3-smbus2-pip:
```

pip rules should start with python3
Accepting this will then also require fixing the alphabetization too.

2021-04-02 01:01 UTC, tfoote approved these changes

2021-04-02 01:02 UTC, tfoote commented
Thanks for the updates.

2021-04-08 19:34 UTC, hidmic approved these changes
LGTM!

2021-04-08 19:34 UTC, merged