clover: 0.21.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #28873
Opened 2021-03-26 16:27 UTC by deadln

Increasing version of package(s) in repository `clover` to `0.21.2-1`:

- upstream repository: https://github.com/CopterExpress/clover.git
- release repository: https://github.com/CopterExpress/clover-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.2`
- previous version for package: `null`

2021-03-26 16:31 UTC, deadln commented
All questions about source code address to @okalachev

2021-03-26 18:29 UTC, deadln commented
Also i've created postinstall rules for `clover` package https://github.com/CopterExpress/clover-release/blob/debian/melodic/clover/debian/postinst

2021-03-28 17:22 UTC, deadln commented
I've created a [page](http://wiki.ros.org/aruco_pose) in ROS wiki for package **aruco_pose**, but it seems that package with name **aruco_pose** already existed sometime ago (but i haven't found it in any distribution.yaml file in rosdistro) and thus the wiki page now contains metadata of this old package. Is there any way to delete this old metadata?

2021-03-30 17:09 UTC, wjwwood commented
> Also i've created postinstall rules for clover package https://github.com/CopterExpress/clover-release/blob/debian/melodic/clover/debian/postinst

Thanks for pointing that out. Can I get a second look from @tfoote or @nuclearsandwich or @cottsay?

2021-03-31 21:07 UTC, tfoote requested changes
Side effecting the system installation with a system-wide pip installation is not good behavior for a debian package post install hook. This should not be accepted.

If you need a custom version of that you should be doing something like embedding it in an internal venv cointained in your package so it won't interfere with other users on the system.

The best solution is to work to create a debian package for it upstream. Howver, this is a long process. The second best approach would be to create a ROS vendor package for it that wraps it up and thus generates debian packages. (Both of these would make sense to work with the upstream maintainers)

2021-03-31 21:12 UTC, tfoote commented
> Re the wiki page.

The metadata is versioned by rosdistro via the tabs at the top. When yours is indexed it will add a new melodic tab at the top. You shouldn't try to delete the older content, but let it be and yours will exist side by side with it.

2021-04-01 06:44 UTC, deadln commented
> Side effecting the system installation with a system-wide pip installation is not good behavior for a debian package post install hook. This should not be accepted.
> 
> If you need a custom version of that you should be doing something like embedding it in an internal venv cointained in your package so it won't interfere with other users on the system.
> 
> The best solution is to work to create a debian package for it upstream. Howver, this is a long process. The second best approach would be to create a ROS vendor package for it that wraps it up and thus generates debian packages. (Both of these would make sense to work with the upstream maintainers)

@tfoote I like the option with internal venv. But which kind of virtual envirmoment it supposed to be? A folder with library inside repo (or maybe symlink to it like **pymavlink** [here](https://github.com/mavlink/mavlink))? An actual python venv? Or something else ROS-specific?

2021-04-01 06:46 UTC, gavanderhoorn commented
For ROS 1 you could perhaps see whether [catkin_virtualenv](http://wiki.ros.org/catkin_virtualenv) could be used.

2021-04-01 06:47 UTC, deadln commented
> For ROS 1 you could perhaps see whether [catkin_virtualenv](http://wiki.ros.org/catkin_virtualenv) could be used.

Thanks! I will check it out!

2021-04-02 20:48 UTC, deadln commented
@tfoote i've created [trial release](https://github.com/deadln/clover-release) files with venv created with [catkin_virtualenv](http://wiki.ros.org/catkin_virtualenv). Please review it and tell me is everything OK?

2021-04-08 19:47 UTC, hidmic commented
I'm not uber familiar with `catkin_virtualenv`, I must say. @deadln have you tried to build your debian locally? I wonder if an extra virtualenv relocation step should happen post debian installation.

2021-04-08 19:53 UTC, gavanderhoorn commented
I've released `haros_catkin` using `catkin_virtualenv` (in #22146).

> I wonder if an extra virtualenv relocation step isn't required post debian installation.

No, it should not be.

See [haros_catkin](https://github.com/rosin-project/haros_catkin/tree/d04963766f76bb29be732f7cf91a53920bdc1d9b) for the source repository.

2021-04-08 20:06 UTC, hidmic commented
> No, it should not be.

Wonderful. Thanks @gavanderhoorn !

@deadln your changes seem OK. I'd still suggest a test.

2021-04-09 05:09 UTC, gavanderhoorn commented
> @deadln your changes seem OK. I'd still suggest a test.

I agree. A [prerelease build](http://wiki.ros.org/bloom/Tutorials/PrereleaseTest) would be a good idea to make sure files end up in the expected locations.

2021-04-09 14:43 UTC, deadln commented
> have you tried to build your debian locally?

@hidmic Thank you for your attention. I tried to do this today, but i got this error:
```
The packages or cmake arguments have changed, forcing cmake invocation

==> Processing catkin package: 'aruco_pose'
==> Creating build directory: 'build_isolated/aruco_pose'
==> cmake /tmp/ws/src/clover__custom-1/aruco_pose -DCATKIN_DEVEL_PREFIX=/tmp/ws/devel_isolated/aruco_pose -DCMAKE_INSTALL_PREFIX=/tmp/ws/install_isolated -DBUILD_TESTING=0 -DCATKIN_SKIP_TESTING=1 -G Unix Makefiles in '/tmp/ws/build_isolated/aruco_pose'
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/lib/ccache/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_d0517/fast"
    /usr/bin/make -f CMakeFiles/cmTC_d0517.dir/build.make CMakeFiles/cmTC_d0517.dir/build
    make[1]: Entering directory '/tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_d0517.dir/testCCompiler.c.o
    /usr/lib/ccache/cc    -o CMakeFiles/cmTC_d0517.dir/testCCompiler.c.o   -c /tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeTmp/testCCompiler.c
    ccache: error: Failed to create directory /home/buildfarm/.ccache/tmp: Permission denied
    CMakeFiles/cmTC_d0517.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_d0517.dir/testCCompiler.c.o' failed
    make[1]: *** [CMakeFiles/cmTC_d0517.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_d0517/fast' failed
    make: *** [cmTC_d0517/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeOutput.log".
See also "/tmp/ws/build_isolated/aruco_pose/CMakeFiles/CMakeError.log".
<== Failed to process package 'aruco_pose': 
  Command '['cmake', '/tmp/ws/src/clover__custom-1/aruco_pose', '-DCATKIN_DEVEL_PREFIX=/tmp/ws/devel_isolated/aruco_pose', '-DCMAKE_INSTALL_PREFIX=/tmp/ws/install_isolated', '-DBUILD_TESTING=0', '-DCATKIN_SKIP_TESTING=1', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /tmp/ws/build_isolated/aruco_pose && cmake /tmp/ws/src/clover__custom-1/aruco_pose -DCATKIN_DEVEL_PREFIX=/tmp/ws/devel_isolated/aruco_pose -DCMAKE_INSTALL_PREFIX=/tmp/ws/install_isolated -DBUILD_TESTING=0 -DCATKIN_SKIP_TESTING=1 -G 'Unix Makefiles'

Command failed, exiting.
# END SUBSECTION
```
I also tried to isolate `clover` package and build prerelease only for it, but got exactly same error.
Some time ago i build `clover` package many times for sake of testing postinst rules using [this](https://gist.github.com/awesomebytes/196eab972a94dd8fcdd69adfe3bd1152) guide. But recently i updated my Ubuntu to 20.04. I tried to build `clover` package on different places (virtual machine, my second PC, docker-container of [img-tool:builder-mod](https://hub.docker.com/r/sfalexrog/img-tool)), but when i run `fakeroot debian/rules binary` i always get this error:
```
Run Build Command:"/usr/bin/make" "cmTC_01b40/fast"
make[2]: Entering directory '/home/deadln/programming/rosdistro/clover/clover/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_01b40.dir/build.make CMakeFiles/cmTC_01b40.dir/build
make[3]: Entering directory '/home/deadln/programming/rosdistro/clover/clover/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_01b40.dir/CheckFunctionExists.c.o
/usr/bin/cc   -g -O2 -fdebug-prefix-map=/home/deadln/programming/rosdistro/clover/clover=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_01b40.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_01b40
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_01b40.dir/link.txt --verbose=1
/usr/bin/cc -g -O2 -fdebug-prefix-map=/home/deadln/programming/rosdistro/clover/clover=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_01b40.dir/CheckFunctionExists.c.o  -o cmTC_01b40 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_01b40.dir/build.make:97: recipe for target 'cmTC_01b40' failed
make[3]: *** [cmTC_01b40] Error 1
make[3]: Leaving directory '/home/deadln/programming/rosdistro/clover/clover/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_01b40/fast' failed
make[2]: *** [cmTC_01b40/fast] Error 2
make[2]: Leaving directory '/home/deadln/programming/rosdistro/clover/clover/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'


dh_auto_configure: cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/melodic -DCMAKE_PREFIX_PATH=/opt/ros/melodic returned exit code 1
debian/rules:25: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 255
make[1]: Leaving directory '/home/deadln/programming/rosdistro/clover/clover'
debian/rules:22: recipe for target 'binary' failed
make: *** [binary] Error 2
```
For now i don't know what else i can do. Except to remove `pymavlink` dependency and ask users to install it manually.

2021-04-09 15:08 UTC, hidmic commented
@deadln https://answers.ros.org/question/347063/error-pre-release-melodic/ may come in handy.

2021-04-09 15:10 UTC, deadln commented
> @deadln https://answers.ros.org/question/347063/error-pre-release-melodic/ may come in handy.

Thank you for reply. It fixed the problem, but another accured:
```
CMake Error at cmake_install.cmake:168 (file):
  file INSTALL cannot find
  "/tmp/ws/devel_isolated/aruco_pose/include/aruco_pose/DetectorParamsConfig.h".


Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1
<== Failed to process package 'aruco_pose': 
  Command '['make', 'install']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /tmp/ws/build_isolated/aruco_pose && make install

Command failed, exiting.
# END SUBSECTION
```

2021-04-09 18:23 UTC, deadln commented
I tried to build a prerelease of isolated `clover` package again, and i succeed! The package has been passed venv tests, but it failed basic tests with:
```
Package [ros_pytest] for test node [ros_pytest/ros_pytest_runner] does not exist
```
Should we delay debian release until every package could build prerelease and pass all tests?

2021-04-16 13:24 UTC, hidmic commented
> Should we delay debian release until every package could build prerelease and pass all tests?

A prerelease isn't mandatory, no. But if it doesn't build for you, chances are it won't build in the buildfarm either. Have you followed [the instructions](http://wiki.ros.org/bloom/Tutorials/PrereleaseTest)?

2021-05-05 12:30 UTC, hidmic commented
@deadln friendly ping.

2021-05-05 13:18 UTC, deadln commented
@hidmic we still not fixed all problems

2021-05-06 15:18 UTC, nuclearsandwich commented
@deadln since the fixes you're working on will likely require a new release does it make sense to close this PR while you work on the fixes?

2021-05-08 00:54 UTC, tfoote commented
Closing this so we don't keep revisiting it and tracking it. The new release will open a new PR for us to review. Please reference back to this one when you/bloom opens the new one.

2021-05-08 00:54 UTC, closed without merging