[dep] Add python3-colcon-common-extensions
ros/rosdistro pull request #28923
Opened 2021-04-01 04:31 UTC by 130s

## Package name:

`python3-colcon-common-extensions`

## Purpose of using this:

Allow `rosdep install` to install `colcon`. 

## Links to Distribution Packages

- x Debian: https://packages.debian.org/
- x Ubuntu: https://packages.ubuntu.com/

## Problem

- I have no idea if this is the right way to achieve installing `colcon` via `rosdep. As asked at [answers.ros.org#q374424](https://answers.ros.org/question/374424/install-colcon-via-rosdep-install/), I can't find a way to achieve that.
- Choice of the package is from [colcon.readthedocs.io](https://colcon.readthedocs.io/en/released/user/installation.html) that recommends installing this pkg to use `colcon`.

2021-04-02 01:13 UTC, tfoote requested changes
This is a valid way to depend on the tools because we make sure that they're in the ROS repositories. https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#expected-rosdep-sources

As such we can add both the debian and ubuntu targets for this as rosdeps.

2021-04-02 01:13 UTC, tfoote commented on rosdep/python.yaml
> +  ubuntu: [python3-colcon-common-extensions]
```suggestion
  debian: [python3-colcon-common-extensions]
  ubuntu: [python3-colcon-common-extensions]
```

2021-04-02 02:26 UTC, cottsay commented
`python3-colcon-common-extensions` is in the repositories for Fedora and EPEL as well: https://src.fedoraproject.org/rpms/python-colcon-common-extensions#bodhi_updates
```yaml
  fedora: [python3-colcon-common-extensions]
  rhel: ['python%{python3_pkgversion}-colcon-common-extensions']
```

2021-04-06 08:40 UTC, 130s commented
Thank you @tfoote  @cottsay. Updated.

I wasn't aware that ros.org is required in apt source for `rosdep`.

2021-04-07 16:41 UTC, tfoote approved these changes

2021-04-07 16:45 UTC, cottsay requested changes

2021-04-07 16:45 UTC, cottsay commented on rosdep/python.yaml
> +  rhel: ['python%{python3_pkgversion}-colcon-common-extensions']
```suggestion
  rhel: ['python%{python3_pkgversion}-colcon-common-extensions']
```

2021-04-08 20:33 UTC, hidmic commented on rosdep/python.yaml
> +  rhel: ['python%{python3_pkgversion}-colcon-common-extensions']
@130s friendly ping

2021-04-08 21:19 UTC, 130s commented on rosdep/python.yaml
> +  rhel: ['python%{python3_pkgversion}-colcon-common-extensions']
Thx, I think addressed.

2021-04-14 20:04 UTC, cottsay approved these changes

2021-04-14 20:05 UTC, merged