cpr_common_core: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #29189
Opened 2021-04-16 15:10 UTC by tonybaltovski

Increasing version of package(s) in repository `cpr_common_core` to `0.1.0-1`:

- upstream repository: https://github.com/clearpathrobotics/cpr_common_core.git
- release repository: https://github.com/clearpath-gbp/cpr_common_core-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.6`
- previous version for package: `null`

## cpr_common_core_msgs

```
* [cpr_common_core_msgs] Added messages.
* Contributors: Tony Baltovski
```

2021-04-21 14:17 UTC, clalancette requested changes

2021-04-21 14:17 UTC, clalancette commented on melodic/distribution.yaml
> +      url: https://github.com/clearpathrobotics/cpr_common_core.git
@tonybaltovski Can you please put a LICENSE file in `cpr_common_core`?  Thanks.

2021-05-05 13:50 UTC, ivanpauno commented
@tonybaltovski friendly ping

2021-05-17 12:55 UTC, clalancette approved these changes

2021-05-17 12:55 UTC, merged