ros2_tracing: 2.3.0-3 in 'galactic/distribution.yaml' [bloom]
ros/rosdistro pull request #29410
Opened 2021-05-04 19:35 UTC by christophebedard

Increasing version of package(s) in repository `ros2_tracing` to `2.3.0-3`:

- upstream repository: https://gitlab.com/ros-tracing/ros2_tracing.git
- release repository: https://gitlab.com/ros-tracing/ros2_tracing-release.git
- distro file: `galactic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `2.3.0-2`

## tracetools

```
* Update QD to be more specific about public API
* Namespace tracetools C++ functions and macros and deprecate current ones
* Contributors: Christophe Bedard
```

## tracetools_test

```
* Update after namespacing C++ tracetools functions and macros
* Contributors: Christophe Bedard
```

2021-05-04 21:57 UTC, nuclearsandwich requested changes
@christophebedard I'm confused by the fact that there is no version bump, just a package revision, but that there also appear to be changes in the changelog.

Was there something particular about this release?

2021-05-04 22:01 UTC, christophebedard commented
> @christophebedard I'm confused by the fact that there is no version bump, just a package revision, but that there also appear to be changes in the changelog.

Maybe the changelog is the same for all increments?

> Was there something particular about this release?

There's nothing new, I just wanted to point the release repo back to gitlab.com. I now realize that there isn't really a need for that, I can just do it when I do the next release. I can just close this if you prefer.

2021-05-04 22:22 UTC, cottsay commented
> there is no version bump, just a package revision, but that there also appear to be changes in the changelog

I think this is typical behavior for bloom.

2021-05-04 23:12 UTC, nuclearsandwich commented
> I think this is typical behavior for bloom.

That could very well be the case. Most of my experience bumping package revisions is on packages which don't have changelog data configured.

2021-05-04 23:44 UTC, nuclearsandwich commented
> I just wanted to point the release repo back to gitlab.com. I now realize that there isn't really a need for that, I can just do it when I do the next release. I can just close this if you prefer.

Actually, it's on my TODO list to talk to the ros-tracing maintainers about the release repository setup and I may as well have that conversation here. In order for the Rolling release tools to work properly release repositories need to be located in the ros2-gbp organization so that new bloom releases can be made automatically when creating new distributions or updating Rolling platforms. This is described in [REP-2002](https://www.ros.org/reps/rep-2002.html#managing-build-farm-writable-release-repositories).

What I would like to do is make sure that the full repository history for the ros2_tracing-release repository is up-to-date in the ros2-gbp copy and then add all of the ros2_tracing maintainers as maintainers to that repository so that future releases in all ROS 2 distributions use the ros2-gbp repository. This will prevent the repository from being re-copied when Rolling updates from 20.04 to 22.04 and when H-turtle is created from Rolling.

If that works for you and the other maintainers, all I need is a list of GitHub usernames who need maintainership access to get started and take care of the rest. Thanks!

2021-05-05 00:27 UTC, christophebedard commented
That makes sense; I actually almost asked about just using the ros2-gbp repo. I don't see why we wouldn't want to do that, so that works for me.

The maintainers are @iluetkeb and me.

2021-05-06 15:16 UTC, nuclearsandwich commented
> That makes sense; I actually almost asked about just using the ros2-gbp repo. I don't see why we wouldn't want to do that, so that works for me.

Thanks. I'll make it happen. I'm going to close this PR for now and have opened https://github.com/ros2-gbp/ros2_tracing-release/issues/2 which I'll see to as soon as I finish my pass through rosdistro reviews.

2021-05-06 15:16 UTC, closed without merging