ros_realtime: 1.0.25-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #29486
Opened 2021-05-11 06:24 UTC by davefeilseifer

Increasing version of package(s) in repository `ros_realtime` to `1.0.25-1`:

- upstream repository: https://github.com/ros/ros_realtime.git
- release repository: https://github.com/ros-gbp/ros_realtime-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## ros_realtime

- No changes

2021-05-11 15:15 UTC, ivanpauno requested changes
[ros_realtime](https://github.com/ros/ros_realtime/blob/e5460c7a63a778f8843ca21190496042f6d10b04/ros_realtime/package.xml#L9) should specify a license in the package.xml, could you add one?

Could you also add a top level `LICENSE` file to the repo?
Thanks!

2021-05-11 15:16 UTC, nuclearsandwich commented
> Could you also add a top level `LICENSE` file to the repo?

I think that license files per-package, if not all packages have the same license, would also be sufficient.

2021-05-13 18:59 UTC, hidmic commented
@davefeilseifer friendly ping.

2021-05-15 07:26 UTC, davefeilseifer commented
done and done


> [ros_realtime](https://github.com/ros/ros_realtime/blob/e5460c7a63a778f8843ca21190496042f6d10b04/ros_realtime/package.xml#L9) should specify a license in the package.xml, could you add one?
> 
> Could you also add a top level `LICENSE` file to the repo?
> Thanks!

2021-05-17 12:58 UTC, merged