Add glpk
ros/rosdistro pull request #29619
Opened 2021-05-21 07:57 UTC by tomlankhorst

Please add the following dependency to the rosdep database.

## Package name:

glpk

## Package Upstream Source:

https://ftp.gnu.org/gnu/glpk/

## Purpose of using this:

> The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems.

This is useful for some robotic algorithms. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/sid/libglpk-dev
- Ubuntu: https://packages.ubuntu.com/focal/libglpk-dev
- Fedora: https://fedora.pkgs.org/32/fedora-x86_64/glpk-devel-4.65-5.fc32.x86_64.rpm.html
- Arch: https://aur.archlinux.org/packages/glpk-git/

2021-05-21 21:06 UTC, mabelzhang reviewed
There's a Gentoo package as well `sci-mathematics/glpk` https://packages.gentoo.org/packages/sci-mathematics/glpk

2021-05-21 23:33 UTC, tfoote requested changes
Please add the Gentoo package Mabel found and then we're good to merge.

2021-05-21 23:33 UTC, tfoote commented on rosdep/base.yaml
> +  fedora: [glpk-devel]
```suggestion
  fedora: [glpk-devel]
  gentoo: [sci-mathematics/glpk]
```

From @mabelzhang 's research

2021-05-23 08:08 UTC, tomlankhorst commented
Thanks for your help!

2021-05-24 18:44 UTC, mabelzhang approved these changes

2021-05-25 04:11 UTC, tfoote approved these changes

2021-05-25 04:11 UTC, merged