Add mpfr
ros/rosdistro pull request #29620
Opened 2021-05-21 08:03 UTC by tomlankhorst

Please add the following dependency to the rosdep database.

## Package name:

mpfr

## Package Upstream Source:

https://scm.gforge.inria.fr/anonscm/svn/mpfr/trunk/

## Purpose of using this:

> The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

Useful for some robotic algorithms

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/sid/libmpfr-dev
- Ubuntu: https://packages.ubuntu.com/focal/libmpfr-dev
- Fedora: https://fedora.pkgs.org/33/fedora-x86_64/mpfr-4.1.0-2.fc33.x86_64.rpm.html
- Arch: https://archlinux.org/packages/core/x86_64/mpfr/

2021-05-21 21:03 UTC, mabelzhang commented on rosdep/base.yaml
> +  ubuntu: [libmpfr-dev]
Thanks for the links!
```suggestion
  gentoo: [dev-libs/mpfr]
  ubuntu: [libmpfr-dev]
```
A trailing space after the `ubuntu` entry is causing the check error
```
$ python scripts/check_rosdep.py rosdep/base.yaml 
checking for trailing spaces...
  ERR: trailing space line 5898
```
There's also a Gentoo package for it.

2021-05-21 23:34 UTC, tfoote requested changes
Please add the gentoo rule that Mabel found and then we're good to go.

2021-05-23 08:08 UTC, tomlankhorst commented
Thanks a lot

2021-05-24 18:44 UTC, mabelzhang approved these changes

2021-05-25 04:11 UTC, tfoote approved these changes

2021-05-25 04:11 UTC, merged