Adding visp_ros to documentation index for noetic
ros/rosdistro pull request #29681
Opened 2021-05-26 16:49 UTC by fspindle

I'd like `visp_ros` to be indexed and documented on ros.org

2021-05-27 21:33 UTC, audrow approved these changes

2021-06-01 23:54 UTC, sloretz requested changes
Hi @fspindle,

Would you be willing to add a LICENSE file to the `master` branch of `visp_ros`? It's needed to before I can merge this to satisfy rule 3. ii. in this document: https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md

2021-06-02 05:57 UTC, fspindle commented
Hi @sloretz 

Thanks to warn me about this important point.
I just added the [LICENCE](https://github.com/lagadic/visp_ros/blob/master/LICENSE) file.

2021-06-02 16:07 UTC, sloretz approved these changes

2021-06-02 16:08 UTC, merged