foxglove_msgs: 1.0.0-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #29682
Opened 2021-05-26 18:20 UTC by jhurliman

Increasing version of package(s) in repository `foxglove_msgs` to `1.0.0-1`:

- upstream repository: https://github.com/foxglove/ros_foxglove_msgs.git
- release repository: https://github.com/foxglove/ros_foxglove_msgs-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## foxglove_msgs

```
* Initial release with foxglove_msgs/ImageMarkerArray message
```

2021-05-27 21:30 UTC, audrow approved these changes

2021-06-01 23:56 UTC, sloretz requested changes
Hi @jhurliman,

Would you be willing to add a LICENSE file to the `main` branch of `foxglove_msgs`? It's needed to before I can merge this to satisfy rule 2. ii. in this document: https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md

2021-06-02 00:09 UTC, jhurliman commented
@sloretz done - https://github.com/foxglove/ros_foxglove_msgs/blob/main/LICENSE

2021-06-02 16:26 UTC, sloretz approved these changes

2021-06-02 23:30 UTC, sloretz approved these changes

2021-06-02 23:30 UTC, merged