Feature/python3 simplejpeg
ros/rosdistro pull request #30308
Opened 2021-07-22 06:51 UTC by hakuturu583

Please add the following dependency to the rosdep database.

## Package name:

python3-simplejpeg

## Package Upstream Source:

https://pypi.org/project/simplejpeg/

## Purpose of using this:

I want to add simplejpeg to the rosdistro.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
https://packages.debian.org/search?keywords=simplejpeg&searchon=names&suite=buster&section=all
- Ubuntu: https://packages.ubuntu.com/
https://packages.ubuntu.com/search?keywords=simplejpeg&searchon=names&suite=hirsute&section=all
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here: 

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2021-07-24 00:05 UTC, tfoote requested changes
This is a pip only package and as such should have the pip extension for the key. 

As a reminder pip packages are not valid dependencies for any package that is expected to be released.

2021-08-09 06:18 UTC, hakuturu583 commented
@tfoote Thank you!
I modify package key.

2021-08-10 21:34 UTC, tfoote approved these changes

2021-08-11 15:24 UTC, nuclearsandwich approved these changes

2021-08-11 15:24 UTC, merged