Added python3-smbus rosdep
ros/rosdistro pull request #30314
Opened 2021-07-22 22:59 UTC by rohbotics

-- ROSDEP_RULE_TEMPLATE: Submitter Please review the contributing guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md -->

Please add the following dependency to the rosdep database.

## Package name:

python3-smbus

## Package Upstream Source:

https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git/

## Purpose of using this:

To enable i2c communication using Python. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/buster/python3-smbus
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/focal/python3-smbus
   - REQUIRED
- Fedora: https://src.fedoraproject.org/rpms/i2c-tools
  - IF AVAILABLE
- Arch: https://archlinux.org/packages/community/x86_64/i2c-tools/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/packages/sys-apps/i2c-tools
  - IF AVAILABLE

It appears that only Debian and Ubuntu package this separately, other distros seem to have the Python bindings as part of the `i2c-tools` package, so I depended on that.

2021-07-26 19:47 UTC, cottsay requested changes
One small fix for Fedora.

2021-07-26 19:47 UTC, cottsay commented on rosdep/python.yaml
> +  fedora: [i2c-tools]
Though provided by the `i2c-tools` source package, the actual python bindings are provided in the `python3-i2c-tools` subpackage: https://src.fedoraproject.org/rpms/i2c-tools/blob/rawhide/f/i2c-tools.spec#_32

```suggestion
  fedora: [python3-i2c-tools]
```

2021-07-26 22:38 UTC, cottsay requested changes
Sorry I didn't catch this one as well in my initial review.

2021-07-26 22:38 UTC, cottsay commented on rosdep/python.yaml
> +  opensuse: [i2c-tools]
> It appears that only Debian and Ubuntu package this separately, other distros seem to have the Python bindings as part of the i2c-tools package, so I depended on that.

This isn't the case for openSUSE either: https://software.opensuse.org/package/python3-smbus
```suggestion
  opensuse: [python3-smbus]
```

I don't really know of a good way to check Gentoo, so the only platform that seems to provide the module in `i2c-tools` directly is Arch. If there's a decent chance the rule is not correct, I'd rather omit the Gentoo rule until someone from the community can show us how to verify it.

2021-07-27 15:39 UTC, rohbotics commented
Thanks for the reviews, updated.

2021-07-27 16:23 UTC, cottsay approved these changes
Thanks for iterating

2021-07-27 17:02 UTC, tfoote approved these changes

2021-07-27 17:02 UTC, merged