cyglidar_d1: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #30341
Opened 2021-07-28 02:06 UTC by imsorapark

Increasing version of package(s) in repository `cyglidar_d1` to `0.0.2-1`:

- upstream repository: https://github.com/CygLiDAR-ROS/cyglidar_d1.git
- release repository: https://github.com/CygLiDAR-ROS/cyglidar_d1-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

2021-08-02 18:58 UTC, gbalke commented
Looking to pass checks. To note, Melodic is on hold at the moment.

2021-08-04 14:06 UTC, clalancette requested changes

2021-08-04 14:06 UTC, clalancette commented on melodic/distribution.yaml
> +    status_description: end-of-life
This is a very odd status to be putting on a new package.  I'll suggest just removing this completely.

2021-08-04 14:06 UTC, clalancette commented on melodic/distribution.yaml
> +      test_pull_requests: true
Did you follow the instructions for allowing pull request hooks in https://wiki.ros.org/buildfarm/Pull%20request%20testing ?

2021-08-04 14:06 UTC, clalancette commented on melodic/distribution.yaml
> +      version: v0.1.2
This version is still confusing, in my opinion.  You are on branch v0.1.2, but the release version below is 0.0.2.  I won't block on this, but I still highly suggest that you make this a named branch on the source repository (`main`, or something like that), and use that instead.

2021-08-11 15:35 UTC, nuclearsandwich commented
@imsorapark can you please reply to @clalancette's feedback. Thanks!

2021-09-09 17:38 UTC, tfoote commented
With no response to multiple pings over a month I'm going to close this. Please resubmit if you'd like another review.

2021-09-09 17:38 UTC, closed without merging