Add python3-gpiozero
ros/rosdistro pull request #30454
Opened 2021-08-10 18:26 UTC by RyanHir

Please add the following dependency to the rosdep database.

## Package name:

python3-gpiozero

## Purpose of using this:

This library is able to read CPU temperature data from the Raspberry Pi and is useful for measuring sensor changes.

## Links to Distribution Packages

- Debian: https://packages.debian.org/buster/python3-gpiozero
- Ubuntu: https://packages.ubuntu.com/bionic/python3-gpiozero
- Fedora: https://src.fedoraproject.org/rpms/python-gpiozero

2021-08-11 15:55 UTC, nuclearsandwich requested changes

2021-08-11 15:55 UTC, nuclearsandwich commented on rosdep/python.yaml
> +  ubuntu: [python3-gpiozero]
Per the check failure, python3-gpiozero does not appear to be available in Ubuntu Bionic.

```suggestion
  ubuntu:
    '*': [python3-gpiozero]
    bionic: null
```

2021-08-11 16:27 UTC, RyanHir commented
It appears that python3-gpiozero is only in the arm ports for Ubuntu Bionic, I have accepted your requested changes.

2021-08-11 16:43 UTC, nuclearsandwich commented
> It appears that python3-gpiozero is only in the arm ports for Ubuntu Bionic, I have accepted your requested changes.

Ah yeah, rosdep does not consider architecture and so our checks only run on the primary Ubuntu repositories. Thanks for clarifying and iterating.

2021-08-11 16:46 UTC, nuclearsandwich approved these changes

2021-08-14 00:38 UTC, mabelzhang approved these changes

2021-08-14 00:38 UTC, merged