paho-mqtt-cpp: 1.2.0-2 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #30542
Opened 2021-08-23 08:16 UTC by Timple

Increasing version of package(s) in repository `paho-mqtt-cpp` to `1.2.0-2`:

- upstream repository: https://github.com/eclipse/paho.mqtt.cpp.git
- release repository: https://github.com/nobleo/paho.mqtt.cpp-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

2021-08-25 23:30 UTC, audrow requested changes
Hey @Timple, I notice two things that aren't quite right for accepting this release:

- This package doesn't appear to be a ROS package. It doesn't seem to have a package.xml or any ROS related dependencies. 
- Also, I don't see a LICENSE file. 

Let me know if you have questions.

2021-08-26 14:09 UTC, ivanpauno approved these changes

2021-08-26 17:18 UTC, audrow approved these changes

2021-08-26 17:18 UTC, merged

2021-08-29 09:37 UTC, Timple commented
I do not understand why the build fails on the buildfarm: 
https://build.ros.org/job/Nbin_ufv8_uFv8__paho-mqtt-cpp__ubuntu_focal_arm64__binary/4/console

The error is:

```
08:48:01 dpkg-shlibdeps: error: cannot find library libpaho-mqtt3as.so.1 needed by debian/ros-noetic-paho-mqtt-cpp/opt/ros/noetic/lib/aarch64-linux-gnu/libpaho-mqttpp3.so.1.2.0 (ELF format: 'elf64-littleaarch64' abi: '020100b700000000'; RPATH: '')
```
But before that it states:
```
08:44:31 -- Found PahoMqttC: /opt/ros/noetic/lib/aarch64-linux-gnu/libpaho-mqtt3as.so  
```

Anyone a clue?

2021-08-30 13:29 UTC, ivanpauno commented
Not really. Does it only fail on aarch64?
In one case says it found `libpaho-mqtt3as.so`, but in the other says it's looking for `libpaho-mqtt3as.so.1`.
Maybe that's the issue (?).

2021-09-13 08:17 UTC, Timple commented
That seems to be the issue indeed. Well spotted.
But on my PC the `libpaho-mqtt3as.so` symlinks to `libpaho-mqtt3as.so.1`. So why wouldn't that be the case on the jenkins server?

2021-09-13 13:35 UTC, ivanpauno commented
> That seems to be the issue indeed. Well spotted.
But on my PC the libpaho-mqtt3as.so symlinks to libpaho-mqtt3as.so.1. So why wouldn't that be the case on the jenkins server?

Did you try to only build the package or to also generate a debian?
I would try the second to see if the issue is reproducible.

> Does it only fail on aarch64?

I was just checking, it seems to be failing in all platforms.

2021-09-13 13:38 UTC, Timple commented
> Did you try to only build the package or to also generate a debian?

I did an `apt-get install ros-noetic-paho-mqtt-c`. So the `paho-mqtt-c` debian seems fine. 

I did not try to generate a debian file for `paho-mqtt-cpp` as I have no idea yet how to reproduce the jenkins build locally.

2021-09-13 13:41 UTC, ivanpauno commented
I think you can try this https://answers.ros.org/question/288410/generate-deb-from-dependent-ros-package-locally/.
@nuclearsandwich probably knows better

2021-09-13 14:11 UTC, Timple commented
Compiling to a debian seems to work fine, as demonstrated in this dockerfile:

```Dockerfile
FROM ros:noetic

RUN apt-get update -qq
RUN apt-get install -qqy git fakeroot dpkg-dev debhelper
RUN apt-get install -qqy ros-noetic-paho-mqtt-c
RUN git clone -b debian/noetic/focal/paho-mqtt-cpp https://github.com/nobleo/paho.mqtt.cpp-release

WORKDIR paho.mqtt.cpp-release
RUN fakeroot debian/rules binary
RUN apt install ../ros-noetic-paho-mqtt-cpp_1.2.0-2focal_amd64.deb
```

2021-09-13 14:29 UTC, ivanpauno commented
> Compiling to a debian seems to work fine, as demonstrated in this dockerfile:

Ok, we will have to try to reproduce what the buildfarm exactly does.
Checking the logs of the failing job, it seems it seems to be using these two commands https://github.com/ros-infrastructure/ros_buildfarm/blob/fe5627d218239f1f0d3292e20de881b98fdf553e/ros_buildfarm/binarydeb_job.py#L132-L135.

```
apt-src import ros-noetic-paho-mqtt-cpp --here --version 1.2.0-2
apt-src build ros-noetic-paho-mqtt-cpp
```
(that probably needs to be run in the root of the repository)

IDK much more, so if that doesn't work let's wait for someone else chiming in

2021-09-14 05:39 UTC, Timple commented
Works just as well:

```Dockerfile
FROM ros:noetic

RUN apt-get update -qq
RUN apt-get install -qqy git fakeroot dpkg-dev debhelper
RUN apt-get install -qqy ros-noetic-paho-mqtt-c
RUN git clone -b debian/noetic/focal/paho-mqtt-cpp https://github.com/nobleo/paho.mqtt.cpp-release

WORKDIR paho.mqtt.cpp-release
RUN apt-get install -qqy apt-src
RUN apt-src import ros-noetic-paho-mqtt-cpp --here --version 1.2.0-2
RUN apt-src build ros-noetic-paho-mqtt-cpp
RUN apt install ../ros-noetic-paho-mqtt-cpp_1.2.0-2focal_amd64.deb
```

Let's wait for help then.

2021-11-08 07:14 UTC, Timple commented
So, someone did have the answer in the end: :slightly_smiling_face: 
https://answers.ros.org/question/389836/buildfarm-dpkg-shlibdeps-error-cannot-find-library/?answer=390167#post-id-390167