Adding python3 support for RPi.GPIO
ros/rosdistro pull request #30565
Opened 2021-08-24 21:18 UTC by greg-burgess

Please add the following dependency to the rosdep database.

## Package name:

RPi.GPIO (python3 support)

## Package Upstream Source:

https://sourceforge.net/p/raspberry-gpio-python/wiki/Home/

## Purpose of using this:

Adds python3 support to useful package. Set GPIO pins high or low on Raspberry Pi. 

Distro packaging links:

## Links to Distribution Packages

More info at https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules -->

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
   - REQUIRED
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here: 

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2021-08-24 21:42 UTC, cottsay requested changes
We're going to see the repository check automation fail here because this package is typically only available for ARM platforms, and the automation specifically checks against amd64. We'll have to validate these rules manually and ignore the check.

2021-08-24 21:42 UTC, cottsay commented on rosdep/python.yaml
> -python-rrdtool:
This part of the change looks unrelated. Please revert it.

2021-08-24 21:43 UTC, cottsay commented on rosdep/python.yaml
> +  ubuntu:
This package is available for Fedora as well: https://src.fedoraproject.org/rpms/python-rpi-gpio

```suggestion
  fedora: [python3-RPi.GPIO]
  ubuntu:
```

2021-08-27 14:18 UTC, ivanpauno requested changes

2021-08-30 17:21 UTC, cottsay requested changes
We can ignore the `test_rosdep_repo_check` test failures, but there are other test failures in this PR due to alphabetical ordering: https://github.com/ros/rosdistro/pull/30565/checks?check_run_id=3464208711#step:6:222

Specifically, the `*` entry in the ubuntu pip list needs to be first, and both of these new keys need to be moved down to the other python3 keys.

2021-08-30 17:21 UTC, cottsay commented on rosdep/python.yaml
> +    buster: [python3-rpi.gpio]
Galactic is targeting Bullseye:
```suggestion
    bullseye: [python3-rpi.gpio]
    buster: [python3-rpi.gpio]
```

2021-09-12 17:49 UTC, greg-burgess commented
Is there anything else I need to add?

2021-09-13 08:23 UTC, cottsay commented
There are still two formatting issues:
1. Trailing white space: https://github.com/ros/rosdistro/pull/30565/checks?check_run_id=3580794321#step:5:6
2. It's still not alphabetized. The key `python3-rpi.gpio` should come after `python3-rospkg-modules`.

2021-10-05 21:26 UTC, hidmic commented
@greg-burgess friendly ping

2021-10-07 12:58 UTC, clalancette commented
There's been no response to the latest comments for 24 days, so I'm going to go ahead and close this.  Please feel free to fix the issues and reopen.  Thanks for the contribution.

2021-10-07 12:58 UTC, closed without merging