base.yaml add libext2fs-dev
ros/rosdistro pull request #30769
Opened 2021-09-13 08:55 UTC by amfern

Please add the following dependency to the rosdep database.

## Package name:
libext2fs-dev

## Package Upstream Source:
https://sourceforge.net/projects/e2fsprogs/

## Purpose of using this:
This dependency is used to interact with drive and it would be really nice to install it with rosdep

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/libext2fs-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/focal/libext2fs-dev
- Fedora: https://src.fedoraproject.org/browse/projects/
  - https://src.fedoraproject.org/rpms/e2fsprogs
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/core/x86_64/e2fsprogs/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/sys-libs/e2fsprogs-libs
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/e2fsprogs#default
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/main/x86_64/e2fsprogs
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=21.05&show=e2fsprogs&from=0&size=50&sort=relevance&type=packages&query=e2fsprogs

Galactic

# The source is here: 
https://sourceforge.net/projects/e2fsprogs/

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2021-09-21 18:15 UTC, wjwwood commented
Please address the CI failure, it looks like you have some things out of alphabetical ordering:

https://github.com/ros/rosdistro/pull/30769/checks?check_run_id=3648304979#step:6:183

2021-09-23 12:15 UTC, amfern commented
sorted packages in alphabetical order and added the CI suggested packages

2021-09-30 18:58 UTC, mabelzhang reviewed
Thank you for providing the links! That helps to speed up the review.
Are `e2fsprogs` and `libext2fs` equivalent? Which ones did CI suggest you to add - there's no diff for that second commit since it was a force push. Sometimes CI suggests things that need to be double-checked by human.

My guess is that because `libext2fs` exists only on Debian, OpenSUSE, and Ubuntu, the `e2fsprogs` for all the other distros are equivalent alternatives? But Debian, OpenSUSE, and Ubuntu also have `esprogs` packages (below). That's why I'm double-checking whether the two are equivalent.
Debian: https://packages.debian.org/bullseye/e2fsprogs
OpenSUSE: https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/e2fsprogs-devel-1.46.4-1.1.x86_64.rpm.html
Ubuntu: https://packages.ubuntu.com/focal/e2fsprogs

2021-10-01 19:51 UTC, amfern commented
That is a good point, it seems like debian, ubuntu and OpenSUSE split the `e2fsprogs` package and `libext2fs2` is one of them. Other distors just install the `e2fsprogs` as a whole. I guess I should change this PR to adding `e2fsprogs` instead of `libext2fs2`

2021-10-01 20:19 UTC, cottsay requested changes, later dismissed
If I understand your intentions correctly, you want the command line utilities, right? It looks like that's what the ubuntu package you're adding contains: https://packages.ubuntu.com/focal/amd64/e2fsprogs/filelist

I think that more of these platforms split the package into parts than you might think - they just don't call the libraries package `libext2fs` like Debian does. It's possible that the other rule needs to be updated to reflect this.

2021-10-01 20:19 UTC, cottsay commented on rosdep/base.yaml
> +  gentoo: [sys-libs/e2fsprogs-libs]
This looks like the libraries, but I think you want the utilities: https://packages.gentoo.org/packages/sys-fs/e2fsprogs
```suggestion
  gentoo: [sys-fs/e2fsprogs]
```

2021-10-01 20:19 UTC, cottsay commented on rosdep/base.yaml
> +  rhel: [e2fsprogs-devel]
This provides the headers, but I think you want the utilities: http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/e2fsprogs-1.45.6-1.el8.x86_64.rpm
```suggestion
  rhel: [e2fsprogs]
```

2021-10-01 20:19 UTC, cottsay commented on rosdep/base.yaml
> +  opensuse: [e2fsprogs-libs]
This looks like the libraries, but I think you want the utilities: https://software.opensuse.org/package/e2fsprogs

```suggestion
  opensuse: [e2fsprogs]
```

2021-10-01 20:39 UTC, amfern commented
I actually needed the libraries only. But adding `e2fsprogs` will work for me, and it will be consistent across other distors

2021-10-04 17:19 UTC, mabelzhang approved these changes

2021-10-07 12:45 UTC, hidmic reviewed
LGTM too, but I'll let @cottsay give the final approval.

2021-10-07 13:02 UTC, clalancette approved these changes

2021-10-07 13:03 UTC, merged