add libext2fs-dev to e2fsprogs
ros/rosdistro pull request #31151
Opened 2021-11-08 08:37 UTC by amfern

Please add the following dependency to the rosdep database. this is somewhat continuation of PR #30769

## Package name:

libext2fs-dev

## Package Upstream Source:
http://e2fsprogs.sourceforge.net/

## Purpose of using this:

This dependency is part of e2fsprogs but debian split some source code into separate packages libext2fs-dev

Distro packaging links:

## Links to Distribution Packages
- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/libext2fs-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/focal/libext2fs-dev

# Please Add This Package to be indexed in the rosdistro.

Galactic

# The source is here: 

https://sourceforge.net/projects/e2fsprogs/

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2021-11-08 18:11 UTC, cottsay requested changes
I would much prefer to see a new key added for this resource. Something like:
```yaml
libext2fs-dev:
  alpine: [e2fsprogs-dev]
  debian: [libext2fs-dev]
  fedora: [e2fsprogs-devel]
  opensuse: [libext2fs-devel]
  rhel: [e2fsprogs-devel]
  ubuntu: [libext2fs-dev]
```

2021-11-09 09:00 UTC, amfern commented
yes, i agree with you proposal. i was under the wrong impression only ubuntu split the e2fsprogs

2021-11-09 18:05 UTC, tfoote approved these changes

2021-11-11 13:56 UTC, clalancette approved these changes

2021-11-11 13:56 UTC, merged