navigation_2d: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #31307
Opened 2021-11-25 15:53 UTC by Priyanka328

Increasing version of package(s) in repository `navigation_2d` to `0.4.3-1`:

- upstream repository: https://github.com/skasperski/navigation_2d.git
- release repository: git@github.com:skasperski/navigation_2d-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

2021-11-29 14:58 UTC, clalancette requested changes
Besides the wrong URL inline, would you also like to add a `doc` and `source` section?  This package had those in previous ROS releases (like Melodic).

2021-11-29 14:58 UTC, clalancette commented on noetic/distribution.yaml
> +      url: git@github.com:skasperski/navigation_2d-release.git
This should be an `https://` URL.

2021-11-30 01:17 UTC, wjwwood commented
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-12-01/23295) (as well as CI failing)

2021-11-30 01:21 UTC, wjwwood commented
@cottsay any idea about these nose test failures? They seem to be causing all the new releases to fail to pass CI but are unrelated to the pull requests.

2021-12-01 05:26 UTC, mabelzhang approved these changes
`doc` and `source` look good now.
Still holding for sync.

2021-12-06 23:49 UTC, merged