serial: 1.2.1-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #31420
Opened 2021-12-08 04:51 UTC by wjwwood

Increasing version of package(s) in repository `serial` to `1.2.1-1`:

- upstream repository: https://github.com/wjwwood/serial.git
- release repository: https://github.com/wjwwood/serial-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## serial

```
* Removed the use of a C++11 feature for compatibility with older browsers.
* Fixed an issue with cross compiling with mingw on Windows.
* Restructured Visual Studio project layout.
* Added include of ``#include <AvailabilityMacros.h>`` on OS X (listing of ports).
* Fixed MXE for the listing of ports on Windows.
* Now closes file device if ``reconfigureDevice`` fails (Windows).
* Added the MARK/SPACE parity bit option, also made it optional.
  Adding the enumeration values for MARK and SPACE was the only code change to an API header.
  It should not affect ABI or API.
* Added support for 576000 baud on Linux.
* Now releases iterator properly in listing of ports code for OS X.
* Fixed the ability to open COM ports over COM10 on Windows.
* Fixed up some documentation about exceptions in ``serial.h``.
```

2021-12-08 17:35 UTC, nuclearsandwich requested changes

2021-12-08 17:35 UTC, nuclearsandwich commented on noetic/distribution.yaml
> +    status: maintained
```suggestion
  serial:
    doc:
      type: git
      url: https://github.com/wjwwood/serial.git
      version: main
    release:
      tags:
        release: release/noetic/{package}/{version}
      url: https://github.com/wjwwood/serial-release.git
      version: 1.2.1-1
    source:
      type: git
      url: https://github.com/wjwwood/serial.git
      version: main
    status: maintained
```

It appears that the default branch has been renamed upstream.

2021-12-17 00:59 UTC, sloretz commented
@clalancette Do packages that have been released in older ROS distros need a LICENSE file? The guidelines seem to say [it's only for brand new packages](https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md).

```
For packages that are brand-new to the ROS ecosystem, some due diligence will be done on the source and release repositories:

    There must be a LICENSE file.
```

There is an upstream PR to add a LICENSE file https://github.com/wjwwood/serial/pull/261

2021-12-17 13:17 UTC, clalancette commented
> @clalancette Do packages that have been released in older ROS distros need a LICENSE file? The guidelines seem to say [it's only for brand new packages](https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md).

If packages have been released into older ROS distributions without a LICENSE file, we usually give them a pass and let them into newer ones.  Given that there is already an open PR to add a LICENSE, I would say it is fine to merge this one.

2022-01-04 15:30 UTC, clalancette approved these changes

2022-01-04 15:30 UTC, merged