Adding quori_ros to documentation index for distro
ros/rosdistro pull request #31424
Opened 2021-12-08 22:09 UTC by bmcdorman

# Please Add This Package to be indexed in the rosdistro.

noetic

# The source is here: 

https://github.com/Quori-ROS/quori_ros

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2021-12-09 16:31 UTC, nuclearsandwich requested changes
@bmcdorman thanks for updating the license entries in each package.xml. The maintainer data is still invalid as seen here:https://github.com/Quori-ROS/quori_ros/blob/cb8b2254a347d95a1528f5388ed9995ce75acc66/src/quori_controller/package.xml#L10

2021-12-09 16:52 UTC, bmcdorman commented
Maintainer information corrected.

2021-12-15 14:52 UTC, hidmic requested changes
@bmcdorman hmm, I see packages with TODO for a license in their `package.xml` (such as [`quori_launch`](https://github.com/Quori-ROS/quori_ros/tree/master/src/quori_launch)), and third-party packages brought in as submodules. That's not ideal.

The typical repo layout reduces to a collection of packages, your packages, at the repo root. It'd be better for that to be the case here as well.

2021-12-15 14:52 UTC, hidmic commented on noetic/distribution.yaml
> +      version: master
@bmcdorman no `source` entry?

2021-12-16 00:50 UTC, bmcdorman commented on noetic/distribution.yaml
> +      version: master
No, just looking for doc generation.

2021-12-16 00:54 UTC, bmcdorman commented
@hidmic quori_launch has been fixed. The workspace layout of the repository is an artifact of our OS distro (Qubuntu) build process. I can change it to work differently, but it's going to take some time. I can also split up every package into its own repository and have quori_ros use submodules exclusively. That way each package can be submitted in separate PRs (as I had done originally).

2021-12-29 01:50 UTC, sloretz approved these changes
License tags in `package.xml` files look OK to me. I'm not sure what the rosdoc tools will do with the submodules, but I think it'd be fine to try it as is and see what the doc job does.

2022-01-06 15:58 UTC, merged