add msr-tools (#5)
ros/rosdistro pull request #31511
Opened 2021-12-17 23:31 UTC by turniphead

Please add the following dependency to the rosdep database.

## Package name:

msr-tools

## Package Upstream Source:

https://github.com/intel/msr-tools

## Purpose of using this:

read and write to CPU registers. useful for debugging and performance improvement.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
   - [msr-tools](https://packages.ubuntu.com/bionic/msr-tools)
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

2021-12-20 14:18 UTC, hidmic reviewed
@turniphead mind to add a few more entries for other OSes? Quick browsing shows `msr-tools` is available on Debian, Fedora, Gentoo, OpenSUSE, Arch, and most Linux distros (see https://pkgs.org/search/?q=msr-tools and https://packages.gentoo.org/packages/sys-apps/msr-tools for instance).

2021-12-28 21:20 UTC, cottsay requested changes

2021-12-28 21:20 UTC, cottsay commented on rosdep/base.yaml
> +  ubuntu: [msr-tools]
Arch: https://archlinux.org/packages/community/x86_64/msr-tools/
Debian: https://packages.debian.org/search?suite=all&exact=1&searchon=names&keywords=msr-tools
Fedora/RHEL: https://src.fedoraproject.org/rpms/msr-tools#bodhi_updates
Gentoo: https://packages.gentoo.org/packages/sys-apps/msr-tools
OpenSUSE: https://software.opensuse.org/package/msr-tools

```suggestion
msr-tools:
  arch: [msr-tools]
  debian: [msr-tools]
  fedora: [msr-tools]
  gentoo: [sys-apps/msr-tools]
  opensuse: [msr-tools]
  rhel: [msr-tools]
  ubuntu: [msr-tools]
```

2022-01-03 19:42 UTC, turniphead commented
thank you @cottsay!

2022-01-03 22:59 UTC, hidmic approved these changes

2022-01-05 16:23 UTC, clalancette approved these changes

2022-01-05 16:23 UTC, merged