mapviz: 2.2.0-3 in 'galactic/distribution.yaml' [bloom]
ros/rosdistro pull request #31528
Opened 2021-12-21 16:32 UTC by danthony06

Increasing version of package(s) in repository `mapviz` to `2.2.0-3`:

- upstream repository: https://github.com/swri-robotics/mapviz.git
- release repository: https://github.com/swri-robotics-gbp/mapviz-release.git
- distro file: `galactic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

2021-12-22 22:57 UTC, cottsay requested changes
Please add a `source` stanza for the repository.

2021-12-22 22:58 UTC, cottsay commented
Also, does this PR replace #31256?

2021-12-24 01:17 UTC, sloretz commented
> Please add a source stanza for the repository.

I don't think a `source` stanza is required. It looks like the source repo is publicly accessible, and matches previous distros (https://github.com/ros/rosdistro/pull/27114) so this PR LGTM

2021-12-24 01:17 UTC, sloretz approved these changes

2021-12-28 18:43 UTC, cottsay approved these changes

2021-12-28 21:03 UTC, merged