ros_image_to_qimage: 0.0.1-1 in 'galactic/distribution.yaml' [bloom]
ros/rosdistro pull request #31690
Opened 2022-01-06 13:23 UTC by ijnek

Increasing version of package(s) in repository `ros_image_to_qimage` to `0.0.1-1`:

- upstream repository: https://github.com/ros-sports/ros_image_to_qimage.git
- release repository: https://github.com/ros-sports/ros_image_to_qimage-release.git
- distro file: `galactic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## ros_image_to_qimage

```
* implemented ros_image_to_qimage package
* Contributors: Kenji Brameld, ijnek
```

2022-01-06 16:23 UTC, nuclearsandwich commented
@ijnek your package's package.xml is missing a description and valid license identifier. https://github.com/ros-sports/ros_image_to_qimage/blob/rolling/package.xml#L6-L8 could you please update those before release.

2022-01-06 16:23 UTC, nuclearsandwich requested changes
package.xml is missing license info

2022-01-07 07:35 UTC, ijnek commented
Don't know how I missed that, thank you for picking it up. 
Closing this PR as superseded by https://github.com/ros/rosdistro/pull/31704.
I'd be interested in knowing if there is an easy way of appending changes to a release without increasing the package version number..?

2022-01-07 07:35 UTC, closed without merging

2022-01-13 22:06 UTC, nuclearsandwich commented
> I'd be interested in knowing if there is an easy way of appending changes to a release without increasing the package version number..?

Releases absolutely should not change without also updating the version number. Most tooling from Git all the way up to the package building tools assume that once a tag is created it is immutable and every release engineer who has ever had to review an unusual change in a dependency will be grateful if package contents never change without a corresponding change in version number.

Changes that affect the repository source should always include a version bump. Updates to package metadata are perfectly valid patch release changes.