fix URL of relaese repository for quaternion_operation
ros/rosdistro pull request #32118
Opened 2022-02-10 08:23 UTC by hakuturu583

Signed-off-by: MasayaKataoka <ms.kataoka@gmail.com>

## Package name:

quaternion_operation

## Purpose of using this:

release repository URL of my package was wrong, so I want to correct this.

# The source is here: 

https://github.com/OUXT-Polaris/quaternion_operation.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2022-02-10 21:22 UTC, hidmic reviewed
@hakuturu583 I don't think the URL is wrong. IIRC for Rolling releases to work, release repositories must live in the `ros2-gbp` org. @nuclearsandwich for confirmation.

2022-02-10 23:50 UTC, nuclearsandwich commented
@hakuturu583 the updated release repository is the result of the automation supporting distribution-wide bloom updates for the Rolling release distribution discussed in [REP-2002](https://www.ros.org/reps/rep-2002.html).

All packages in Rolling which did not maintain a release repository in the ros2-gbp have a release repository created there during the migration which ran this week as part of #32036. Now that the initial migration is under way I am in the process of updating the ros2-gbp organization repositories and notifying maintainers of the updated repository and assisting with the recommended transition to using the ros2-gbp organization for all ROS 2 release repositories.

Some additional information is up on Discourse: 
* https://discourse.ros.org/t/holding-releases-to-perform-rolling-transition-to-new-platforms/24191/
* https://discourse.ros.org/t/ros2-gbp-release-repository-permissions-are-now-managed-via-github-repository/24250

2022-02-10 23:51 UTC, nuclearsandwich requested changes
See the comments in https://github.com/ros/rosdistro/pull/32118#issuecomment-1035652789

2022-02-11 11:46 UTC, hakuturu583 commented
@nuclearsandwich @hidmic I want to update quaternion_operation package version in rolling, and I found that I have no rights to write ros2-gdb repo.
How can I update quaternion_operation package?

2022-02-12 01:29 UTC, nuclearsandwich commented
@hakuturu583 there is [a pull request deploying now](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/6/files#diff-ad4ff3f5b6fb45cc1bdf487ff551b6223f6bf3a77a2cf3ea0efbedb75e27a68e) which will invite you to the ros2-gbp organization with access to the repositories that you have released recently. Please open an issue on https://github.com/ros2-gbp/ros2-gbp-github-org if you encounter any difficulties. Thanks!

2022-02-12 07:34 UTC, hakuturu583 commented
OK, I close this issue, and if I face some problem in the future, I will re-open issue.

2022-02-12 07:34 UTC, closed without merging