lockmount_description: 0.0.2-2 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #32140
Opened 2022-02-11 21:30 UTC by tonybaltovski

Increasing version of package(s) in repository `lockmount_description` to `0.0.2-2`:

- upstream repository: https://github.com/clearpathrobotics/lockmount_description.git
- release repository: https://github.com/clearpath-gbp/lockmount_description-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## lockmount_description

```
* Remove a copy & paste error in the cmake file that's breaking the install
* Contributors: Chris Iverach-Brereton
```

2022-02-14 13:35 UTC, hidmic approved these changes
@tonybaltovski the release itself looks to good to me, but I'd much rather prefer a less generic name. I don't have a good one to propose though. @sloretz ?

2022-02-14 19:08 UTC, civerachb-cpr commented
The specific model of mount this replicates is https://www.fath24.us.com/portfolio/products/pivot-joint-25-1-with-locking-lever

We could rename it to `fath_pivot_mount_description`?  Or if we want to avoid including the brand name would `locking_pivot_mount_description` be sufficiently specific while not being needlessly verbose?

2022-02-15 01:00 UTC, sloretz approved these changes
> I'd much rather prefer a less generic name. I don't have a good one to propose though. @sloretz ?

It could be prepended with the name, following https://www.ros.org/reps/rep-0144.html#naming-rules

> if a package is specialized for a hardware piece, prepend its name

It might be `fath_lockmount_description`. That said, `lockmount_description` seems unlikely to conflict with anything else, so this seems fine to me.

Another good question for @clalancette though. Thoughts?

2022-02-15 16:09 UTC, clalancette commented
> Another good question for @clalancette though. Thoughts?

I'd go with `fath_lockmount_description` as a balance between length and the naming rules in REP-144.  But `fath_pivot_mount_description` and `locking_pivot_mount_description` would also be fine with me.

2022-03-02 06:32 UTC, tfoote requested changes
I'm going to mark this as request changes so that we can track it for the rename instead of giving a sense of pending.

2022-03-02 20:19 UTC, tonybaltovski commented
I am about to change this to `locking_pivot_mount`.  It was merged for Noetic: https://github.com/ros/rosdistro/pull/32138 Shall I change both?

2022-03-02 21:28 UTC, tfoote commented
Great. A rerelease with the consistent name for noetic would make sense too.

2022-03-02 21:29 UTC, tfoote commented
I'll close this as you'll do a new bloom release. Please refer back to this in a comment on the new PR.

2022-03-02 21:29 UTC, closed without merging