robot_upstart: 1.0.0-2 in 'foxy/distribution.yaml' [bloom]
ros/rosdistro pull request #32194
Opened 2022-02-16 15:37 UTC by tonybaltovski

Increasing version of package(s) in repository `robot_upstart` to `1.0.0-2`:

- upstream repository: https://github.com/clearpathrobotics/robot_upstart.git
- release repository: https://github.com/clearpath-gbp/robot_upstart-release.git
- distro file: `foxy/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## robot_upstart

```
* Fixed package.xml and setup.py information.
* Removed CMakeLists.txt.
* Removed src folder.
* ros2 foxy
* Contributors: Tony Baltovski, zifengqi123
```

2022-02-17 08:55 UTC, ahcorde requested changes

2022-02-17 08:55 UTC, ahcorde commented on foxy/distribution.yaml
> +      url: git
This link is wrong

2022-02-18 01:44 UTC, tonybaltovski commented
Fixed the typo.

2022-02-18 09:20 UTC, ahcorde approved these changes

2022-02-18 09:20 UTC, merged