Add python3-moderngl-pip, python3-scipy-pip, python3-objloader-pip
ros/rosdistro pull request #32272
Opened 2022-02-22 16:52 UTC by bcbuckles

Please add the following dependency to the rosdep database.

## Package name:

-python3-moderngl-pip
-python3-scipy-pip
-python3-objloader-pip

## Package Upstream Source:

https://github.com/moderngl/moderngl
https://github.com/scipy/scipy
https://github.com/szabolcsdombi/objloader

## Purpose of using this:

python3-moderngl-pip - moderngl is a very helpful python wrapper for opengl that simplifies handling of vertex buffer and array binding.

python3-scipy-pip - the scipy version in apt package manager is outdated.  The newer version in pip was required for my project

python3-objloader-pip - this python package handles loading of .obj files, useful for building 3D applications in opengl, etc.

2022-02-22 18:05 UTC, cottsay approved these changes
Please keep in mind that using pip rules in your package manifests will prevent the package from being released in Bloom and built on the buildfarm.

Please add links to the packaging dashboard in the future:
* https://pypi.org/project/moderngl/
* https://pypi.org/project/objloader/
* https://pypi.org/project/scipy/

2022-02-23 17:39 UTC, nuclearsandwich approved these changes, later dismissed

2022-02-23 17:45 UTC, nuclearsandwich requested changes
Since neither moderngl nor objloader appear to be packaged in Ubuntu at this time I have no objection to those additions.

However, since scipy is available in Debian and Ubuntu repositories we should not add a conflicting pip key there. I've linked a conversation on the line comment with further details.

2022-02-23 17:45 UTC, nuclearsandwich commented on rosdep/python.yaml
> +      packages: [scipy]
```suggestion
```

Please see the conversation in https://github.com/ros/rosdistro/pull/25615 for why we are not adding pip keys for packages which are available from distribution package managers.

2022-03-02 21:34 UTC, tfoote commented
> The newer version in pip was required for my project

Unfortunately this is part of being in a distribution we all need to use the consistent released version. For your personal project you're welcome to create your own rosdep rules that will override the upstream ones here. But for consistency across the community we don't want them in the public ruleset as it will likely break other users who expect the standard version.

2022-03-23 18:13 UTC, closed without merging