aruco_ros: 3.0.1-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #32454
Opened 2022-03-15 10:41 UTC by saikishor

Increasing version of package(s) in repository aruco_ros to 3.0.1-1:

- upstream repository: https://github.com/pal-robotics/aruco_ros.git
- release repository: https://github.com/pal-gbp/aruco_ros-release.git
- distro file: noetic/distribution.yaml
- bloom version: 0.9.8
- previous version for package: null

## aruco

* fixes pal-robotics/aruco_ros/https://github.com/pal-robotics/aruco_ros/issues/89
* Contributors: 444lhc

## aruco_msgs

    No changes

## aruco_ros

* Merge branch 'fix_camera_matrix_gallium' into 'gallium-devel' fix the issue with the improper camera matrix with non rectified images See merge request ros-overlays/aruco_ros!2
* fix the issue with the improper camera matrix with non rectified images
* Contributors: Sai Kishor Kothakota, saikishor

* fixes pal-robotics/aruco_ros/https://github.com/pal-robotics/aruco_ros/issues/89
* Contributors: 444lhc

2022-03-17 00:22 UTC, sloretz requested changes
CI failed to validate this PR, and while I'm not sure why it failed I do notice it was made with an old bloom version. Would you be willing to update bloom to the latest version (0.10.7 at the moment) and release again?

2022-03-17 09:02 UTC, saikishor commented
> CI failed to validate this PR, and while I'm not sure why it failed I do notice it was made with an old bloom version. Would you be willing to update bloom to the latest version (0.10.7 at the moment) and release again?

@sloretz Thanks for pointing out the issue, I have done the release again with the bloom version `0.10.7`, Could we check now if everything is okay?

2022-03-22 01:32 UTC, mabelzhang commented
Do we just need to rerun the tests or does the new release need to be in a new PR?

This is the current error on CI:
```
======================================================================
ERROR: test.test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/rosdistro/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
    raise RuntimeError('\n'.join(errors))
RuntimeError: noetic: missing package.xml file for package "aruco"
noetic: missing package.xml file for package "aruco_msgs"
noetic: missing package.xml file for package "aruco_ros"
```

I've triggered a rerun of that test.

2022-03-22 11:17 UTC, saikishor commented
@mabelzhang @sloretz Thank you for the efforts. I appreciate it.

> I see those files exist in the source repo.

It's strange that it shows the error of missing package.xml (https://github.com/pal-robotics/aruco_ros). Do you think it is better to open a new MR bumping the release_inc?

Best Regards,
Sai Kishor Kothakota

2022-03-23 18:19 UTC, ivanpauno commented
> It's strange that it shows the error of missing package.xml (https://github.com/pal-robotics/aruco_ros). Do you think it is better to open a new MR bumping the release_inc?

Yes, I think that making sure you're using the latest bloom and opening a new MR increasing the build number seems fine.

2022-03-28 07:52 UTC, saikishor commented
> Yes, I think that making sure you're using the latest bloom and opening a new MR increasing the build number seems fine.

Hello @ivanpauno ,

I have opened a new PR increasing the build number here : https://github.com/ros/rosdistro/pull/32537, and yes I'm using the latest bloom version.

2022-03-28 07:52 UTC, closed without merging