ros2_example: 0.0.1-2 in 'foxy/distribution.yaml' [bloom]
ros/rosdistro pull request #32538
Opened 2022-03-28 08:37 UTC by dippingconda

Increasing version of package(s) in repository `ros2_example` to `0.0.1-2`:

- upstream repository: https://github.com/dippingconda/ros2_example.git
- release repository: https://github.com/dippingconda/ros2_example-release.git
- distro file: `foxy/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

2022-03-28 14:33 UTC, ivanpauno requested changes

2022-03-28 14:33 UTC, ivanpauno commented on foxy/distribution.yaml
> +  ros2_example:
the name of the repo and package are to generic, please check the [package naming guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-naming)

2022-03-28 14:33 UTC, ivanpauno commented on foxy/distribution.yaml
> +  ros2_example:
The repo name doesn't matter actually, but the package name must follow those guidelines.

2022-04-14 14:58 UTC, nuclearsandwich commented
@dippingconda once this package has been renamed please use bloom to open a new release PR.

2022-04-14 14:58 UTC, closed without merging