khi_robot: 1.3.0-2 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #32688
Opened 2022-04-07 01:51 UTC by matsui-hiro

Increasing version of package(s) in repository `khi_robot` to `1.3.0-2`:

- upstream repository: https://github.com/Kawasaki-Robotics/khi_robot.git
- release repository: https://github.com/Kawasaki-Robotics/khi_robot-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## khi_duaro_description

- No changes

## khi_duaro_gazebo

- No changes

## khi_duaro_ikfast_plugin

- No changes

## khi_duaro_moveit_config

```
* Merge pull request #52 <https://github.com/Kawasaki-Robotics/khi_robot/issues/52> from k-okada/add_ikfast_plugin
  add khi_*_ikfast_plugin to moveit_config
* add khi_*_ikfast_plugin to moveit_config
* Contributors: HirokiTakami, Kei Okada
```

## khi_robot

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Contributors: Hiroki Matsui
```

## khi_robot_bringup

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Bugfix for noetic release (#44 <https://github.com/Kawasaki-Robotics/khi_robot/issues/44>)
  * update .travis.yml to add noetic test
  * update .travis.yml to change ubuntu version for noetic test
  * Changed to use xacro instead of xacro.py which is deprecated. like https://github.com/ros/urdf_sim_tutorial/pull/8
  * fixed "except A, a:" to "except A as a:" for python3 compatibility
  * add version checking of moveit_commander to the test script due to changes of the return value of MoveGroupCommander.plan() in 1.1.0
  * remove armhf build test for ubuntu 20.04
* Contributors: Hiroki Matsui, Koki Shinjo
```

## khi_robot_control

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Contributors: Hiroki Matsui
```

## khi_robot_msgs

- No changes

## khi_robot_test

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Bugfix for noetic release (#44 <https://github.com/Kawasaki-Robotics/khi_robot/issues/44>)
  * update .travis.yml to add noetic test
  * update .travis.yml to change ubuntu version for noetic test
  * Changed to use xacro instead of xacro.py which is deprecated. like https://github.com/ros/urdf_sim_tutorial/pull/8
  * fixed "except A, a:" to "except A as a:" for python3 compatibility
  * add version checking of moveit_commander to the test script due to changes of the return value of MoveGroupCommander.plan() in 1.1.0
  * remove armhf build test for ubuntu 20.04
* Contributors: Hiroki Matsui, Koki Shinjo
```

## khi_rs007l_moveit_config

```
* Merge pull request #52 <https://github.com/Kawasaki-Robotics/khi_robot/issues/52> from k-okada/add_ikfast_plugin
  add khi_*_ikfast_plugin to moveit_config
* add khi_*_ikfast_plugin to moveit_config
* Contributors: HirokiTakami, Kei Okada
```

## khi_rs007n_moveit_config

```
* Merge pull request #52 <https://github.com/Kawasaki-Robotics/khi_robot/issues/52> from k-okada/add_ikfast_plugin
  add khi_*_ikfast_plugin to moveit_config
* add khi_*_ikfast_plugin to moveit_config
* Contributors: HirokiTakami, Kei Okada
```

## khi_rs013n_moveit_config

```
* Merge pull request #52 <https://github.com/Kawasaki-Robotics/khi_robot/issues/52> from k-okada/add_ikfast_plugin
  add khi_*_ikfast_plugin to moveit_config
* add khi_*_ikfast_plugin to moveit_config
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Contributors: Hiroki Matsui, HirokiTakami, Kei Okada
```

## khi_rs080n_moveit_config

```
* Merge pull request #52 <https://github.com/Kawasaki-Robotics/khi_robot/issues/52> from k-okada/add_ikfast_plugin
  add khi_*_ikfast_plugin to moveit_config
* add khi_*_ikfast_plugin to moveit_config
* Contributors: HirokiTakami, Kei Okada
```

## khi_rs_description

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Bugfix for noetic release (#44 <https://github.com/Kawasaki-Robotics/khi_robot/issues/44>)
  * update .travis.yml to add noetic test
  * update .travis.yml to change ubuntu version for noetic test
  * Changed to use xacro instead of xacro.py which is deprecated. like https://github.com/ros/urdf_sim_tutorial/pull/8
  * fixed "except A, a:" to "except A as a:" for python3 compatibility
  * add version checking of moveit_commander to the test script due to changes of the return value of MoveGroupCommander.plan() in 1.1.0
  * remove armhf build test for ubuntu 20.04
* Contributors: Hiroki Matsui, Koki Shinjo
```

## khi_rs_gazebo

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Contributors: Hiroki Matsui
```

## khi_rs_ikfast_plugin

```
* Add rs013n (#50 <https://github.com/Kawasaki-Robotics/khi_robot/issues/50>)
  * Add rs013n
  * Update rs013n pkgs
  * Update libkrnx
  * Fixed rs013n_bringup.launch to use xacro
  * Update libkrnx to 2.2.0
  * Modify test program for RS series robots
  * Remove kinetic from travis.yml
* Contributors: Hiroki Matsui
```

2022-04-07 07:36 UTC, ahcorde requested changes

2022-04-07 07:36 UTC, ahcorde commented on noetic/distribution.yaml
> +    doc:
do you mind to add a `source` entry ?

2022-04-07 21:10 UTC, cottsay reviewed
Hi @matsui-hiro. It's also highly recommended that you include the full text of the associated LICENSE in the source repository. Looks like these packages are licensed as BSD.

2022-04-08 00:48 UTC, matsui-hiro commented on noetic/distribution.yaml
> +    doc:
OK.
I added a `source` entry.

2022-04-08 04:23 UTC, matsui-hiro commented
Hi, @cottsay.
I created `LICENSE` file and merged into khi_robot. 
https://github.com/Kawasaki-Robotics/khi_robot/pull/61

2022-04-12 01:44 UTC, cottsay approved these changes

2022-04-12 07:05 UTC, ahcorde approved these changes

2022-04-12 07:05 UTC, merged