chore: update velodyne ros2 release repo
ros/rosdistro pull request #32699
Opened 2022-04-08 02:57 UTC by wep21

I updated ros2 release repository for velodyne.
See https://github.com/ros2-gbp/velodyne-release/issues/1.

2022-04-08 02:57 UTC, wep21 commented
cc @JWhitleyWork

2022-04-08 19:41 UTC, cottsay requested changes
Dashing and Eloquent are both EOL, so we're not accepting any changes to those distributions.

2022-04-09 18:20 UTC, wep21 commented
@cottsay I reverted changes toward the EOL distributions.

2022-04-12 01:28 UTC, cottsay approved these changes

2022-04-12 01:32 UTC, merged