[dep] python*-elasticsearch
ros/rosdistro pull request #32702
Opened 2022-04-08 14:50 UTC by 130s

## Package name:

`python-elasticsearch`, `python3-elasticsearch`

## Package Upstream Source:

https://github.com/elastic/elasticsearch-py

## Purpose of using this:

Handling JSON formated data.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?keywords=%20elasticsearch
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?keywords=elasticsearch
- Fedora: https://src.fedoraproject.org/browse/projects/
  - https://src.fedoraproject.org/rpms/python-elasticsearch

2022-04-08 19:39 UTC, cottsay requested changes

2022-04-08 19:39 UTC, cottsay commented on rosdep/python.yaml
> +  fedora: [python-elasticsearch]
Fedora is now aliasing unversioned python package names to Python 3. There is no Python 2 package for Fedora.
```suggestion
```

2022-04-08 19:39 UTC, cottsay commented on rosdep/python.yaml
> +  rhel: [python3-elasticsearch]
Looks like this is only available for RHEL 8.

```suggestion
  rhel:
    '*': [python3-elasticsearch]
    '7': null
```

2022-04-12 09:29 UTC, cottsay approved these changes
Thanks!

2022-04-14 14:33 UTC, nuclearsandwich approved these changes
Thanks for iterating!

2022-04-14 14:33 UTC, merged