Add sysv-ipc pip package
ros/rosdistro pull request #32898
Opened 2022-04-26 06:19 UTC by meganetaaan

Please add the following dependency to the rosdep database.

## Package name:

pip/pip3 sysv-ipc

## Package Upstream Source:

http://semanchuk.com/philip/sysv_ipc/

## Purpose of using this:

Our private package depends on it. We need to get it from pip since the one on apt is old.

## Links to Distribution Packages

- Pip: https://pypi.org/project/sysv-ipc/

2022-04-26 17:47 UTC, tfoote requested changes
Thanks for the contribution of rosdep keys. Please take a moment to update your PR following our rosdep rule [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions). You can add changes to the branch you have submitted from or edit the description. When you make the changes please comment back on this PR so that we get a notification that you've updated it.

This appears to be packaged natively. https://packages.ubuntu.com/impish/python3-sysv-ipc as such we should use that version not the one from pip.

2022-05-02 02:20 UTC, meganetaaan commented
I updated the PR to use native `python3-sysv-ipc` package. Would you re-review it.

2022-05-02 17:08 UTC, jacobperron approved these changes

2022-05-03 19:01 UTC, methylDragon approved these changes
Will merge in.

Just note that the native version is 1.0.0 while the pip version is 1.1.0. for your internal uses!

2022-05-03 19:01 UTC, merged