[emoji] Add pip emoji package
ros/rosdistro pull request #33248
Opened 2022-05-17 13:52 UTC by tkmtnt7000

Please add the following dependency to the rosdep database.

## Package name:

pip/pip3 emoji

## Package Upstream Source:

https://github.com/carpedm20/emoji/

## Purpose of using this:

I want to release the package that depends on this library. 

Distro packaging links: https://github.com/jsk-ros-pkg/jsk_robot

## Links to Distribution Packages

- Pip: https://pypi.org/project/emoji/

2022-05-17 21:10 UTC, ivanpauno commented on rosdep/python.yaml
> +python-emoji-pip:
do you want to make it available for python3?
In that case, the key should be `python3-emoji-pip`.

2022-05-17 21:10 UTC, ivanpauno commented on rosdep/python.yaml
> +python-emoji-pip:
There's an ubuntu debian package available: https://packages.ubuntu.com/jammy/python3-emoji.

So consider adding a `python3-emoji` key instead

2022-05-18 00:52 UTC, tfoote requested changes
If it's available from debian packages we should use that and not the pip rules. 

Thanks for the contribution of rosdep keys. Please take a moment to update your PR following our rosdep rule [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions). You can add changes to the branch you have submitted from or edit the description. When you make the changes please comment back on this PR so that we get a notification that you've updated it.

2022-05-18 04:09 UTC, tkmtnt7000 commented
Thank you for quick reply.
Changed to use debian package if debian package is released.

2022-05-18 17:52 UTC, tfoote reviewed
Thanks for the quick update. I see that it's also available for debian as of bookworm. https://packages.debian.org/bookworm/python3-emoji

Please use the same wildcard technique to list older version of debian via pip and the wildcard for goign forwardard. 

And the linter has identified that there's python3-emoji on rhel and python-emoji on suse.

2022-05-19 11:50 UTC, hidmic approved these changes
@tkmtnt7000 would you mind updating the PR description with [a package listing](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) for future reference?

2022-05-19 13:19 UTC, tkmtnt7000 commented
I updated the PR description.

2022-05-20 22:04 UTC, tfoote approved these changes
lgtm

2022-05-20 22:04 UTC, merged