orocos-kdl_python3: 1.4.1-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #33329
Opened 2022-05-23 08:02 UTC by k-okada

Increasing version of package(s) in repository `orocos-kdl_python3` to `1.4.1-1`:

- upstream repository: https://github.com/jsk-ros-pkg/orocos_kinematics_dynamics_python3.git
- release repository: https://github.com/tork-a/orocos-kdl_python3-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.11.1`
- previous version for package: `null`

2022-05-23 08:02 UTC, k-okada commented
same motivation as https://github.com/ros/rosdistro/pull/32505, cc: @iory

2022-05-24 00:30 UTC, tfoote requested changes
Same feedback as https://github.com/ros/rosdistro/pull/33330#pullrequestreview-982466720

2022-06-15 16:42 UTC, sloretz requested changes
https://github.com/ros/rosdistro/pull/33330#pullrequestreview-1007819952

2022-06-15 18:46 UTC, audrow commented
https://github.com/ros/rosdistro/pull/33330#pullrequestreview-1007968618

2022-06-15 18:47 UTC, audrow requested changes
https://github.com/ros/rosdistro/pull/33330#pullrequestreview-1007968618

2022-06-20 16:52 UTC, sloretz commented
Continued in https://github.com/ros/rosdistro/pull/33631

2022-06-20 16:52 UTC, closed without merging