geomerty_python3: 1.12.2-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #33328
Opened 2022-05-23 07:58 UTC by k-okada

Increasing version of package(s) in repository `geomerty_python3` to `1.12.2-1`:

- upstream repository: https://github.com/jsk-ros-pkg/geometry_python3.git
- release repository: https://github.com/tork-a/geometry_python3-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.11.1`
- previous version for package: `null`

2022-05-23 08:01 UTC, k-okada commented
same motivation as https://github.com/ros/rosdistro/pull/32505, cc: @iory

2022-05-23 13:03 UTC, hidmic reviewed
@k-okada hmm, is this a Python3 backport of a core library? I understand the need but this highly unusual. FYI @tfoote.

2022-05-24 00:31 UTC, tfoote requested changes
high level feedback same as: https://github.com/ros/rosdistro/pull/33330#pullrequestreview-982466720

2022-05-24 00:31 UTC, tfoote commented on melodic/distribution.yaml
> +      version: 1.12.2-1
As it's a backport no doc is probably better.

2022-06-15 16:42 UTC, sloretz requested changes
https://github.com/ros/rosdistro/pull/33330#pullrequestreview-1007819952

2022-06-15 18:48 UTC, audrow requested changes
https://github.com/ros/rosdistro/pull/33330#pullrequestreview-1007968618

2022-06-20 08:02 UTC, k-okada commented
based on @iory 's comment at https://github.com/ros/rosdistro/pull/33330#issuecomment-1153710987, we do not need this

2022-06-20 08:02 UTC, closed without merging