performance_test-release: 1.1.0-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #33443
Opened 2022-06-02 15:44 UTC by revati-naik

Increasing version of package(s) in repository `performance_test-release` to `1.1.0-1`:

- upstream repository: https://gitlab.com/ApexAI/performance_test.git
- release repository: https://github.com/ros2-gbp/performance_test-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `null`

2022-06-02 16:48 UTC, clalancette requested changes
Besides the comment inline, shouldn't we merge https://github.com/ros2-gbp/performance_test-release/pull/1 before blooming and merging this?

2022-06-02 16:48 UTC, clalancette commented on humble/distribution.yaml
> +  performance_test-release:
The key here should be `performance_test`, not `performance_test-release`.

2022-06-07 18:55 UTC, audrow approved these changes

2022-06-07 19:10 UTC, audrow requested changes

2022-06-07 19:10 UTC, audrow commented on humble/distribution.yaml
> +      test_pull_requests: true
```suggestion
```
This line should be removed so that the checks pass.

2022-06-10 21:55 UTC, audrow approved these changes

2022-06-10 21:56 UTC, merged