orocos-kdl_python3: 1.4.2-2 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #33631
Opened 2022-06-20 07:50 UTC by k-okada

Increasing version of package(s) in repository `orocos-kdl_python3` to `1.4.2-2`:

- upstream repository: https://github.com/jsk-ros-pkg/orocos_kinematics_dynamics_python3.git
- release repository: https://github.com/tork-a/orocos-kdl_python3-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.11.1`
- previous version for package: `null`

2022-06-20 16:56 UTC, sloretz requested changes
Please add a LICENSE file to https://github.com/jsk-ros-pkg/orocos_kinematics_dynamics_python3

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-contents

2022-06-22 11:37 UTC, k-okada commented
@sloretz thanks for comments, added https://github.com/jsk-ros-pkg/orocos_kinematics_dynamics_python3/pull/2

2022-06-22 21:06 UTC, methylDragon commented
Awaiting merge:
- https://github.com/jsk-ros-pkg/orocos_kinematics_dynamics_python3/pull/2
-

2022-06-23 03:27 UTC, k-okada commented
@methylDragon merged

2022-06-23 16:18 UTC, merged