fluent_rviz: 0.0.3-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #33665
Opened 2022-06-22 15:44 UTC by HansRobo

Increasing version of package(s) in repository `fluent_rviz` to `0.0.3-1`:

- upstream repository: https://github.com/ForteFibre/FluentRviz.git
- release repository: https://github.com/ros2-gbp/fluent_rviz-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.11.1`
- previous version for package: `null`

## fluent_rviz

```
* Add CONTRIBUTING.md
* Add LICENSE file
* Contributors: Kotaro Yoshimoto
```

2022-06-22 15:53 UTC, HansRobo commented
I fixed problems in #33634

2022-06-23 18:37 UTC, ivanpauno commented on rolling/distribution.yaml
> +    release:
could you add `source` and `doc` entries as well?
Thanks!

2022-06-25 07:03 UTC, methylDragon requested changes
Needs source and doc entries

2022-06-25 13:12 UTC, HansRobo commented
Thank you for telling me about the lack of information.
I added source and doc entries just now!

2022-06-25 17:21 UTC, merged