Add robodk-pip
ros/rosdistro pull request #33679
Opened 2022-06-23 23:53 UTC by rshanor

Please add the following dependency to the rosdep database.

## Package name:

robodk

## Package Upstream Source:

https://github.com/RoboDK/RoboDK-API
https://robodk.com/doc/en/PythonAPI/index.html

## Purpose of using this:

RoboDK is a software for controlling industrial robot arms. I am trying to write a ros node to interface with the robodk simulator.

https://robodk.com/index

Distro packaging links:

## Links to Distribution Packages

- pip: https://pypi.org/project/robodk/

2022-06-24 00:07 UTC, methylDragon approved these changes

2022-06-27 13:23 UTC, ivanpauno requested changes
Please, read the contributing guidelines for python packages https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#python-rules.

2022-06-30 12:44 UTC, hidmic approved these changes

2022-06-30 12:46 UTC, ivanpauno approved these changes

2022-06-30 12:48 UTC, merged