performance_test: 1.2.1-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #33763
Opened 2022-06-30 21:55 UTC by revati-naik

Increasing version of package(s) in repository `performance_test` to `1.2.1-1`:

- upstream repository: https://gitlab.com/ApexAI/performance_test.git
- release repository: https://github.com/ros2-gbp/performance_test-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `1.1.0-1`

2022-07-01 19:02 UTC, hidmic commented on humble/distribution.yaml
> -      - performance_report
@revati-naik IIUC this means `performance_report` will no longer be released. Is that intended?

2022-07-07 21:06 UTC, tfoote commented on humble/distribution.yaml
>        version: 1.1.0
This tag is out of date now. Is there a branch we can track instead? @revati-naik

2022-07-07 21:11 UTC, tfoote requested changes
@hidmic If you're raising a concern that should block release, please use the request changes so it is known to need attention.

2022-07-07 23:55 UTC, nuclearsandwich requested changes
Once https://github.com/ros/rosdistro/pull/33763/files#r916281228 is resolved this release is ✅

2022-07-09 01:53 UTC, tfoote approved these changes
`performance_report` has never built so this isn't a regression, and will just safe time on the farm. I'm going to merge as such. 

@revati-naik Please update the docs as appropriate. I'm not going to consider that a blocker, but they should really be using a branch not the tag which will get out of date.

2022-07-09 01:53 UTC, merged