performance_test: 1.2.1-1 in 'foxy/distribution.yaml' [bloom]
ros/rosdistro pull request #33765
Opened 2022-06-30 22:01 UTC by revati-naik

Increasing version of package(s) in repository `performance_test` to `1.2.1-1`:

- upstream repository: https://gitlab.com/ApexAI/performance_test.git
- release repository: https://github.com/ros2-gbp/performance_test-release.git
- distro file: `foxy/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `1.0.0-1`

2022-06-30 22:58 UTC, adityapande-1995 commented
Holding for [Foxy sync](https://discourse.ros.org/t/preparing-for-foxy-sync-2022-07-01/26297)

2022-07-08 22:42 UTC, nuclearsandwich requested changes
The doc entry requires an update before this is ready to merge.

2022-07-08 22:42 UTC, nuclearsandwich commented on foxy/distribution.yaml
>        version: 1.0.0
Now that this is out of sync hold I think it is blocked on the same comment as the other distributions. https://github.com/ros/rosdistro/pull/33763#discussion_r916281228

2022-07-09 01:56 UTC, tfoote approved these changes
@revati-naik Please update the docs to be on a branch.

2022-07-09 01:57 UTC, merged