Add asyncapi_gencpp, log_view, rpad, rpad_ros, and param_util source to rolling
ros/rosdistro pull request #34108
Opened 2022-08-11 01:59 UTC by malban

References https://github.com/ros2-gbp/ros2-gbp-github-org/issues/88

# Please Add This Package to be indexed in the rosdistro.

rolling

# The source is here:
  * [log_view](https://github.com/hatchbed/log_view)
  * [asyncapi_gencpp](https://github.com/hatchbed/asyncapi_gencpp) 
  * [rpad](https://github.com/hatchbed/rpad)
  * [rpad_ros](https://github.com/hatchbed/rpad_ros)
  * [param_util](https://github.com/hatchbed/param_util)

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2022-08-11 19:02 UTC, methylDragon requested changes
Nosetest is failing due to ordering issues

2022-08-11 19:09 UTC, cottsay commented on rolling/distribution.yaml
> +  log_vew:
```suggestion
  log_view:
```

2022-08-11 19:17 UTC, clalancette commented
I have to agree with @cottsay that the names `param_util` and `log_view` are too generic.  For that matter, while `rpad` isn't that generic, I'd also argue that it is a bad name for it.  Maybe `slamware_driver` or something like that might be better.  At the end of the day, users are going to be doing things like installing:

`ros-rolling-rpad`, and that just doesn't seem to provide enough context about it.

For reference, here is our naming guidelines for packages: https://www.ros.org/reps/rep-0144.html .  Particularly, see https://www.ros.org/reps/rep-0144.html#global-rules

2022-08-11 20:06 UTC, malban commented
Yeah, I understand on `param_util`.  I'll come up with something else.

`log_view` has already been released in ros1 for a while, though, and also more recently in galactic: https://index.ros.org/p/log_view/github-hatchbed-log_view/

Good point about `rpad`, but I'm not sure about using a commercial trademark like `slamware`, `slamtek`, `rplidar`, etc in the name.  I'm fine with the name being a bit cryptic to avoid potential trademark liability since the package description and readme explain the use case.   I'm also open to a name that gives more context, but it's not clear to me what that would be.  Maybe `opensw` and `opensw_driver` are marginally better?

2022-08-11 20:31 UTC, malban commented
Here are some alternate name for `param_util`:
 - parameterize
 - rosparam_helper
 - rosparam_kit
 - rosparam_assist
 - param_kit
 - param_helper
 - param_assist
 - param_aid

Let me know if any of those work

2022-08-16 00:14 UTC, tfoote commented
Unfortunately most of those proposed names don't really help you if you want to search for this package. One easy way to think about this is what would I find if I searched for the name? If I search for `param` `rosparam` or any of the generic modifiers like `kit` how likely is it that I'll find documentation for this package? Obviously a full string match will likely find it but others not so much. 

For the trademark you don't want to pretend to be them, but if you're writing something that works with a device you can talk about how you're compatible with that device. And if you use a good searchable term then people can find the package easily.

2022-08-16 03:51 UTC, malban commented
> Unfortunately most of those proposed names don't really help you if you want to search for this package. One easy way to think about this is what would I find if I searched for the name? If I search for param rosparam or any of the generic modifiers like kit how likely is it that I'll find documentation for this package? Obviously a full string match will likely find it but others not so much.

Yeah, I see that.

Doing a search of [rosparam](https://index.ros.org/search/?term=rosparam) on the ROS package index turns up:
 - [rosparam_shortcuts](https://index.ros.org/p/rosparam_shortcuts/github-davetcoleman-rosparam_shortcuts/) - (1st page) a similar package to help with parameters, but different approach and set of features
 - [rosparam_handler](https://index.ros.org/p/rosparam_handler/github-cbandera-rosparam_handler/#melodic) - (2nd page) a similar package, but different approach and set of features
 - [rtt_rosparam](https://github.com/orocos/rtt_ros_integration/blob/toolchain-2.9/rtt_rosparam) - (2nd page) "Plugin for synchronizing ROS parameters with Orocos component properties."
 -   core packages: `rosparam`, `ros_comm`, `test_rosparam`

Searching for [param](https://index.ros.org/search/?term=param):
 - [launch_param_builder](https://index.ros.org/p/launch_param_builder) - (1st page) "Python library for loading parameters in launch files"
 - [choreo_param_helpers](https://index.ros.org/p/choreo_param_helpers/github-yijiangh-Choreo#kinetic) - (3rd page) "Implements routines for loading, saving, and checking for the existence of user parameters."
 - core packages:  `rcl_yaml_param_parser`, `ros2param`, 

That seems pretty reasonable to me.  I think including `rosparam` in the package name gives more context than simply `param` and would certainly be more searchable outside of ROS.  

A second word like `kit` or `helper` provides more context when paired with `rosparam`, but on it's own is very generic and would pull unrelated packages into the results even paired with `rosparam`.  I'm not sure in what context someone would search for just `helper`, `kit`, `utils`, etc.

So, is `rosparam_<some acceptable modifier>` a good approach?
- rosparam_tools
   - another generic option, LOTS of `_tools` packages and results when searching for 'tools'
   - but it sounds good to me and seems the most on point
- rosparam_toolset 
- yarpp
   - YetAnotherRosParamPackage :laughing:  
- rosparam_yarp

Open to suggestions

2022-08-16 03:53 UTC, malban commented
> For the trademark you don't want to pretend to be them, but if you're writing something that works with a device you can talk about how you're compatible with that device. And if you use a good searchable term then people can find the package easily.

Right, I agree with that.  It shouldn't be an issue to describe that the software is compatible with the devices and that is in the [README](https://github.com/hatchbed/rpad/blob/main/README.md), package.xml, etc.  It's more of putting the trademark in the actual name of the package, which, not being a lawyer, but doing some web searching, looks like is generally not recommended.

Not sure how to add more context to the package name in this case, other than my previous suggestion of using `opensw` and `opensw_driver` which might be marginally better for context.

Open to suggestions, though.

2022-09-28 15:09 UTC, ivanpauno commented on rolling/distribution.yaml
> +      url: https://github.com/hatchbed/param_util.git
> So, is rosparam_<some acceptable modifier> a good approach?

Yes, that or `<prefix>_rosparam` would work.
But the modifier/prefix, should be something not generic, i.e. avoid "tool" or "kit".

Of the ones you listed, `choreo_param_helpers` and `rtt_rosparam` are good examples, as it's clear to what they refer to.
Example that could work for you: `hatchbed_rosparam` (you may find something better :smile: )

2022-10-05 13:54 UTC, hidmic commented
@malban friendly ping

2022-10-05 15:01 UTC, malban commented
> @malban friendly ping

Thanks for the reminder!

2022-10-05 15:19 UTC, ivanpauno commented on rolling/distribution.yaml
> +      url: https://github.com/hatchbed/log_view.git
that sounds fine to me.
@clalancette @tfoote is that okay?

2022-10-05 15:20 UTC, ivanpauno commented on rolling/distribution.yaml
> +      url: https://github.com/hatchbed/param_util.git
That sounds good to me as well

2022-10-12 02:04 UTC, malban commented
Ok, based on comments, I've renamed:
- `param_util` -> `hatchbed_common`
- `rpad` -> `opensw`
- `rpad_ros` -> `opensw_ros`

2022-10-12 16:46 UTC, nuclearsandwich approved these changes
The latest proposed names look acceptable to me but I think it is worth getting a ✔️ from at least one of the original reporters as well.

2022-10-12 17:49 UTC, cottsay approved these changes
Thanks for iterating, @malban. I think we've arrived at something better.

2022-10-12 18:28 UTC, clalancette commented
Generally this looks good to me now.  Thanks for the iteration.

The `log_view` one is unfortunate, since it is really generic.  But it was accepted into other ROS 2 distributions, so we can take that one on precedent.

2022-10-12 18:28 UTC, clalancette approved these changes

2022-10-14 21:42 UTC, merged