rviz: 1.14.18-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #34129
Opened 2022-08-12 16:33 UTC by rhaschke

Increasing version of package(s) in repository `rviz` to `1.14.18-1`:

- upstream repository: https://github.com/ros-visualization/rviz.git
- release repository: https://github.com/ros-gbp/rviz-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `1.14.16-1`

## rviz

```
* Fixup to #1760 <https://github.com/ros-visualization/rviz/issues/1760>, SplitterHandle (#1766 <https://github.com/ros-visualization/rviz/issues/1766>)
* Contributors: Robert Haschke
```

2022-08-12 18:25 UTC, ivanpauno approved these changes

2022-08-12 22:24 UTC, methylDragon commented
Sorry if I missed it, but could you add a LICENSE file?
I know `rviz` is a pretty old package, but it's just to bring it up to speed to the [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md)

2022-08-12 22:24 UTC, methylDragon requested changes
Sorry if I missed it, but could you add a LICENSE file?
I know rviz is a pretty old package, but it's just to bring it up to speed to the [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md?rgh-link-date=2022-08-12T22%3A24%3A33Z)

2022-08-14 05:05 UTC, rhaschke commented
> Could you add a LICENSE file?

Sure. I will prepare yet another release.

2022-08-14 05:05 UTC, closed without merging