[dep]Adding libao-dev
ros/rosdistro pull request #34204
Opened 2022-08-24 07:23 UTC by KanayaNakamura

Please add the following dependency to the rosdep database.

## Package name:

libao-dev

## Package Upstream Source:

https://www.xiph.org/ao/

## Purpose of using this:

Development library to implement simple audio output.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?keywords=libao-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?keywords=libao-dev
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/libao/libao-devel
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/packages?name=libao-dev&branch=edge&repo=&arch=&maintainer=

2022-08-24 19:09 UTC, tfoote requested changes
This looks good. Please add the two suggestions from the linter. Otherwise it's ready to go.

2022-08-24 19:09 UTC, tfoote commented on rosdep/base.yaml
> +  fedora: [libao-devel]
```suggestion
  fedora: [libao-devel]
  opensuse: [libao-devel]
  rhel: [libao-devel]
```

Add suggested targest from linter

2022-08-25 00:03 UTC, KanayaNakamura commented on rosdep/base.yaml
> +  fedora: [libao-devel]
That's a great suggestions. Thanks!

2022-08-25 13:02 UTC, nuclearsandwich approved these changes

2022-08-25 17:48 UTC, tfoote approved these changes
Thanks for the updates

2022-08-25 17:48 UTC, merged