Add qtpy for rhel
ros/rosdistro pull request #34247
Opened 2022-08-29 16:01 UTC by ipa-cmh

Please add the following dependency to the rosdep database.

## Package name:

python3-qtpy

## Package Upstream Source:

https://github.com/spyder-ide/qtpy

## Purpose of using this:

Add support for RHEL. See https://github.com/ros-visualization/python_qt_binding/issues/114

Distro packaging links:

## Links to Distribution Packages

- EPEL 8: 
  - https://packages.fedoraproject.org/pkgs/python-QtPy/python3-QtPy/

2022-09-02 19:59 UTC, jacobperron approved these changes
lgtm

Mind adding an entry for fedora as well?

2022-09-07 18:50 UTC, cottsay commented on rosdep/python.yaml
>    gentoo: [dev-python/QtPy]
```suggestion
  fedora: [python3-QtPy]
  gentoo: [dev-python/QtPy]
```

2022-09-19 17:23 UTC, clalancette requested changes
Need the fixes that @cottsay pointed out, then this will be good.

2022-09-26 01:19 UTC, cottsay approved these changes

2022-09-26 12:57 UTC, clalancette approved these changes

2022-09-26 12:57 UTC, merged