add python-flask-sqlalchemy key to python.yaml
ros/rosdistro pull request #34462
Opened 2022-09-13 11:38 UTC by ppanagiotidis

Please add the following dependency to the rosdep database.

## Package name:

python3-flask-sqlalchemy

## Package Upstream Source:

https://github.com/pallets-eco/flask-sqlalchemy

## Purpose of using this:

Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/python3-flask-sqlalchemy
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/focal/python3-flask-sqlalchemy
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-flask-sqlalchemy/python3-flask-sqlalchemy/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/community/any/python-flask-sqlalchemy/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/flask-sqlalchemy
- macOS: https://formulae.brew.sh/
  - Not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - Not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=22.05&show=python39Packages.flask_sqlalchemy&from=0&size=50&sort=relevance&type=packages&query=flask-sqlalchemy
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/python-Flask-SQLAlchemy

2022-09-13 19:10 UTC, clalancette requested changes
One thing to fix, then this is good from my standpoint.

2022-09-13 19:10 UTC, clalancette commented on rosdep/python.yaml
> +python-flask-sqlalchemy:
This should make the Ubuntu package name, so should be:

```suggestion
python3-flask-sqlalchemy:
```

2022-09-13 19:31 UTC, clalancette requested changes

2022-09-13 19:31 UTC, clalancette commented on rosdep/python.yaml
> +    '*': [python3-flask-sqlalchemy]
Sorry, I just noticed this:

```suggestion
  ubuntu: [python3-flask-sqlalchemy]
```

2022-09-13 19:45 UTC, clalancette requested changes
Sorry for all of the back-n-forth here.  I think we are almost there, one more fix for RHEL I think should do it.

2022-09-13 19:45 UTC, clalancette commented on rosdep/python.yaml
> +  nixos: [python39Packages.flask_sqlalchemy]
CI is pointing out that this is available in EPEL-8 for RHEL, which is why it is failing.  This should fix it:

```suggestion
  nixos: [python39Packages.flask_sqlalchemy]
  rhel:
    '*': [python3-flask-sqlalchemy]
    '7': null
```

2022-09-13 20:17 UTC, clalancette requested changes
Now CI is complaining about alphabetical order.  Besides the fix I have inline, the entire key should be moved into the `python3-` section of keys in alphabetical order.

2022-09-13 20:17 UTC, clalancette commented on rosdep/python.yaml
> +  opensuse: [python-Flask-SQLAlchemy]
```suggestion
  nixos: [python39Packages.flask_sqlalchemy]
  opensuse: [python-Flask-SQLAlchemy]
  rhel:
    '*': [python3-flask-sqlalchemy]
    '7': null
  ubuntu: [python3-flask-sqlalchemy]
```

2022-09-13 20:43 UTC, clalancette approved these changes

2022-09-20 22:26 UTC, jacobperron approved these changes

2022-09-20 22:26 UTC, merged