Add jax and jaxlib mapping
ros/rosdistro pull request #34558
Opened 2022-09-14 12:16 UTC by halejo-as

Please add the following dependency to the rosdep database.

## Jax and JaxLib:

`jax`
`jaxlib`

## Package Upstream Source:

[jax](https://github.com/google/jax)

## Purpose of using this:

What’s new is that JAX uses [XLA](https://www.tensorflow.org/xla) to compile and run your NumPy programs on GPUs and TPUs.

## Links to Distribution Packages

- Debian:
  https://pypi.org/project/jax/
  https://pypi.org/project/jaxlib/
- Ubuntu: 
  https://pypi.org/project/jax/
  https://pypi.org/project/jaxlib/

2022-09-19 17:21 UTC, clalancette requested changes
Please see our [contributing guidelines for pip](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1), where both of these keys should be suffixed with `-pip`.

2022-09-28 15:29 UTC, ivanpauno commented
@halejo-as friendly ping

2022-09-29 23:46 UTC, methylDragon commented on rosdep/python.yaml
> +python3-jax:
```suggestion
python3-jax-pip:
```

2022-09-29 23:46 UTC, methylDragon commented on rosdep/python.yaml
> +python3-jaxlib:
```suggestion
python3-jaxlib-pip:
```

2022-09-29 23:46 UTC, methylDragon requested changes
:>

2022-10-05 10:26 UTC, halejo-as commented
Thanks @methylDragon for the changes

2022-10-13 02:18 UTC, nuclearsandwich commented
@halejo-as it looks like the current outstanding issue is that the entry is out of order.

```
ERR: list out of alphabetical order line 7200.  'python3-j1939-pip' should come before 'python3-jaxlib'
```

2022-11-15 21:56 UTC, ivanpauno commented
It has happened more than one month since the last comment, so closing.
@halejo-as Please reopen or open a new PR when it's ready.
Thanks!

2022-11-15 21:56 UTC, closed without merging