jackal_desktop: 1.0.1-1 in 'foxy/distribution.yaml' [bloom]
ros/rosdistro pull request #34700
Opened 2022-09-29 21:38 UTC by tonybaltovski

Increasing version of package(s) in repository `jackal_desktop` to `1.0.1-1`:

- upstream repository: https://github.com/jackal/jackal_desktop.git
- release repository: https://github.com/clearpath-gbp/jackal_desktop-release.git
- distro file: `foxy/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## jackal_desktop

- No changes

## jackal_viz

```
* [jackal_viz] Changes rviz to rviz2.
* Contributors: Tony Baltovski
```

2022-09-29 23:49 UTC, methylDragon requested changes
Would it be possible to add a [LICENSE file](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-contents)?

2022-10-05 13:57 UTC, hidmic commented
@tonybaltovski friendly ping. 

Also, this needs conflict resolution.

2022-10-13 00:36 UTC, nuclearsandwich commented
@tonybaltovski I'm going to close this PR for now but please do re-open it once the requested changes are made and the merge conflicts are resolved.

2022-10-13 00:36 UTC, closed without merging

2022-10-13 14:15 UTC, tonybaltovski commented
Added https://github.com/jackal/jackal_desktop/commit/65c99611fa8050c8f7b2b37b5aac0404c7966b5a