Add python3-rosinstall-generator rules for Fedora and RHEL
ros/rosdistro pull request #34817
Opened 2022-10-05 17:52 UTC by cottsay

Fedora: https://packages.fedoraproject.org/pkgs/python-rosinstall_generator/python3-rosinstall_generator/

In both RHEL 7 and 8, this package is provided by EPEL: https://packages.fedoraproject.org/pkgs/python-rosinstall_generator/python3-rosinstall_generator/

2022-10-06 14:52 UTC, hidmic requested changes

2022-10-11 16:10 UTC, cottsay commented on rosdep/python.yaml
> +  rhel: [python3-rosinstall_generator]
As was mentioned in https://github.com/ros/rosdistro/pull/34818#discussion_r989303615, this is one of the more freshly rebuilt packages which provide the virtual package `python3-rosinstall_generator`. We could explicitly use `%{python3_pkgversion}` here, but it's not really necessary.

```
$ rpm --qf '[%{PROVIDES}\n]' -q python36-rosinstall_generator
python3-rosinstall_generator
python3.6dist(rosinstall-generator)
python36-rosinstall_generator
```

2022-10-13 01:13 UTC, nuclearsandwich approved these changes

2022-10-16 13:58 UTC, adityapande-1995 approved these changes

2022-10-17 15:04 UTC, clalancette approved these changes

2022-10-17 15:04 UTC, merged