Libdc1394 dev 0
ros/rosdistro pull request #34978
Opened 2022-10-17 16:09 UTC by FranekStark

Please add the following dependency to the rosdep database.

## Package name:

libdc1394-dev

## Purpose of using this:
Since Ubuntu kinetic the package `libdc1394-22-dev` is replaced by `libdc1394-dev`. 
Therefore I set `libdc1394-dev` as the new standard package for Ubuntu and added rules for the older Ubuntu releases.
See:
- https://askubuntu.com/questions/1407580/unable-to-locate-package-libdc1394-22-dev
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963924

closes [#34921](https://github.com/ros/rosdistro/issues/34921)

## Links to Distribution Packages
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/jammy/libdc1394-dev
   - https://packages.ubuntu.com/kinetic/libdc1394-dev

2022-10-18 08:17 UTC, nuclearsandwich requested changes
I suggest dropping the out-of-support distributions to keep things maintainable. It would also be nice to update the Debian keys equivalently (at least for bullseye and bookworm) but I can't use the suggestion API because those lines weren't touched.

2022-10-18 08:24 UTC, FranekStark commented on rosdep/base.yaml
> +    'artful': [libdc1394-22-dev]
ok thanks for the comment.
Yes makes sense, I wasn't sure how outdated distributions are handled. So I tried to add as many old distributions I found to be backwards compatible. 
Also I will add a new commit for debian in a moment

2022-10-18 08:36 UTC, FranekStark commented
@nuclearsandwich I removed the outdated ubuntu keys, and added the debian keys.

2022-10-18 15:11 UTC, clalancette requested changes
Two small things to change, then I'm happy to approve this.

2022-10-18 15:11 UTC, clalancette commented on rosdep/base.yaml
> +    'stretch': [libdc1394-22-dev]
While we aren't totally consistent about this, we don't typically quote these:

```suggestion
    buster: [libdc1394-22-dev]
    stretch: [libdc1394-22-dev]
```

2022-10-18 15:11 UTC, clalancette commented on rosdep/base.yaml
> +    'bionic': [libdc1394-22-dev]
Same here:

```suggestion
    focal: [libdc1394-22-dev]
    bionic: [libdc1394-22-dev]
```

2022-10-19 12:41 UTC, clalancette approved these changes

2022-10-19 12:46 UTC, clalancette requested changes
One more change should fix CI.

2022-10-19 12:46 UTC, clalancette commented on rosdep/base.yaml
> +    bionic: [libdc1394-22-dev]
```suggestion
    bionic: [libdc1394-22-dev]
    focal: [libdc1394-22-dev]
```

2022-10-19 13:08 UTC, clalancette approved these changes

2022-10-20 13:25 UTC, audrow approved these changes

2022-10-20 13:25 UTC, merged