smacc: 0.9.4-3 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #35016
Opened 2022-10-21 20:53 UTC by pabloinigoblasco

Increasing version of package(s) in repository `smacc` to `0.9.4-3`:

- upstream repository: https://github.com/reelrbtx/SMACC
- release repository: https://github.com/reelrbtx/SMACC-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

2022-10-24 13:18 UTC, clalancette commented
What's the relationship between this package and https://github.com/robosoft-ai/SMACC2 ?  That is, is there any reason they aren't under the same organization?

2022-11-08 18:23 UTC, methylDragon requested changes
> What's the relationship between this package and [robosoft-ai/SMACC2](https://github.com/robosoft-ai/SMACC2) ? That is, is there any reason they aren't under the same organization?

Looks like the repo redirects to robosoft-ai. Maybe rebloom with that name instead of its less confusing @pabloinigoblasco ?

2022-11-08 18:31 UTC, pabloinigoblasco commented
We are just migrating at this current to robosoft-ai.
I hope we have this issue clean in short.

Since this is the first release of SMACC for ROS1 I hope this would be easy.
I am also just hard resetting the SMACC-release repo (in robosoft-ai repo )

2022-11-08 18:33 UTC, pabloinigoblasco commented
I request tol cancel this PR since we are going to create a totally new and clean one associated to robosoft-ai

2022-11-08 18:52 UTC, closed without merging