pmb2_simulation: 3.0.3-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #35058
Opened 2022-10-26 12:21 UTC by Noel215

Increasing version of package(s) in repository `pmb2_simulation` to `3.0.3-1`:

- upstream repository: https://github.com/pal-robotics/pmb2_simulation.git
- release repository: https://github.com/pal-gbp/pmb2_simulation-gbp.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## pmb2_2dnav_gazebo

```
* Merge branch 'cleanup' into 'humble-devel'
  Update package.xml deps
  See merge request robots/pmb2_simulation!46
* update package.xml deps
* Merge branch 'refactor_launch_files' into 'humble-devel'
  Refactor ld population
  See merge request robots/pmb2_simulation!42
* refactor LaunchDescription population
* Merge branch 'update_copyright' into 'humble-devel'
  Update copyright and license
  See merge request robots/pmb2_simulation!41
* update copyright and license
* Merge branch 'update_maintainers' into 'humble-devel'
  update maintainers
  See merge request robots/pmb2_simulation!40
* update maintainers
* Contributors: Jordan Palacios, Noel Jimenez
```

## pmb2_gazebo

```
* Merge branch 'add_missing_dep' into 'humble-devel'
  add missing dependency
  See merge request robots/pmb2_simulation!47
* add missing dependency
* Merge branch 'cleanup' into 'humble-devel'
  Update package.xml deps
  See merge request robots/pmb2_simulation!46
* update package.xml deps
* Merge branch 'refactor_launch_files' into 'humble-devel'
  Refactor ld population
  See merge request robots/pmb2_simulation!42
* refactor LaunchDescription population
* Merge branch 'update_copyright' into 'humble-devel'
  Update copyright and license
  See merge request robots/pmb2_simulation!41
* update copyright and license
* Merge branch 'update_maintainers' into 'humble-devel'
  update maintainers
  See merge request robots/pmb2_simulation!40
* update maintainers
* Merge branch 'run_tests' into 'humble-devel'
  fix linter errors
  See merge request robots/pmb2_simulation!39
* linters
* Contributors: Jordan Palacios, Noel Jimenez
```

## pmb2_simulation

```
* Merge branch 'update_copyright' into 'humble-devel'
  Update copyright and license
  See merge request robots/pmb2_simulation!41
* update copyright and license
* Merge branch 'update_maintainers' into 'humble-devel'
  update maintainers
  See merge request robots/pmb2_simulation!40
* update maintainers
* Contributors: Jordan Palacios, Noel Jimenez
```

2022-10-26 13:26 UTC, ahcorde requested changes
could you add a LICENSE file in the https://github.com/pal-robotics/pmb2_simulation repository ?

2022-10-26 13:34 UTC, Noel215 commented
It already exists: https://gitlab/robots/pmb2_simulation/-/blob/humble-devel/LICENSE

2022-10-28 18:00 UTC, ahcorde approved these changes
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2022-11-01/27990)

2022-11-04 00:22 UTC, sloretz approved these changes

2022-11-04 00:22 UTC, merged