Adding fields2cover_ros to documentation index for Noetic
ros/rosdistro pull request #35111
Opened 2022-10-31 20:40 UTC by Gonzalo-Mier

# Please Add This Package to be indexed in the rosdistro.

fields2cover-ros

# The source is here:

https://github.com/Fields2Cover/fields2cover_ros

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

2022-11-02 21:00 UTC, tfoote requested changes

2022-11-02 21:00 UTC, tfoote commented on noetic/distribution.yaml
> +      url: https://github.com/Fields2Cover/fields2cover_ros
Please add `.git` here

2022-11-03 08:00 UTC, Gonzalo-Mier commented on noetic/distribution.yaml
> +      url: https://github.com/Fields2Cover/fields2cover_ros
Done

2022-11-03 20:49 UTC, tfoote approved these changes
Thanks that fixes CI.

2022-11-03 20:49 UTC, merged