Add more fine-grained libpcl-* packages (in addition to ...
ros/rosdistro pull request #35137
Opened 2022-11-02 16:20 UTC by mvieth

...existing libpcl-all and libpcl-all-dev)

No new dependencies are added, the new items just make it possible to be more specific when asking for PCL module libraries. For `libpcl-common` for example, I copied the definition of `libpcl-all` and deleted all distribution packages except for `libpcl-common*`. Most distributions, except for debian and ubuntu, currently don't have individual packages for PCL modules, only one package for all of PCL.

This is a continuation of https://github.com/ros/rosdistro/pull/26448

2022-11-02 20:07 UTC, tfoote reviewed
These are a lot of extra rules with strong versioning included which will need to be updated regularly. How much benefit do they provide to call out the individual libraries versus installing the full package? 

And related I see that you've only called out specific versions for ubuntu and debian. Can this same level of granularity not be achieved on the other platforms?

2022-11-03 10:35 UTC, mvieth commented
> These are a lot of extra rules with strong versioning included which will need to be updated regularly. How much benefit do they provide to call out the individual libraries versus installing the full package?

The existing rules `libpcl-all` and `libpcl-all-dev` also link to packages with strong versions, so the additional work for these new rules when updating for a new debian/ubuntu release would not be that much IMO.
Some PCL modules, e.g. visualization, have a lot of dependencies (tens or hundreds of MB). See also https://github.com/ros-perception/perception_pcl/issues/307 for more details. So it would be great if the user is not forced to install dependencies for PCL modules they don't need.

> And related I see that you've only called out specific versions for ubuntu and debian. Can this same level of granularity not be achieved on the other platforms?

Except for ubuntu and debian, I am not aware that other platforms offer the PCL modules (common, filters, features, ...) as individual packages. This may change in the future, I don't know.

2022-11-08 18:32 UTC, methylDragon requested changes
Packages look like they're missing

2022-11-09 09:29 UTC, mvieth commented
> Packages look like they're missing

I assume you are referring to the error messages that package `pcl` can not be found on platforms `arch` and `opensuse`.
However, the package does exist for both:
https://build.opensuse.org/package/show/science/pcl and https://aur.archlinux.org/packages/pcl
I am not sure why the check does not find them?
Please also note that the two existing rules `libpcl-all` and `libpcl-all-dev` already refer to the package `pcl` on `arch` and `opensuse`. So I didn't introduce any new dependencies.

2022-11-09 22:36 UTC, nuclearsandwich commented
> Please also note that the two existing rules `libpcl-all` and `libpcl-all-dev` already refer to the package `pcl` on `arch` and `opensuse`. So I didn't introduce any new dependencies.

This indicates that there are regressions in those rules and ideally those regressions would be cleaned up as a general improvement along with these new changes. However, if you limit the changes to dropping the no-longer-valid definitions for these platforms for your newly added keys then that will at least allow review to proceed.

2022-11-11 09:01 UTC, mvieth commented
Thanks for the explanation! I removed the package definitions for arch and opensuse for the newly added keys.

2022-11-16 20:00 UTC, mvieth commented
@ivanpauno I have updated the description

2022-11-16 20:28 UTC, ivanpauno commented
May be a dup of https://github.com/ros/rosdistro/pull/35289, I will double check when reviewing again

2022-11-17 11:47 UTC, ivanpauno approved these changes

2022-11-17 11:58 UTC, ivanpauno reviewed
Could you please apply the suggested changes to all the new entries?
Thanks

2022-11-17 11:58 UTC, ivanpauno commented on rosdep/base.yaml
> +  alpine: [pcl-libs]
could you add `arch: [pcl]`?

```suggestion
  arch: [pcl]
  alpine: [pcl-libs]
```

2022-11-17 11:58 UTC, ivanpauno commented on rosdep/base.yaml
> +  openembedded: [pcl@meta-ros-common]
```suggestion
  openembedded: [pcl@meta-ros-common]
  opensuse: [pcl]
```

2022-11-17 12:03 UTC, ivanpauno commented
> May be a dup of #35289, I will double check when reviewing again

It's not exactly a dup, but there's some duplication.
I will merge the first one that's ready, the other one will need a rebase after that.

2022-11-22 13:45 UTC, ivanpauno commented
https://github.com/ros/rosdistro/pull/35289 is now a superset of this, and it only needs a few minor changes for CI to pass.
So I will close this one.
If for any reason https://github.com/ros/rosdistro/pull/35289 doesn't get merged, please feel free to reopen.

@mvieth thanks for this PR and for your help in https://github.com/ros/rosdistro/pull/35289!!

2022-11-22 13:45 UTC, closed without merging