python3-deprecated added to rosdep dependencies
ros/rosdistro pull request #35491
Opened 2022-12-01 09:25 UTC by gv11181989

Please add the following dependency to the rosdep database.

## Package name:  
Deprecated 

## Package Upstream Source: 
https://github.com/tantale/deprecated

## Purpose of using this:
This dependency is Python @deprecated decorator to deprecate old python classes, functions, or methods

## Links to Distribution Packages
- Debian: https://packages.debian.org/bullseye/python3-deprecated
- Ubuntu: https://packages.ubuntu.com/jammy/python3-deprecated

2022-12-01 23:45 UTC, nuclearsandwich requested changes
There are several changes that need to be made.

This entry does not follow our conventions for pip keys, which should be of the form `python3-deprecated-pip` rather than `deprecated-pip` regardless of which major python versions are supported by the package.

Furthermore, you've linked to the debian and ubuntu repository listings for this package which means that pip keys should _not_ be used and instead keys for the system packages should be added instead. For example:
```yaml
python3-deprecated:
  debian:
    '*': [python3-deprecated]
    buster: null
  ubuntu:
    '*': [python3-deprecated]
    bionic: null
```

2022-12-02 10:56 UTC, gv11181989 commented
> There are several changes that need to be made.
> 
> This entry does not follow our conventions for pip keys, which should be of the form `python3-deprecated-pip` rather than `deprecated-pip` regardless of which major python versions are supported by the package.
> 
> Furthermore, you've linked to the debian and ubuntu repository listings for this package which means that pip keys should _not_ be used and instead keys for the system packages should be added instead. For example:
> 
> ```yaml
> python3-deprecated:
>   debian:
>     '*': [python3-deprecated]
>     buster: null
>   ubuntu:
>     '*': [python3-deprecated]
>     bionic: null
> ```

Changes made as requested.

2022-12-07 18:04 UTC, cottsay requested changes
The tests failed with the following error:
```
ERR: list out of alphabetical order line 179.  'dpath-pip' should come before 'python3-deprecated'
```

Additionally, there are two suggestions on the [Files changed](https://github.com/ros/rosdistro/pull/35491/files) tab of this PR that appear to be valid.

2022-12-21 23:25 UTC, sloretz approved these changes

2023-01-02 18:34 UTC, clalancette requested changes
There are still 2 suggestions on the Files tab: https://github.com/ros/rosdistro/pull/35491/files

Once those are fixed, I think this can go in.

2023-01-18 14:58 UTC, clalancette requested changes

2023-01-18 14:58 UTC, clalancette commented on rosdep/python.yaml
> +  rhel: [python3-deprecated]
```suggestion
  rhel: 
    '*': [python3-deprecated]
    '7': null
```

2023-01-18 18:16 UTC, clalancette requested changes

2023-01-18 18:16 UTC, clalancette commented on rosdep/python.yaml
> +  rhel:
Looks like there is trailing whitespace on this line that is causing CI to fail.

2023-01-18 18:40 UTC, clalancette approved these changes

2023-01-18 18:41 UTC, merged