casadi: 3.5.5-3 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #35555
Opened 2022-12-04 10:55 UTC by yakunouyang

Increasing version of package(s) in repository `casadi` to `3.5.5-3`:

- upstream repository: https://github.com/casadi/casadi.git
- release repository: https://github.com/yakunouyang/casadi-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

2022-12-06 18:42 UTC, nuclearsandwich commented
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/casadi/casadi/blob/master/LICENSE.txt
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): LGPL-3.0
- [x] License correctly listed in package.xmls
  - [x] casadi (release repo): https://github.com/yakunouyang/casadi-release/blob/master/noetic/package.xml#L11
- [x] Public source repo: https://github.com/casadi/casadi
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - The packaged software is not a native ROS package and has a package.xml included in the release repository.
  - Foxy and Dashing have a casadi_vendor package: https://github.com/ros/rosdistro/blob/b5fef677134a551953178b7d9290bafb3d4ef884/foxy/distribution.yaml#L540-L554

2022-12-06 19:20 UTC, sloretz requested changes
First, [I don't see an upstream system package in Focal](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=casadi)

Next, checking if consistent with recommendations in [REP 136](https://ros.org/reps/rep-0136.html)

* Is a package.xml injected via bloom? 
   * Yes there is a [patches directory in the Noetic track](https://github.com/yakunouyang/casadi-release/blob/5cf05a0b97cd04e02ec77fd9c6d8fad7a62a118c/tracks.yaml#L20), and it does [have a package.xml](https://github.com/yakunouyang/casadi-release/blob/master/noetic/package.xml)
* Is there an install rule patch that installs the package.xml
   * [Yes](https://github.com/yakunouyang/casadi-release/blob/patches/release/noetic/casadi/0001-Added-install-rule-for-package.xml.patch)
* Is there an exec_depend or run_depend on catkin?
   * **No**
* Is the build_type set appropriately?
   * Yes, [build_type is set to cmake, and it's a cmake packge](https://github.com/yakunouyang/casadi-release/blob/5cf05a0b97cd04e02ec77fd9c6d8fad7a62a118c/noetic/package.xml#L22)  


If I understand correctly, I think it needs an `<exec_depend>catkin</exec_depend>` in the patched in package.xml, and then a re-bloom.

2022-12-06 21:39 UTC, yakunouyang commented
Thank you for your thorough review! I've added `<exec_depend>catkin</exec_depend>` to `noetic/package.xml` according to your comment.

2022-12-07 00:37 UTC, nuclearsandwich commented
> I noticed that the release inc was set to 3 before because of several incautious `bloom-release` run, I've reset the release inc back to 1 and re-bloomed the release repository, hopefully this won't cause any problems. smile

I would recommend not modifying that value at all. Most packages released via bloom that do anything other than very standard ROS releases will require a few revisions and package revisions are a normal part of the workflow. You cannot change that value without changing the contents of the release which means that fixes made since the first revision will no longer be present.

If you make a follow up release, please preserve the release increment as-is. Failing to do so will likely create broken packages.

2022-12-07 14:02 UTC, yakunouyang commented
> > I noticed that the release inc was set to 3 before because of several incautious `bloom-release` run, I've reset the release inc back to 1 and re-bloomed the release repository, hopefully this won't cause any problems. smile
> 
> I would recommend not modifying that value at all. Most packages released via bloom that do anything other than very standard ROS releases will require a few revisions and package revisions are a normal part of the workflow. You cannot change that value without changing the contents of the release which means that fixes made since the first revision will no longer be present.
> 
> If you make a follow up release, please preserve the release increment as-is. Failing to do so will likely create broken packages.

Will do, thank you for your kind reminder.

2022-12-21 23:16 UTC, sloretz approved these changes
Tag ending in deb inc of `1` seems to have the exec_depend on `catkin` now, so this looks good to me if it looks ok to @nuclearsandwich too

https://github.com/yakunouyang/casadi-release/blob/657ca77de0c66cb58dc0cc95e516208ee985d3c4/package.xml#L13

2023-01-26 01:11 UTC, nuclearsandwich commented
> Tag ending in deb inc of `1` seems to have the exec_depend on `catkin` now, so this looks good to me if it looks ok to @nuclearsandwich too
> 
> https://github.com/yakunouyang/casadi-release/blob/ros-noetic-casadi_3.5.5-1_focal/package.xml#L13

The above link has an apparent typo but likely refers to https://github.com/yakunouyang/casadi-release/blob/debian/ros-noetic-casadi_3.5.5-1_focal/package.xml#L13 ([permalink](https://github.com/yakunouyang/casadi-release/blob/657ca77de0c66cb58dc0cc95e516208ee985d3c4/package.xml#L13))

I agree that it looks alright there but I think that it would be best for @yakunouyang to close this PR and run a full bloom-release without changing the release increment to make sure that bloom is configured correctly for this repository.

2023-01-27 09:02 UTC, closed without merging