VDA 5050 Connector for mobile transport robots in intralogistics
ros/rosdistro pull request #35675
Opened 2022-12-20 13:33 UTC by frothm

# Please Add This Package to be indexed in the rosdistro.

melodic vda5050_connector
noetic vda5050_connector

# The source is here:

http://sourcecode_url

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-01-02 18:12 UTC, clalancette requested changes

2023-01-02 18:12 UTC, clalancette commented on melodic/distribution.yaml
> +      version: v0.0.3
The version listed here needs to be a branch, not a tag.  CI will fail if this is not a branch.  Same goes for all of the instances below.

2023-01-23 16:08 UTC, clalancette commented
No response in 3 weeks, so closing.  Feel free to respond to the comments and open the PR again.

2023-01-23 16:08 UTC, closed without merging

2023-02-03 16:06 UTC, frothm commented
Sorry for the late response. I have changed the version tags to version branches now.