Add python3-parse
ros/rosdistro pull request #35688
Opened 2022-12-21 11:09 UTC by ggorjup

Please add the following dependency to the rosdep database.

## Package name:

`parse`

## Package Upstream Source:

Repository: https://github.com/r1chardj0n3s/parse

## Purpose of using this:

Parse strings using a specification based on the Python format() syntax.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?keywords=python3-parse
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?keywords=python3-parse
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-parse/python3-parse
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/community/any/python-parse/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/parse
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/python3-parse

2022-12-22 02:05 UTC, tfoote approved these changes
Thanks yes. We should use the native packages not the pip ones.

Thanks for doing the research to fill in all the platforms

2022-12-22 13:42 UTC, clalancette requested changes
It looks like there is a RHEL package that would fit here as well.  Once that is added, I'm happy to approve this.

2022-12-22 14:27 UTC, ggorjup commented
@clalancette thanks for the suggestion.

I've searched for the package on https://access.redhat.com/downloads/content/package-browser but it doesn't pop up.
(Followed from the answer [here](https://unix.stackexchange.com/questions/6864/how-to-search-for-official-rhel-packages).)

Is there an alternative package list for RHEL that I can check?

2023-01-02 18:07 UTC, clalancette commented
Sorry for the delay.

It looks like that package is listed in https://ftp-osl.osuosl.org/pub/fedora-epel/8/Everything/x86_64/Packages/p/ (which is where the automation found it).  But that is kind of an unusual place to find it; @cottsay , can you suggest whether that is an appropriate suggestion?

2023-01-02 19:19 UTC, cottsay commented
>  But that is kind of an unusual place to find it; cottsay , can you suggest whether that is an appropriate suggestion?

When we were having trouble hitting the Fedora archive mirror, I updated the code to leverage mirror lists (#35237). It appears that it broke the association between the download URLs and the dashboards, so the code is dumping the package URL as a fallback.

It's a completely appropriate suggestion, we'll just have to look it up on packages.fedoraproject.org manually: https://packages.fedoraproject.org/pkgs/python-parse/python3-parse/

2023-01-03 09:15 UTC, ggorjup commented
Thank you for the links.

However, it seems that the linked packages are for the Fedora distribution, which is already included in the PR.
It says [here](https://www.redhat.com/en/topics/linux/fedora-vs-red-hat-enterprise-linux) that Fedora "is the upstream, community distro of RHEL", but rosdep entries for RHEL seem to be different from Fedora entries. For example, a Fedora entry is `python3-<package>` and a RHEL entry is `python%{python3_pkgversion}-<package>`.

Am I missing something here?
Can I just add an entry like `python%{python3_pkgversion}-parse` for RHEL based on the Fedora link?

2023-01-03 15:51 UTC, clalancette commented
> However, it seems that the linked packages are for the Fedora distribution, which is already included in the PR.

The RHEL packages come from EPEL, which is technically part of Fedora.  If you click on https://packages.fedoraproject.org/pkgs/python-parse/python3-parse/ , you'll see entries for Fedora as well as EPEL 8 and EPEL 9.

So what we should add here is just an entry for RHEL:

```
[rhel]: [python3-parse]
```

2023-01-03 18:46 UTC, cottsay commented
It's worth noting that the `python36-foo` packages in EPEL 7 should be providing a `python3-foo` virtual package for compatibility in scenarios like this. EPEL 8 and 9 name the packages `python3-foo` and don't really need `%{python3_pkgversion}` like that.

All that said, this package isn't available for RHEL 7 at all, so it will need to be excluded. I'd propose this:
```yaml
  rhel:
    '*': [python3-parse]
    '7': null
```

2023-01-04 11:20 UTC, ggorjup commented
Thank you for the explanation and suggestions, I've updated the PR.

2023-01-04 13:43 UTC, clalancette approved these changes
Looks good to me.  Thanks for the iteration, @ggorjup !

2023-01-04 13:43 UTC, merged