Added openai python
ros/rosdistro pull request #35708
Opened 2022-12-28 20:38 UTC by davesarmoury

Please add the following dependency to the rosdep database.

## Package name:

openai

## Package Upstream Source:

https://github.com/openai/openai-python

## Purpose of using this:

This dependency allows access to OpenAI's servers for off-robot AI processing

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - pip
    - https://pypi.org/project/openai/
- Ubuntu: https://packages.ubuntu.com/
  - pip
    - https://pypi.org/project/openai/
- Fedora: https://packages.fedoraproject.org/
  - pip
    - https://pypi.org/project/openai/

2023-01-02 17:51 UTC, clalancette requested changes

2023-01-02 17:51 UTC, clalancette commented on rosdep/python.yaml
> +openai:
The name of this key should be:

```suggestion
python3-openai-pip:
```

2023-01-06 22:15 UTC, methylDragon approved these changes

2023-01-13 22:18 UTC, tfoote approved these changes

2023-01-13 22:19 UTC, tfoote requested changes

2023-01-13 22:19 UTC, tfoote commented on rosdep/python.yaml
> +python3-openai-pip:
With the rename it's out of alphabetical order.

2023-01-18 14:36 UTC, clalancette commented
Totally unrelated to the contents of this PR, this needs a rebase.  If you could rebase this onto the latest, then we can get CI to pass.  Sorry for the inconvenience.

2023-01-18 14:36 UTC, clalancette approved these changes

2023-01-18 14:48 UTC, davesarmoury commented
@clalancette  Rebased

2023-01-18 14:56 UTC, clalancette requested changes

2023-01-18 14:56 UTC, clalancette commented on rosdep/python.yaml
> +python3-openai-pip:
Oh, right.  This key also needs to move to be among the `python3-` section, otherwise it is out-of-order alphabetically.

2023-01-18 15:08 UTC, clalancette approved these changes

2023-01-18 15:09 UTC, merged