Add libboost-coroutine(-dev) to rosdep
ros/rosdistro pull request #35789
Opened 2023-01-09 09:54 UTC by BartKeulen

Please add the following dependency to the rosdep database.

## Package name:

- libboost-coroutine
- libboost-coroutine-dev

## Package Upstream Source:

- https://github.com/boostorg/coroutine

## Purpose of using this:

Useful when you only want to install the boost coroutine library and not the full boost library.

## Links to Distribution Packages

### libboost-coroutine
- Debian:
  - Bullseye: https://packages.debian.org/bullseye/libboost-coroutine1.74.0
  - Buster: https://packages.debian.org/buster/libboost-coroutine1.67.0
- Fedora: https://packages.fedoraproject.org/pkgs/boost/boost-coroutine/
- Gentoo: https://packages.gentoo.org/packages/dev-libs/boost
- NixOS: https://search.nixos.org/packages?channel=22.11&show=boost&from=0&size=50&sort=relevance&type=packages&query=boost
- openSUSE: https://software.opensuse.org/package/libboost_coroutine1_66_0
- RHEL: https://pkgs.org/search/?q=boost-coroutine
- Ubuntu:
  - Bionic:  https://packages.ubuntu.com/bionic/libboost-coroutine1.65.1
  - Eoan: https://packages.ubuntu.com/eoan/libboost-coroutine1.67.0 (EOL)
  - Focal: https://packages.ubuntu.com/focal/libboost-coroutine1.71.0
  - Jammy: https://packages.ubuntu.com/jammy/libboost-coroutine1.74.0
  - Xenial: https://packages.ubuntu.com/xenial/libboost-coroutine1.58.0 (EOL)

### libboost-coroutine-dev
- Debian: 
  - Bullseye: https://packages.debian.org/bullseye/libboost-coroutine-dev
  - Buster:  https://packages.debian.org/buster/libboost-coroutine-dev
- Fedora: https://packages.fedoraproject.org/pkgs/boost/boost-devel/
- Gentoo: https://packages.gentoo.org/packages/dev-libs/boost
- NixOS: https://search.nixos.org/packages?channel=22.11&show=boost&from=0&size=50&sort=relevance&type=packages&query=boost
- openSUSE: https://software.opensuse.org/package/libboost_coroutine1_66_0-devel?search_term=libboost_coroutine1_66_0-devel
- RHEL: https://pkgs.org/search/?q=boost-devel
- Ubuntu: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libboost-coroutine-dev&searchon=names

2023-01-13 22:26 UTC, tfoote requested changes, later dismissed
Thanks for the contribution. Please resolve the RHEL 7 linter error then it lgtm.

2023-01-13 22:26 UTC, tfoote commented on rosdep/base.yaml
> +  rhel: [boost-coroutine]
```suggestion
  rhel:
    '*': [boost-coroutine]
    '7': null
```

Nulling out RHEL 7 as caught by the linters.

2023-01-26 01:24 UTC, nuclearsandwich commented
@BartKeulen is this PR something you are still interested in? If not can it be closed?

2023-02-13 09:50 UTC, BartKeulen commented
> @BartKeulen is this PR something you are still interested in? If not can it be closed?

Yes, I am still interested. Apologies it took a while.

2023-02-15 18:22 UTC, emersonknapp approved these changes
This looks good now, thanks for the followup

2023-02-15 19:03 UTC, emersonknapp requested changes
One more quick addition for Alpine should make the tests happi

2023-02-15 19:03 UTC, emersonknapp commented on rosdep/base.yaml
> +  debian:
```suggestion
libboost-coroutine:
  alpine: [boost-dev]
  debian:
```

2023-02-15 19:03 UTC, emersonknapp commented on rosdep/base.yaml
> +  debian: [libboost-coroutine-dev]
```suggestion
  alpine: [boost-dev]
  debian: [libboost-coroutine-dev]
```

2023-02-17 17:13 UTC, emersonknapp approved these changes

2023-02-21 13:54 UTC, mjcarroll approved these changes

2023-02-21 13:54 UTC, merged