behaviortree_cpp: 3.8.2-1 in 'rolling/distribution.yaml' [manual]
ros/rosdistro pull request #35800
Opened 2023-01-10 09:31 UTC by facontidavide

Increasing version of package(s) in repository behaviortree_cpp to 3.8.2-1

Done manually to fix other issues

2023-01-10 19:24 UTC, facontidavide commented
Does that repo even exist? I can't find it

On Tue, Jan 10, 2023, 8:06 PM Chris Lalancette ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In rolling/distribution.yaml
> <https://github.com/ros/rosdistro/pull/35800#discussion_r1066198270>:
>
> >        tags:
>          release: release/rolling/{package}/{version}
> -      url: https://github.com/ros2-gbp/behaviortree_cpp-release.git
> -      version: 3.8.0-1
> +      url: https://github.com/BehaviorTree/behaviortree_cpp_v3-release.git
>
> Are you sure you want to move this back out of the ros2-gbp repository?
> It's allowed, but it also means that this package won't be automatically
> released into Iron when we branch off.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ros/rosdistro/pull/35800#pullrequestreview-1242812171>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVRF2EVBH7IBEGZ245R723WRWXKRANCNFSM6AAAAAATWPMTAU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-11 09:06 UTC, tfoote requested changes
It would be much better to use the ros2-gbp in general, we generally insist for rolling releases.  Otherwise as Chris mentions it will get dropped from rolling the next time that we migrate platforms or fork a new release (Iron is pending soon)

2023-01-11 13:32 UTC, facontidavide commented
ok, let me fix that

2023-01-11 20:54 UTC, tfoote commented
I wouldn't recommend making a new one for v3 and then continuing to use the default for v4. The contents of the repository are already there with the full history of v3 so making a new one for the latest release will just be confusing as all the old releases will still be in the original repository. And moving the existing repo isn't recommended as it will break any cache dreferences. 

So to that end I'd recommend just using the same release repository and then everything will be in one place. That repo already has the full history of v2 and v3 releases now it will have v4 as well. 

My alternative to that would be to make a new release repo `_v4` which would have the new series. But unless we're running out of storage or anything like that I'd suggest just sticking to the single repository. 

For reference to get a new repository you can request that yourself by opening a PR to extend this list: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/bd80f85c71856bee7499b5e4838f71e34097ec0b/behaviortree.tf#L6

But again I'd strongly suggest just leveraging the existing repository which already has the history until it gets too large and then we just leave it for archival purposes and make a new one.

2023-01-13 22:03 UTC, tfoote approved these changes
Thanks for the adjustment in plan. I've pinged Steven about the new repo creation.

2023-01-13 22:03 UTC, merged