Added package python-mistune
ros/rosdistro pull request #35838
Opened 2023-01-12 04:52 UTC by peci1

Please add the following dependency to the rosdep database.

## Package name:

python-mistune

## Package Upstream Source:

https://github.com/lepture/mistune

## Purpose of using this:

Markdown parser, useful for documentation tools.

## Links to Distribution Packages

- Debian: https://packages.debian.org/buster/python-mistune
- Ubuntu: https://packages.ubuntu.com/bionic/python-mistune
- Fedora: https://packages.fedoraproject.org/pkgs/python-mistune/python3-mistune/
- Arch: https://archlinux.org/packages/community/any/python-mistune/
- Gentoo: https://packages.gentoo.org/packages/dev-python/mistune
- macOS: not available (via [pip](https://pypi.org/project/mistune/))
- Alpine: not available (via [pip](https://pypi.org/project/mistune/))
- NixOS/nixpkgs: https://search.nixos.org/packages?channel=22.11&show=m2r&from=0&size=50&sort=relevance&type=packages&query=mistune
- openSUSE: https://software.opensuse.org/package/python3-mistune

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-01-13 22:23 UTC, tfoote requested changes
Please update this to be python3 primary. And if you need it on python2 create a separate rule. but if you're not needing that I'd suggest skipping that.

2023-01-13 22:23 UTC, tfoote commented on rosdep/python.yaml
> +    bionic: [python-mistune]
We shouldn't be mixing python2 and 3 rules. here.

2023-01-13 22:23 UTC, tfoote commented on rosdep/python.yaml
> +python-mistune:
Most of these are python 3 rules so I'd suggest that this be python3-mistune

For the older releases we can backfill pip for python3 (aka bionic and buster) 

And with that we'd call this python3-mistune

In general we're expecting all python 2 rules to eventually disappear as python2 is now strongly deprecated.

2023-01-15 14:14 UTC, peci1 commented
Okay, I've split the rules for py2 and py3. I have a use for it on Melodic which requires the py2 version, so I need both rules.

2023-01-17 23:28 UTC, tfoote approved these changes
Great thanks for splitting it out. 

If you have a moment to add the suggested 'rhel' target from the linter for python3-mistune before the 2nd review that would be great.

2023-01-18 14:25 UTC, clalancette approved these changes

2023-01-18 14:26 UTC, merged