add rosdep package libadolc-dev
ros/rosdistro pull request #36016
Opened 2023-02-01 12:08 UTC by yakunouyang

Please add the following dependency to the rosdep database.

## Package name: libadolc-dev

## Package Upstream Source:

https://github.com/coin-or/adol-c

## Purpose of using this:

This dependency is being used for automatic differentiation along with [IPOPT](https://github.com/coin-or/Ipopt) in optimal control applications.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/libadolc-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?searchon=names&keywords=libadolc-dev
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - https://aur.archlinux.org/packages/adol-c
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/sci-libs/adolc
- macOS: https://formulae.brew.sh/
  - https://github.com/brewsci/homebrew-science/blob/master/Formula/adol-c.rb
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=22.11&show=adolc&from=0&size=50&sort=relevance&type=packages&query=adolc
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/adolc

2023-02-02 22:58 UTC, sloretz approved these changes

2023-02-15 18:08 UTC, yakunouyang commented
Hi, just want to check in and see if there are any updates @sloretz

2023-02-15 20:04 UTC, emersonknapp requested changes
Sorry for the slow turnaround there. I noticed that there's a typo `debain` which should be `debian`. I've left the suggestion inline, and an `opensuse` addition which is optional but recommended. If that's all right, go ahead and commit them, then we can move forward.

2023-02-15 20:04 UTC, emersonknapp commented on rosdep/base.yaml
> +  debain: [libadolc-dev]
```suggestion
  debian: [libadolc-dev]
```

2023-02-15 20:04 UTC, emersonknapp commented on rosdep/base.yaml
> +  nixos: [adolc]
```suggestion
  nixos: [adolc]
  opensuse: [adolc-devel]
```

2023-02-16 09:25 UTC, yakunouyang commented
fixed, sorry for the typo :smiling_face_with_tear:

2023-02-17 05:07 UTC, emersonknapp approved these changes

2023-02-21 13:55 UTC, mjcarroll approved these changes

2023-02-21 13:56 UTC, merged