Ubuntu jammy entry for python3-udev
ros/rosdistro pull request #36076
Opened 2023-02-09 01:39 UTC by boilerbots

## Package name:

python3-dev

## Package Upstream Source:

https://packages.ubuntu.com/source/jammy/pyudev

## Purpose of using this:

Adding an entry for Ubuntu jammy so the default "python-udev" is not used.

## Links to Distribution Packages

https://packages.ubuntu.com/jammy/python3-pyudev

2023-02-10 02:59 UTC, SteveMacenski commented
@clalancette this is a bit of an odd situation - how is this handled with the others having `_python3` ?

2023-02-10 14:43 UTC, clalancette commented
> @clalancette this is a bit of an odd situation - how is this handled with the others having `_python3` ?

Right, good question.  The `_python3` keys are a historical artifact, and we shouldn't add new ones anymore[1].

Instead, what we should do here is to add an entirely new key called `python3-pyudev`, and populate it with the python3 keys.  It will look something like:

```
python3-pyudev:
  debian: [python3-pyudev]
  fedora: [python3-pyudev]
  gentoo: [dev-python/pyudev]
  nixos: [pythonPackages.pyudev]
  ubuntu: [python3-pyudev]
```

The `python-pyudev` key can remain as-is, mostly for Python 2 and legacy purposes.

[1] The history is that these were our first attempt to handle Python 3 keys alongside Python 2 ones.  But we found that this didn't work well, so we switched to the system we use today.

2023-02-10 18:06 UTC, SteveMacenski commented
@boilerbots can you update accordingly?

2023-02-14 18:36 UTC, boilerbots commented
Yes let me rework this.

2023-02-15 20:12 UTC, emersonknapp requested changes
This looks good now, except that the new key is now not in alphabetical order. It'll need to go down in the `python3-` area. Output from tests:

> list out of alphabetical order line 4091.  'python-pyusb-pip' should come before 'python3-pyudev'

2023-02-15 21:38 UTC, boilerbots commented
Hope I didn't break this, I rebased my branch to keep up with the changes.

2023-02-15 22:46 UTC, emersonknapp approved these changes
LGTM - I might suggest adding `rhel` and `opensuse` as per automated suggestions, but it's not required.

2023-02-15 23:55 UTC, boilerbots commented
sorry I don't want to keep touching these files.

2023-02-17 05:03 UTC, emersonknapp commented
@mjcarroll i think we just need another set of eyes on this one

2023-02-21 13:56 UTC, mjcarroll approved these changes

2023-02-21 13:56 UTC, merged