quaternion_operation: 0.0.12-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #36190
Opened 2023-02-14 17:48 UTC by hakuturu583

Increasing version of package(s) in repository `quaternion_operation` to `0.0.12-1`:

- upstream repository: https://github.com/OUXT-Polaris/quaternion_operation.git
- release repository: https://github.com/ros2-gbp/quaternion_operation-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `0.0.7-2`

## quaternion_operation

```
* add header file (#63 <https://github.com/OUXT-Polaris/quaternion_operation/issues/63>)
* Setup workflow (#62 <https://github.com/OUXT-Polaris/quaternion_operation/issues/62>)
* [Bot] Update workflow (#61 <https://github.com/OUXT-Polaris/quaternion_operation/issues/61>)
  * Setup workflow
  * empty commit
  Co-authored-by: Masaya Kataoka <mailto:ms.kataoka@gmail.com>
* Contributors: Masaya Kataoka, wam-v-tan
```

2023-02-14 17:55 UTC, SteveMacenski approved these changes

2023-02-15 20:45 UTC, emersonknapp commented
More specifically, `quaternion_operation: doc: version:` is currently `master`, but this branch doesn't exist on the source repo anymore. If you update this to be `ros2` it should solve the issue

2023-02-15 20:46 UTC, emersonknapp requested changes
More specifically, `quaternion_operation: doc: version:` is currently `master`, but this branch doesn't exist on the source repo anymore. If you update this to be `ros2` it should solve the issue

2023-02-17 02:07 UTC, hakuturu583 commented
Thanks!

2023-02-17 02:07 UTC, closed without merging