Segno has to be added as a pip package for focal and bionic
ros/rosdistro pull request #36417
Opened 2023-03-08 08:28 UTC by gv11181989

Please modify the following dependency to the rosdep database to add it as a pip package  for focal and bionic.

Package name:
Segno

Package Upstream Source:
https://github.com/heuer/segno

Purpose of using this:
Pure Python QR Code generator with no dependencies

Links to Distribution Packages
Debian: https://packages.debian.org/bullseye/python3-segno
Ubuntu: https://packages.ubuntu.com/jammy/python3-segno

2023-03-09 01:43 UTC, adityapande-1995 requested changes
The review guidelines strongly suggest preffering system packages over pip, is there a specific reason for preferring  pip in this case ? cc @mjcarroll

2023-03-09 08:14 UTC, gv11181989 commented
> The review guidelines strongly suggest preffering system packages over pip, is there a specific reason for preferring pip in this case ? cc @mjcarroll

Segno has to added as a pip package for focal as there is no debian release for it.

2023-03-10 21:04 UTC, mjcarroll commented
If there is no debian release, then this is fine.  Be aware that no other debian releases built in the buildfarm can depend on this rosdep keys.

2023-03-10 21:04 UTC, mjcarroll approved these changes

2023-03-13 17:57 UTC, adityapande-1995 approved these changes

2023-03-13 17:57 UTC, merged