Update python-bottle definition for ubuntu focal
ros/rosdistro pull request #36469
Opened 2023-03-14 14:10 UTC by jibweb

Please update the following dependency to the rosdep database: python-bottle

## Package name:

python-bottle

## Package Upstream Source:

System package update for ubuntu

## Purpose of using this:

python-bottle key is already defined in the list, but the package it points to is no longer available on ubuntu focal 

## Links to Distribution Packages

- Ubuntu:
   - https://packages.ubuntu.com/kinetic/python3-bottle
   
# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-03-14 19:41 UTC, clalancette requested changes

2023-03-14 19:41 UTC, clalancette commented on rosdep/python.yaml
> +    'focal': [python3-bottle]
We shouldn't make this change here, as the `python-` keys are implicitly for Python 2.

Instead, what we should do is to add in a new key which is `python3-bottle`, and then add in the python3 package entries as appropriate.

2023-03-15 09:12 UTC, jibweb commented
Does that look more appropriate then ?

2023-03-15 13:36 UTC, clalancette approved these changes

2023-03-16 18:16 UTC, audrow approved these changes

2023-03-16 18:16 UTC, merged