marker_msgs: 0.0.8-2 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #36519
Opened 2023-03-19 15:29 UTC by maxbader

Increasing version of package(s) in repository `marker_msgs` to `0.0.8-2`:

- upstream repository: https://github.com/tuw-robotics/marker_msgs.git
- release repository: https://github.com/tuw-robotics/marker_msgs-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## marker_msgs

```
* updated for ros2
* Update MarkerDetection.msg
* Update README.md
* Create README.md
* Contributors: Markus Bader
```

2023-03-20 14:33 UTC, clalancette requested changes

2023-03-20 14:33 UTC, clalancette commented on humble/distribution.yaml
> +    release:
Would you like to add a `doc` and a `source` section here?  That was done for all ROS 1 releases, e.g. https://github.com/ros/rosdistro/blob/57b8bfd2d425aeba494a33b3834af10e9dbefc21/noetic/distribution.yaml#L4948-L4962

2023-03-20 19:01 UTC, maxbader commented
I can make a new merge request also for the other requests.

2023-03-24 01:31 UTC, quarkytale commented
Continued in https://github.com/ros/rosdistro/pull/36557

2023-03-24 01:31 UTC, closed without merging