[python.yaml] add pip package pypdf
ros/rosdistro pull request #36590
Opened 2023-03-24 14:16 UTC by tlipps

Please add the following dependency to the rosdep database.

## Package name:

pypdf

## Package Upstream Source:

https://github.com/py-pdf/pypdf

## Purpose of using this:

pypdf is a free and open-source pure-python PDF library capable of splitting, [merging](https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html), [cropping, and transforming](https://pypdf.readthedocs.io/en/stable/user/cropping-and-transforming.html) the pages of PDF files. It can also add custom data, viewing options, and [passwords](https://pypdf.readthedocs.io/en/stable/user/encryption-decryption.html) to PDF files. pypdf can [retrieve text](https://pypdf.readthedocs.io/en/stable/user/extract-text.html) and [metadata](https://pypdf.readthedocs.io/en/stable/user/metadata.html) from PDFs as well.

In our case it is utilized to visualize and save ROS data. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - NOT AVAILABLE (via [pip](https://pypi.org/project/pypdf/))
- Ubuntu: https://packages.ubuntu.com/
  - NOT AVAILABLE (via [pip](https://pypi.org/project/pypdf/))
- Fedora: https://packages.fedoraproject.org/
  - NOT AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - NOT AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - INOT AVAILABLE
- macOS: https://formulae.brew.sh/
  - NOT AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - NOT AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - NOT AVAILABLE
- openSUSE: https://software.opensuse.org/package/
  - NOT AVAILABLE

2023-03-24 23:51 UTC, tfoote requested changes
I found https://packages.ubuntu.com/lunar/python3-pypdf2 

We can't accept this as a pip rule. It's already packaged generally upstream and the pip installation would conflict and override the system version. 

If you'd like to research and submit an entry using the system dependencies we'd be happy to review that. 

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules

2023-03-27 10:42 UTC, tlipps commented
> I found https://packages.ubuntu.com/lunar/python3-pypdf2
> 
> We can't accept this as a pip rule. It's already packaged generally upstream and the pip installation would conflict and override the system version.
> 
> If you'd like to research and submit an entry using the system dependencies we'd be happy to review that.
> 
> https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules

There are two different `pypdf` packages upstream: `python3-pypdf` and `python3-pypdf2`. The package `python3-pypdf2` contains older versions of `pypdf`: 1.26, 2.10 for ubuntu 18 to 23 , which are very different from the current pip version `pypdf` (3.7.0): 

Quoting from `pypdf`'s GitHub: 
> `NOTE: pypdf>=3.1.0 improved a lot compared to pyPdf<2.0.0 and compared to PyPDF2 < 2.0.0. Please read [the migration guide](https://pypdf.readthedocs.io/en/latest/user/migration-1-to-2.html).` 

So I do not see a reason to create a PR for `python3-pypdf2`, since it is pretty much outdated.

But there still exists a second package called `python3-pypdf` for lunar, which has no ROS build. So I can change it to `python3-pypdf` (referring to https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-mixed-with-system-packages ) instead of `python3-pypdf-pip` but it will only contain pip packages.

2023-03-29 12:39 UTC, tlipps commented
> Sorry I assumed pypdf2 was newer than pypdf without looking closer.
> 
> I see that pypdf is in debian as of bookworm too: https://packages.debian.org/bookworm/python3-pypdf
> 
> Please do update it to be lunar and bookworm for the newer platforms and pip for backfilling. These rules will persist long into the future so we need to make sure that we are converging on the native packages.

Done.

2023-03-29 23:48 UTC, tfoote approved these changes
Thanks for the update, this now meets the minimum of debian and ubuntu. Is there a package for fedora/rhel or anything else yet?

2023-03-30 10:03 UTC, tlipps commented
> Thanks for the update, this now meets the minimum of debian and ubuntu. Is there a package for fedora/rhel or anything else yet?

Found something on gentoo, but otherwise no.

2023-04-01 00:14 UTC, tfoote approved these changes

2023-04-04 15:09 UTC, cottsay approved these changes

2023-04-04 15:09 UTC, merged