pal_navigation_cfg_public: 3.0.1-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #36692
Opened 2023-04-04 11:06 UTC by Noel215

Increasing version of package(s) in repository `pal_navigation_cfg_public` to `3.0.1-1`:

- upstream repository: https://github.com/pal-robotics/pal_navigation_cfg_public.git
- release repository: https://github.com/pal-gbp/pal_navigation_cfg_public-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## pal_navigation_cfg

```
* init ROS2 migration
* Contributors: antoniobrandi
```

## pal_navigation_cfg_bringup

```
* Merge branch 'fix/unify-nav' into 'humble-devel'
  unify nav launch files
  See merge request navigation/pal_navigation_cfg_public!45
* unify nav launch files
* added default parameters and launch files
* init ROS2 migration
* Contributors: antoniobrandi
```

## pal_navigation_cfg_params

```
* added default parameters and launch files
* init ROS2 migration
* Contributors: antoniobrandi
```

2023-04-04 15:25 UTC, nuclearsandwich commented
New package review:

- [ ] At least one of the following must be present
  - [ ] Top level license file: 
  - [ ] Per package license files
- [ ] License is [OSI-approved](https://opensource.org/licenses): Proprietary
- [ ] License correctly listed in package.xmls
  - [ ] pal_navigation_cfg: https://github.com/pal-robotics/pal_navigation_cfg_public/blob/humble-devel/pal_navigation_cfg_public/package.xml#L7
  - [ ] pal_navigation_cfg_bringup: https://github.com/pal-robotics/pal_navigation_cfg_public/blob/humble-devel/pal_navigation_cfg_bringup/package.xml#L7
  - [ ] pal_navigation_cfg_params: https://github.com/pal-robotics/pal_navigation_cfg_public/blob/humble-devel/pal_navigation_cfg_params/package.xml#L7
- [x] Public source repo: https://github.com/pal-robotics/pal_navigation_cfg_public/tree/humble-devel
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] pal_navigation_cfg
  - [ ] pal_navigation_cfg_bringup
  - [ ] pal_navigation_cfg_params

2023-04-04 15:51 UTC, nuclearsandwich requested changes, later dismissed
@Noel215 this package is currently missing license terms and the packaeg.xml license lines are all listed as `Proprietary`. Is that intended? At the very least the license terms need to be present for review of this pull request to proceed but it is worth noting that the ROS build farm is primarily set up to build and distribute open source packages.

2023-04-04 16:13 UTC, Noel215 commented
> @Noel215 this package is currently missing license terms and the packaeg.xml license lines are all listed as `Proprietary`. Is that intended? At the very least the license terms need to be present for review of this pull request to proceed but it is worth noting that the ROS build farm is primarily set up to build and distribute open source packages.

It's a mistake, I'll fix it. What about the naming conventions? I cannot see what is wrong

2023-04-05 07:55 UTC, Noel215 commented
Licensing issues are fixed :)

2023-04-05 19:42 UTC, emersonknapp approved these changes
I checked off the clear stuff in the review checklist, licensing all looks good. And the names seem REP-144 compliant to me, so I'm giving my one signoff on this

2023-04-13 16:56 UTC, nuclearsandwich approved these changes
Thanks for iterating!

2023-04-13 16:56 UTC, merged