Add debian bookworm packages
ros/rosdistro pull request #36714
Opened 2023-04-06 07:35 UTC by mosfet80

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-04-06 19:40 UTC, emersonknapp approved these changes

2023-04-11 20:08 UTC, emersonknapp commented on rosdep/base.yaml
> +
```suggestion
    bookworm: [libogre-1.12-dev]
```

2023-04-13 16:59 UTC, nuclearsandwich commented
@mosfet80 can you please fill out the pull request template with some basic details and intent. Since the changes are all updates to existing keys it's not an impossible review but it is made more challenging by the lack of information in the PR description.

2023-04-13 17:02 UTC, nuclearsandwich requested changes
There are issues in the PR checks to address before this is ready to review.

2023-04-14 17:03 UTC, nuclearsandwich submitted a review, later dismissed
Thank you for iterating on the PR description. I made some additional formatting and phrasing edits to it and it is now in much better shape.

Can you please address the issues reported in the CI checks. For example:
```
 checking for item order...
  ERR: list out of alphabetical order line 1969.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2076.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2634.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2669.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2778.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2810.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 2913.  'bookworm' should come before 'buster'
  ERR: list out of alphabetical order line 4410.  'bookworm' should come before 'wheezy'
  ```

2023-05-15 16:57 UTC, clalancette approved these changes

2023-05-15 16:57 UTC, merged