Adding libdw to osx
ros/rosdistro pull request #36753
Opened 2023-04-11 05:16 UTC by CursedRock17

This PR aims to add the libdw dependency to osx via homebrew

## Package name:

libdw

## Package Upstream Source:

https://sourceware.org/elfutils/

## Purpose of using this:

This dependency is already needed in packages like backward_ros and is being used on other OS like ubuntu. While it at first seems misleading that it brews with the entire elfutils library instead of just libdw, ubuntu currently uses the exact same tar.bz file via apt that macos would use the homebrew. If needing reference [osx](https://github.com/Homebrew/homebrew-core/blob/b3e60b5e8ef82db4e226184552568c6820a26e14/Formula/elfutils.rb) and [ubuntu](https://packages.ubuntu.com/kinetic/libdw-dev)

- macOS: https://formulae.brew.sh/formula/elfutils#default

2023-04-15 00:59 UTC, nuclearsandwich requested changes
@CursedRock17 it took a few reviews for my macOS memories to come back to me, but our preference for osx/homebrew rosdep keys is now to maintain them in base.yaml and python.yaml alongside the other platforms so that it's easier to track them. Even python.yaml itself may eventually get merged back into base.yaml.

Could you please move this definition into the libdw-dev key in base.yaml.

2023-04-15 02:28 UTC, CursedRock17 commented
Should all definitions related to homebrew have the osx version completely moved into the python.yaml and base.yaml files? Or can they sit in both?

2023-04-18 13:53 UTC, nuclearsandwich requested changes, later dismissed

2023-04-18 13:53 UTC, nuclearsandwich commented on rosdep/osx-homebrew.yaml
> +      packages: [elfutils]
```suggestion
```

This section is spurious ad the cause of the failures in CI checks.

2023-05-02 15:50 UTC, adityapande-1995 approved these changes

2023-05-02 21:21 UTC, mjcarroll approved these changes

2023-05-02 21:22 UTC, mjcarroll commented
@nuclearsandwich any other issues here?

2023-05-15 17:01 UTC, clalancette approved these changes

2023-05-15 17:01 UTC, merged