Added range-v3 to OSX
ros/rosdistro pull request #36752
Opened 2023-04-11 04:31 UTC by CursedRock17

This PR looks to add the range-v3 homebrew formula to OSX

## Package name:

range-v3

## Package Upstream Source:

https://ericniebler.github.io/range-v3/

## Purpose of using this:

There are other packages that need this package as there is already a section for it in Ubuntu and others, since there was a homebrew package already, this can be added.

- macOS: https://formulae.brew.sh/formula/range-v3#default

2023-04-15 00:54 UTC, nuclearsandwich commented on rosdep/osx-homebrew.yaml
> +      packages: []
Is this package list intended to be empty?

2023-04-15 01:01 UTC, nuclearsandwich requested changes
Please move this definition to the existing key in base.yaml.

See the review comment in https://github.com/ros/rosdistro/pull/36753#pullrequestreview-1386282809 for rationale.

2023-04-18 13:52 UTC, nuclearsandwich submitted a review, later dismissed

2023-04-18 13:52 UTC, nuclearsandwich commented on rosdep/osx-homebrew.yaml
> +      packages: []
```suggestion
```

This section is spurious and the cause of the failed checks in CI

2023-05-03 18:45 UTC, adityapande-1995 approved these changes

2023-05-03 21:12 UTC, merged