Adding fmt on osx
ros/rosdistro pull request #36750
Opened 2023-04-11 03:31 UTC by CursedRock17

Adding fmt to the osx homebrew base of rosdep because ubuntu already has access to this, while osx still needs it.

## Package name:

fmt

## Package Upstream Source:

[TODO link to source repository](https://fmt.dev/latest/index.html)

## Purpose of using this:

fmt is required by many packages such as parameter_traits and ubuntu already uses it in their distribution, so since there's already a homebrew package it should be added.

- macOS: https://formulae.brew.sh/formula/fmt#default

2023-04-11 15:07 UTC, emersonknapp approved these changes

2023-04-15 01:00 UTC, nuclearsandwich requested changes
Please add this definition to the existing key in base.yaml rather than here. See the review comment on https://github.com/ros/rosdistro/pull/36753#pullrequestreview-1386282809 for rationale.

2023-04-18 13:48 UTC, nuclearsandwich requested changes, later dismissed
Thanks for iterating. CI is warning, correctly, of duplicate keys. The empty entry in the rosdep/osx-homebrew.yaml file is spurious. Prior iterations of rosdep maintenance tried to split files up for easier management but it is actually easier (at least for the current maintenance team) to keep all definitions for a key in one place.

2023-04-18 13:48 UTC, nuclearsandwich commented on rosdep/osx-homebrew.yaml
> +      packages: []
```suggestion
```

The changes here are unnecessary and can be dropped.

2023-04-18 15:11 UTC, CursedRock17 commented
I appreciate the explanations, I was wondering about package management and the practices this repository followed. I tried to follow other patterns in file after trying to search through the contributing guide. From now on I will attempt to make only clear definitions of packages and their requires.

2023-04-18 15:21 UTC, CursedRock17 commented
>Prior iterations of rosdep maintenance tried to split files up for easier management but it is actually easier (at least for the current maintenance team) to keep all definitions for a key in one place.

To extend on top of this would it make more sense to just move all definition of osx-homebrew.yaml into their respectable libraries in base.yaml. It would remove this file and prevent more of these duplication issues from happening. I know MacOS is tier 3, but if this is worth doing could I make a general, large PR moving everything over.

2023-05-15 16:59 UTC, clalancette approved these changes

2023-05-15 17:00 UTC, merged