Adding gpgme to OSX
ros/rosdistro pull request #36840
Opened 2023-04-13 03:56 UTC by CursedRock17

This PR adds the libgpgme-dev package to OSX via homebrew.

## Package name:

ibgpgme-dev

## Package Upstream Source:

https://www.gnupg.org/related_software/gpgme/

## Purpose of using this:

There are packages such as rosbag_storage which utilize this library and it is already included in linux builds, so since it's already on homebrew it's worth installing

- macOS: https://formulae.brew.sh/formula/gpgme#default

2023-04-15 01:07 UTC, nuclearsandwich requested changes
Please move this definition to the existing key in base.yaml.

See the review comment in https://github.com/ros/rosdistro/pull/36753#pullrequestreview-1386282809 for rationale.

2023-04-18 13:59 UTC, nuclearsandwich requested changes, later dismissed
Removing the empty definition from the osx-homebrew file should get this PR ready for approval.

2023-04-18 13:59 UTC, nuclearsandwich commented on rosdep/osx-homebrew.yaml
> +      packages: [gpgme]
```suggestion
```

This section is spurious and the cause of failed checks in CI.

2023-04-23 08:12 UTC, methylDragon approved these changes

2023-05-02 15:49 UTC, adityapande-1995 approved these changes

2023-05-15 17:01 UTC, clalancette approved these changes

2023-05-15 17:02 UTC, merged