dingo: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #36919
Opened 2023-04-20 22:12 UTC by tonybaltovski

Increasing version of package(s) in repository `dingo` to `0.3.1-1`:

- upstream repository: https://github.com/dingo-cpr/dingo.git
- release repository: https://github.com/clearpath-gbp/dingo-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `0.3.0-1`

## dingo_control

- No changes

## dingo_description

```
* Adding Sick TIM551 lidar
* Standard mounting locations persist in PACS
* Update README.md
* Update README
* Contributors: Hilary Luo, luis-camero
```

## dingo_msgs

- No changes

## dingo_navigation

- No changes

2023-04-23 08:25 UTC, methylDragon approved these changes

2023-04-23 08:26 UTC, methylDragon requested changes
Could you add a LICENSE files?

2023-04-24 12:56 UTC, tonybaltovski commented
Added here: https://github.com/dingo-cpr/dingo/commit/68806fdffabfd612a3414b7e8d6cb19c496f8a0e

2023-04-24 23:58 UTC, methylDragon approved these changes
Thanks!!

2023-04-24 23:58 UTC, merged