Adding flatbuffers as pip depdendency
ros/rosdistro pull request #36970
Opened 2023-04-26 13:00 UTC by ct2034

Please add the following dependency to the rosdep database.

## Package name:

flatbuffers

## Package Upstream Source:

https://github.com/google/flatbuffers

## Purpose of using this:

it is needed to decode the fbl logfiles of https://github.com/BehaviorTree/BehaviorTree.CPP

Distro packaging links:

## Links to Distribution Packages

There is no ubuntu package available, so I propose to use https://pypi.org/project/flatbuffers/

2023-04-26 23:17 UTC, tfoote requested changes, later dismissed
It looks like your last commit got a lot of extra content into it (~1300 extra lines from a merge potentially) Please clean it up for us to be able to review.

2023-04-27 13:53 UTC, ct2034 commented
Sorry for that, @tfoote. My yaml formatter must have a different idea about yaml formatting ;)

2023-05-02 15:42 UTC, adityapande-1995 requested changes
Could you also add the key ``python3-flatbuffers`` for opensuse and rhel ?
https://software.opensuse.org/package/python-flatbuffers
https://mirrors.lug.mtu.edu/epel/9/Everything/x86_64/Packages/p/python3-flatbuffers-2.0.8-2.el9.noarch.rpm

2023-05-02 22:45 UTC, clalancette requested changes, later dismissed

2023-05-02 22:45 UTC, clalancette commented on rosdep/python.yaml
> +        packages: [flatbuffers]
This should be before `focal` so they are in alphabetical order.

2023-05-03 12:54 UTC, mjcarroll approved these changes

2023-05-03 12:55 UTC, mjcarroll approved these changes

2023-05-03 18:42 UTC, adityapande-1995 approved these changes

2023-05-03 18:42 UTC, merged