add sysbench key
ros/rosdistro pull request #37094
Opened 2023-05-01 05:12 UTC by knorth55

Please add the following dependency to the rosdep database.

## Package name:

sysbench

## Package Upstream Source:

https://github.com/akopytov/sysbench

## Purpose of using this:

Benchmarking the robot computers

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?keywords=sysbench
- Ubuntu: https://packages.ubuntu.com/
  - https://manpages.ubuntu.com/manpages/trusty/man1/sysbench.1.html
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/sysbench/sysbench/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/community/x86_64/sysbench/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/app-benchmarks/sysbench
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/sysbench
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/community/x86_64/sysbench
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/tools/misc/sysbench/default.nix#L43
- openSUSE: https://software.opensuse.org/package/
  - https://build.opensuse.org/package/show/openSUSE:Factory/sysbench

2023-05-02 15:29 UTC, adityapande-1995 requested changes
Could you add the entry for rhel as well ? The key is called ``sysbench`` http://mirror.math.princeton.edu/pub/epel/9/Everything/x86_64/Packages/s/sysbench-1.0.20-11.el9.x86_64.rpm

2023-05-02 16:12 UTC, knorth55 commented
@adityapande-1995 I updated.

2023-05-03 13:01 UTC, mjcarroll approved these changes

2023-05-03 18:39 UTC, adityapande-1995 approved these changes

2023-05-03 18:39 UTC, merged