add stress-ng key
ros/rosdistro pull request #37095
Opened 2023-05-01 05:19 UTC by knorth55

Please add the following dependency to the rosdep database.

## Package name:

stress-ng

## Package Upstream Source:

https://github.com/ColinIanKing/stress-ng

## Purpose of using this:

For benchmarking robot computer

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/stress-ng
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/bionic/stress-ng
- Fedora: https://packages.fedoraproject.org/
  - https://src.fedoraproject.org/rpms/stress-ng
- Arch: https://www.archlinux.org/packages/
  - https://aur.archlinux.org/packages/stress-ng
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/app-benchmarks/stress-ng
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/stress-ng
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/community/x86_64/stress-ng
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/tools/system/stress-ng/default.nix#L42
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/stress-ng

2023-05-02 15:25 UTC, adityapande-1995 requested changes
Could you also add an entry for rhel ? The key is called ``stress-ng`` http://eastus.azure.repo.almalinux.org/almalinux/9.1/AppStream/x86_64/os/Packages/stress-ng-0.14.00-2.el9.x86_64.rpm

2023-05-03 13:01 UTC, mjcarroll approved these changes

2023-05-03 13:03 UTC, mjcarroll commented
> If you require rhel for optional, please update PR template to inform that.

While it is optional, we typically like to go ahead and add any platforms that the linter detects packages for.  It saves a potential pull request in the future and is easiest when the author and reviewers have context.  Thanks for your help!

2023-05-03 18:39 UTC, adityapande-1995 approved these changes

2023-05-03 18:39 UTC, merged