add libnanopb
ros/rosdistro pull request #37139
Opened 2023-05-05 11:49 UTC by Svastits

Please add the following dependencies to the rosdep database.

## Package name:

libnanop-dev

## Package Upstream Source:

https://github.com/nanopb/nanopb

## Purpose of using this:

nanopb is a commonly used messaging protocol, which is necessary for the ROS2 hardware interface of some KUKA robots

## Links to Distribution Packages

- Debian: 
  - nanopb is still in unstable https://packages.debian.org/sid/libnanopb-dev
- Ubuntu:
  - nanopb: https://packages.ubuntu.com/jammy/libnanopb-dev

UPDATE: I have removed libgrpc, as there is another PR for those packages

2023-05-15 17:12 UTC, clalancette requested changes
Please check the failures on the "Files changed" screen, and make appropriate updates.

2023-05-16 09:05 UTC, Svastits commented
Added debian bullseye:
https://packages.debian.org/bullseye/libnanopb-dev

2023-05-16 12:08 UTC, clalancette requested changes

2023-05-16 12:08 UTC, clalancette commented on rosdep/base.yaml
> +    bullseye: [libnanopb-dev]
Since this is available in all stable versions of Debian, we can just use:

```suggestion
  debian: [libnanopb-dev]
```

2023-05-16 14:25 UTC, clalancette approved these changes

2023-05-18 17:38 UTC, merged