Add chromium-chromedriver entry to base.yaml
ros/rosdistro pull request #37167
Opened 2023-05-10 04:05 UTC by sktometometo

Please add the following dependency to the rosdep database.

## Package name:

chromedriver

## Package Upstream Source:

https://chromedriver.chromium.org

## Purpose of using this:

`chromedriver` executable is necessary when controlling chroimum browser from selenium. I am create a ROS node controlling web browser and it is necessary for it.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/chromium-driver
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/kinetic/chromium-chromedriver
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/chromium/chromedriver/
- Arch: https://www.archlinux.org/packages/
  - contained in https://archlinux.org/packages/extra/x86_64/chromium/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/www-apps/chromedriver-bin
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/cask/chromedriver#default
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/community/armv7/chromium-chromedriver
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=chromedriver
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/chromedriver

2023-05-15 17:22 UTC, clalancette requested changes, later dismissed

2023-05-15 17:22 UTC, clalancette commented on rosdep/base.yaml
> +  rhel: [chromedriver]
This list needs to be in alphabetical order to satisfy the linters.

2023-05-25 06:29 UTC, sktometometo commented
Thank you for reviewing!. I update the branch

2023-05-31 20:18 UTC, nuclearsandwich approved these changes

2023-05-31 21:16 UTC, cottsay approved these changes

2023-05-31 21:16 UTC, merged