Adding Cairo Lang to osx
ros/rosdistro pull request #37179
Opened 2023-05-11 02:39 UTC by CursedRock17

This PR adds the Cairo package to OSX via python

## Package name:

Python-Cairo

## Package Upstream Source:

https://github.com/starkware-libs/cairo-lang

## Purpose of using this:

Packages like rqt_bag_plugins need access to Cairo and OSX currently didn't have access to it.

Distro packaging links:

## Links to Distribution Packages

- macOS: https://pypi.org/project/cairo-lang/

2023-05-15 17:59 UTC, clalancette requested changes

2023-05-15 18:14 UTC, CursedRock17 commented on rosdep/python.yaml
> +      packages: [cairo-lang]
Since there are some Python2 versions of Cairo, is it just best to see if they need updates now while we're working on this pull request?

2023-05-15 18:16 UTC, clalancette commented on rosdep/python.yaml
> +      packages: [cairo-lang]
No, I don't think so.  I think we should eventually aim to remove the `python-` keys completely, and just have the `python3-` keys going forward.

2023-05-31 20:44 UTC, nuclearsandwich commented
@clalancette's comments still hold. @CursedRock17 would you please update the PR description to refer to Cairo rather than Cairo Language

If you need Cairo itself on mac but not its Python bindings, I would suggest using Cairo from Homebrew, which is what the pycairo instructions require in order to build anyway https://formulae.brew.sh/formula/cairo#default

2023-06-03 01:09 UTC, nuclearsandwich commented
Thanks for updating the PR body. I'm still not completely clear what precise dependency you're trying to support here. Is it cairo itself? In which case I'd drop the `pycairo` addition in python.yaml and update the `libcairo2-dev` definition in base.yaml or the python bindings for cairo, in which case you might need both the `libcairo2-dev` dependency and the `pycairo` one in order to make it work on macOS.

2023-06-27 19:30 UTC, clalancette commented
No response in quite a while, so I'll close this out.  Feel free to reopen if you'd like to continue the conversation.

2023-06-27 19:30 UTC, closed without merging