Add rosdep key for 'semgrep'
ros/rosdistro pull request #37218
Opened 2023-05-11 18:52 UTC by florcabral

Please add the following dependency to the rosdep database.

## Package name:

`semgrep`

## Package Upstream Source:

https://github.com/returntocorp/semgrep

## Purpose of using this:

Semgrep is an open source static analysis engine. I have developed a [wrapper for the ament build system](https://github.com/florcabral/ament_semgrep) to run Semgrep in ROS projects. For this package to build, the `semgrep` rosdep key is required.

Distro packaging links:

## Links to Distribution Packages

- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/semgrep
- pip
  - https://pypi.org/project/semgrep/

2023-05-15 18:05 UTC, clalancette requested changes

2023-05-15 18:05 UTC, clalancette commented on rosdep/base.yaml
> +  pip: [semgrep]
This is not how the `pip` key works; you'll instead need to split this out for each distribution (debian, ubuntu, etc), and then put a pip key underneath it.

Even then, you should know that you cannot release packages that depend on `pip` keys into ROS.  All of the dependencies must be available via system packages.

2023-05-31 20:45 UTC, nuclearsandwich approved these changes

2023-06-06 14:36 UTC, clalancette approved these changes

2023-06-06 14:37 UTC, merged