Add natsort to python.yaml
ros/rosdistro pull request #37254
Opened 2023-05-17 08:49 UTC by JafarAbdi

Should I just keep one of these, or is it ok if we have both?

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-05-18 17:36 UTC, tfoote requested changes
Also for future reference you submitted a rosdep key but you used the issue template section from a new package submission. The rosdep template asks you to submit links to the packages in the databases of the different distros such as ubuntu and rhel and gentoo so that reviewers don't have to go search and check for the presence of the packages manually.

2023-05-18 17:36 UTC, tfoote commented on rosdep/python.yaml
> +python3-natsort-pip:
Please remove the pip rule. The natively packaged version is the version we will select if it's available.

2023-05-18 22:50 UTC, JafarAbdi commented
> Also for future reference you submitted a rosdep key but you used the issue template section from a new package submission. The rosdep template asks you to submit links to the packages in the databases of the different distros such as ubuntu and rhel and gentoo so that reviewers don't have to go search and check for the presence of the packages manually.

Apologizes, I update the PR description, thanks!

2023-05-19 21:56 UTC, tfoote approved these changes
Thanks for the update and extra links. It looks good to me. Just one more reviewer to land it.

2023-05-22 17:17 UTC, quarkytale approved these changes

2023-05-22 17:17 UTC, merged