Add fluent_bit_vendor in humble
ros/rosdistro pull request #37289
Opened 2023-05-19 17:26 UTC by Minipada

Please add the following dependency to the rosdep database.

## Package name:

fluent_bit_vendor

## Package Upstream Source:

https://github.com/Minipada/fluent_bit_vendor

## Purpose of using this:

I want to use Fluent Bit as a third party library for https://github.com/Minipada/ros2_data_collection
At the moment it is in this repo but I want to take it out.

Distro packaging links:

## Links to Distribution Packages

# Please Add This Package to be indexed in the rosdistro.

humble

# The source is here:

https://github.com/fluent/fluent-bit

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

2023-05-19 17:38 UTC, Minipada commented
I am not sure what is wrong here. I can fix it but I would need a hint.

2023-05-20 21:39 UTC, Minipada commented
I can't get the problem:
`FAILED test/test_build_caches.py::test_build_caches - RuntimeError: humble: missing package.xml file for package "fluent_bit_vendor"

It is here https://github.com/Minipada/fluent_bit_vendor/blob/humble/package.xml#L4

2023-05-22 17:06 UTC, quarkytale requested changes

2023-05-22 17:06 UTC, quarkytale commented on humble/distribution.yaml
> +      url: https://github.com/minipada/fluent_bit_vendor-release.git
My initial guess is a problem with the release repository it doesn't have the release/humble/{package}/{version} branch. I see you are trying to create a release in ros2-gbp, so first just add the source entry here, then continue the process in ros2-gbp, then you can create another PR to add the release repository. More details here https://docs.ros.org/en/rolling/How-To-Guides/Releasing/Release-Team-Repository.html#what-if-my-existing-release-repo-isn-t-on-ros2-gbp.
Also please consider following the recommended release workflow using Bloom https://docs.ros.org/en/rolling/How-To-Guides/Releasing/First-Time-Release.html.

2023-05-22 18:58 UTC, Minipada commented
Thanks for the links... I tried to follow the steps and even asked on the discord.
Seems ok now

2023-05-22 20:21 UTC, quarkytale approved these changes

2023-05-22 20:21 UTC, merged