Update python.yaml
ros/rosdistro pull request #37335
Opened 2023-05-23 09:44 UTC by belorenz

Moved from apt to pip dependency for `python3-tqdm` in ubuntu focal because last apt version available in focal is from Mai 2019 latest pip version is from March 23.

Please add the following dependency to the rosdep database.

## Package name: python3-tqdm

## Package Upstream Source:

[repo](https://github.com/tqdm/tqdm)

## Purpose of using this:

Instantly make your loops show a smart progress meter. Looking good!

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/buster/python3-tqdm
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/focal/python/python3-tqdm
  - REQUIRED
- PyPi: https://pypi.org/project/tqdm/

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-05-23 10:02 UTC, belorenz commented on rosdep/python.yaml
> +         packages: [tqdm]
```suggestion
        packages: [tqdm]
```

2023-05-23 21:05 UTC, peci1 commented
I don't support this change. The general rule is that APT packages have strong preference to pip packages unless there is a very good reason. This would also break buildfarm builds of all existing packages that depend on the rosdep key because buildfarm cannot install pip packages.

If you need a newer version, you have to manually install it on the machines.

Alternatively, you could create a new rosdep key `python3-tqdm-pip`, but I'm not sure what's the policy on such dualities...

2023-05-31 20:51 UTC, nuclearsandwich requested changes
As a policy, we generally discourage the use of pip dependencies on platforms which provide those via system packages and replacing an existing system dependency with a pip dependency is completely off the table within an existing key.

Sticking with released dependencies for the lifetime of a distribution is part of the trade-off that allows us to leverage that distribution's support and inter-compatibility.

2023-05-31 22:48 UTC, emersonknapp commented
I will also recommend just closing out this PR - as noted above it doesn't meet the standards for rosdistro, and the existing code already does without a change.

2023-06-06 14:38 UTC, closed without merging