Removed turtlesim key
ros/rosdistro pull request #37449
Opened 2023-06-02 14:54 UTC by ahcorde

Removed `turtlesim` key. Related with the comment from @clalancette in this PR https://github.com/ros/ros_tutorials/pull/153. 

If I'm not wrong we should remove the key in the active ROS 2 distros and then release the package with the right key, isn't it ?

2023-06-03 00:59 UTC, nuclearsandwich commented
I think we might get away here with an inline edit rather than having to remove and replace.

Suggestion

```
  ros_tutorials:
    doc:
      type: git
      url: https://github.com/ros/ros_tutorials.git
      version: rolling
    release:
      packages:
        - turtlesim
      tags:
        release: release/rolling/{package}/{version}
      url: https://github.com/ros2-gbp/ros_tutorials-release.git
      version: 1.7.1-1
    source:
      test_pull_requests: true
      type: git
      url: https://github.com/ros/ros_tutorials.git
      version: rolling
    status: maintained
```

2023-06-03 14:32 UTC, clalancette commented
> I think we might get away here with an inline edit rather than having to remove and replace.

Yeah, I think that would be better.  My suggestion is the following:

1.  Make the update as @nuclearsandwich suggests.
2.  Merge this in.
3.  Immediately do a new `bloom-release ros_tutorials` of the package to verify that this does what we expect.

We may then want to consider backporting this to both `humble` and `iron`.

2023-06-05 10:24 UTC, ahcorde commented
Thank you @clalancette and @nuclearsandwich

2023-06-05 11:36 UTC, clalancette requested changes

2023-06-05 11:36 UTC, clalancette commented on rolling/distribution.yaml
> +      version: 1.7.1-1
I think this is going to need to be:

```suggestion
    release:
      packages:
        - turtlesim
      tags:
        release: release/rolling/{package}/{version}
      url: https://github.com/ros2-gbp/ros_tutorials-release.git
      version: 1.7.1-1
```

(though I could use confirmation from @nuclearsandwich )

2023-06-05 13:07 UTC, clalancette approved these changes
This looks good to me.

2023-06-05 13:08 UTC, merged