electronic-io: 1.0.1-1 in 'melodic/distribution.yaml' [bloom]
ros/rosdistro pull request #37708
Opened 2023-06-18 23:02 UTC by peci1

Increasing version of package(s) in repository `electronic-io` to `1.0.1-1`:

- upstream repository: https://github.com/ctu-vras/electronic-io.git
- release repository: https://gitlab.fel.cvut.cz/cras/ros-release/electronic-io.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## electronic_io

```
* Added support for simplified specification of pins in config.
* Added BinaryPWM virtual pin.
* Added virtual pins.
* It topic is set to empty, the topics and services will not be created.
* Added Battery device.
* Export the provided devices.
* Allow setting queue_size and latching for output devices.
* Added support for output groups.
* Robustified IO board client.
* Initial commit
* Contributors: Martin Pecka
```

## electronic_io_msgs

```
* Initial commit
* Contributors: Martin Pecka
```

2023-06-20 17:38 UTC, clalancette requested changes

2023-06-20 19:30 UTC, peci1 commented on melodic/distribution.yaml
> +  electronic-io:
The goal was indeed to create a generically usable package. I wanted to promote it a bit in the coming weeks so the community would get to know it.

I understand why you suggest prepending organization. I have two points which led me to  not do so:

1. There are (imo) really no competing packages trying to achieve this in a generic way. Yet I think some standardization would be beneficial.
2. Was there actually some package that started with organzation prefix and then dropped it over time? I get that this is a REP recommendation, yet I think it is actually very impractical to force users of an established package to use a different name.

One point for prefixing is the dependency on cras_msgs. However, this package just adds what's missing in sensor_msgs (Voltage, ElectricCurrent...).

If you still think this package should be prefixed, I'll do it.

2023-06-26 20:50 UTC, mjcarroll commented on melodic/distribution.yaml
> +  electronic-io:
I think that if it's intended to be generic, then the package name is fine.

2023-06-30 16:01 UTC, clalancette commented
Since melodic is now EOL, closing this.  I've reproduce the conversation above into #37709

2023-06-30 16:01 UTC, closed without merging