Add helyos_agent_sdk to rosdep database
ros/rosdistro pull request #37726
Opened 2023-06-19 15:01 UTC by jkkolb

Please add the following dependency to the rosdep database.

## Package name:

- python3-helyos_agent_sdk-pip

## Package Upstream Source:

[helyOS Agent SDK](https://github.com/FraunhoferIVI/helyOS-agent-sdk)

## Purpose of using this:

The helyos-agent-sdk python package encloses methods and data structure definitions that facilitate the connection of autonomous vehicles to [helyOS Framework](https://helyos-manual.readthedocs.io/en/latest/) through rabbitMQ.

Distro packaging links:

## Links to Distribution Packages
The package is OS independent and distributed via [PyPI](https://pypi.org/project/helyos-agent-sdk/)

- Debian: https://packages.debian.org/
  - [not available](https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=helyos_agent_sdk)
- Ubuntu: https://packages.ubuntu.com/
  - [not available](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=helyos_agent_sdk&searchon=names)

We are aware of the restriction that packages depending on pip packages cannot be released to the official build farm

2023-06-27 19:18 UTC, clalancette requested changes
Hm, there seems to be something odd in this PR.  I know it is unrelated, but the `python-pylint3` key here is different from the one that is in the official file: https://github.com/ros/rosdistro/blob/5eebfb7b4f73f4ce2ee7d6f6706e64e215123922/rosdep/python.yaml#L3097-L3103 .  That is what is causing CI to be unhappy.

@jkkolb Can you please rebase this onto the latest and see if that resolves the issue?

2023-06-30 07:33 UTC, jkkolb reviewed
Thanks for pointing that out, I rebased on the latest right now. Hopefully it solves the issue

2023-06-30 15:58 UTC, clalancette approved these changes

2023-07-05 12:26 UTC, clalancette approved these changes

2023-07-05 16:46 UTC, audrow approved these changes

2023-07-05 16:46 UTC, merged