Fixed gz_ros2_control keys: Iron and Rolling
ros/rosdistro pull request #37773
Opened 2023-06-23 09:17 UTC by ahcorde

Due the renaming from ign to gz this package should use a different key, package names have changed too.

2023-06-26 20:41 UTC, mjcarroll commented
Iron is held for sync https://discourse.ros.org/t/preparing-for-iron-sync-2023-06-30/32099

2023-07-05 12:50 UTC, clalancette requested changes

2023-07-05 12:50 UTC, clalancette commented on iron/distribution.yaml
> +      version: 1.1.0-1
Something is weird here; this version does not exist in https://github.com/ros2-gbp/ign_ros2_control-release , and that is why CI is failing.

2023-07-12 22:33 UTC, sloretz commented on iron/distribution.yaml
> +      url: https://github.com/ros2-gbp/ign_ros2_control-release.git
@ahcorde is this the right release repo? I notice it still has "ign" in the name. Not a problem, but @clalancette noticed the version listed here doesn't exist in this release repo.

2023-07-13 09:26 UTC, ahcorde commented
@clalancette and @sloretz I will try a different approach, I will remove the key `gz_ros2_control` and I will release again `gz_ros2_control`

 - https://github.com/ros/rosdistro/pull/37952
 - https://github.com/ros/rosdistro/pull/37951

2023-07-14 02:47 UTC, tfoote commented
I'm going to close this one and assume that you'll redo the iron release in the same way as rolling above.

2023-07-14 02:47 UTC, closed without merging