submit flexbe for ROS 2 naming review prior to creating release repos
ros/rosdistro pull request #37823
Opened 2023-06-29 15:10 UTC by dcconner

Submitting FlexBE for naming review before first ROS 2 release.

Will be submitting release team and release repo creation requests tied to this PR.

## Package names:

        - flexbe_app
        - flexbe_behavior_engine
        - flexbe_core
        - flexbe_input
        - flexbe_mirror
        - flexbe_msgs
        - flexbe_onboard
        - flexbe_states
        - flexbe_testing
        - flexbe_widget

## Package Upstream Source:
https://github.com/flexbe/flexbe_app.git
https://github.com/flexbe/flexbe_behavior_engine.git

## Purpose of using this:

FlexBE is available in ROS 1.   The ROS 2 version has been tested, and continuous integration tests are now functioning so ready for ROS 2 release.

Proposed release package names (have not created yet)
https://github.com/ros2-gbp/flexbe_app-release.git
https://github.com/ros2-gbp/flexbe_behavior_engine-release.git

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X ] This repository has a LICENSE file
 - [X ] This package is expected to build on the submitted rosdistro

2023-06-30 15:48 UTC, clalancette reviewed
This generally looks good to me, particularly because it is grandfathered in by being in Noetic.

I do have one concern, though.  In Noetic, the source repository is at https://github.com/team-vigir/flexbe_behavior_engine.git, while here it is at https://github.com/flexbe/flexbe_behavior_engine.git .  That can be seen as a takeover of the repository.  What's the relationship between them?

2023-06-30 15:55 UTC, dcconner commented
The noetic issue is due to ignorance on my part when we moved over.  I thought changing the release repo https://github.com/FlexBE/flexbe_behavior_engine-release/blob/master/tracks.yaml#L126 was sufficient.  I will update the PR to include the changes to Noetic as well.  As background I was the PI on team-vigir project when FlexBE initially released. Then FlexBE_App was developed later by @pschillinger .  We're (@pschillinger  and myself) are moving all things FlexBE to github.com/FlexBE and have already (March '22) made note on team-vigir site that is not longer maintained. https://github.com/team-vigir/flexbe_behavior_engine/blob/main/README.md.  I've taken over primary responsibility for ROS 2 development and maintenance given current research project.

2023-07-05 12:48 UTC, clalancette commented
OK, sounds good.  Thanks for verifying.

CI is failing on this because the release repositories aren't yet created.  What I'll suggest here is that you remove the `release` sections of both stanzas.  Once that is done, CI should pass and we can go ahead and merge this.  That will then unblock https://github.com/ros2-gbp/ros2-gbp-github-org/issues/289 , and then once that is fixed you can do a `bloom-release`.

2023-07-05 15:10 UTC, clalancette requested changes

2023-07-05 15:10 UTC, clalancette commented on humble/distribution.yaml
> +   #   version: 3.1.0
Just remove this section; `bloom` will end up recreating it when you do the actual release.

2023-07-05 15:10 UTC, clalancette commented on humble/distribution.yaml
> +    #   version: 2.2.0
Ditto.

2023-07-05 15:38 UTC, clalancette approved these changes

2023-07-05 15:38 UTC, merged