Add liblttng-ctl-dev
ros/rosdistro pull request #37824
Opened 2023-06-29 21:15 UTC by christophebedard

Please add the following dependency to the rosdep database.

## Package name:

`liblttng-ctl-dev`

## Package Upstream Source:

https://github.com/lttng/lttng-tools

License: LGPL-2.1-only (for the library itself)

## Purpose of using this:

Configuring tracing directly.

## Links to Distribution Packages

The source repository (https://github.com/lttng/lttng-tools) includes:

- Tracing control library (`liblttng-ctl0` on Ubuntu)
- Tracing control library - development files (`liblttng-ctl-dev` on Ubuntu)
- CLI tool based on the library (`lttng-tools` on Ubuntu)

Some platforms only have "lttng-tools," so they either have all of the above in a single package, or they only offer the CLI tool (and `liblttng-ctl0`) but not the development files for the library.

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/liblttng-ctl-dev
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/liblttng-ctl-dev
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/lttng-tools/lttng-tools-devel/
- Arch: https://www.archlinux.org/packages/
  - not found
- Gentoo: https://packages.gentoo.org/
  - not sure if this includes `liblttng-ctl-dev`: https://packages.gentoo.org/packages/dev-util/lttng-tools
- macOS: https://formulae.brew.sh/
  - N/A
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/community/x86/lttng-tools-dev
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not sure if this includes `liblttng-ctl-dev`: https://hydra.nixos.org/job/nixos/release-23.05/nixpkgs.lttng-tools.x86_64-linux
- openSUSE: https://software.opensuse.org/package/
  - doesn't seem to be generally available: https://software.opensuse.org/package/liblttng-ctl-dev

2023-06-30 15:42 UTC, clalancette requested changes
The bot seems to think this is available in `lttng-tools-devel` like it is on RHEL.  I think that is worthwhile adding.

2023-06-30 15:51 UTC, christophebedard commented
Added!

2023-06-30 15:52 UTC, christophebedard commented
Wait, `lttng-tools-devel` doesn't exist, does it?

2023-06-30 15:57 UTC, christophebedard commented
Ah, it seems to work. It wasn't clear to me that "lttng-tools" was providing the `lttng-tools-devel` key.

2023-06-30 16:03 UTC, clalancette commented
> Ah, it seems to work. It wasn't clear to me that "lttng-tools" was providing the `lttng-tools-devel` key.

Yeah, I find the OpenSUSE package database to be hard to navigate.  Thanks for adding it!

2023-06-30 16:03 UTC, clalancette approved these changes

2023-07-05 16:43 UTC, audrow approved these changes

2023-07-05 16:43 UTC, merged