Add cpp-httplib
ros/rosdistro pull request #37826
Opened 2023-06-29 21:52 UTC by Ryanf55

* SOURCE: 
* License: MIT https://github.com/yhirose/cpp-httplib/blob/master/LICENSE
* Debian: https://packages.debian.org/search?suite=bookworm&arch=any&searchon=names&keywords=libcpp-httplib-dev
  * Only bookworm
* Ubuntu: https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=libcpp-httplib-dev
* Fedore: https://packages.fedoraproject.org/pkgs/cpp-httplib/cpp-httplib-devel/
* Arch: None
* Gentoo: https://packages.gentoo.org/packages/dev-cpp/cpp-httplib
  * It doesn't seem like this is the dev version
* macOS: https://formulae.brew.sh/formula/cpp-httplib#default
* Alpine: None

Please add the following dependency to the rosdep database.

## Package name:

cpp-httplib (dev)

## Package Upstream Source:

[cpp-httplib](https://github.com/yhirose/cpp-httplib)

## Purpose of using this:

This allows making simple HTTP(S) servers in C++. Header only. 

## Links to Distribution Packages

- Debian: https://packages.debian.org/search?suite=bookworm&arch=any&searchon=names&keywords=libcpp-httplib-dev
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=libcpp-httplib-dev
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/pkgs/cpp-httplib/cpp-httplib-devel/
  - IF AVAILABLE
- Arch: not available
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/packages/dev-cpp/cpp-httplib
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/formula/cpp-httplib#default
  - IF AVAILABLE
- Alpine: not available
  - IF AVAILABLE
- NixOS/nixpkgs: Skipped
  - OPTIONAL
- openSUSE: Skipped
  - IF AVAILABLE
  - 
# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-06-29 22:22 UTC, audrow approved these changes
LGTM!

2023-06-29 22:34 UTC, Ryanf55 commented
> LGTM!

Thanks. Do you have any recommendation on the four options for the rosdep library name?

2023-06-30 15:45 UTC, clalancette requested changes
Besides the changes pointed out in review, the bot also thinks this is available in RHEL as `cpp-httplib-devel`, so we should add that as well.

2023-06-30 15:45 UTC, clalancette commented on rosdep/base.yaml
> +    sid: [libcpp-httplib-dev]
To make this futureproof, we should probably do:

```suggestion
  debian:
    '*': [libcpp-httplib-dev]
    bullseye: null
```

2023-06-30 15:45 UTC, clalancette commented on rosdep/base.yaml
> +    jammy: [libcpp-httplib-dev]
Same here:

```suggestion
  ubuntu:
    '*': [libcpp-httplib-dev]
    focal: null
```

2023-06-30 15:45 UTC, clalancette commented
> Thanks. Do you have any recommendation on the four options for the rosdep key name?

Our general policy is to have the key name match the Ubuntu package name, so what you have now is good.

2023-06-30 16:23 UTC, Ryanf55 commented
@clalancette After applying your rules: 
`Error: Package 'libcpp-httplib-dev' could not be found for ubuntu bionic on amd64`

Do I need to go set `null` for deprecated distros?

2023-06-30 16:51 UTC, clalancette commented
> Do I need to go set `null` for deprecated distros?

Oh, we just forgot to shut `bionic` off in the bot.  We can do that separately.  For now, I'll just suggest adding in `bionic: null`, which should silence that warning.

2023-06-30 17:01 UTC, Ryanf55 commented
> > Do I need to go set `null` for deprecated distros?
> 
> Oh, we just forgot to shut `bionic` off in the bot. We can do that separately. For now, I'll just suggest adding in `bionic: null`, which should silence that warning.

Added in 71cb3b9fe7df56bae4ceb16597c8096b78732578

2023-06-30 17:04 UTC, clalancette approved these changes

2023-06-30 17:05 UTC, merged