qb_softhand_industry: 1.0.6-3 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #38122
Opened 2023-08-02 08:13 UTC by GDqbrobotics

Increasing version of package(s) in repository `qb_softhand_industry` to `1.0.6-3`:

- upstream repository: https://bitbucket.org/qbrobotics/qbshin-ros.git
- release repository: https://bitbucket.org/qbrobotics/qbshin-ros-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## qb_softhand_industry

- No changes

## qb_softhand_industry_bringup

- No changes

## qb_softhand_industry_control

- No changes

## qb_softhand_industry_description

- No changes

## qb_softhand_industry_driver

```
* qb_softhand_industry_driver version number fix
```

## qb_softhand_industry_hardware_interface

- No changes

## qb_softhand_industry_msgs

- No changes

## qb_softhand_industry_srvs

- No changes

## qb_softhand_industry_utils

- No changes

2023-08-02 13:08 UTC, clalancette commented
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2023-08-03/)

2023-08-04 12:29 UTC, clalancette requested changes

2023-08-04 12:29 UTC, clalancette commented on noetic/distribution.yaml
> +      version: master
This is the correct repository for the documentation; this should be:

```suggestion
      url: https://bitbucket.org/qbrobotics/qbshin-ros.git
      version: production-noetic
```

2023-08-04 12:29 UTC, clalancette commented on noetic/distribution.yaml
> +      version: production-noetic
I'll note that several of the packages in the source repository have their `package.xml` url set to `https://bitbucket.org/qbrobotics/qbshin-ros-internal`; that should probably be changed to `https://bitbucket.org/qbrobotics/qbshin-ros`

2023-08-04 16:46 UTC, audrow commented
Closed in favor of https://github.com/ros/rosdistro/pull/38153.

2023-08-04 16:46 UTC, closed without merging