Please add python3-attrs to rosdep
ros/rosdistro pull request #38148
Opened 2023-08-04 08:41 UTC by SubaruArai

Please add the following dependency to the rosdep database.

## Package name:

python3-attrs

## Package Upstream Source:

https://www.attrs.org/en/stable/
https://github.com/python-attrs/attrs

## Purpose of using this:

`attrs` is a widely used library for making data-oriented classes.
It was in the list with python2, and there are packages that specify it as a dependency with python3. (e.g. `python3-twisted`)

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/python3-attr
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/python3-attr
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-attrs/python3-attrs/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/extra/any/python-attrs/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/attrs
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://hydra.nixos.org/job/nixos/release-23.05/nixpkgs.python311Packages.attrs.x86_64-linux
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/python3-attrs

2023-08-04 20:29 UTC, clalancette requested changes

2023-08-04 20:29 UTC, clalancette commented on rosdep/python.yaml
> +  opensuse: [python3-attrs]
The bot thinks that this is also available on RHEL, so:

```suggestion
  fedora: [python3-attrs]
  opensuse: [python3-attrs]
  rhel: [python3-attrs]
```

2023-08-06 23:52 UTC, SubaruArai commented
Done!

2023-08-07 12:00 UTC, clalancette approved these changes

2023-08-07 15:04 UTC, audrow approved these changes

2023-08-07 15:04 UTC, merged