adding python3-nmcli-pip to python
ros/rosdistro pull request #38180
Opened 2023-08-08 17:45 UTC by ARK3r

Allows network control using python similar to the bash nmcli package.

Two points however:
1. for the nmcli pip package to work, apt needs to install network-manager
2. The package only worked for ubuntu 20.04 and 22.04 as I tested in docker.

2023-08-09 00:57 UTC, sloretz requested changes

2023-08-09 00:57 UTC, sloretz commented on rosdep/python.yaml
> +python3-nmcli:
Please name this `python3-nmcli-pip`: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1

2023-08-09 01:53 UTC, ARK3r commented
Is there any way to enforce the network-manager dependency while installing this package?

2023-08-10 16:49 UTC, sloretz approved these changes

2023-08-10 17:51 UTC, tfoote commented
Yes you can add a depends line for pip rules

Spec: https://www.ros.org/reps/rep-0111.html#dependencies

Enabled: https://github.com/ros-infrastructure/rosdep/blob/05b49e4d588a4f36f222a02c7e492b46002dca86/src/rosdep2/platforms/pip.py#L130C14-L130C14

Implementation: https://github.com/ros-infrastructure/rosdep/blob/05b49e4d588a4f36f222a02c7e492b46002dca86/src/rosdep2/installers.py#L403C38-L403C38

Example: 

https://github.com/ros/rosdistro/blob/ee18ca7343a7da32b9049ce3171c117166141fe3/rosdep/python.yaml#L963-L966

2023-08-21 06:22 UTC, methylDragon approved these changes

2023-08-21 06:22 UTC, merged