feat: add 'pandas' pip install
ros/rosdistro pull request #38243
Opened 2023-08-14 19:35 UTC by rickstaa

This commit adds the pip install of the pandas package. This allows users to use more recent versions for their distro than those available through system packages. This pull request is closely related to https://github.com/ros/rosdistro/pull/38242.

Please add the following dependency to the rosdep database.

## Package name:

Pip version of [pandas](https://pypi.org/project/pandas/).

## Package Upstream Source:

https://github.com/pandas-dev/pandas

## Purpose of using this:

This dependency is needed because other items that are available in the [rosdep/python.yaml](https://github.com/ros/rosdistro/blob/b6b1a7f3d9931b19efaee421982fbca875531087/rosdep/python.yaml#L221-L233)
file which does not have a system package available throws errors when the system pandas is installed. When for example, numpy is installed through pip (see https://github.com/ros/rosdistro/pull/38242) it requires `pandas>=1.1.0" since the older version of pandas expects the `np.bool` to be not deprecated (see https://github.com/brightway-lca/brightway2/issues/64).

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-08-14 19:50 UTC, rickstaa commented
It looks like the error is caused by the already present `python-pandas` rule and not the new `python-pandas-pip` rule.

2023-08-17 17:02 UTC, tfoote requested changes
Sorry we don't allow using pip rules when they will override the apt rules.

2023-08-17 18:35 UTC, cottsay commented
There's a discussion to be had here around dropping Python 2 package rules that are no longer valid in Ubuntu. We did it for Fedora, but the scope of work is larger for Ubuntu.

I believe that the policy previously employed was that a package for which we never expect to be a system package is allowed to get a pip rule under a non-pip-exclusive key. Since the Python 2 package was explicitly dropped, I think it's safe to say that we don't expect it to appear in future Ubuntu releases, and qualifies for dual-installer listing here.

2023-08-18 08:51 UTC, rickstaa commented
> Sorry, we don't allow using pip rules when they will override the apt rules.

Ah, I see, because when multiple ROS packages have the `python3-numpy` dependency, and one box has the `python3-numpy-pip` dependency, the latter will get installed while the ROS packages that require `python3-numpy` expect a lower python version and will break. That makes sense 👍🏻.

I created this pull request because the Gymnasium package, which I added in https://github.com/ros/rosdistro/pull/37334 expects the [numpy.typing](https://numpy.org/devdocs/reference/typing.html) module to be present. As Numpy 1.17.4 is installed on Ubuntu 20.04 when using the system package, the `gymnasium-pip` install will not be working as expected, and the following error will be thrown when trying to use the gymnasium package:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/__init__.py", line 4, in <module>
    from gymnasium.core import (
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/core.py", line 9, in <module>
    from gymnasium import spaces
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/spaces/__init__.py", line 13, in <module>
    from gymnasium.spaces.box import Box
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/spaces/box.py", line 7, in <module>
    from numpy.typing import NDArray
ModuleNotFoundError: No module named 'numpy.typing'
```

To fix this, I created https://github.com/ros/rosdistro/pull/38242, which required https://github.com/ros/rosdistro/pull/38243 to be created because the `np.bool` type is appreciated in `numpy>1.20`. 

Based on what you said, we can close both https://github.com/ros/rosdistro/pull/38242 and https://github.com/ros/rosdistro/pull/38243.

@tfoote, what would be the best way to handle this conflict on Ubuntu20.04 when using Gymnasium?

- Remove the Gymnasium key added in https://github.com/ros/rosdistro/pull/37334. People can then create a note in their documentation that `Gymnasium` should be installed using pip?
- Leaving the Gymnasium key in our index and accepting that people can run into issues on Ubuntu-20.04? Is there a way to prevent a key from being used on a given distribution?
- Request a new release of numpy and pandas for Ubuntu 20.04. I guess this is a lot of work for a slight edge case which can be solved by installing the Python packages using pip in a virtual environment 😅 .

**TLDNR**: Gymnasium requires `numpy>1.20.1` -> if pip is used `numpy>1.24` is installed -> this numpy version requires `pandas>1.1.0`.

2023-08-18 08:54 UTC, rickstaa commented
Also affects https://github.com/ros/rosdistro/pull/38244.

2023-08-18 09:06 UTC, rickstaa commented
> There's a discussion to be had here around dropping Python 2 package rules that are no longer valid in Ubuntu. We did it for Fedora, but the scope of work is larger for Ubuntu.
> 
> I believe that the policy previously employed was that a package for which we never expect to be a system package is allowed to get a pip rule under a non-pip-exclusive key. Since the Python 2 package was explicitly dropped, I think it's safe to say that we don't expect it to appear in future Ubuntu releases, and qualifies for dual-installer listing here.

@cottsay, thanks for your comment 😄. I'm not f I understand it correctly, but you say that in this case, a pip rule under a non-pip rule would be allowed since the python2.7 version of pandas (i.e. `python-pandas`) is no longer released?

2023-08-22 23:04 UTC, tfoote commented
The python2 comment is related to simply dropping the nearby python-pandas key. The pip rules pick up the default version so since python3 is the now the default version of python all pip rules are in herently python3. Ad so should use the `python3-` prefix now to help detect conflicts. 


But that aside I would suggest that you setup a custom rules for your repository and move all three of these rules, `numpy`, `pandas`, `gymnasium` into there instead of trying to make them generic enough for the public usage. In your documentation you should be clear about how they will override your system versions and include how to clear them if people aren't aware of or don't want the side effects. 

And then just add to your documentation to add your rules to their rosdep sources when using your repository/packages.

2023-08-23 16:18 UTC, rickstaa commented
> The python2 comment is related to simply dropping the nearby python-pandas key. The pip rules pick up the default version so since python3 is the now the default version of python all pip rules are in herently python3. Ad so should use the `python3-` prefix now to help detect conflicts.
> 
> But that aside I would suggest that you setup a custom rules for your repository and move all three of these rules, `numpy`, `pandas`, `gymnasium` into there instead of trying to make them generic enough for the public usage. In your documentation you should be clear about how they will override your system versions and include how to clear them if people aren't aware of or don't want the side effects.
> 
> And then just add to your documentation to add your rules to their rosdep sources when using your repository/packages.

That makes sense. Thanks for the explanation 🙏🏻! 

I quickly created [an issue](https://github.com/ros/rosdistro/issues/38332) if people run into problems regarding the `gymnasium-pip` rosdep rule (see https://github.com/ros/rosdistro/issues/38332). Let's close this and https://github.com/ros/rosdistro/pull/38242 for now 👍🏻.

2023-08-23 16:18 UTC, closed without merging