metro_nav: 0.1.0-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #38370
Opened 2023-08-30 02:47 UTC by DLu

Increasing version of package(s) in repository `metro_nav` to `0.1.0-1`:

- upstream repository: https://github.com/MetroRobots/metro_nav.git
- release repository: https://github.com/ros2-gbp/metro_nav-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## kinematics_2d

```
* Initial kinematics_2d_msgs and kinematics_2d packages
* Contributors: David V. Lu
```

## kinematics_2d_msgs

```
* Initial kinematics_2d_msgs and kinematics_2d packages
* Contributors: David V. Lu
```

2023-08-30 06:18 UTC, quarkytale commented
By looking at the source, I'm unsure if the functionality in the packages `kinematics_2d` and `kinematics_2d_msgs` is generic. Can you please confirm if these aren't specific to any application or robot perhaps?

2023-08-31 01:25 UTC, DLu commented
This is a generalization from the nav stack. The goal is to cover a wide range of mobile base applications where the base moves in x, y and theta directions. It does not apply to ackermann bases. What name would you suggest?

2023-09-05 22:32 UTC, emersonknapp commented
I'd suggest prefixing with the project name to easily meet REP144 requirements. `metronav_kinematics_2d` (etc.) would be great

2023-09-05 22:32 UTC, emersonknapp requested changes
Per REP144 naming discussion

2023-09-06 01:19 UTC, DLu commented
Would you consider `base2d_kinematics` as sufficiently specific?

2023-09-07 17:07 UTC, emersonknapp commented
yeah, in the interest of unblocking, that seems to at least narrow in the package scope somewhat - let's move forward with that proposal

2023-09-08 19:55 UTC, DLu commented
Closing for https://github.com/ros/rosdistro/pull/38484

2023-09-08 19:55 UTC, closed without merging