Add tiled rosdep
ros/rosdistro pull request #38383
Opened 2023-08-31 08:44 UTC by Vuwij

Please add the following dependency to the rosdep database.

## Package name:

tiled

## Package Upstream Source:

https://github.com/mapeditor/tiled

## Purpose of using this:

Used as a tile editor

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/tiled
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/focal/tiled
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/tiled/tiled/

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-09-05 22:33 UTC, emersonknapp requested changes, later dismissed

2023-09-05 22:33 UTC, emersonknapp commented on rosdep/base.yaml
> +tiled:
Would you mind adding the arch/alpine/opensuse rules as suggested by the tooling? Otherwise this looks fine

2023-09-13 16:01 UTC, kjeremy commented on rosdep/base.yaml
> +  ubuntu: [tiled]
nixos also provides `tiled`:  https://search.nixos.org/packages?channel=23.05&show=tiled&from=0&size=50&sort=relevance&type=packages&query=tiled

2023-10-13 06:35 UTC, quarkytale commented
@Vuwij friendly ping, are you still planning to take this forward?

2023-11-03 05:15 UTC, nuclearsandwich approved these changes
Added the suggestions from CI and review @Vuwij if this is still valuable to you please consider accepting the suggestion to move the PR forward. Otherwise we will close it next week. Thanks.

2023-11-03 05:15 UTC, nuclearsandwich commented on rosdep/base.yaml
> +  ubuntu: [tiled]
```suggestion
tiled:
  alpine: [tiled]
  archlinux: [tiled]
  debian: [tiled]
  fedora: [tiled]
  nixos: [tiled]
  opensuse: [tiled]
  ubuntu: [tiled]
```

2023-11-08 16:04 UTC, clalancette approved these changes

2023-11-08 16:04 UTC, merged