rosdep: Add libfyaml-dev
ros/rosdistro pull request #38406
Opened 2023-09-03 07:20 UTC by wentasah

Please add the following dependency to the rosdep database.

## Package name:

libfyaml-dev

## Package Upstream Source:

https://github.com/pantoniou/libfyaml

## Purpose of using this:

This dependency is used by [mrpt2](https://index.ros.org/search/?term=mrpt2) package. Currently, it fetches the copy of the library source code by cmake. However, this fails on Nix(OS), because packages are built in a sandbox without network access. Having it in rosdep allows building the package without problems.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/search?keywords=libfyaml-dev
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/search?keywords=libfyaml-dev
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/ (NOT AVAILABLE)
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/ (NOT AVAILABLE)
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/ (NOT AVAILABLE)
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/ (NOT AVAILABLE)
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages (NOT AVAILABLE)
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages?channel=unstable&show=libfyaml
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/libfyaml
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/ (NOT AVAILABLE)
  - IF AVAILABLE

2023-09-05 17:02 UTC, emersonknapp approved these changes

2023-09-08 21:38 UTC, cottsay requested changes, later dismissed
An empty list carries different meaning than omitting the rule entirely. An empty list says that the dependency is implicitly met without installing anything, where omitting the rule or explicitly `null` states that the dependency is not available.

I see no reason that we should have empty lists here.

2023-09-09 06:12 UTC, wentasah commented
Thanks for explaining the difference. I've removed the `[]` lines.

2023-09-12 15:50 UTC, clalancette requested changes
The bot thinks we can satisfy the dependency on `fedora` as well (take a look at the "Files changed" tab).  Once that is fixed this looks good to me.

2023-09-12 15:58 UTC, wentasah commented
I've added the fedora entry. Now, there are no hints from the bot.

2023-09-12 16:06 UTC, clalancette approved these changes

2023-09-12 16:06 UTC, merged