aandd_ekew_driver_py: 0.0.1-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #38416
Opened 2023-09-06 00:54 UTC by Kansea

Increasing version of package(s) in repository `aandd_ekew_driver_py` to `0.0.1-1`:

- upstream repository: https://github.com/TechMagicKK/aandd_ekew_driver_py.git
- release repository: https://github.com/TechMagicKK/aandd_ekew_driver_py-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## aandd_ekew_driver_py

```
* relesase
* Contributors: Jiaqing Lin
```

2023-09-07 17:05 UTC, emersonknapp commented
As this appears to be a brand new package release, going through the checklist

- [ ] At least one of the following must be present
  - [ ] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/TechMagicKK/aandd_ekew_driver_py
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

Looks like there is a missing LICENSE file in the repository, otherwise everything else seems in order

2023-09-07 17:05 UTC, emersonknapp requested changes, later dismissed
Add LICENSE file to repo

2023-09-08 02:43 UTC, Kansea commented
@emersonknapp
I have added the license file to repo.

2023-09-11 21:59 UTC, cottsay commented
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2023-09-11/33303)

2023-09-12 16:04 UTC, clalancette approved these changes

2023-09-12 16:04 UTC, merged