added libpcsclite1
ros/rosdistro pull request #38546
Opened 2023-09-14 13:11 UTC by codename-astroboy

Please add the following dependency to the rosdep database.

## Package name:

libpcsclite1

## Package Upstream Source:

https://pcsclite.apdu.fr/

## Purpose of using this:

This dependency has some required tools for use with pcscd to use with smart cards

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/libpcsclite1
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/focal/libpcsclite1
- Fedora: https://packages.fedoraproject.org/
  - NOT AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - NOT AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - NOT AVAILABLE
- macOS: https://formulae.brew.sh/
  - NOT AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - NOT AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - NOT AVAILABLE
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/libpcsclite1
- rhel: https://rhel.pkgs.org/
  - https://pkgs.org/search/?q=libpcsclite1

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-09-14 19:12 UTC, clalancette requested changes

2023-09-14 19:12 UTC, clalancette commented on rosdep/base.yaml
> +  ubuntu: [libpcsclite1]
I believe this is available in RHEL and Fedora as `pcsc-lite-libs`.  So:

```suggestion
  debian: [libpcsclite1]
  fedora: [pcsc-lite-libs]
  opensuse: [libpcsclite1]
  rhel: [pcsc-lite-libs]
  ubuntu: [libpcsclite1]
```

2023-09-15 13:44 UTC, clalancette approved these changes

2023-09-19 19:22 UTC, audrow approved these changes

2023-09-19 19:22 UTC, merged