Adding python-gsmmodem-new
ros/rosdistro pull request #38658
Opened 2023-09-29 19:37 UTC by DavidD121

added python-gsmmodem-new

Please add the following dependency to the rosdep database.

## Package name:

python-gsmmodem-new

## Package Upstream Source:

https://github.com/babca/python-gsmmodem/tree/master

## Purpose of using this:

Control an attached GSM modem: send/receive SMS messages, handle calls, etc

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - Pip: https://pypi.org/project/python-gsmmodem-new/
- Ubuntu: https://packages.ubuntu.com/
  - Pip: https://pypi.org/project/python-gsmmodem-new/

2023-10-03 22:17 UTC, methylDragon requested changes
Thanks for the contribution! Could you add the pip packages under the "*" match rules like some of the rosdep bindings below?

2023-10-04 05:37 UTC, DavidD121 commented
> Thanks for the contribution! Could you add the pip packages under the "*" match rules like some of the rosdep bindings below?

Just to be clear, are you looking for something more general like this:
```
python-gsmmodem-pip: &migrate_eol_2025_04_30_python3_gsmmodem_pip
  '*':
    pip:
      packages: [python-gsmmodem-new]
```
or to use '*' matching within the distros? i.e:
```
python-gsmmodem-pip: &migrate_eol_2025_04_30_python3_gsmmodem_pip
  debian:
    '*':
      pip:
        packages: [python-gsmmodem-new]
  ubuntu:
    '*':
      pip:
        packages: [python-gsmmodem-new]
```

2023-10-06 17:44 UTC, methylDragon commented
> > Thanks for the contribution! Could you add the pip packages under the "*" match rules like some of the rosdep bindings below?
> 
> Just to be clear, are you looking for something more general like this:
> 
> ```
> python-gsmmodem-pip: &migrate_eol_2025_04_30_python3_gsmmodem_pip
>   '*':
>     pip:
>       packages: [python-gsmmodem-new]
> ```
> 
> or to use '*' matching within the distros? i.e:
> 
> ```
> python-gsmmodem-pip: &migrate_eol_2025_04_30_python3_gsmmodem_pip
>   debian:
>     '*':
>       pip:
>         packages: [python-gsmmodem-new]
>   ubuntu:
>     '*':
>       pip:
>         packages: [python-gsmmodem-new]
> ```

I think I would go with the latter, matching the distros!

2023-10-13 06:31 UTC, quarkytale approved these changes

2023-11-03 05:10 UTC, nuclearsandwich commented
@methylDragon I'm slightly perplexed by your suggestions as they contradict the ones I would make and I want to make sure that I'm not misunderstanding the rules or out of date on current preferences.

Is there a reason _not_ to elide the ubuntu and debian version field and to prefer an explicit wildcard there? I've always advocated eliding where possible in order to keep the rules as readable as possible.

2023-11-07 16:45 UTC, clalancette commented on rosdep/python.yaml
> +python3-gsmmodem-pip: *migrate_eol_2025_04_30_python3_gsmmodem_pip
Personally, I don't really think we need the migration key.  Python 2 is dead, so adding in new keys for it doesn't seem to make much sense.  So I would suggest just making the key `python3-gsmmodem-pip`, and dispensing with the `python-gsmmodem-pip` key and the migration anchor altogether.

2023-11-07 16:45 UTC, clalancette commented on rosdep/python.yaml
> +        packages: [python-gsmmodem-new]
It's a little odd that this is a `-new` version of this package.  Is this a fork of the original pip package?  If so, should we name the key `python3-gsmmodem-new-pip` instead?

2023-11-28 19:58 UTC, clalancette commented
There's been no response in 3 weeks here, so I'll close this out.  Please feel free to respond to the latest feedback and reopen.

2023-11-28 19:58 UTC, closed without merging