rtctree: 3.0.1-3 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #38675
Opened 2023-10-03 03:25 UTC by k-okada

Increasing version of package(s) in repository `rtctree` to `3.0.1-3`:

- upstream repository: https://github.com/gbiggs/rtctree.git
- release repository: https://github.com/tork-a/rtctree-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

2023-10-03 15:07 UTC, wjwwood commented
Sorry, this has conflicts now since the other repo was merged. Can you fix it up?

2023-10-04 05:42 UTC, k-okada commented
@wjwwood done!

2023-10-04 12:50 UTC, clalancette requested changes

2023-10-04 12:50 UTC, clalancette commented on noetic/distribution.yaml
> +      url: https://github.com/gbiggs/rtctree.git
This is missing a `version`, and an overall `status`:

```suggestion
      url: https://github.com/gbiggs/rtctree.git
      version: master
    status: maintained
```

2023-10-04 13:01 UTC, clalancette approved these changes

2023-10-04 13:01 UTC, merged