Add robot_module_msgs and digital_interface_msgs
ros/rosdistro pull request #38721
Opened 2023-10-05 13:31 UTC by smihael

## Package name:

1. robot_module_msgs
2. digital_interface_msgs

## Package Upstream Source:

1. https://github.com/ReconCycle/robot_module_msgs
2. https://github.com/ReconCycle/digital_interface_msgs

## Purpose of using this:

1. Provides message, service, and action definitions for general purpose robot-agnostic controllers. Notably, it includes JointCommand.msg and CartesianCommand.msg, which include fields to specify positions, velocities, accelerations and additional force applied by the robot as well as an option to set robot compliance. it is used in https://github.com/abr-ijs/ijs_controllers
3. Provides message and service definitions for controlling GPIO pins. It is used for https://github.com/ReconCycle/raspi_ros and https://github.com/ReconCycle/rqt_raspi_ros

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-10-09 22:37 UTC, methylDragon commented
I am unsure if the message definitions are general enough to be taking a package name in the global namespace.
It's generally a good idea to [prefix the package names](https://ros.org/reps/rep-0144.html).

This is especially because some messages are:
- [Specific to raspberry pis](https://github.com/ReconCycle/digital_interface_msgs/blob/release/srv/ConfigRead.srv)
- Or have potentially more general analogues in major, pre-existing prefixed packages: [JointCommand](https://github.com/ReconCycle/robot_module_msgs/blob/release/msg/JointCommand.msg) ([moveit_msgs/RobotTrajectory](http://docs.ros.org/en/noetic/api/moveit_msgs/html/msg/RobotTrajectory.html))

2023-10-09 22:38 UTC, methylDragon commented
I'd wait for someone else to chime in. Maybe @tfoote ?

2023-10-09 22:56 UTC, tfoote requested changes
Yes, these package names are not specific enough. 

My first reaction is digital interface to what? This is not the package that will provide all digital interfaces.  Likewise what robot's module are these messages for? This is not provideing all messages possible for any robot module. 

Based on the use in raspi_ros the `raspi_` prefix might make sense. 

Though I'll note that that package doesn't follow the naming guides either. It should be something more like `raspi_deployment` If I read the README correctly. `ros` in a ROS package name is redundant as it is a ROS package.

2023-10-10 17:50 UTC, smihael commented
Thank you for your constructive comments. The package names are inherited from various previous projects, but we will consider renaming them (@BorisKuster).

`digital_interface_msgs` are used in conjunction with [raspi_ros](https://github.com/ReconCycle/raspi_ros) package to expose GPIOs as named ROS services, but the messages are more general and could be used with any other board providing GPIOs. @Rok-Pahic, perhaps `gpio_msgs` would be better?

`robot_module_msgs` are used in conjunction with internally developed controllers within a broader modular software architecture. We could go with some non-descriptive prefix `ijs_` (institution name). I don't agree that the messages can be replaced with "more general analogues in major, pre-existing prefixed packages".

Both [moveit_msgs/CartesianTrajectoryPoint and JointTrajectoryPoint](http://docs.ros.org/en/noetic/api/moveit_msgs/html/index-msg.html) are fairly new (robot_module_msgs existed since 2016)don't support setting compliance. 

Furthermore, there are no action server definitions and messages for executing
- joint space point-to-point trajectory with trapezoidal velocity profile,
- Cartesian space straight line point-to-point motion & quaternion SLERP trajectory with minimum jerk
time evolution,
- joint space point-to-point trajectory with trapezoidal velocity profile, with the initial and final pose provided
in Cartesian space and transformed into joint space using inverse kinematics,
- dynamic movement primitive (DMP) in joint space,
- Cartesian space DMP.

Alternatively, the messages could be split into multiple packages, I'm open to naming suggestions.

2023-10-10 20:31 UTC, sloretz commented
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2023-10-12/)

2023-10-12 03:41 UTC, tfoote commented
An `ijk_robot_module_msgs` makes complete sense. 

The name `gpio_msgs` is again very broad claim implicitly suggesting that it covers all gpio for the whole ROS ecosystem. I would suggest `raspi_gpio_msgs` as it appears to be very specific to one implementation. If it were to be a generic implementation it should be an abstraction of the gpio that can be self documenting.

2023-10-24 18:15 UTC, quarkytale commented
@smihael friendly ping, are you planning on taking this forward?

2023-11-02 13:12 UTC, smihael commented
> @smihael friendly ping, are you planning on taking this forward?

We discussed this internally and will proceed with refactoring. Tentatively, this should be done by the end of this month.

2023-11-03 05:16 UTC, nuclearsandwich commented
@smihael thanks for the update. Since a new release will be required for updated package names, I am going to close this PR. It would also be very helpful if you would link it and this conversation when opening the follow-up so that the reviewers there have the full discussion context.

2023-11-03 05:16 UTC, closed without merging