Add python-pip-rapidfuzz to python.yaml
ros/rosdistro pull request #38821
Opened 2023-10-29 21:55 UTC by laurence-diack-pk

Added rapidfuzz pip package

Please add the following dependency to the rosdep database.

## Package name:

python-rapidfuzz-pip

## Package Upstream Source:

https://github.com/maxbachmann/RapidFuzz

## Purpose of using this:

This is a widely used fuzzing lib. We already have python-fuzzywuzzy-pip and this is a more up to date, performant and widely used version of that.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-11-03 04:53 UTC, nuclearsandwich approved these changes
With the usual caveats that pip packages cannot be used by packages released onto the ROS build farm (where dependencies must be satisfied by apt) this addition is approved.

2023-11-03 04:54 UTC, nuclearsandwich commented
Two approvals are required for rosdep reviews.

2023-11-03 05:04 UTC, nuclearsandwich requested changes, later dismissed
Updating my review until the CI results are addressed.

2023-11-08 16:18 UTC, clalancette approved these changes

2023-11-08 17:01 UTC, audrow approved these changes

2023-11-08 17:01 UTC, merged