ouster-ros: 0.11.1-3 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #38841
Opened 2023-11-01 17:32 UTC by Samahu

Increasing version of package(s) in repository `ouster-ros` to `0.11.1-3`:

- upstream repository: https://github.com/ouster-lidar/ouster-ros.git
- release repository: https://github.com/ros2-gbp/ouster-ros-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## ouster_ros

```
* breaking: rename ouster_msgs to ouster_sensor_msgs
* shutdown the driver when unable to connect to the sensor on startup
```

## ouster_sensor_msgs

```
* breaking: rename ouster_msgs to ouster_sensor_msgs
```

2023-11-01 21:20 UTC, tfoote requested changes
Thank you for the rename from the discussion at: https://github.com/ros/rosdistro/pull/38415#issuecomment-1788127872 to ease the transition for the community. 

There's one small fixup for this PR (suggestion added) but otherwise it looks ready to go.

2023-11-01 21:20 UTC, tfoote commented on rolling/distribution.yaml
> +      url: https://github.com/ouster-lidar/ouster-ros.wiki.git
```suggestion
      url: https://github.com/ouster-lidar/ouster-ros.git
```

This is supposed to be the url of the repository on which to run the automatic code documentation job. Not a link to human readable documentation. That should go in the package.xml.

2023-11-01 21:20 UTC, tfoote commented on rolling/distribution.yaml
> +      version: master
```suggestion
      version: rolling-devel
```

Fix branch name too.

2023-11-01 22:35 UTC, clalancette commented
I'm going to suggest that we wait on merging this until next week.  We'll have a definitive answer for the way forward then.

2023-11-02 07:09 UTC, Samahu commented
Fair enough, we can wait.

On Wed, Nov 1, 2023 at 11:35 PM Chris Lalancette ***@***.***>
wrote:

> I'm going to suggest that we wait on merging this until next week. We'll
> have a definitive answer for the way forward then.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ros/rosdistro/pull/38841#issuecomment-1789783328>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAET6UI6OFFVODE4QB6QNX3YCLFCNAVCNFSM6AAAAAA6ZUFQ2OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBZG44DGMZSHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-27 19:50 UTC, closed without merging