Update distribution.yaml
ros/rosdistro pull request #38857
Opened 2023-11-04 22:21 UTC by Zhven

# Please Add This Package to be indexed in the rosdistro.

ROLLING

# The source is here:

https://github.com/robotont/robotont_msgs

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2023-11-05 19:29 UTC, nuclearsandwich commented
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/robotont/robotont_msgs/blob/noetic-devel/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
  - [ ] robotont_msgs: https://github.com/robotont/robotont_msgs/blob/noetic-devel/LICENSE
- [x] Public source repo: https://github.com/robotont/robotont_msgs/tree/noetic-devel/
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] robotont_msgs

2023-11-05 19:32 UTC, nuclearsandwich requested changes, later dismissed
Can you please address the CI failure by accepting the suggestion. Other than that this change appears ready for approval.

2023-11-05 19:32 UTC, nuclearsandwich commented on rolling/distribution.yaml
> +      url: https://github.com/robotont/robotont_msgs
```suggestion
      url: https://github.com/robotont/robotont_msgs.git
```

rosdistro repository urls use explicit suffixes to denote the vcs used.

2023-11-08 16:27 UTC, clalancette approved these changes

2023-11-08 16:27 UTC, merged