Add rosdep key for python3-pyinotify
ros/rosdistro pull request #38933
Opened 2023-11-11 08:14 UTC by emersonknapp

Please add the following dependency to the rosdep database.

## Package name:

`python3-pyinotify`

## Package Upstream Source:

https://github.com/seb-m/pyinotify

## Purpose of using this:

To use Python scripts to watch directories for changes. In this particular case, to see rosbags as they are split in order to upload them to cloud storage.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/python3-pyinotify
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/python3-pyinotify
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-inotify/python3-inotify/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/extra/any/python-pyinotify/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/pyinotify
- macOS: https://formulae.brew.sh/
  - pip
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-inotify
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=23.05&show=python311Packages.pyinotify
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/python3-pyinotify

2023-11-12 13:47 UTC, clalancette requested changes, later dismissed
There is the one warning about RHEL packages, otherwise this looks pretty good to me.

2023-11-13 19:27 UTC, emersonknapp commented
@clalancette that search only revealed [python3-inotify_simple-1.3.5-4.el9.noarch.rpm](https://rhel.pkgs.org/9/epel-x86_64/python3-inotify_simple-1.3.5-4.el9.noarch.rpm.html) which is https://pypi.org/project/inotify-simple/ , a different package than the key I'm trying to add here. (that pkgs.org search is very hard to use, there's no "clear all" button for the distro checkboxes..., and I don't think the full query is encoded in the URL)

2023-11-29 18:40 UTC, emersonknapp commented
K. It wasn't clear to me that AlmaLinux was what I was supposed to be looking at, I've never heard of it before today. Is that what we mean when we say "RHEL" - or at least a proxy for it? Perhaps that should be specified in the PR template instructions

2023-11-29 18:43 UTC, clalancette commented
> Is that what we mean when we say "RHEL" - or at least a proxy for it?

Yeah, that's one of the open-source rebuilds of RHEL, and the one we actually build our packages against.  Happy to take a look at a PR to update the PR template.

2023-11-30 18:14 UTC, adityapande-1995 approved these changes

2023-12-01 18:57 UTC, sloretz approved these changes

2023-12-01 18:58 UTC, merged