rosdep: nixos: Add transforms3d packages
ros/rosdistro pull request #39010
Opened 2023-11-17 03:43 UTC by hacker1024

2023-11-20 17:49 UTC, clalancette requested changes

2023-11-20 17:49 UTC, clalancette commented on rosdep/python.yaml
> +  nixos: [python3Packages.transforms3d]
There's no real reason to add to this one; this is implicitly Python 2, which is no longer supported.

```suggestion
```

2023-11-20 17:49 UTC, clalancette commented on rosdep/python.yaml
>    fedora: [python3-transforms3d]
This needs to be in alphabetical order:

```suggestion
  fedora: [python3-transforms3d]
  nixos: [python3Packages.transforms3d]
```

2023-11-22 19:51 UTC, tfoote commented
I merged the fix for the formatting but I don't have a link to validate the package. Please fill out the description with more information so we can validate the package linked is correct.

2023-12-01 19:05 UTC, sloretz approved these changes
https://search.nixos.org/packages?channel=23.11&show=python311Packages.transforms3d&from=0&size=50&sort=relevance&type=packages&query=transforms3d

2023-12-01 19:24 UTC, clalancette approved these changes

2023-12-01 19:24 UTC, merged