rplidar_ros: 2.1.5-1 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #39028
Opened 2023-11-20 07:30 UTC by deyouslamtec

Increasing version of package(s) in repository `rplidar_ros` to `2.1.5-1`:

- upstream repository: https://github.com/Slamtec/rplidar_ros.git
- release repository: https://github.com/Slamtec/rplidar_ros-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `2.0.0-1`

## rplidar_ros

```
* Update RPLIDAR SDK to 2.1.0
  * Support RPLIDAR C1 (#142 <https://github.com/Slamtec/rplidar_ros/issues/142>)
  * Re-implemented the data retrieving logic based on async fetching and decoding mechanism to improve performance
  * UltraDense protocol support
  * support for stoppping A1 motor
  * bugfix:start/stop_motor(service) cause lidar to stop scanning
* Fix build with C++14 && --march=native
* scan frequency configuration support
* Add launch file for RPLIDAR a2m*,C1
* Install udev rules via debian. (#126 <https://github.com/Slamtec/rplidar_ros/issues/126>)
* Bugfix:create_udev_rules.sh dose not take effect immediately.
* When node starts to reset rplidar, if rplidar info is not obtained within 15 seconds, rplidar reset fails
* Add initial_reset option to reset rplidar on node start
* Compilation optimization
* Contributors: Babak-SSh, Tim Clephas, Tony Baltovski, Ubuntu248, Victor Belov, Wang DeYou, WubinXia, kint, yzx
```

2023-11-20 16:45 UTC, clalancette requested changes
Need a response from @Timple before we can merge.

2023-11-20 16:45 UTC, clalancette commented on noetic/distribution.yaml
> +      url: https://github.com/Slamtec/rplidar_ros-release.git
Hm, this is changing the release repository that we've been using up until now.  @Timple, are you OK with this?

2023-11-21 09:12 UTC, Timple commented
I kind of took the initiative after over a year of unresponsiveness: https://github.com/Slamtec/rplidar_ros/issues/40
_qui tacet consentire videtur_ :slightly_smiling_face: 

Since Slamtec is also the owner of the driver, I have no objections of them taking over. I'm glad the software stack gets some love!

2023-11-22 20:22 UTC, clalancette approved these changes

2023-11-22 20:22 UTC, merged