Update distribution.yaml with multidim_rrt_planner
ros/rosdistro pull request #39050
Opened 2023-11-22 05:49 UTC by daviddorf2023

## Package name:

multidim_rrt_planner

## Package Upstream Source:

https://github.com/daviddorf2023/multidim_rrt_planner/tree/iron

## Purpose of using this:

There is no replacement for the RRT planner from ROS 1 (rrt_exploration). This package has both 2D and 3D RRT path and live node publishing in RViz that can go around markers within the confines of an occupancy grid.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://github.com/daviddorf2023/multidim_rrt_planner/tree/iron
- Ubuntu: https://packages.ubuntu.com/
  - https://github.com/daviddorf2023/multidim_rrt_planner/tree/iron
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  - not available
- rhel: https://rhel.pkgs.org/
  - not available

# Please Add This Package to be indexed in the rosdistro.

Iron

# The source is here:

https://github.com/daviddorf2023/multidim_rrt_planner/tree/iron

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2023-11-22 19:55 UTC, tfoote requested changes
A few tweaks to the formatting and then this will be good to go.

2023-11-24 17:22 UTC, daviddorf2023 commented on iron/distribution.yaml
> +      url: https://github.com/daviddorf2023/multidim_rrt_planner/tree/iron
Resolved in latest commit

2023-12-01 19:26 UTC, clalancette approved these changes

2023-12-01 19:26 UTC, clalancette commented
[Holding for Iron sync](https://discourse.ros.org/t/preparing-for-iron-sync-2023-12-01/)

2023-12-02 00:07 UTC, tfoote approved these changes
Thanks for the fixes.

2023-12-04 03:53 UTC, merged