Magladko rosdep base qtwebengine5 dev
ros/rosdistro pull request #39395
Opened 2023-12-30 21:45 UTC by magladko

Please add the following dependency to the rosdep database.

## Package name:

qtwebengine5-dev

## Package Upstream Source:

https://github.com/qt/qtwebengine

## Purpose of using this:

Support for Qt5 Webengine utilities to make it possible to work with the Qt5 GUI application project using the webengine utilities.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/qtwebengine5-dev
- Ubuntu: https://packages.ubuntu.com/ [available only from focal onwards, added nulls only for current distros]
  - https://packages.ubuntu.com/jammy/qtwebengine5-dev
  - https://packages.ubuntu.com/search?keywords=qtwebengine5-dev&searchon=names&suite=all&section=all
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/qt5-qtwebengine/qt5-qtwebengine/
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-qt/qtwebengine
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=23.11&show=libsForQt5.qt5.qtwebengine&from=0&size=50&sort=relevance&type=packages&query=webengine
- openSUSE: https://software.opensuse.org/package/
  - not available
- rhel: https://rhel.pkgs.org/
  - https://alpine.pkgs.org/3.18/alpine-community-aarch64/qt5-qtwebengine-dev-5.15.13-r13.apk.html

2023-12-31 16:26 UTC, clalancette requested changes

2023-12-31 16:26 UTC, clalancette commented on rosdep/base.yaml
> +  arch: null
No need to add nulls for entries we don't have:

```suggestion
```

2023-12-31 16:26 UTC, clalancette commented on rosdep/base.yaml
> +  osx: null
Same:

```suggestion
```

2023-12-31 16:26 UTC, clalancette commented on rosdep/base.yaml
> +  rhel: qt5-qtwebengine-dev
This needs to be a list:

```suggestion
  rhel: [qt5-qtwebengine-devel]
```

2023-12-31 16:26 UTC, clalancette commented on rosdep/base.yaml
> +  fedora: [qt5-qtwebengine]
```suggestion
  fedora: [qt5-qtwebengine-devel]
```

2023-12-31 16:26 UTC, clalancette commented on rosdep/base.yaml
> +    xenial: null
No need to add in keys for end-of-life distributions:

```suggestion
  ubuntu: [qtwebengine5-dev]
```

2023-12-31 20:56 UTC, magladko commented
@clalancette thanks for the changes, it's my first PR here

2024-01-01 15:25 UTC, clalancette requested changes

2024-01-01 15:25 UTC, clalancette commented on rosdep/base.yaml
> +  gentoo: [dev-qt/qtwebengine-5.15.11_p20231120]
```suggestion
  gentoo: [dev-qt/qtwebengine]
```

2024-01-02 13:31 UTC, clalancette approved these changes

2024-01-02 15:58 UTC, mjcarroll approved these changes

2024-01-02 16:36 UTC, merged