Added linux-isolate-process rosdep key
ros/rosdistro pull request #39418
Opened 2024-01-03 02:13 UTC by adityapande-1995

Please add the following dependency to the rosdep database.

## Package name:

linux-isolate-process

## Package Upstream Source:

Link to source : https://github.com/adityapande-1995/linux-isolate-process

## Purpose of using this:

This tool is useful to isolate and contain ROS nodes, so that they cannot communicate or discover other ROS nodes, kind of like ROS DOMAIN IDs. This approach is more scalable than domain ids, and isn't bound to ports. Instead, this uses the ``unshare()`` system call, and is linux specific. Primary use case would be isolate tests, so that a large number of tests can be run in parallel without them interfering with each other. Working on a colcon extension to use this tool, so that tests can be isolated.

Distro packaging links:

## Links to Distribution Packages

- Pip:
 - https://pypi.org/project/linux-isolate-process
- Debian: https://packages.debian.org/
  - Use the pip link above
- Ubuntu: https://packages.ubuntu.com/
  - Use the pip link above

2024-01-03 22:09 UTC, adityapande-1995 commented
cc @cottsay @nuclearsandwich

2024-01-03 23:22 UTC, wjwwood commented
nitpick: if it's `linux_isolate_process` in the `setup.py` and on the command-line, then it really shouldn't be `linux-isolate-process` in the repo or on pypi... It's an unnecessary inconsistency. It will need `_` replaced with `-` in Debian, but that's a well understood Debian requirement that affects lots of packages, plus you don't have a Debian yet.

2024-01-05 00:15 UTC, methylDragon requested changes
See William's comment

2024-01-08 21:10 UTC, adityapande-1995 commented
Updated the name to include underscores in the repo. For Pypi, I'm not sure if underscores are allowed. Are there any advantages to this being a ros package rather than a pip package with a rosdep key ? cc @cottsay

2024-01-09 10:20 UTC, methylDragon approved these changes, later dismissed
Ok pending the rest

Edit: Were the changes made to the repo? I don't see it :o

2024-01-09 19:47 UTC, adityapande-1995 commented
As per discussion in the ROS2 meeting earlier today, closing this out in favor of a pure python ROS package.

2024-01-09 19:47 UTC, closed without merging