Add libopus to base.yml
ros/rosdistro pull request #39712
Opened 2024-01-25 12:10 UTC by vicmassy

Please add the following dependency to the rosdep database.

## Package name:

 `libopus-dev`

## Package Upstream Source:

[Opus Codec](https://gitlab.xiph.org/xiph/opus)

## Purpose of using this:

This dependency is used to transmit audio over a wide range of applications, including
Voice over IP, videoconferencing, in-game  chat, and even remote live music
performances. It can scale from low bit-rate narrowband speech to very high
quality stereo music. Some robotic payloads, such as a Speaker can benefit from this library. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/libopus-dev
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/libopus-dev
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/opus-tools/opus-tools/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/extra/x86_64/opus-tools/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/media-sound/opus-tools
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/opus-tools#default
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/packages?name=opus-dev&branch=edge&repo=&arch=&maintainer=
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=23.11&show=libopus&from=0&size=50&sort=relevance&type=packages&query=libopus
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/libopus-dev
- rhel: https://rhel.pkgs.org/
  - https://pkgs.org/download/libopus-dev

2024-01-25 14:15 UTC, clalancette requested changes

2024-01-25 14:53 UTC, vicmassy commented
@clalancette Totally right! Pushed a fix for it

2024-01-25 16:35 UTC, clalancette approved these changes
Thanks for iterating, looks good to me.

2024-01-26 16:30 UTC, mjcarroll approved these changes

2024-01-26 16:31 UTC, merged