marine_msgs: 2.0.1-2 in 'noetic/distribution.yaml' [bloom]
ros/rosdistro pull request #39888
Opened 2024-02-13 17:58 UTC by rolker

Increasing version of package(s) in repository `marine_msgs` to `2.0.1-2`:

- upstream repository: https://github.com/CCOMJHC/marine_msgs
- release repository: https://github.com/CCOMjhc/marine_msgs-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## marine_acoustic_msgs

- No changes

## marine_sensor_msgs

```
* Add radar message and migration rules. (#40 <https://github.com/rolker/marine_msgs/issues/40>)
  Add radar messages and migration rules.
* Contributors: Roland Arsenault
```

2024-02-13 18:02 UTC, rolker commented
This is a resubmission of #35488 which has been long overdue!

2024-02-13 21:56 UTC, clalancette requested changes
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses):
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/CCOMJHC/marine_msgs
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

I have two concerns with this release:
1.  There are no `source` or `doc` entries here.  While it isn't strictly required, it would be much better to add these in so users can more easily find the source.
2.  https://github.com/CCOMJHC/marine_msgs is a fork of another repository.  Why is this release being done from the fork, rather than the upstream?

2024-02-14 13:40 UTC, rolker commented
This is my first release so I appreciate your patience as I get the hang of bloom and rosdistro.

1. I've added a doc and source sections pointing to the upstream repo.
2. The upstream repo is part of @lauralindzey's organization. She initiated the effort to standardize the messages which I and others took part in. She doesn't have the bandwidth at the moment to manage a release so I volunteered to do so. Being part of a different organization, I don't have the rights needed to the upstream repo in order to let bloom do its magic. I used the fork from my organization, which is kept in sync with the upstream repo, in order to follow the tutorials and let bloom generate the tags and such.

2024-02-14 13:55 UTC, lauralindzey commented
Hi @rolker -- I didn't realize that you didn't have full permissions on the marine_msgs repo. I've bumped you from maintainer to admin. Would this allow you to do the release directly from marine_msgs?

2024-02-14 14:14 UTC, rolker commented
> Hi @rolker -- I didn't realize that you didn't have full permissions on the marine_msgs repo. I've bumped you from maintainer to admin. Would this allow you to do the release directly from marine_msgs?

Thanks, I'll give it a try. I marked this PR as a draft for now.

2024-02-14 14:39 UTC, rolker commented
Replaced by #39899

2024-02-14 14:39 UTC, closed without merging