Add `overrides` python.yaml
ros/rosdistro pull request #39905
Opened 2024-02-15 00:46 UTC by amalnanavati

Please add the following dependency to the rosdep database.

## Package name:

`overrides`

## Package Upstream Source:

https://github.com/mkorpela/overrides

## Purpose of using this:

This dependency makes it easier and cleaner to manage docstrings when using class inheritance in Python3.

## Links to Distribution Packages

- pip: https://pypi.org
    - https://pypi.org/project/overrides
- Debian: https://packages.debian.org/
  - Use `pip` package linked above. Not available in the Debian repositories.
- Ubuntu: https://packages.ubuntu.com/
  - Use `pip` package linked above. Not available in the Ubuntu repositories.
- Fedora: https://packages.fedoraproject.org/
  - Use `pip` package linked above. Not available in the Fedora repositories.
- Arch: https://www.archlinux.org/packages/
  -https://archlinux.org/packages/extra/any/python-overrides/
- Gentoo: https://packages.gentoo.org/
  - Not available
- macOS: https://formulae.brew.sh/
  - Use `pip` package linked above. Not available in the Homebrew repositories.
- Alpine: https://pkgs.alpinelinux.org/packages
  - Not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - Not available
- openSUSE: https://software.opensuse.org/package/
  - Not available
- rhel: https://rhel.pkgs.org/
  - Not available

2024-02-15 14:04 UTC, clalancette requested changes

2024-02-15 14:04 UTC, clalancette commented on rosdep/python.yaml
> +python3-overrides:
Since this is a pip-only key, this should have a `-pip` suffix:

```suggestion
python3-overrides-pip:
```

2024-02-15 21:52 UTC, amalnanavati commented
Done. The reason I originally kept it with a non-pip ID is because the arch package is non-pip. However, given that that is a less commonly used OS, I understand the logic in keeping `pip` in the ID.

2024-02-16 15:33 UTC, clalancette commented
> Done. The reason I originally kept it with a non-pip ID is because the arch package is non-pip. However, given that that is a less commonly used OS, I understand the logic in keeping `pip` in the ID.

Ah, sorry, I totally missed that it was available as a package in `arch`.  Sorry about that.

At this point, we can either:
1.  Go back to the non-pip key, given that it does have at least one OS where it is packaged.
2.  Remove the `arch` entry, and leave it as a pip key.

I'm fine with either one, I'll leave it up to you.

2024-02-16 17:55 UTC, amalnanavati commented
Done, I reverted back to the non-pip key.

2024-02-20 14:05 UTC, mjcarroll approved these changes

2024-02-20 14:07 UTC, clalancette approved these changes

2024-02-20 14:07 UTC, merged