Update pull_request_template.md to include package name review template
ros/rosdistro pull request #39987
Opened 2024-02-21 22:32 UTC by ijnek

Updates issue template

2024-02-29 15:36 UTC, ijnek commented
@nuclearsandwich fyi

2024-03-14 16:45 UTC, audrow commented on .github/pull_request_template.md
> +- [ ] Does the package naming comply with [REP-144](https://ros.org/reps/rep-0144.html) ?
```suggestion
- [ ] Does the package naming comply with [REP-144](https://ros.org/reps/rep-0144.html)? 
```

2024-03-14 16:46 UTC, audrow reviewed
Seems okay to me. I'd like to get some other eyes on it before merging.

2024-03-19 15:48 UTC, nuclearsandwich requested changes
Thanks for making the suggestion here! I brought this up in today's ROS core meeting and we're concerned with adding an additional tree to the "choose your own adventure" template. Do you think you could instead make the REP-144 requirement part of the DOC INDEX review, which already serves a similar purpose of registering a source repository to be indexed in rosdistro?

2024-04-09 03:11 UTC, ijnek commented
Thanks for the review @audrow and @nuclearsandwich , i have addressed your feedback in #40518. Closing this PR since it is superceded.

2024-04-09 03:11 UTC, closed without merging