Removing euslime
ros/rosdistro pull request #40413
Opened 2024-03-29 16:13 UTC by Affonso-Gui

Binary builds for the euslime package have been failing for some time, so I'm taking them down until I (or someone else) can figure out a fix.

https://build.ros.org/job/Nbin_ufv8_uFv8__euslime__ubuntu_focal_arm64__binary/
https://build.ros.org/job/Nbin_ufhf_uFhf__euslime__ubuntu_focal_armhf__binary/

On a related note, any info on how to replicate the buildfarm results locally?
I've been trying the prerelease tests, but I can't quite get the arm ones running.
(do I really need an arm machine to run the arm tests?)
https://wiki.ros.org/regression_tests

@k-okada

2024-03-29 16:17 UTC, sloretz commented
> (do I really need an arm machine to run the arm tests?)

You can use qemu-user-static, but I don't know of a good resource that explains it, and I don't understand it sufficiently to give a good short explanation.

I think installing qemu-user-static and then running one of the official docker images under the target architecture is probably the easiest way. Maybe this page has enough info? https://github.com/multiarch/qemu-user-static/blob/master/README.md

2024-03-29 16:19 UTC, sloretz requested changes
It looks like it's building on amd64. 

https://build.ros.org/job/Nbin_uF64__euslime__ubuntu_focal_amd64__binary/

Instead of removing it here, I'd recommend adding euslime to the ROS 1 buildfarm's package blacklists for arm64 and armhf. Here's a PR that shows how: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/224/files

2024-03-30 09:47 UTC, Affonso-Gui commented
@sloretz 

Blacklisting on ARM does seem like a better solution for this case!
Created a PR in https://github.com/ros-infrastructure/ros_buildfarm_config/pull/228

> I think installing qemu-user-static and then running one of the official docker images under the target architecture is probably the easiest way. Maybe this page has enough info? https://github.com/multiarch/qemu-user-static/blob/master/README.md

Thanks for the hint, I will take a look.

2024-04-01 16:08 UTC, sloretz commented
Closing as completed by https://github.com/ros-infrastructure/ros_buildfarm_config/pull/228 🎉

2024-04-01 16:08 UTC, closed without merging