fix: pynput with apt
ros/rosdistro pull request #40529
Opened 2024-04-09 19:45 UTC by dnikitop

Please add the following dependency to the rosdep database.

## Package name:

pynput (python3-pynput)

## Package Upstream Source:

https://github.com/moses-palmer/pynput

## Purpose of using this:

Uses apt instead of pip.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=pynput)
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/search?keywords=pynput&searchon=names
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  - not available
- rhel: https://rhel.pkgs.org/
  - not available

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-04-10 12:23 UTC, clalancette requested changes

2024-04-10 12:23 UTC, clalancette commented on rosdep/python.yaml
> +  debian: [python3-pynput]
This should generally match the name of the debian key.  Also, there is no reason to call out the Ubuntu names explicitly.  And finally, the distribution names need to be in alphabetical order.  So this should be:

```suggestion
python3-pynput:
  debian: [python3-pynput]
  ubuntu: [python3-pynput]
```

(you'll also need to move this around within this file to make the whole thing alphabetical)

2024-04-10 13:34 UTC, clalancette commented on rosdep/python.yaml
> +  debian: [python3-pynput]
> Focal for ubuntu doesn't host python3-pynput, so only have nobel and jammy specified. We can combine `pynput-pip` and `python3-pynput` and specify pip/non pip for specific releases, but will break backwards compatibility the the name 'pynput-pip'

OK, good point about Focal.  In that case, let's change this to be forwards-compatible:

```
  ubuntu:
    '*': [python3-pynput]
    focal: null
```

2024-04-11 13:54 UTC, mjcarroll approved these changes

2024-04-11 13:57 UTC, clalancette approved these changes

2024-04-11 13:58 UTC, merged