Add Jazzy distribution as pre-release
ros/rosdistro pull request #40675
Opened 2024-04-18 15:47 UTC by marcoag

As part of the work towards [branching Jazzy from Rolling](https://discourse.ros.org/t/preparing-for-jazzy-branching-from-rolling-2024-04-18/37260) using the [rosdistro migration tools](https://github.com/ros/rosdistro/tree/master/migration-tools) we need an empty target distribution for `Jazzy`.

The first commit of this PR updates de index files and adds the `distribution.yaml` file for `jazzy` which will get re-populated when the migration tool runs.

I'd like to get review of this pull request in two phases.

I'd like on review phase to approve the platform list and source ref as I prepare to run the migration tool. This PR won't be merged as-is once approved. Instead it will be used as the foundation for a migration using the following migration command:
```
python3 migration-tools/migrate-rosdistro.py --source rolling --dest jazzy \
  --source-ref ad3bf8c1330cea014e30e4c68c2e318dfbd43b6e \
  --release-org ros2-gbp \
```
Once the migration is complete, I'll update this PR and request a second phase of reviews for merging the completed migration.

2024-04-18 16:15 UTC, clalancette requested changes, later dismissed

2024-04-18 16:15 UTC, clalancette commented on index-v4.yaml
> +    distribution_status: active
We should set this to pre-release for now:

```suggestion
    distribution_status: pre-release
```

(see also #36923 , where we did this for Iron)

2024-04-18 16:16 UTC, nuclearsandwich commented on jazzy/distribution.yaml
> +repositories: []
```suggestion
repositories: {}
```
Repositories is associative / dictish / mapish not an array.

2024-04-18 16:19 UTC, nuclearsandwich commented
CI wants an empty list of repositories to be an empty value. But the migration script will only work if there's an empty map there instead.
So we can leave CI angry about this for now.

```
 --- file:///home/runner/work/rosdistro/rosdistro/jazzy/distribution.yaml
+++ loaded-and-saved
@@ -11,3 +11,3 @@
   - noble
-repositories: []
+repositories:
 type: distribution
```

2024-04-18 16:22 UTC, clalancette reviewed
This looks good to me now.  I'm not going to approve it, and just leave that for @nuclearsandwich to do as needed.

2024-04-18 16:41 UTC, nuclearsandwich approved these changes
https://butt.holdings and also https://www.youtube.com/watch?v=861jOEqVr4Q

2024-04-19 17:48 UTC, nuclearsandwich approved these changes

2024-04-19 17:55 UTC, merged