flir_camera_driver: 2.0.16-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #40691
Opened 2024-04-20 10:57 UTC by berndpfrommer

Increasing version of package(s) in repository `flir_camera_driver` to `2.0.16-1`:

- upstream repository: https://github.com/ros-drivers/flir_camera_driver.git
- release repository: https://github.com/ros-drivers-gbp/flir_camera_driver-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `2.0.15-1`

## flir_camera_description

- No changes

## flir_camera_msgs

- No changes

## spinnaker_camera_driver

```
* add option to disable external control (default!)
* updated docs for sync driver, switch to RST
* widened the ExposureController interface
* fix build errors on rolling/noble
* added blacklevel and whitebalance support for blackfly
* use proper name for camerainfo when using sync driver
* Contributors: Bernd Pfrommer
```

## spinnaker_synchronized_camera_driver

```
* updated docs for sync driver, switch to RST
* added follower exposure controller renamed individual -> master
* Contributors: Bernd Pfrommer
```

2024-04-24 00:03 UTC, clalancette requested changes

2024-04-24 00:03 UTC, clalancette commented on rolling/distribution.yaml
> +      url: https://github.com/ros-drivers-gbp/flir_camera_driver-release.git
This is incorrect; all release repositories in rolling need to be in the `ros2-gbp` organization.

2024-04-24 00:32 UTC, berndpfrommer commented
Well, I first tried using ros2-gbp, but got this error and didn't know how to fix it. I also tried specifying "https" as push-url, but bloom-release ignored it and again tried to use ssh.
Saving 'rolling' track.
==> Testing for push permission on release repository
==> git remote -v
origin	git@github.com:ros2-gbp/flir_camera_driver-release.git (fetch)
origin	git@github.com:ros2-gbp/flir_camera_driver-release.git (push)
==> git push origin master --dry-run
ERROR: Permission to ros2-gbp/flir_camera_driver-release.git denied to berndpfrommer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cannot push to remote release repository.
Hint: If you just typed in your username/password and you have two-factor authentication,see:
  http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization
pfrommer@manifold:~/Documents/flir/src/flir_camera_driver$ 

```

2024-05-05 14:01 UTC, closed without merging

2024-05-05 14:02 UTC, clalancette commented
> See [ros2-gbp/ros2-gbp-github-org#507](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/507) , which should restore your access.

All right, you should have access again, so you should be able to do a new bloom-release and get this released into Rolling.

Because this needs a new bloom-release anyway, I'm actually just going to close this out (since `bloom` will open a new PR anyway).