remove package that was deprecated in I-turtle
ros/rosdistro pull request #40701
Opened 2024-04-20 16:41 UTC by ijnek

Please remove soccer_object_msgs from rolling and j-turtle. The package was deprecated in I-turtle, and was intended to be removed in J-turtle.

Resolves: https://github.com/ijnek/soccer_object_msgs/issues/12

2024-04-24 00:26 UTC, clalancette approved these changes

2024-04-24 00:28 UTC, clalancette requested changes
Actually, scratch that.  It appears to me like https://github.com/ijnek/soccer_visualization/blob/0a7c5e1a905bb1b4d990a083645626e37bb6c05c/soccer_marker_generation/package.xml#L14 still depends on this package.  Are you also intending on removing `soccer_visualization`?

2024-04-24 00:30 UTC, clalancette approved these changes
Never mind, I found https://github.com/ros/rosdistro/pull/40703 :).

2024-04-24 00:30 UTC, merged

2024-04-25 00:03 UTC, ijnek commented
Thanks @clalancette