Add s_graphs_msgs to rosdistro
ros/rosdistro pull request #40801
Opened 2024-04-24 08:48 UTC by hridaybavle

## Package names:

  * [s_graphs_msgs](https://github.com/snt-arg/s_graphs_msgs.git)
  
## Package Upstream Source:

https://github.com/snt-arg/s_graphs_msgs.git

## Purpose of using this:

Repository to contains custom ros2 msgs for [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git), required for exchanging information to and from the `lidar_s_graphs` node.  

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/snt-arg/s_graphs_msgs.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

2024-04-29 15:04 UTC, clalancette requested changes

2024-04-30 05:40 UTC, hridaybavle commented on humble/distribution.yaml
> +  s_graphs_msgs:
I will do the changes and commit.

2024-05-28 13:26 UTC, mjcarroll approved these changes

2024-05-28 13:57 UTC, clalancette approved these changes
This looks great.  Thank you so much for going through the work here to rename.

2024-05-28 13:59 UTC, merged