Add libblosc-dev
ros/rosdistro pull request #40865
Opened 2024-04-26 08:31 UTC by Timple

Please add the following dependency to the rosdep database.

## Package name:

`libblosc-dev`

## Package Upstream Source:

https://github.com/Blosc/c-blosc

## Purpose of using this:

For: https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/288

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/buster/libblosc-dev
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/search?keywords=libblosc-dev
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/blosc/blosc-devel/index.html
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

Iron, humble, rolling, jazzy

# The source is here:

https://github.com/Blosc/c-blosc

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-04-26 12:57 UTC, clalancette requested changes

2024-04-26 12:57 UTC, clalancette commented on rosdep/base.yaml
> +  debian: [libblosc-dev]
```suggestion
libblosc-dev:
  alpine: [blosc-dev]
  debian: [libblosc-dev]
```

2024-04-26 13:02 UTC, Timple commented on rosdep/base.yaml
> +  debian: [libblosc-dev]
Thanks!

2024-04-26 20:18 UTC, Timple commented on rosdep/base.yaml
> +  fedora: [blosc-devel]
Thanks for the help!

2024-04-26 20:48 UTC, clalancette approved these changes

2024-05-02 06:24 UTC, Timple commented
So who's now in charge of hitting the merge button? :slightly_smiling_face:

2024-05-03 17:50 UTC, nuclearsandwich approved these changes

2024-05-03 17:52 UTC, nuclearsandwich commented
> So who's now in charge of hitting the merge button? 🙂

rosdep database changes require two reviewers: https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md so the merge was blocked by the second review.

2024-05-03 17:52 UTC, merged

2024-05-03 20:43 UTC, Timple commented
> > So who's now in charge of hitting the merge button? 🙂
> 
> rosdep database changes require two reviewers: https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md so the merge was blocked by the second review.

Didn't know, learning everyday!