qbdevice-ros: 4.0.2-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #40999
Opened 2024-04-29 10:54 UTC by GDqbrobotics

Increasing version of package(s) in repository `qbdevice-ros` to `4.0.2-1`:

- upstream repository: https://bitbucket.org/qbrobotics/qbdevice-ros
- release repository: https://bitbucket.org/qbrobotics/qbdevice-ros2-release
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## qb_device

- No changes

## qb_device_bringup

- No changes

## qb_device_driver

- No changes

## qb_device_msgs

- No changes

## qb_device_ros2_control

- No changes

## qb_device_test_controllers

- No changes

2024-04-29 14:43 UTC, clalancette requested changes
Besides the inline comment, it would also be nice to add in at least a `source` entry here.

2024-04-29 14:43 UTC, clalancette commented on humble/distribution.yaml
> +  qbdevice-ros:
Can you make this key `qb_device` like it was in Noetic?

2024-05-03 07:50 UTC, GDqbrobotics commented
Should I open another pull request with bloom instead of editing this? I can't find any format error but I suppose there must be some...

2024-05-07 14:38 UTC, clalancette commented
> Should I open another pull request with bloom instead of editing this? I can't find any format error but I suppose there must be some...

There are trailing whitespaces on some of the lines you changed.

Besides that, it would be a good idea to rebase this onto the latest, as there have been some changes (unrelated to this PR) that you'll need in order to pass CI.

2024-05-09 07:49 UTC, closed without merging