json-stream
ros/rosdistro pull request #41063
Opened 2024-05-06 09:00 UTC by iam-shanmukha

## Package name: json-stream

## Package Upstream Source: 
- https://pypi.org/project/json-stream/

## link to source repository
- https://github.com/daggaz/json-stream

## Purpose of using this:

From Documentation:

>  Simple streaming JSON parser and encoder.
When [reading](https://pypi.org/project/json-stream/#reading) JSON data, json-stream can decode JSON data in a streaming manner, providing a pythonic dict/list-like interface, or a [visitor-based interfeace](https://pypi.org/project/json-stream/#visitor). Can stream from files, [URLs](https://pypi.org/project/json-stream/#urls) or [iterators](https://pypi.org/project/json-stream/#iterators).
> When [writing](https://pypi.org/project/json-stream/#writing) JSON data, json-stream can stream JSON objects as you generate them.
> These techniques allow you to [reduce memory consumption and latency](https://pypi.org/project/json-stream/#standard-json-problems).

Distro packaging links:

## Links to Distribution Packages

- pip: 
  - https://pypi.org/project/json-stream/

2024-05-06 21:51 UTC, nuclearsandwich commented on rosdep/python.yaml
> +      packages: [json-stream]
```suggestion
  '*':
    pip:
      packages: [json-stream]
  ```

For pip keys we are now taking advantage of an OS-level wildcard feature that was added to rosdep.

2024-05-06 21:51 UTC, nuclearsandwich approved these changes

2024-05-06 21:52 UTC, nuclearsandwich commented
@iam-shanmukha please note that packages with pip-based dependencies are not eligible for release on the ROS build farm.

This change requires an additional rosdep reviewer to approve before it can be merged.

2024-05-06 22:47 UTC, nuclearsandwich requested changes
@iam-shanmukha CI reports that this key is in the wrong place in lexicographical / alphabetical sort order. Could you please update the order to fix the error.

2024-05-07 14:25 UTC, clalancette approved these changes

2024-05-07 14:53 UTC, nuclearsandwich approved these changes

2024-05-07 14:53 UTC, merged