aruco_ros: 5.0.5-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #41115
Opened 2024-05-09 13:14 UTC by saikishor

Increasing version of package(s) in repository `aruco_ros` to `5.0.5-1`:

- upstream repository: https://github.com/pal-robotics/aruco_ros.git
- release repository: https://github.com/pal-gbp/aruco_ros-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## aruco

- No changes

## aruco_msgs

- No changes

## aruco_ros

```
* Merge pull request #135 from wep21/jazzy-devel
  Update cv_bridge header
* check header exists
* feat: update cv bridge header
* Contributors: Sai Kishor Kothakota, wep21
```

2024-05-13 14:52 UTC, clalancette requested changes

2024-05-13 14:52 UTC, clalancette commented on rolling/distribution.yaml
> +    status: maintained
Same suggestion as https://github.com/ros/rosdistro/pull/41114#pullrequestreview-2052944702

2024-05-13 15:41 UTC, saikishor commented on rolling/distribution.yaml
> +    status: maintained
Done

2024-05-14 12:16 UTC, clalancette approved these changes

2024-05-14 12:16 UTC, merged