Add libflatbuffers to rosdep/base.yaml
ros/rosdistro pull request #41519
Opened 2024-06-06 13:07 UTC by frankkusters

Please add the following dependency to the rosdep database.

## Package name:

libflatbuffers

## Package Upstream Source:

https://github.com/google/flatbuffers

## Purpose of using this:

Flatbuffers is a serialization protocol by Google, similar to Protobuf.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=libflatbuffers-dev
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/search?keywords=libflatbuffers-dev&searchon=names&exact=1&suite=all&section=all
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/flatbuffers/flatbuffers/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/extra/x86_64/flatbuffers/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-libs/flatbuffers
- macOS: https://formulae.brew.sh/
  - https://formulae.brew.sh/formula/flatbuffers
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/packages?name=flatbuffers&branch=edge&repo=&arch=&maintainer=
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=24.05&show=flatbuffers&from=0&size=1&sort=relevance&type=packages&query=flatbuffers
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/flatbuffers
- rhel: https://rhel.pkgs.org/
  - https://pkgs.org/download/flatbuffers
- freebsd:
  - https://cgit.freebsd.org/ports/tree/devel/flatbuffers

2024-06-11 13:53 UTC, wjwwood approved these changes

2024-06-11 19:33 UTC, clalancette requested changes

2024-06-11 19:33 UTC, clalancette commented on rosdep/base.yaml
> +libflatbuffers:
To match the Ubuntu name, I think this should be:

```suggestion
libflatbuffers-dev:
```

2024-06-11 19:33 UTC, clalancette commented on rosdep/base.yaml
> +    '*': [flatbuffers]
```suggestion
    '*': [flatbuffers-devel]
```

2024-06-11 19:33 UTC, clalancette commented on rosdep/base.yaml
> +  fedora: [flatbuffers]
```suggestion
  fedora: [flatbuffers-devel]
```

2024-06-11 19:33 UTC, clalancette commented on rosdep/base.yaml
> +  alpine: [flatbuffers]
```suggestion
  alpine: [flatbuffers-dev]
```

2024-06-11 19:33 UTC, clalancette commented on rosdep/base.yaml
> +    '*': [flatbuffers]
```suggestion
    '*': [flatbuffers-devel]
```

2024-06-12 09:24 UTC, frankkusters commented
@clalancette I tested your proposed changes, and they look fine. My changes were based on the `libgrpc` key added in #37138. That key has the same issues. I opened an issue for it (#41602).

2024-06-12 12:21 UTC, clalancette approved these changes

2024-06-12 12:21 UTC, merged