Add matio-devel for RHEL 9
ros/rosdistro pull request #41550
Opened 2024-06-07 14:34 UTC by wxmerkt

Cf. https://rhel.pkgs.org/9/epel-x86_64/matio-devel-1.5.27-1.el9.x86_64.rpm.html

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-06-11 13:55 UTC, wjwwood approved these changes

2024-06-11 19:34 UTC, clalancette requested changes

2024-06-11 19:34 UTC, clalancette commented on rosdep/base.yaml
> +    '9': [matio-devel]
Given that we expect this package to be available moving forward, I think we should redo this a bit to be:

```suggestion
  rhel: [matio-devel]
```

2024-06-12 12:23 UTC, clalancette reviewed
Well, now I'm confused.  CI is saying that `matio-devel` doesn't exist for RHEL-9, but that is explicitly what @wxmerkt is trying to add, and rhel.pkgs.org shows it available.  @cottsay any thoughts on what might be happening here?

2024-06-12 13:44 UTC, cottsay commented
> any thoughts on what might be happening here?

Evidently UMD's EPEL mirror is very out-of-date and doesn't have the package. The rerun selected a different mirror and passed.

2024-06-12 13:45 UTC, cottsay approved these changes

2024-06-12 13:57 UTC, clalancette approved these changes

2024-06-12 13:57 UTC, merged