Add `source` entry for ros2_openai_server (jazzy)
ros/rosdistro pull request #42014
Opened 2024-07-09 17:27 UTC by AndyZe

This is a new package so I'm adding the `source` entry per https://docs.ros.org/en/jazzy/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository

@brettpac @yassiezar

2024-07-10 13:24 UTC, AndyZe commented
I'd be fine with `chatgpt_server` if that floats your boat. I'm aware that I should drop `ros2_` from the front

2024-07-10 23:19 UTC, Yadunund requested changes
- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses):  Apache License 2.0
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/robosoft-ai/ros2_openai_server/tree/jazzy
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
<name>ros2_openai_server</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license>" "{}" "+"
<license>Apache-2.0</license>
```
</details>

Echoing @marcoag sentiments I too think the naming is very generic and does not pass [REP 144](https://www.ros.org/reps/rep-0144.html). It would be good to properly suffix the package, eg. `robosoft_ai_openai_server`. (`ros2` can be dropped imo but not a strict requirement).

2024-07-10 23:19 UTC, Yadunund commented on jazzy/distribution.yaml
> +    source:
Do you also want to add a doc entry?

2024-07-11 00:02 UTC, AndyZe commented on jazzy/distribution.yaml
> +    source:
sure

2024-07-11 00:03 UTC, AndyZe commented
OK, I can live with `robosoft_openai_server` or `robosoft_openai`

2024-07-11 03:47 UTC, marcoag approved these changes

2024-07-11 21:11 UTC, Yadunund approved these changes
LGTM, thanks for iterating!

2024-07-16 15:23 UTC, merged