Add `luma.core` and `luma.oled` pip dependencies to python.yaml
ros/rosdistro pull request #42073
Opened 2024-07-13 18:23 UTC by SPGC

Please add the following dependency to the rosdep database.

## Package name:

`luma.core`, `luma.oled` 

## Package Upstream Source:

luma.core - https://github.com/rm-hull/luma.core
luma.oled - https://github.com/rm-hull/luma.oled

## Reason to add:
1. luma.core - component library providing a [Pillow](https://pillow.readthedocs.io/)-compatible drawing canvas for Python 3, and other functionality to support drawing primitives and text-rendering capabilities for small displays on the Raspberry Pi and other single board computers
2. luma.oled - Python 3 library interfacing OLED matrix displays with the SSD1306, SSD1309, SSD1322, SSD1325, SSD1327, SSD1331, SSD1351, SH1106, SH1107 or WS0010 driver using I2C/SPI/Parallel on the Raspberry Pi and other linux-based single-board computers

Both libraries are useful for rendering on displays on robots

Distro packaging links:

## Links to Distribution Packages
+ `pip`:
  + https://pypi.org/project/luma.core/
  + https://pypi.org/project/luma.oled/

2024-07-14 15:28 UTC, marcoag commented
A quick search shows me that this packages exist in `Ubuntu noble` :

https://packages.ubuntu.com/noble/python3-luma.core
https://packages.ubuntu.com/noble/python3-luma.oled

and in consequence at least in `Debian bookwrom`. We usually try to avoid adding pip packages where binaries are available at the system leve, i.e.: https://github.com/ros/rosdistro/pull/41870#pullrequestreview-2148978970.

If you're looking to add it to a specific OS that don't have the system package please narrow down the scope of the rosdistro entry.

2024-07-23 19:55 UTC, mjcarroll commented
@SPGC friendly ping

2024-07-25 13:00 UTC, SPGC commented
> A quick search shows me that this packages exist in `Ubuntu noble` :
> 
> https://packages.ubuntu.com/noble/python3-luma.core https://packages.ubuntu.com/noble/python3-luma.oled
> 
> and in consequence at least in `Debian bookwrom`. We usually try to avoid adding pip packages where binaries are available at the system leve, i.e.: [#41870 (review)](https://github.com/ros/rosdistro/pull/41870#pullrequestreview-2148978970).
> 
> If you're looking to add it to a specific OS that don't have the system package please narrow down the scope of the rosdistro entry.

Changed to binary package for Ubuntu

2024-07-28 18:47 UTC, mjcarroll approved these changes
@clalancette for second approval on rosdep rules

2024-07-29 15:43 UTC, clalancette requested changes

2024-07-29 15:43 UTC, clalancette commented on rosdep/python.yaml
> +    noble: [python3-luma.oled]
So I think we should make this whole thing more forwards-compatible, and support Debian:

```suggestion
python3-luma-core:
  debian: [python3-luma.core]
  ubuntu:
    '*': [python3-luma.core]
    focal: null
python3-luma-oled:
  debian: [python3-luma.oled]
  ubuntu:
    '*': python3-luma.oled
    focal: null
```

2024-08-20 15:52 UTC, clalancette commented
This is failing CI, and there has been no response to the outstanding comments from 3 weeks ago.  I'm going to go ahead and close this, but if you'd still like to get it merged please feel free to reopen.

2024-08-20 15:52 UTC, closed without merging