Patch 3
ros/rosdistro pull request #42102
Opened 2024-07-16 12:50 UTC by mosfet80

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-07-16 13:38 UTC, marcoag commented
Info is confusing:
```
python3-vcstools for debian bullseye
python3-vcstool for other Debian distributions
```
it also provides a link to `bookworm` but modifies `bullseye`.

2024-07-16 14:00 UTC, cottsay requested changes
The [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#debian) describes the expected package sources for each distribution. For Debian, the ROS package repositories are included in the list.

The `python3-vcstool` package is available for all current Debian releases in the ROS repositories. That package is what this rule refers to. Upstream debian later decided to package vcstool as well, and then in Bookworm decided to rename the package to `vcstool`. That's fine - they can do what they want - but this rule still refers to the package provided by the ROS repositories, as it always has.

If your system can't find the package, you need to add the ROS package source to the system.

2024-07-22 16:44 UTC, tfoote requested changes
I'm going to put request changes on this for the moment to make sure we don't merge this without thinking it through fully. 

The current rule is pointing to the ROS packaged version. It appears to have just been adopted upstream and we should make a migration plan for switching over to the upstream assuming we test it as functional for our purposes. 

@nuclearsandwich @cottsay FYI (also we probably need to add a conflicts now for our version too)

2024-12-04 20:34 UTC, quarkytale commented
@mosfet80 are you still interested in taking this forward?

2024-12-05 20:26 UTC, audrow commented
I'm going to close this. Feel free to reopen, if there's interest.

2024-12-05 20:26 UTC, closed without merging