Adding adi_tmc_coe to documentation index for distro
ros/rosdistro pull request #42126
Opened 2024-07-18 23:06 UTC by CAcarADI

# Please Add This Package to be indexed in the rosdistro.

adi_tmc_coe

# The source is here:

https://github.com/analogdevicesinc/adi_tmc_coe

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-07-23 20:03 UTC, clalancette requested changes
In addition to the change inline, this also needs to be rebased due to some unrelated changes in this area of the file.

2024-07-23 20:03 UTC, clalancette commented on noetic/distribution.yaml
> +      url: https://github.com/analogdevicesinc/adi_tmc_coe
```suggestion
      url: https://github.com/analogdevicesinc/adi_tmc_coe.git
```

2024-07-24 04:03 UTC, CAcarADI commented
Hi @clalancette , Ive already pushed the suggested commit and rebased the commit but the Merging is blocked, is there anything I need to do to fix this?

2024-07-26 14:47 UTC, clalancette commented
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/analogdevicesinc/adi_tmc_coe/blob/noetic/LICENSE
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): https://opensource.org/license/bsd-3-clause
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/analogdevicesinc/adi_tmc_coe
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

2024-07-26 14:47 UTC, clalancette approved these changes

2024-07-26 14:47 UTC, merged