puma_motor_driver: 1.0.0-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #42213
Opened 2024-07-25 19:07 UTC by tonybaltovski

Increasing version of package(s) in repository `puma_motor_driver` to `1.0.0-1`:

- upstream repository: https://github.com/clearpathrobotics/puma_motor_driver.git
- release repository: https://github.com/clearpath-gbp/puma_motor_driver-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

## clearpath_socketcan_interface

```
* Deleted the CHANGELOG
* Version match to puma_motor_driver
* Renamed socketcan_interface to clearpath_socket_interface
* Contributors: Luis Camero
```

## puma_motor_driver

```
* Removed info logging
* Restored commandSpeed
* Spacing fixes
* Updated topics to match API
* Renamed socketcan_interface to clearpath_socket_interface
* Topic in node namespace
* Renamed robot to multi_puma_node
* Fixed include
* Add launch files and configuration files
* Add new multi puma node
* Modified header to include new functions
* Removed launch files
* Removed split multi control node
* Add retrieval functions with received checks
* properly using Boost shared library now
* added -fPIC build option
* exported header files
* built in ROS Foxy without errors
* Contributors: Joep Tool, Luis Camero, joe28965
```

## puma_motor_msgs

```
* updated msgs to foxy
* Contributors: joe28965
```

2024-07-26 13:53 UTC, clalancette commented
### New package review checklist

You can copy-paste the below into your review comment when reviewing a new package addition into rosdistro.

- [ ] At least one of the following must be present
  - [ ] Top level license file:
  - [ ] Per package license files:  - Not present, need a LICENSE or COPYING file in each package, since some are LGPL and some are BSD
- [x] License is [OSI-approved](https://opensource.org/licenses): https://opensource.org/license/lgpl-3-0
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/clearpathrobotics/puma_motor_driver
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

Once the LICENSE files are added, I think this will be good to go.

2024-07-26 13:53 UTC, clalancette requested changes
Needs LICENSE files.

2024-07-26 14:11 UTC, tonybaltovski commented
Added!  https://github.com/clearpathrobotics/puma_motor_driver/commit/87f21efe49011d4bce6abad76638856baa64bc5b

2024-07-28 18:46 UTC, mjcarroll approved these changes

2024-07-29 15:39 UTC, clalancette approved these changes

2024-07-29 15:39 UTC, merged