rslidar_sdk: 1.5.14-3 in 'jazzy/distribution.yaml' [bloom]
ros/rosdistro pull request #42238
Opened 2024-07-29 06:05 UTC by Timple

Increasing version of package(s) in repository `rslidar_sdk` to `1.5.14-3`:

- upstream repository: https://github.com/RoboSense-LiDAR/rslidar_sdk.git
- release repository: https://github.com/ros2-gbp/rslidar_sdk-release.git
- distro file: `jazzy/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

2024-07-31 02:03 UTC, sloretz requested changes
Looks like CI complains about a missing package.xml, I think because it exists on `main` but not `dev` which is listed in the source entry here: https://github.com/RoboSense-LiDAR/rslidar_sdk/tree/dev

```
RuntimeError: jazzy: missing package.xml file for package "rslidar_sdk"
```

But once that is fixed, the new package review looks good

---

- [X] At least one of the following must be present
  - [ ] Top level license file: 
  - [X] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package_ros2.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>rslidar_sdk</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package_ros2.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
  <license>BSD</license>
```
</details>

2024-08-02 07:31 UTC, Timple commented
You are correct, they did change to the `main` branch. I'll update!

2024-08-02 08:33 UTC, Timple commented
Seems like the tooling is confused by the version numbers in the package.xml.

Despite that the package.xml is overwritten with a correct one, it still tries to search for a 1.5.0 tag.

Proper fix: https://github.com/RoboSense-LiDAR/rslidar_sdk/pull/150/files

2024-08-02 21:02 UTC, Timple commented
I will re-open when it makes sense.

2024-08-02 21:02 UTC, closed without merging