Adding nmea_parser package to documentation index for distro<humble>
ros/rosdistro pull request #42321
Opened 2024-08-05 09:11 UTC by HundredGB

Please add the following dependency to the rosdep database.

## Package name: nmea_parser

A node that receives nmea data (GGA, RMC, HDT), parses it, and then publishes it

## Package Upstream Source: https://github.com/HundredGB/nmea_parser

TODO link to source repository

## Purpose of using this: for education

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - not available
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  -not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  -not available
- rhel: https://rhel.pkgs.org/
  - not available

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME : humble

# The source is here:

https://github.com/HundredGB/nmea_parser

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-08-05 16:53 UTC, sloretz commented
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-and-patch-release-2024-08-06/38909)

2024-08-06 00:31 UTC, HundredGB commented
The issue has been fixed! Please re-register.

2024-08-16 12:46 UTC, audrow approved these changes

2024-08-16 12:56 UTC, audrow reviewed
It looks like CI is failing due to a formatting issue.

2024-08-26 15:55 UTC, clalancette requested changes

2024-08-26 15:55 UTC, clalancette commented on humble/distribution.yaml
> +    tags:
This should be removed:

```suggestion
```

2024-09-25 15:19 UTC, audrow commented
Closing because it's stale. Feel free to reopen.

2024-09-25 15:19 UTC, closed without merging