robotraconteur: 1.2.2-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #42399
Opened 2024-08-10 04:19 UTC by johnwason

Increasing version of package(s) in repository `robotraconteur` to `1.2.2-1`:

- upstream repository: https://github.com/robotraconteur/robotraconteur.git
- release repository: https://github.com/robotraconteur-packaging/robotraconteur-ros2-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `1.1.1-1`

2024-08-12 02:57 UTC, marcoag commented
Same as #42402, let's keep there the discussion to avoid duplication.

2024-08-20 16:05 UTC, clalancette requested changes
Thanks for changing to the ros2-gbp organization. It looks like that has been merged and deployed now, so you should be able to change the release repository here.

(this also needs a rebase to fix conflicts)

2024-08-20 16:07 UTC, clalancette requested changes
Actually, this just needs to be rebased to fix conflicts now, then we can merge it in.

2024-08-20 16:50 UTC, johnwason commented
See #42465

2024-08-20 16:51 UTC, johnwason commented
Oh nevermind that is still the old version.

2024-08-26 15:52 UTC, clalancette commented
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-08-28/39316)

2024-08-29 13:53 UTC, clalancette approved these changes

2024-08-29 13:53 UTC, merged