robotraconteur: 1.2.2-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #42402
Opened 2024-08-10 04:29 UTC by johnwason

Increasing version of package(s) in repository `robotraconteur` to `1.2.2-1`:

- upstream repository: https://github.com/robotraconteur/robotraconteur.git
- release repository: https://github.com/robotraconteur-packaging/robotraconteur-ros2-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

2024-08-12 02:46 UTC, marcoag commented
The release repository of this package is not part of [ros2-gbp](https://github.com/ros2-gbp), please consider moving it to this org. [Here you have some instructions on how to create a ros2-gbp release repository for a ROS 2 package](https://docs.ros.org/en/jazzy/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository). 

Quoting from the how-to:
"It is now strongly recommended for release repositories to live in this dedicated GitHub organization."

2024-08-12 02:57 UTC, marcoag commented
I just realized all the other distros release from the same from the same non `ros2-gbp` repo. Any chance we could start transitioning to ros2-gbp?

2024-08-12 12:43 UTC, johnwason commented
See https://github.com/ros2-gbp/ros2-gbp-github-org/issues/582

2024-08-20 16:04 UTC, clalancette requested changes
Thanks for changing to the `ros2-gbp` organization.  It looks like that has been merged and deployed now, so you should be able to change the release repository here.

2024-08-26 15:53 UTC, clalancette approved these changes

2024-08-26 15:53 UTC, merged