add python3-pyotp
ros/rosdistro pull request #42428
Opened 2024-08-13 08:51 UTC by lennewbrook

Please add the following dependency to the rosdep database.

## Package name:

python3-pyotp

## Package Upstream Source:

(https://github.com/pyotp/pyotp)

## Purpose of using this:

This dependency is being used to add a one time password creation package for python.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/python3-pyotp
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/source/jammy/python-pyotp
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-pyotp/python3-pyotp/fedora-40.html
- Arch: https://www.archlinux.org/packages/
  - https://gitlab.archlinux.org/archlinux/packaging/packages/python-pyotp
- FreeBSD: https://pkg.freebsd.org/
  - https://cgit.freebsd.org/ports/tree/security/py-pyotp
- OpenSUSE: https://software.opensuse.org/
  - https://build.opensuse.org/package/show/openSUSE:Leap:15.6/python3-pyotp

2024-08-15 15:23 UTC, mjcarroll approved these changes

2024-08-20 16:08 UTC, clalancette requested changes
This looks like it is available for `RHEL-9`

2024-08-20 16:08 UTC, clalancette commented on rosdep/python.yaml
> +  opensuse: [python3-pyotp]
```suggestion
  rhel:
    '*': [python3-pyotp]
    '8': null
  opensuse: [python3-pyotp]
```

2024-08-26 16:02 UTC, clalancette submitted a review, later dismissed
For reasons unrelated to this PR, this needs a rebase, then it should pass CI.

2024-09-19 17:32 UTC, sloretz requested changes, later dismissed

2024-09-19 17:32 UTC, sloretz commented on rosdep/python.yaml
> +  opensuse: [python3-pyotp]
Looks like CI is failing here: 

```
    ERR: list out of alphabetical order line 8314.  'opensuse' should come before 'rhel'
```

2024-09-23 23:20 UTC, clalancette approved these changes

2024-09-25 15:17 UTC, audrow approved these changes

2024-09-25 15:18 UTC, merged