Add python3-easyocr
ros/rosdistro pull request #42504
Opened 2024-08-20 11:14 UTC by Plexiglas

Please add the following dependency to the rosdep database.

python3-easyocr:
Package Upstream Source:
https://github.com/JaidedAI/EasyOCR

Purpose of using this:
Used for optical character detection and recognition.

Distro packaging links:

Links to Distribution Packages
pip https://pypi.org/project/easyocr/

2024-08-20 13:32 UTC, mjcarroll commented
Standard pip disclaimer: ROS packages that depend on pip keys cannot be released into a ROS distribution. They can only be depended on by from-source builds. Because of this, system packages are highly preferred to pip packages.

2024-08-20 13:32 UTC, mjcarroll approved these changes

2024-08-20 16:11 UTC, clalancette requested changes

2024-08-20 16:11 UTC, clalancette commented on rosdep/python.yaml
> +python3-easyocr:
```suggestion
python3-easyocr-pip:
```

2024-09-21 06:20 UTC, clalancette commented
There's been no response to this in a month, so closing it out.  If you'd still like to get this in, please feel free to respond to the comments and reopen.

2024-09-21 06:20 UTC, closed without merging