sick_safetyscanners_base: 1.0.3-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #42513
Opened 2024-08-20 14:57 UTC by puck-fzi

Increasing version of package(s) in repository `sick_safetyscanners_base` to `1.0.3-1`:

- upstream repository: https://github.com/SICKAG/sick_safetyscanners_base.git
- release repository: https://github.com/SICKAG/sick_safetyscanners_base-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

## sick_safetyscanners_base

```
* Adding missing includes for ubuntu24 compiler
* Adding dependencies on specific boost libraries, exporting dep to chrono
* Fix Sync example
* Fix read checksums
* UDPPacketMerger: fixing missing include
* Contributors: Carl Morgan, Denis Taniguchi, Lennart Puck, Marco Bassa, Matthias Schoepfer, Rein Appeldoorn, Soren Holm, 张天宇
```

2024-08-20 19:42 UTC, clalancette requested changes, later dismissed

2024-08-20 19:42 UTC, clalancette commented on rolling/distribution.yaml
> +      url: https://github.com/SICKAG/sick_safetyscanners_base-release.git
With our current rules, all releases into Rolling must use the `ros2-gbp` organization for the release repositories; see https://github.com/ros/rosdistro/blob/09be553dc16a84478274693fff2b11ab524007dd/REVIEW_GUIDELINES.md#L47 .

2024-09-12 20:19 UTC, puck-fzi commented
Updated to ros2-gbp release repo

2024-09-19 18:24 UTC, nuclearsandwich approved these changes

2024-09-19 18:29 UTC, nuclearsandwich commented
Unless I bungled the merge conflict this PR can be merged once CI checks clear.

2024-09-20 18:57 UTC, merged