sick_safetyscanners_base: 1.0.3-1 in 'jazzy/distribution.yaml' [bloom]
ros/rosdistro pull request #42512
Opened 2024-08-20 14:53 UTC by puck-fzi

Increasing version of package(s) in repository `sick_safetyscanners_base` to `1.0.3-1`:

- upstream repository: https://github.com/SICKAG/sick_safetyscanners_base.git
- release repository: https://github.com/SICKAG/sick_safetyscanners_base-release.git
- distro file: `jazzy/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

## sick_safetyscanners_base

```
* Adding missing includes for ubuntu24 compiler
* Adding dependencies on specific boost libraries, exporting dep to chrono
* Fix Sync example
* Fix read checksums
* UDPPacketMerger: fixing missing include
* Contributors: Carl Morgan, Denis Taniguchi, Lennart Puck, Marco Bassa, Matthias Schoepfer, Rein Appeldoorn, Soren Holm, 张天宇
```

2024-08-20 19:42 UTC, clalancette requested changes
See the comment in https://github.com/ros/rosdistro/pull/42513#pullrequestreview-2248951725

2024-09-12 20:20 UTC, puck-fzi commented
update to ros2-gbp release repo

2024-09-17 22:07 UTC, sloretz commented
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-09-17/)

2024-09-23 22:42 UTC, marcoag approved these changes

2024-09-23 23:14 UTC, clalancette approved these changes

2024-09-23 23:14 UTC, merged