sick_safetyscanners2_interfaces: 1.0.0-1 in 'jazzy/distribution.yaml' [bloom]
ros/rosdistro pull request #42514
Opened 2024-08-20 15:00 UTC by puck-fzi

Increasing version of package(s) in repository `sick_safetyscanners2_interfaces` to `1.0.0-1`:

- upstream repository: https://github.com/SICKAG/sick_safetyscanners2_interfaces.git
- release repository: https://github.com/SICKAG/sick_safetyscanners2_interfaces-release.git
- distro file: `jazzy/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

## sick_safetyscanners2_interfaces

```
* Initial Release
```

2024-08-20 19:43 UTC, clalancette requested changes
See the comment in https://github.com/ros/rosdistro/pull/42515#pullrequestreview-2248953735

2024-09-12 20:17 UTC, puck-fzi commented
Updated the release repo to the ros2-gbp

2024-09-17 22:08 UTC, sloretz commented
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-09-17/)

2024-09-23 22:42 UTC, marcoag approved these changes

2024-09-23 23:20 UTC, clalancette commented
This looks good to me, but needs a rebase now because of the other PR that we merged.  Once that is done, we can merge this in.

2024-09-23 23:20 UTC, clalancette approved these changes

2024-09-24 10:20 UTC, puck-fzi commented
Should be rebased now

2024-09-24 10:35 UTC, puck-fzi commented
apparently i messed something up, could you maybe give me a pointer what to resolve here, I though i applied the correct steps. or at least resolved the rebase conflict, however the check does not seem to be happy

2024-09-25 02:44 UTC, clalancette commented
> apparently i messed something up, could you maybe give me a pointer what to resolve here, I though i applied the correct steps. or at least resolved the rebase conflict, however the check does not seem to be happy

The whole block needs to be before `sick_safetyscanners_base`.

2024-09-25 07:59 UTC, puck-fzi commented
adapted and should be ready now

2024-09-25 07:59 UTC, clalancette approved these changes

2024-09-25 07:59 UTC, merged