hri_face_detect: 2.0.10-2 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #42869
Opened 2024-09-16 12:44 UTC by severin-lemaignan

Increasing version of package(s) in repository `hri_face_detect` to `2.0.10-2`:

- upstream repository: https://github.com/ros4hri/hri_face_detect.git
- release repository: https://github.com/ros4hri/hri_face_detect-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## hri_face_detect

```
* use python3-mediapipe-pip on non-PAL environments
  While here, add missing dep on cv_bridge
* Contributors: Séverin Lemaignan
```

2024-09-17 21:57 UTC, sloretz commented
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-09-19/39649)

2024-09-20 18:46 UTC, nuclearsandwich commented
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/ros4hri/hri_face_detect/blob/humble-devel/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
  - [x] hri_face_detect: https://github.com/ros4hri/hri_face_detect/blob/humble-devel/package.xml#L8
- [x] Public source repo: https://github.com/ros4hri/hri_face_detect/tree/humble-devel/
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] hri_face_detect

2024-09-20 18:48 UTC, nuclearsandwich requested changes
> which means debian can not be automatically generated.

With this in mind, the release stanza of this pull request is invalid. Including a release stanza will create doomed-to-fail build farm jobs attempting to create source and binary packages for Ubuntu without available metadata.

2024-09-20 18:49 UTC, nuclearsandwich commented on humble/distribution.yaml
> +      version: 2.0.10-2
This stanza should be removed since the build farm binary packaging jobs will not succeed without metadata.

2024-11-18 20:10 UTC, clalancette commented
Given that there's been no follow-up here for a while, I'm going to close this out.  Please feel free to reopen once the problems have been resolved.

2024-11-18 20:10 UTC, closed without merging