hri_face_body_matcher: 2.0.3-1 in 'humble/distribution.yaml' [bloom]
ros/rosdistro pull request #42871
Opened 2024-09-16 13:43 UTC by severin-lemaignan

Increasing version of package(s) in repository `hri_face_body_matcher` to `2.0.3-1`:

- upstream repository: https://github.com/ros4hri/hri_face_body_matcher.git
- release repository: https://github.com/ros4hri/hri_face_body_matcher-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## hri_face_body_matcher

```
* make pal_module_cmake an optional dependency
* Contributors: Séverin Lemaignan
```

2024-09-17 22:00 UTC, sloretz commented
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-09-19/39649)

2024-09-25 15:05 UTC, audrow commented
I'm not sure if we should accept this because of the license. Asking...

2024-09-25 15:34 UTC, audrow commented
Hey @severin-lemaignan, we can't accept that license on the buildfarm. If you can change it to a common open source license, we can accept it.

2024-09-25 15:34 UTC, tfoote requested changes
This doesn't have an OSI approved license which allows us to redistribute it freely to the community. 

For reference LICENSE: https://github.com/ros4hri/hri_face_body_matcher/blob/humble-devel/LICENSE

2024-11-18 20:11 UTC, clalancette commented
Given that there's been no activity here for a while, I'm going to close this out.  Feel free to reopen once the LICENSE situation has been sorted.

2024-11-18 20:11 UTC, closed without merging

2024-11-19 07:50 UTC, severin-lemaignan commented
@clalancette -- following up in #43548 as I can not re-open this PR and github does not let me update it by pushing to the same branch.

2024-11-19 08:24 UTC, severin-lemaignan commented
hi @tfoote @audrow -- license updated to Apache 2 in `hri_face_body_matcher 2.1.0`. New PR replacing this one: #43549