create3_examples: 1.0.0-1 in 'jazzy/distribution.yaml' [bloom]
ros/rosdistro pull request #42978
Opened 2024-09-28 17:03 UTC by alsora

Increasing version of package(s) in repository `create3_examples` to `1.0.0-1`:

- upstream repository: https://github.com/iRobotEducation/create3_examples.git
- release repository: https://github.com/ros2-gbp/create3_examples-release.git
- distro file: `jazzy/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

## create3_coverage

- No changes

## create3_examples_msgs

- No changes

## create3_examples_py

- No changes

## create3_lidar_slam

- No changes

## create3_republisher

```
* Merge pull request #58 <https://github.com/iRobotEducation/create3_examples/issues/58> from civerachb-cpr/patch-1
  Adds the new /cmd_vel_stamped topic to the robot subscriptions.
* Merge pull request #56 <https://github.com/iRobotEducation/create3_examples/issues/56> from hilary-luo/hluo/rel-namespace-fix
  Relative Namespace Fix
* Remove manual handling of namespace not being fully qualified
* Contributors: Alberto Soragna, Chris Iverach-Brereton, Hilary Luo
```

## create3_teleop

- No changes

2024-09-29 15:50 UTC, fujitatomoya approved these changes
- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses):
- [x] License correctly listed in package.xmls
- [x] Public source repo:
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

2024-09-30 19:47 UTC, clalancette requested changes
This looks fine (and was previously released into Humble), but would you mind adding in a `doc` and `source` section for this package?

2024-09-30 22:18 UTC, alsora commented
@clalancette we don't really have docs for these examples (besides the README in the repo).
I can add that.

Do I need to do the bloom process again or can I manually edit the PR to add the fields?

2024-09-30 22:47 UTC, clalancette commented
> @clalancette we don't really have docs for these examples (besides the README in the repo).

While that is nice to do, you don't have to go out of your way to add it.  The buildfarm will automatically generate API documentation for it regardless, though without annotations it will only show what the API is.

> Do I need to do the bloom process again or can I manually edit the PR to add the fields?

You can manually edit the PR, that is fine.

2024-10-02 15:22 UTC, civerachb-cpr commented
If these changes aren't absolutely necessary, is it possible to expedite this merge?  This is the last dependency we're waiting on before we can release Jazzy support for the Turtlebot 4.

2024-10-03 14:46 UTC, clalancette approved these changes

2024-10-03 14:46 UTC, merged