Added adi_3dtof_image_stitching package
ros/rosdistro pull request #43003
Opened 2024-10-01 10:44 UTC by raebelchristo-adi

Please add the following dependency to the rosdep database.

## Package name:

adi_3dtof_image_stitching

## Package Upstream Source:

https://github.com/analogdevicesinc/adi_3dtof_image_stitching/tree/v1.1.0

## Purpose of using this:

`adi_3dtof_image_stitching` dependency allows a user to stitch together multiple depth and IR images published by the ADI's ADTF3175D ToF sensor. This has a significance in wide angle applications to increase the field of view.

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2024-10-01 23:47 UTC, sloretz commented
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2024-10-03/)

2024-10-03 03:25 UTC, MichaelOrlov requested changes
The license should be one of the open-source ones listed in https://opensource.org/licenses (preferably one of the "Popular licenses").
However, the license file https://github.com/analogdevicesinc/adi_3dtof_image_stitching/blob/v1.1.0/LICENSE
has an Analog Devices license which is not listed in the https://opensource.org/licenses

2024-10-03 06:14 UTC, raebelchristo-adi commented
We have used the **BSD-3-Clause** license which comes under the "Popular/Strong Community" Category as listed in [https://opensource.org/licenses](https://opensource.org/licenses). We only replaced the year and copyright holder placeholders with the corresponding year and the name of our organization.

2024-10-04 16:15 UTC, MichaelOrlov commented
@raebelchristo-adi I don't know how it happened, but https://github.com/analogdevicesinc/adi_3dtof_image_stitching/blob/v1.1.0/LICENSE have ADI license
![image](https://github.com/user-attachments/assets/172d77b4-e523-4e3a-be53-9bb38cb6c5aa)
And this is what gitlab officially shows under the what license this project is.

However, at the same time in the https://github.com/analogdevicesinc/adi_3dtof_image_stitching/blob/v1.1.0/package.xml
mentioned BSD license.
![image](https://github.com/user-attachments/assets/ce81eb8b-dc66-440a-b849-64ba3b09e4e4)

The licenses must be the same. Please adjust.

As regards your latest commit with changing the source version to the `noetic-devel` branch instead of the pinned version with a  tag. We usually do not allow this "workaround".

2024-10-04 19:54 UTC, raebelchristo-adi commented
> The licenses must be the same. Please adjust.

Could it be that the extra lines appended at the bottom of the LICENSE file that makes github think it is an ADI license rather than BSD-3? In that case I might need to check with an internal resource regarding how this can be altered.

> As regards your latest commit with changing the source version to the `noetic-devel` branch instead of the pinned version with a tag. We usually do not allow this "workaround".

We had an edit in the package.xml and CMakelists.txt that was merged into the noetic-devel branch. Hence we wanted this to be the main source branch as all maintenance happens here. Do you have any other suggestions if this workaround is not allowed?

2024-10-07 09:51 UTC, raebelchristo-adi commented
Regarding license changes. we are reviewing the alterations for the LICENSE file internally. I will update about it here.

2024-10-07 17:50 UTC, MichaelOrlov reviewed
@sloretz @clalancette Please correct me if I am wrong, if I understand correctly we shouldn't allow sources of the packages to track development branches like https://github.com/analogdevicesinc/adi_3dtof_image_stitching/tree/humble-devel unless some extraordinary cases.
The `source: version:` should refer to the tag in the repo associated with the release for the package. 
Otherwise, if source version will be set to track the development branch and, If it will be a regression, it will be no way to quickly revert changes by the ROS Boss when he preparing  be-weekly synch.

2024-10-07 18:10 UTC, sloretz commented
@MichaelOrlov The `source: version:` should be [the development branch from which release are made](https://docs.ros.org/en/rolling/How-To-Guides/Releasing/Index-Your-Packages.html#make-changes-to-your-fork) rather than a tag. The `source` block is used by tools like `rosinstall_generator --upstream-development` to get the latest unreleased sources for a package.

> Otherwise, if source version will be set to track the development branch and, If it will be a regression, it will be no way to quickly revert changes by the ROS Boss when he preparing be-weekly synch.

Syncs are only affected by content in the `release` block.

2024-10-07 18:25 UTC, MichaelOrlov commented
@sloretz Thanks for the clarification.
@raebelchristo-adi As soon as licensing issue will be resolved this PR will be good to go.

2024-10-08 12:13 UTC, raebelchristo-adi commented
The license of the repository has been updated. It now shows as BSD-3-Clause.

2024-10-08 14:45 UTC, cottsay approved these changes

2024-10-08 15:16 UTC, MichaelOrlov approved these changes

2024-10-08 16:41 UTC, clalancette approved these changes

2024-10-08 16:41 UTC, merged