Add clangd to rosdep/base.yaml
ros/rosdistro pull request #43167
Opened 2024-10-12 15:50 UTC by eshjordan

Please add the following dependency to the rosdep database.

## Package name:

clangd

## Package Upstream Source:

https://github.com/llvm/llvm-project/

## Purpose of using this:

We are using clangd for linting in-IDE and for significantly faster (but less insightful) static analysis than clang-tidy. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/clangd
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/noble/clangd
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/clang/clang-tools-extra/
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/extra/x86_64/clang/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/sys-devel/clang
- Alpine: https://pkgs.alpinelinux.org/packages
  - https://pkgs.alpinelinux.org/package/v3.16/main/x86_64/clang-extra-tools
- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?query=libclang
- openSUSE: https://software.opensuse.org/package/
  - https://software.opensuse.org/package/clang
- rhel: https://rhel.pkgs.org/
  - https://rhel.pkgs.org/8/raven-modular-x86_64/clang-tools-extra-19.1.1-1.el8.x86_64.rpm.html

2024-10-15 11:54 UTC, clalancette requested changes

2024-10-15 11:54 UTC, clalancette commented on rosdep/base.yaml
> +    '7': null
We don't need to worry about RHEL-7 anymore:

```suggestion
  rhel: [clang-tools-extra]
```

2024-10-15 11:54 UTC, clalancette commented on rosdep/base.yaml
> +    '*': [clangd]
```suggestion
  ubuntu: [clangd]
```

2024-10-15 13:06 UTC, clalancette approved these changes

2024-10-17 23:17 UTC, methylDragon approved these changes

2024-10-17 23:17 UTC, merged