Add python3-bloom to rosdep/python.yaml
ros/rosdistro pull request #43171
Opened 2024-10-14 11:06 UTC by frankkusters

Please add the following dependency to the rosdep database.

## Package name:

python3-bloom

## Package Upstream Source:

https://github.com/ros-infrastructure/bloom

## Purpose of using this:

Bloom is a release automation tool, designed to make generating platform specific release artifacts from source projects easier.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/python3-bloom
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/python3-bloom
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  - not available
- rhel: https://rhel.pkgs.org/
  - https://rhel.pkgs.org/8/epel-x86_64/python3-bloom-0.11.2-2.el8.noarch.rpm.html

2024-10-15 11:41 UTC, clalancette requested changes
I think we need to be really careful with this one, since it is provided both by upstream Ubuntu, and also by us.

Pinging @cottsay for a look.

2024-10-15 15:34 UTC, cottsay approved these changes
I don't see a very strong use case to have this here, but I also don't have any reason to object to adding it.

2024-10-15 15:53 UTC, clalancette approved these changes

2024-10-15 15:54 UTC, merged

2024-10-21 10:30 UTC, frankkusters commented
> I don't see a very strong use case to have this here, but I also don't have any reason to object to adding it.

The reason for adding this is that we package pretty much _everything_ as ROS packages in our project.* We also have a package for our build scripts, which depend on bloom.

\* It makes setting up a new developer machine incredibly easy: `rosdep install`, done.