Add rosdep key for rich
ros/rosdistro pull request #43386
Opened 2024-11-08 10:53 UTC by JafarAbdi

Please add the following dependency to the rosdep database.

## Package name:

rich

## Package Upstream Source:

https://github.com/Textualize/rich

## Purpose of using this:

render rich text, tables, progress bars, syntax highlighting, markdown

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bookworm/python3-rich
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/jammy/python3-rich
- Fedora: https://packages.fedoraproject.org/
  - https://packages.fedoraproject.org/pkgs/python-rich/python3-rich/
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/rich
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

2024-11-08 19:07 UTC, clalancette requested changes
Can you please add a key for `rhel`, as suggested by the bot?  This otherwise looks good.

2024-11-09 17:38 UTC, christophebedard approved these changes

2024-11-12 17:40 UTC, wjwwood approved these changes

2024-11-12 18:00 UTC, clalancette approved these changes

2024-11-12 18:00 UTC, merged