Add rosdep key for minijinja
ros/rosdistro pull request #43391
Opened 2024-11-08 11:48 UTC by JafarAbdi

Please add the following dependency to the rosdep database.

## Package name:

minijinja

## Package Upstream Source:

https://github.com/mitsuhiko/minijinja/tree/main/minijinja-py

## Purpose of using this:

A powerful template engine for Python

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://pypi.org/project/minijinja/
- Ubuntu: https://packages.ubuntu.com/
  - https://pypi.org/project/minijinja/
- macOS: https://formulae.brew.sh/
  - https://pypi.org/project/minijinja/

2024-11-08 19:06 UTC, clalancette requested changes
So it looks like minijinja is available in [Debian Trixie and later](https://packages.debian.org/search?keywords=minijinja&searchon=names&suite=all&section=all), as well as [Ubuntu Oracular and later](https://packages.ubuntu.com/search?keywords=minijinja&searchon=names&suite=all&section=all).  So we should rename the key to `python3-minijinja`, put the system dependencies in there, and mark the rest as `pip` installable.

2024-11-08 22:08 UTC, JafarAbdi commented
> So it looks like minijinja is available in [Debian Trixie and later](https://packages.debian.org/search?keywords=minijinja&searchon=names&suite=all&section=all), as well as [Ubuntu Oracular and later](https://packages.ubuntu.com/search?keywords=minijinja&searchon=names&suite=all&section=all). So we should rename the key to `python3-minijinja`, put the system dependencies in there, and mark the rest as `pip` installable.

Thanks! I wasn't aware of that, I updated the keys

2024-11-12 17:41 UTC, wjwwood approved these changes

2024-11-12 18:01 UTC, clalancette approved these changes
Thanks for iterating!

2024-11-12 18:01 UTC, merged