Add python3-validators-pip to rosdistro
ros/rosdistro pull request #43485
Opened 2024-11-13 06:52 UTC by Barry-Xu-2018

Please add the following dependency to the rosdep database.

## Package name:

python3-validators-pip

## Package Upstream Source:

https://github.com/python-validators/validators/

## Purpose of using this:

For robot AI processing, while using AI python packages like openai or ollama, they will rely on this python package.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
    - pip
        - https://pypi.org/project/validators/
- Ubuntu: https://packages.ubuntu.com/
   - pip
        - https://pypi.org/project/validators/
- Fedora: https://packages.fedoraproject.org/
    - pip
        - https://pypi.org/project/validators/
- rhel: https://rhel.pkgs.org/
    - pip
        - https://pypi.org/project/validators/

2024-11-15 19:50 UTC, sloretz requested changes, later dismissed
It looks like this is available from system packages. Please create a [system package key instead of a pip key](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1)

* fedora: [python3-validators](https://packages.fedoraproject.org/pkgs/python-validators/python3-validators/)
* debian: [python3-validators](https://packages.debian.org/bookworm/python3-validators)
* ubuntu: [python3-validators](https://packages.ubuntu.com/jammy/python3-validators)

2024-11-16 20:05 UTC, fujitatomoya reviewed
@Barry-Xu-2018 thanks for opening the PR. can you address @sloretz comments?

2024-11-18 02:22 UTC, Barry-Xu-2018 commented
> @Barry-Xu-2018 thanks for opening the PR. can you address @sloretz comments?

Thanks for the reminder. It is done.

2024-11-18 05:54 UTC, Barry-Xu-2018 commented
`python3-validators`  wasn't provided in `Bionic` and `Focal` version for Ubuntu.  
So for the Bionic and Focal versions of Ubuntu, I'll continue using pip to install validators.

2024-11-18 19:14 UTC, clalancette requested changes
The bot thinks we may be able to satisfy this on `opensuse` as well.  Once that is added, this should be good to go.

2024-11-19 02:26 UTC, Barry-Xu-2018 commented
> The bot thinks we may be able to satisfy this on `opensuse` as well. Once that is added, this should be good to go.

Okay. I added `opensuse` platform.

2024-11-20 16:23 UTC, fujitatomoya approved these changes

2024-11-21 05:38 UTC, nuclearsandwich requested changes, later dismissed
Thanks for continuing to iterate @Barry-Xu-2018. I have a few recommended changes based on the current state.

2024-11-21 05:38 UTC, nuclearsandwich commented on rosdep/python.yaml
> +        packages: [validators]
Bionic is un-supported so we shouldn't add handling for it. Focal is nearly EOL so I think it's not worth adding unless you're actually using it.

```suggestion
```

2024-11-21 06:54 UTC, Barry-Xu-2018 commented
> Bionic is no longer supported so we don't need to add it. Unless you're actually using the pip package on Focal I don't think it's worth adding there either since its nearly end-of-support itself.

Get it. Thank you for your information.   
I will remove Bionic and Focal.

2024-11-21 14:11 UTC, clalancette approved these changes
I think we need to have "something" for `focal`, otherwise the linters will fail.  So I think this is good as it is.

2024-11-21 14:12 UTC, merged