[rosdep] no more distutils as of Python 3.12
ros/rosdistro pull request #43500
Opened 2024-11-14 07:51 UTC by mikaelarguedas

As per PEP 632 https://peps.python.org/pep-0632/ distutils has been deprecated from Python 3.10 and is not distributed as of Python 3.12.

The package cannot be installed on newer platforms.

Distro packaging links:

## Links to Distribution Packages

This PR mark explicitly past distros as providing the package and defaults to null for all other distros.

- Debian: https://packages.debian.org/search?keywords=python3-distutils&searchon=names&suite=all&section=all
- Ubuntu: https://packages.ubuntu.com/search?keywords=python3-distutils&searchon=names&suite=all&section=all

Not sure how to deal with other distros that juste reference python standard library

2024-11-15 19:51 UTC, sloretz approved these changes

2024-11-18 19:08 UTC, clalancette requested changes, later dismissed
So, hm.  I'm not sure what to do here.

For Fedora, Gentoo, and nixOS, it looks like we set this to "python" long ago (2020, it looks like).  But that is actually a lie.

What I'd be in favor of here is removing all stanzas here except for the Ubuntu versions it can still be installed on, and the Debian versions it can still be installed on.  That way we'll be consistent everywhere.  In other words, remove fedora, gentoo, and nixos stanzas as well.

2024-11-18 19:22 UTC, cottsay commented
> But that is actually a lie.

It wasn't at the time. Python 3.11 and older provide `distutils` as part of the stdlib. Debian decided to pull it into a separate package for whatever reason, but that rule was right for platforms which didn't split it out.

I do however agree that platforms targeting Python >= 3.12 should drop rules now, which includes Fedora.

2024-11-18 20:18 UTC, clalancette commented
> It wasn't at the time. Python 3.11 and older provide `distutils` as part of the stdlib. Debian decided to pull it into a separate package for whatever reason, but that rule was right for platforms which didn't split it out.

I see, thanks for the info.

> I do however agree that platforms targeting Python >= 3.12 should drop rules now, which includes Fedora.

Hm, though now I think it might be provided by `setuptools`?  At least if I go on my Ubuntu 24.04 container (with Python 3.12), I can run:

```
$ python3.12 -c "import distutils ; print(distutils.__file__)"
/usr/lib/python3/dist-packages/setuptools/_distutils/__init__.py
```

2024-11-18 20:23 UTC, cottsay commented
> Hm, though now I think it might be provided by `setuptools`?

It might on some platforms, yes. On Fedora, a `distutils-precedence.pth` file is created that conditionally injects the bundled distutils from setuptools into Python's module search path. If that sort of injection happens by default, I think you could say that `python3-setuptools` provides this.

2024-11-21 05:47 UTC, nuclearsandwich approved these changes

2024-11-21 05:51 UTC, nuclearsandwich commented
> It might on some platforms, yes. On Fedora, a `distutils-precedence.pth` file is created that conditionally injects the bundled distutils from setuptools into Python's module search path. If that sort of injection happens by default, I think you could say that `python3-setuptools` provides this.

I think we should decide whether or not we want to seamlessly transition to the setuptools shim (which will doubtless get dropped in some major version unceremoniously, possibly even in the near future) or if we think that people depending on setuptools to provide distutils should update their dependency declaration explicitly.

2024-11-27 22:39 UTC, nuclearsandwich commented
In the ROS PMC meeting this week, we discussed this and decided that the best thing to do is null out the python3-distutils key where it is not provided via python3 (or a split package on distros that were splitting it out).

There is a shim library provided by setuptools for distutils support but it is not providing distutils itself, only a compatible interface. So packages which wish to continue without switching to the setuptools interface must still update their rosdep keys to `python3-setuptools` to use the new dependency.

2024-11-27 22:40 UTC, merged