add ROS Sugar package to rosdistro
ros/rosdistro pull request #43513
Opened 2024-11-15 08:51 UTC by mkabtoul

# Please add sugar to be indexed in the rosdistro

## Package name:

`sugar`

## Package Upstream Source:

https://github.com/automatika-robotics/ros-sugar.git

## Purpose of using this:

`sugar`  is a meta-framework that provides a whole lot of syntactic sugar for creating event-driven multinode systems in ROS2, using an intuitive Python API

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2024-11-15 20:07 UTC, sloretz commented
[Iron Irwini is already in its final sync hold](https://discourse.ros.org/t/preparing-for-final-iron-irwini-patch-release-and-sync-2024-11-18/)

2024-11-18 09:04 UTC, mkabtoul commented
Thanks @sloretz, I removed the package from Iron's distribution

2024-11-18 19:00 UTC, clalancette requested changes, later dismissed
This name is too generic for ROS distro, and thus violates [REP-144](https://ros.org/reps/rep-0144.html).

I'm going to suggest that you rename the package to something like "automatika_ros_sugar", which both prefixes with the organization name and describes more of what it does.

2024-11-19 15:02 UTC, mkabtoul commented
@clalancette , I updated the package name as suggested

2024-11-21 05:44 UTC, nuclearsandwich commented
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/automatika-robotics/ros-sugar/blob/main/LICENSE
- [x] License is [OSI-approved](https://opensource.org/licenses): MIT
- [x] License correctly listed in package.xmls
  - [x] automatika_ros_sugar: https://github.com/automatika-robotics/ros-sugar/blob/main/package.xml#L9 @mkabtoul the license field is usually an SPDX license identifier rather than a Copyright declaration as well.
- [x] Public source repo: https://github.com/automatika-robotics/ros-sugar/tree/main
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] automatika_ros_sugar

2024-11-21 05:46 UTC, nuclearsandwich approved these changes

2024-11-21 05:46 UTC, merged