[python] add python3-babel
ros/rosdistro pull request #43539
Opened 2024-11-18 12:31 UTC by severin-lemaignan

python-babel was already present; add the py3 version.

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

2024-11-18 18:48 UTC, clalancette requested changes
Can you please add the key for RHEL-9 as suggested by the bot?

2024-11-18 22:01 UTC, severin-lemaignan commented
@clalancette done

2024-11-19 18:48 UTC, clalancette approved these changes

2024-11-21 05:58 UTC, nuclearsandwich commented
@severin-lemaignan in the future please use the issue template to provide the requested information for rosdep updates

* https://packages.debian.org/bookworm/python3-babel
* https://packages.ubuntu.com/noble/python3-babel
* https://pkgs.org/search/?q=python3-babel
* https://packages.fedoraproject.org/pkgs/babel/python3-babel/
* https://software.opensuse.org/package/python3-Babel

2024-11-21 05:59 UTC, nuclearsandwich approved these changes

2024-11-21 05:59 UTC, merged