Add ar4_ros_driver
ros/rosdistro pull request #43773
Opened 2024-12-03 13:41 UTC by ycheng517

# Please Add This Package to be indexed in the rosdistro.

ar4_ros_driver

# The source is here:

https://github.com/ycheng517/ar4_ros_driver

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

2024-12-04 19:20 UTC, clalancette requested changes
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/ycheng517/ar4_ros_driver/blob/main/LICENSE
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): https://opensource.org/license/mit
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/ycheng517/ar4_ros_driver
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions: Sort of.  The repository is named `ar4_ros_driver`, which I think is an OK name.  However, the various packages are called `ar_{description,gazebo,hardware_interface,moveit_config}`, which I think is too generic.  I'm going to suggest that the packages are renamed to `annin_ar4_{description,gazebo,hardware_interface,moveit_config}`

2024-12-04 19:20 UTC, clalancette commented on jazzy/distribution.yaml
> +      url: https://github.com/ycheng517/ar4_ros_driver
```suggestion
      url: https://github.com/ycheng517/ar4_ros_driver.git
```

2024-12-04 19:36 UTC, clalancette commented
Besides fixing the CI, we also need to rename the packages (see https://github.com/ros/rosdistro/pull/43773#pullrequestreview-2479696453).

2024-12-19 15:09 UTC, ycheng517 commented
I am working on renaming the packages. Should be ready in a few days. Will request for re-review soon!

2024-12-20 13:31 UTC, ycheng517 commented
I've updated the package names in my repo to `annin_ar4_{description,gazebo,hardware_interface,moveit_config}`. Please re-review!

2025-01-02 13:26 UTC, clalancette approved these changes
Thanks for the update!

2025-01-02 13:26 UTC, merged