eiquadprog: 1.2.9-1 in 'rolling/distribution.yaml' [bloom]
ros/rosdistro pull request #43826
Opened 2024-12-07 10:56 UTC by nim65s

Increasing version of package(s) in repository `eiquadprog` to `1.2.9-1`:

- upstream repository: git@github.com:stack-of-tasks/eiquadprog.git
- release repository: https://github.com/stack-of-tasks/eiquadprog-ros-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `null`

2024-12-09 13:26 UTC, audrow requested changes
@nim65s, 

To quote @clalancette:
> In order to release into Rolling, the release repository must be in the `ros2-gbp` organization.  Please see https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/CONTRIBUTING.md on how to do this.

Also, see https://github.com/ros/rosdistro/pull/43824#pullrequestreview-2488794553.

2024-12-09 13:58 UTC, nim65s commented on rolling/distribution.yaml
> +      url: https://github.com/stack-of-tasks/eiquadprog-ros-release.git
```suggestion
      url: https://github.com/ros2-gbp/eiquadprog-release
```

2024-12-09 13:59 UTC, nim65s commented on rolling/distribution.yaml
> +      url: https://github.com/stack-of-tasks/eiquadprog-ros-release.git
```suggestion
      url: https://github.com/ros2-gbp/eiquadprog-release.git
```

2024-12-09 14:07 UTC, nim65s commented
Thanks @audrow, I updated the repo.

But a test is failing because I think I forgot to push some tags to the new repo. It should be fixed now. Can it be retried ? ?

2024-12-10 14:04 UTC, audrow approved these changes

2024-12-10 14:09 UTC, merged