Nix
ros/rosdistro pull request #43904
Opened 2024-12-13 16:26 UTC by nim65s

Hi,

This add the nixos packages for:
- python-omniorb: https://search.nixos.org/packages?channel=unstable&show=python312Packages.omniorb&from=0&size=50&sort=relevance&type=packages&query=python312Packages.omniorb
- python3-pyside2: https://search.nixos.org/packages?channel=unstable&show=python312Packages.pyside2&from=0&size=50&sort=relevance&type=packages&query=python312Packages.pyside2

2024-12-13 18:55 UTC, clalancette requested changes

2024-12-13 18:55 UTC, clalancette commented on rosdep/python.yaml
> +  nixos: [python3Packages.omniorb]
This key is effectively dead, so please move this to the `python3-omniorb` key.

2024-12-17 16:32 UTC, nim65s commented
I think so, yes

2024-12-17 18:58 UTC, clalancette requested changes

2024-12-17 19:34 UTC, clalancette approved these changes

2024-12-30 14:22 UTC, audrow approved these changes

2024-12-30 14:22 UTC, merged